/**
 * Shared small validators for API JSON.
 *
 * Use these instead of writing a new UUID/date rule in every contract file.
 */
// Zod checks values at runtime.
import { z } from "zod";

// UUID ids generated by the database/API.
export const uuidSchema = z.uuid();

// ISO date strings sent over JSON, usually from Date#toISOString().
export const isoDateTimeSchema = z.iso.datetime();

// Calendar dates without a timezone, interpreted by the endpoint that owns
// them (for example lead submission days use Africa/Algiers).
export const isoDateSchema = z.iso.date();

// Merchant-owned product identifier. Trimming keeps accidental surrounding
// whitespace out of immutable snapshots; control characters are never valid
// inside an order-facing code.
export const productSkuSchema = z
	.string()
	.regex(/^[^\p{Cc}]*$/u, "Product SKU must not contain control characters")
	.trim()
	.min(1)
	.max(100);
