/**
 * Shared small validators for API JSON.
 *
 * Use these instead of writing a new UUID/date rule in every contract file.
 */
// Zod checks values at runtime.
import { z } from "zod";

// UUID ids generated by the database/API.
export const uuidSchema = z.uuid();

// ISO date strings sent over JSON, usually from Date#toISOString().
export const isoDateTimeSchema = z.iso.datetime();
