/**
 * Called by the publish pipeline's HTML transform (slice 0) as one more
 * html→html step, alongside pixel injection.
 *
 * Plain exported functions, NO NestJS DI on purpose (precedent: stampHtml) —
 * the Nest publish path and Trigger.dev tasks share this module.
 */
import { leadsRoutes } from "@wandit/contracts";

import { buildLeadsRuntimeScript } from "./leads-runtime-script";

export const LEADS_RUNTIME_SCRIPT_ID = "wandit-leads-runtime";

/**
 * Insert the leads runtime immediately before the LAST `</body>`
 * (case-insensitive); with no body close tag, append at the end — same
 * strategy as the preview-editor injection. Canonical generated runtime
 * blocks are replaced so archived publish bytes are restamped with the
 * pending deployment id. If the id survives canonical removal, the document
 * carries bytes the injector does not recognize and is returned unchanged.
 */
export function injectLeadsRuntime(
	html: string,
	options: { captureUrl: string; deploymentId: string },
): string {
	const escapedId = LEADS_RUNTIME_SCRIPT_ID.replace(
		/[.*+?^${}()|[\]\\]/g,
		"\\$&",
	);
	// Only a block that looks like our own generated bytes is removed: the exact
	// opener followed by the IIFE prefix every historical build started with.
	const canonicalBlock = new RegExp(
		`<script id="${escapedId}">\\s*\\(function[\\s\\S]*?<\\/script>`,
		"g",
	);
	const stripped = html.replace(canonicalBlock, "");
	// Any surviving carrier of the id is bytes we do not understand (variant
	// opener, marker inside a string). Never risk deleting merchant content or
	// running two runtimes: fall back to the pre-restamp behavior and return the
	// document untouched (the stale runtime keeps capturing; the server falls
	// back to the active deployment for its stale id).
	if (stripped.includes(`id="${LEADS_RUNTIME_SCRIPT_ID}"`)) return html;

	const block = `<script id="${LEADS_RUNTIME_SCRIPT_ID}">${buildLeadsRuntimeScript(options)}</script>`;
	// Match on the case-preserved HTML: toLowerCase is not length-preserving
	// ("İ" lowers to two code units), so an index taken from a lowered copy
	// can splice the script into the middle of the closing tag.
	let index = -1;

	for (const match of stripped.matchAll(/<\/body>/gi)) {
		index = match.index;
	}

	if (index === -1) return stripped + block;

	return stripped.slice(0, index) + block + stripped.slice(index);
}

/**
 * Absolute capture URL baked into the published page: the public,
 * unauthenticated endpoint addressed by the project's unguessable
 * publicFormId (leadsRoutes.capture).
 */
export function buildLeadsCaptureUrl(
	apiOrigin: string,
	publicFormId: string,
): string {
	return apiOrigin.replace(/\/+$/, "") + leadsRoutes.capture(publicFormId);
}
