/**
 * Publish-time ad-pixel injection. The builder is forbidden from emitting
 * trackers, so pixels enter the page here, into the published bytes only.
 * Draft versions in R2 never contain them. Canonical generated blocks are
 * replaced from current project settings; if a marker survives canonical
 * removal, the document carries bytes this injector does not recognize and
 * is returned unchanged.
 *
 * Pure functions on purpose — no Nest, no I/O — so tests are trivial and the
 * publish pipeline stays the only caller.
 */
import { load } from "cheerio";

export type PixelIds = {
	metaPixelId: string | null;
	tiktokPixelId: string | null;
};

const PIXEL_MARKER = "data-wandit-pixel";

/**
 * The editor stamps its artifacts with `__wandit-` id prefixes and strips
 * them before every R2 write (pages/domain/stamp.ts). Publish reads bytes
 * from R2, so a leak is structurally impossible — this assertion exists to
 * keep it that way if anyone ever changes where publish reads from.
 */
export function assertNoEditorArtifacts(html: string): void {
	if (html.includes("__wandit-")) {
		throw new Error(
			"Refusing to publish: editor artifacts (__wandit-) found in HTML",
		);
	}
}

export function injectPixels(html: string, pixels: PixelIds): string {
	let strippedMetaScript = false;
	// Only blocks that look like our own generated bytes are removed: the exact
	// marker and IIFE openers from every historical snippet build.
	const canonicalMetaScript =
		/<script data-wandit-pixel="meta">\s*!function\(f,b,e,v,n,t,s(?:,c,q,r,p)?\)\{[\s\S]*?<\/script>/g;
	const canonicalTiktokScript =
		/<script data-wandit-pixel="tiktok">\s*!function\(w,d,t\)\{[\s\S]*?<\/script>/g;
	const canonicalMetaNoscript =
		/<noscript data-wandit-pixel="meta"><img height="1" width="1" style="display:none" src="https:\/\/www\.facebook\.com\/tr\?id=[\s\S]*?<\/noscript>/g;
	const legacyMetaNoscript =
		/<noscript><img height="1" width="1" style="display:none" src="https:\/\/www\.facebook\.com\/tr\?id=[\s\S]*?<\/noscript>/g;
	let stripped = html.replace(canonicalMetaScript, () => {
		strippedMetaScript = true;
		return "";
	});

	stripped = stripped
		.replace(canonicalTiktokScript, "")
		.replace(canonicalMetaNoscript, "");

	// The first Meta fallback was unmarked. Remove that exact generated shape
	// only when its canonical script proves this page carried our Meta block;
	// an otherwise identical merchant-authored fallback is not ours to delete.
	if (strippedMetaScript) stripped = stripped.replace(legacyMetaNoscript, "");

	// Any surviving marker is bytes we do not understand (variant opener,
	// marker inside a string). Never risk deleting merchant content or running
	// duplicate pixels: return the original document, not a partial rewrite.
	if (stripped.includes(PIXEL_MARKER)) return html;

	// No pixels configured → return the stripped bytes without a cheerio
	// round-trip. A clean document remains byte-identical to the draft.
	if (!pixels.metaPixelId && !pixels.tiktokPixelId) return stripped;

	const $ = load(stripped);

	// Scripts go in <head> (both providers' documented placement — the base
	// code must load before the visitor can convert); Meta's <noscript>
	// fallback image stays in <body> where an img is valid.
	if (pixels.metaPixelId) {
		$("head").append(metaPixelScript(pixels.metaPixelId));
		$("body").append(metaPixelNoscript(pixels.metaPixelId));
	}

	if (pixels.tiktokPixelId) {
		$("head").append(tiktokPixelSnippet(pixels.tiktokPixelId));
	}

	return $.html();
}

/**
 * Meta base code, split in two on purpose:
 *
 * 1. The STUB (window.fbq + its n.queue buffer) stays SYNCHRONOUS. The leads
 *    runtime feature-detects `typeof window.fbq === "function"` before it
 *    fires the Meta Lead and Purchase conversions
 *    (leads/runtime/leads-runtime-script.ts) and
 *    swallows a miss in an empty catch, so a visitor who converts early must
 *    still find the stub. `fbq('init',…)` and `fbq('track','PageView')` only
 *    push into n.queue; the SDK replays them when it arrives.
 * 2. The SDK <script> insert (fbevents.js) is DEFERRED to idle time after
 *    load. The fetch was already `async`, so this does not remove a
 *    render-blocking request — it moves ~100 KB of bandwidth and main-thread
 *    parse out of the critical window (TBT / Lighthouse third-party).
 *
 * WHY THE DEFER IS BOUNDED. Queued events are only SENT once the SDK arrives,
 * so "wait for load" alone would put PageView — and the conversion events —
 * behind every subresource on the page, including connector media served from
 * a provider's own host that this platform does not control. The insert is
 * therefore scheduled on the EARLIEST of: load, a 3 s timer, the page turning
 * hidden, pagehide, and an explicit flush. The last three are what rescue the
 * visitor who converts and closes the tab; `r` keeps every path idempotent.
 *
 * THE FLUSH HOOK. window.wanditFlushPixels fetches the SDKs immediately; the
 * leads runtime calls it after it queues the conversion events, so they are
 * never left sitting in the stub queue. Each snippet chains the hook the
 * other one may have installed, so Meta and TikTok both flush. The name
 * carries no `__wandit-` prefix on purpose — assertNoEditorArtifacts rejects
 * that prefix in published bytes.
 *
 * `async`/`defer` attributes on the tag itself would be a no-op: this is an
 * inline classic script with no `src`, and the HTML spec ignores them there.
 */
function metaPixelScript(pixelId: string): string {
	const id = escapeForScript(pixelId);

	return `<script ${PIXEL_MARKER}="meta">!function(f,b,e,v,n,t,s,c,q,r,p){if(f.fbq)return;n=f.fbq=function(){n.callMethod?n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];r=0;c=function(){if(r)return;r=1;t=b.createElement(e);t.async=!0;t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)};q=function(){f.requestIdleCallback?f.requestIdleCallback(c,{timeout:2500}):f.setTimeout(c,1)};p=f.wanditFlushPixels;f.wanditFlushPixels=function(){c();p&&p()};b.readyState==='complete'?q():f.addEventListener('load',q);f.setTimeout(q,3000);f.addEventListener('pagehide',c);b.addEventListener('visibilitychange',function(){b.visibilityState==='hidden'&&c()})}(window,document,'script','https://connect.facebook.net/en_US/fbevents.js');fbq('init','${id}');fbq('track','PageView');</script>`;
}

function metaPixelNoscript(pixelId: string): string {
	return `<noscript ${PIXEL_MARKER}="meta"><img height="1" width="1" style="display:none" src="https://www.facebook.com/tr?id=${encodeURIComponent(pixelId)}&ev=PageView&noscript=1" alt=""/></noscript>`;
}

function tiktokPixelSnippet(pixelId: string): string {
	const id = escapeForScript(pixelId);

	// NOTE the `};` after insertBefore: ttq.load must be ASSIGNED, not
	// immediately invoked. The earlier version accidentally executed the
	// loader with (window,document,"ttq") — leaving ttq.load undefined, so
	// ttq.load(id) threw and the TikTok pixel never registered anything.
	//
	// Same split as Meta: the stub (ttq array + setAndDefer queue) runs at
	// parse time so window.ttq.track exists for early conversions, and only the
	// `ttq.load(id);ttq.page()` pair — which is what fetches events.js — waits
	// for the idle scheduler. ttq.page() pushes into the array queue, so the
	// SDK still replays it in order once it loads.
	return `<script ${PIXEL_MARKER}="tiktok">!function(w,d,t){w.TiktokAnalyticsObject=t;var ttq=w[t]=w[t]||[];ttq.methods=["page","track","identify","instances","debug","on","off","once","ready","alias","group","enableCookie","disableCookie"];ttq.setAndDefer=function(t,e){t[e]=function(){t.push([e].concat(Array.prototype.slice.call(arguments,0)))}};for(var i=0;i<ttq.methods.length;i++)ttq.setAndDefer(ttq,ttq.methods[i]);ttq.instance=function(t){for(var e=ttq._i[t]||[],n=0;n<ttq.methods.length;n++)ttq.setAndDefer(e,ttq.methods[n]);return e};ttq.load=function(e,n){var i="https://analytics.tiktok.com/i18n/pixel/events.js";ttq._i=ttq._i||{};ttq._i[e]=[];ttq._i[e]._u=i;ttq._t=ttq._t||{};ttq._t[e]=+new Date;ttq._o=ttq._o||{};ttq._o[e]=n||{};var o=d.createElement("script");o.type="text/javascript";o.async=!0;o.src=i+"?sdkid="+e+"&lib="+t;var a=d.getElementsByTagName("script")[0];a.parentNode.insertBefore(o,a)};var r=0;var c=function(){if(r)return;r=1;ttq.load('${id}');ttq.page();};var q=function(){w.requestIdleCallback?w.requestIdleCallback(c,{timeout:2500}):w.setTimeout(c,1)};var p=w.wanditFlushPixels;w.wanditFlushPixels=function(){c();p&&p()};d.readyState==="complete"?q():w.addEventListener("load",q);w.setTimeout(q,3000);w.addEventListener("pagehide",c);d.addEventListener("visibilitychange",function(){d.visibilityState==="hidden"&&c()});}(window,document,'ttq');</script>`;
}

// Pixel ids are numeric-ish strings from the project settings form. Allowlist
// rather than escape: anything outside [A-Za-z0-9_-] cannot be a pixel id and
// must never reach an inline script.
function escapeForScript(value: string): string {
	return value.replace(/[^A-Za-z0-9_-]/g, "");
}
