import type { DesignWorld } from "./types";

/**
 * BAZAR — bazaar heat with craft. The loud pole of the COD library: three
 * saturated spice poles color-blocked onto warm paper, offer stamps slammed on
 * at 2-4deg with hard offset shadows, a price so large it gets a hand-drawn ink
 * circle around it, and a deals ticker running the width of the page. Built for
 * general ecommerce, household goods and multi-variant cash-on-delivery offers.
 * The doc is appended VERBATIM to the builder system prompt.
 */
export const bazar: DesignWorld = {
	avoidFor: [
		"luxury",
		"law",
		"notary",
		"medical",
		"clinic",
		"dental",
		"finance",
		"funeral",
	],
	doc: `# DESIGN WORLD: BAZAR — the market stall, printed

## Philosophy
This page is a MARKET STALL that has been printed properly. Not a marketplace listing — a stall run by someone who paints their own signs, stamps their own boxes, stacks the goods so the best deal is physically bigger than the others, and shouts the price because the price is the point.

Two failure modes sit on either side. The cheap-deal page — flashing red URGENT bar, fake clock, screaming yellows, a green WhatsApp blob in the corner, a starburst PNG on the product — converts once and burns the merchant's credibility. The timid boutique page — white ground, 1px gray hairlines, 16px-radius cards, a whispered price — never converts at all, because a page that will not state its offer is assumed to be hiding something.

BAZAR is the third thing: LOUD and MADE. Every loud element is a physical object — a stamp, a crate, a tag, a plank, an awning, a slip of paper — with a border, an angle, and a shadow falling at a hard 45 degrees with zero blur.

AND THE OBJECTS ARE MARKET OBJECTS, NEVER PRINT-SHOP FURNITURE. This is the distinction that keeps the world from collapsing into a zine or a brutalist poster page, which is the nearest wrong answer and the easiest one to drift into. The vocabulary is a STALL — awning valances, crates, rope, hanging tags, painted boards, stamped slips, a crier's call — set on warm kraft with a real tooth. It is NOT the print shop: no registration crosses, no barcode rules, no halftone dot fields, no photocopy grain, no outline-stroke display type, no zine collage. Loudness here comes from spice colour, poster type scale and hand-placed angles; it never comes from reprographic ornament. The loudness comes from COLOR AREA and TYPE SCALE, never from alarm. Nothing flashes, nothing pulses, nothing lies. It is a full stall on a Friday morning, not a siren. What keeps it out of clown territory is repetition: THREE poles, ONE sticker shape, FOUR rotation angles, ONE shadow physics, FOUR rule weights, repeated forty times. Forty repetitions of one idea reads as a brand; forty ideas read as a mess.

## The vibe
The merchant is standing right there, and they are proud of the price. Copy is direct, concrete, generous, second-person, and never begs.
- Every headline states an OFFER or a FACT, never a mood. Not "Découvrez notre sélection" but "Deux pour le prix d'un. Jusqu'à dimanche." Not "Qualité supérieure" but "Livré chez vous. Vous payez à la porte."
- One word per headline gets a SLAB behind it (see typography): the deal word — the number, the free, the today, the two.
- Every claim carries a unit or a number that came from the brief: dinars, pièces, jours, wilayas, mois de garantie. An adjective doing sales work with no number behind it gets deleted.
- Micro-copy talks like a person at a counter: "Vous payez quand le livreur sonne." / "Un numéro, c'est tout ce qu'il nous faut."
- Validation errors are short and warm, never scolding: "Il nous manque votre numéro." / "Choisissez une wilaya, on calcule la livraison."
- Banned in every language: solutions, seamless, elevate, expérience as a vague noun, transformer, premium as an adjective about itself, révolutionnaire, exclusif when nothing is exclusive.
- Write in the brief's language. The voice survives translation because it is built from numbers and verbs, not adjectives.

## Visual signatures (what makes it instantly recognizable)
- COLOR BLOCKS, not sections: a vertical stack of full-bleed flat color fields — warm paper, a saturated pole, paper, a darker pole — cut at hard horizontal edges with zero gradient between them. Scrolled fast, the page is a striped awning.
- THE OFFER STAMP, the recurring object and the motif that travels: a rectangle, 2.5px ink border, ZERO radius, rotated to one of exactly four angles, two to four uppercase words, on a hard offset shadow with no blur. It recurs in the nav lockup, the hero, the bundle grid, on a seam, in the order slip and in the success state.
- PRICE THEATRE: the old price struck in ink-at-alpha, the new price at poster scale in the hot pole, and a HAND-DRAWN SVG CIRCLE looping around it — imperfect, overshooting itself, stroked live as you arrive.
- ONE BUNDLE IS PHYSICALLY BIGGER, and it stands straight while its neighbours lean. A DEALS TICKER of uppercase offers slides sideways forever between chapters.
- HARD OFFSET SHADOWS: every object casts 3px 3px or 4px 4px of solid ink at 0 blur. Photographs alone get a soft one, and they are CUT OUT AND PINNED behind a 6px paper outline plus a 2.5px ink border, radius min(var(--radius), 0px), one of them rotated -1.5deg.
- Nothing interactive is under 3.2rem tall. The page ends on a monument wordmark in the hot pole, clipped by the bottom of the document.

## Color physics (route the brief's palette through the fixed tokens — the physics is law)
FIXED TOKEN MAP — PAPER→--background · INK→--foreground · HOT→--primary · PAPER-ON-DEEP→--primary-foreground · DEEP→--secondary · GOLD→--accent · ink at 56%→--muted · INK→--border · 999px→--radius · DISPLAY→--font-heading · BODY→--font-body. These are the only CSS color/type/radius variables: every pole below is a prose role, literal register hexes belong only in these :root values, and every sibling or alpha step is a color-mix(in srgb, var(--foreground) N%, transparent), substituting the mapped fixed token for that pole, or a color-mix between two mapped fixed-token references. Every unmapped role below MUST reuse the nearest mapped token or such a mix; it never gets another custom property or literal. Non-color lean, shadow-offset and layout properties may keep their own custom properties. Any rgba(POLE, a) notation below is design shorthand for that color-mix, never emitted CSS.
A THREE-POLE SPICE RACK on warm paper. That deliberately overrides the global one-accent instinct: a market is polychrome. The discipline is that each pole has SEALED JOBS and they never trade. Build TEN tonal roles from the fixed tokens, never an eleventh hue — and the alpha ladder below introduces no hue of its own.
- PAPER: the palette's lightest warm pole, a kraft-tinted paper in the #F8EEDA / #F5E9D2 register. Never #fff, never a cool white.
- PAPER-DEEP: 4-6 RGB points warmer and darker (the #EFE0C4 register). Two jobs only — alternate blocks and input fills.
- INK: a warm near-black brown where R is greater than G is greater than B (the #241A0E / #2B1D0D register). Never #111. INK is every border, rule, shadow and headline.
- INK AT ALPHA is the only gray that exists: body rgba(ink,.76) · captions rgba(ink,.56) · tertiary rgba(ink,.40) · the struck price rgba(ink,.45) · placeholder rgba(ink,.34) · the stock-meter track rgba(ink,.16). A detached #888 is a correctness bug.
- HOT: the loudest spice pole — paprika, harissa, tomato (#D63A1E / #E0491C / #C42B2B register). Never pure #FF0000.
- GOLD: turmeric, saffron, honey (#EFA916 / #D99A2B register). Never pure #FFFF00.
- DEEP: the dark ground — burnt henna, deep olive, ink-teal, aubergine-brown (#5E1F16 / #24463A / #1D3B4A register), dark enough to carry cream text at 7:1.
- PAPER-ON-DEEP: a dedicated cream (#FBF2E0 register) for ALL text on saturated blocks. White is never used for text on this page.
- HOT-DEEP and GOLD-DEEP: siblings 14-18 percent darker, for pressed states and for text sitting on its own pole.
- ERROR introduces no alarm tone: the field gets a 4px var(--primary) bar on its inline-start edge and the message uses a contrast-safe color-mix between var(--primary) and var(--foreground) at full weight.

THE PROPORTION LAW — what stops three saturated poles from becoming a clown suit. By painted area: roughly 58 percent PAPER and PAPER-DEEP, 22 percent DEEP, 12 percent GOLD, 8 percent HOT. The hottest color is the SMALLEST area on the page. HOT covering a whole section ground means the law is inverted and the page reads as a discount flyer.

SEALED JOBS, assigned once. HOT: the new price, the drawn circle, the primary slab CTA, the price stamp, the affaire card's ground, the live total row, the stock-meter fill, the monument, the shadow under a checked pill. GOLD: stamp grounds, the trust block, star rows, LOT numerals, section numbers, the awning scallop, ::selection, ticker diamonds. DEEP: the crier bar, the ticker band, one inverted chapter, the WhatsApp CTA, the footer, the headline slab when the page needs a calmer emphasis than HOT. INK: every border, rule, hard shadow, headline and non-price numeral. Use at least twelve of those jobs; a pole that appears once is not a pole, it is a mistake.

Declare color-scheme:light and a theme-color meta matching PAPER — saturated blocks do not change it. ::selection is GOLD ground with INK text.

## Typography system
THREE families, three sealed jobs. Never Inter, Roboto or Open Sans. Load only the weights used.
- DISPLAY: a WIDE, HEAVY poster grotesk with a real 800 or 900 — the Archivo Black / Anton / Bricolage Grotesque Bold / Familjen Grotesk 800 / Syne Extrabold territory. Headlines, prices, stamp text, ticker, total, wordmark, monument. WIDE and heavy, not narrow: this world's shout is broad, which is what separates it from a gym page.
- BODY: a warm humanist workhorse at 400/600/700 — the Figtree / Work Sans / Cabin / Public Sans territory. Prose, labels, helper text, inputs, captions.
- SIGN: one printed-sign face used ONLY in stamps, LOT numbers and the crier bar — a wood-type slab or heavy geometric in the Alfa Slab One / Bevan / Zilla Slab Bold territory, ONE weight, UPPERCASE ONLY, never above 1.3rem. If the brief's pairing gives two faces only, SIGN collapses into DISPLAY 800 at +.04em tracking — never into BODY.

Scale, all clamp, all measured: hero h1 clamp(2.9rem,9.4vw,6.6rem)/.92/-.02em/800 · section h2 clamp(2.1rem,5.6vw,3.8rem)/.98/-.015em, max-width 15em · card h3 clamp(1.2rem,2.2vw,1.6rem)/1.1/700 · THE PRICE clamp(3.6rem,13vw,7.2rem)/.84/-.03em/800/tabular-nums · struck old price 1.5rem/600/rgba(ink,.45) · live total clamp(2rem,5vw,2.8rem)/800 · body 1.0625rem/1.62 · micro-caps .72-.84rem uppercase at .14-.22em/700 · stamp text .68-.92rem uppercase at .08em/800/1.05 · ticker items 1.1-1.25rem uppercase at .06em · monument clamp(3.6rem,17vw,15rem)/.82/900 filled HOT. The price and the h1 are the two largest things on the page and nothing else comes within 40 percent of them. Target a display-to-micro ratio of at least 9:1; a page whose biggest type is 3rem has not entered this world.

TRACKING IS A FUNCTION OF SIZE: -.03em on the price, -.02em above 80px, -.015em at 40-70px, -.005em at 24-30px, 0 at body, +.14em to +.22em at 11-14px uppercase.

THE SLAB WORD — this world's emphasis device, and it OVERRIDES the global "one italic word in the headline" rule, because a heavy poster grotesk has no usable italic. Exactly one word per headline, never two: display:inline-block; background HOT or DEEP; color PAPER-ON-DEEP; padding .06em .26em .12em; border-radius min(var(--radius), 0px); rotate -1.5deg; box-decoration-break:clone; plus a 3px 3px 0 INK shadow when it sits on paper. Pick HOT or DEEP once per page and hold it. It is RTL-safe and Arabic-safe, which is precisely why it exists.

NEVER LET A HEADLINE AUTO-WRAP — break every h1 and h2 into explicit line spans so the rag is authored, then reuse those spans as the masked-reveal targets.

PROMOTE EVERY NUMBER: any numeral inside a sentence (delivery days, warranty months, piece counts) is wrapped in a strong tag set in the DISPLAY face at 1.3rem inside a .98rem body line, tabular-nums. "Livraison en 48h" carries a display-face 48 inside a body-face sentence. That one rule is half of this world's market energy.

## Page chassis
- THE CRIER BAR: a full-bleed DEEP strip above the nav, height 2.6rem, holding an INFINITE MARQUEE of the day's real offers (never a centered static sentence) at .82rem uppercase, .16em tracking, 700, in PAPER-ON-DEEP, with GOLD diamond separators (an 8px square rotated 45deg), 30s linear infinite so it never synchronises with the 24s deals ticker.
- NAV — THE STALL FRONT: sticky, top 0, z-index 120, height 4.1rem, PAPER ground, no blur, no transparency games. Past 40px of scroll it gains a 3px INK bottom rule and the wordmark shrinks from 1.35rem to 1.15rem over .28s. That is the whole state machine: this nav is a painted board, not a piece of glass.
- WORDMARK IS A STAMP LOCKUP: the name in DISPLAY 800 uppercase at 1.35rem, tracking .02em, PAPER-ON-DEEP on a HOT slab, padding .16em .5em .2em, rotate -1.5deg, 2.5px INK border, 3px 3px 0 INK shadow. On hover the shadow closes to 1px 1px and the mark translates (2px,2px) over .12s — the wordmark itself is pressable.
- Nav row: flex, space-between, max-width 84rem, padding-inline var(--pad). Links .92rem/600 in rgba(ink,.76) going to INK with a 3px GOLD underline drawn from scaleX(0) over .2s. Right side: the WhatsApp pill. Below 820px the links vanish and only the wordmark and pill remain — no burger overlay is needed here.
- PAPER TOOTH: fixed, inset 0, z-index 95, pointer-events none, two layers — (1) an inline-SVG data URI of feTurbulence type fractalNoise baseFrequency 1.05 numOctaves 3 with feColorMatrix saturate 0, painted at opacity .5 on a 200x200 rect, the layer at opacity .10, mix-blend-mode multiply; (2) repeating-linear-gradient(0deg, transparent 0 2px, rgba(ink,.014) 2px 3px) as laid ruling. Three lines of CSS and the flat blocks stop looking like a screenshot of a color picker.
- Global base: html,body{overflow-x:clip}; scroll-behavior smooth; antialiased. :focus-visible is a 3px HOT outline at offset 2px, radius min(var(--radius), 0px). A skip link sliding from top:-4rem to top:1rem over .3s.
- THE COORDINATED NUMBERS — derive all five from the measured crier+nav stack (2.6 + 4.1 = 6.7rem), never guess them: hero min-height calc(100svh - 6.7rem) · sticky offsets top 5.6rem · scroll-margin-top 7.5rem on every anchor · the mobile order bar at 4.6rem · body padding-bottom calc(4.6rem + env(safe-area-inset-bottom)) below 900px so the footer is never covered.

## Hero forms (pick the one the offer calls for — every one is LOADED)
1. L'ÉTAL / THE STALL FRONT (default, strongest for one hero product). The hero ground is a full-bleed saturated block (DEEP by default; HOT only if it carries cream text at 7:1) with a printed poster frame inside it: a 2.5px PAPER-ON-DEEP border inset 12px from the block's edges, 8px on mobile. The page's first object is a printed sheet, not a hero section. Grid 1.08fr .92fr, gap clamp(1.8rem,5vw,4.5rem), align-items center, padding-block clamp(2.4rem,6vh,4rem) clamp(3.2rem,7vh,5rem).
LEFT COLUMN, max-width 34rem, carries the whole offer: THE OPENING STAMP (rotate -2.5deg, GOLD, three words) — this world opens on a STAMP, never on a letter-spaced micro-label with a rule; the hand-broken h1 with its slab word; a lede at clamp(1rem,1.4vw,1.15rem)/1.6 capped at 28em; THE PRICE THEATRE BLOCK in full; a CTA row holding the HOT slab CTA and the DEEP WhatsApp slab as equals, not primary and ghost; and one reassurance line at .88rem saying exactly what happens on submit. Seven differentiated pieces of commerce information before the fold.
RIGHT COLUMN IS A PINNED CUT-OUT, not a photo slab: the product at width min(100%,30rem), justify-self center, radius min(var(--radius), 0px), box-shadow 0 0 0 6px var(--background), 0 0 0 8.5px var(--foreground), 0 26px 60px -34px color-mix(in srgb, var(--foreground) 55%, transparent), rotate -1.5deg. A PRICE STAMP crosses its top corner at top:-1.4rem, inset-inline-end:-1.2rem, rotate 3.5deg, z-index 4. Behind it a GOLD burst — an inline-SVG 24-point star polygon at width 128 percent, opacity .9, rotating 90s linear infinite. That burst is the only purely decorative shape this world allows, and only here.
2. THE CRATE WALL (general ecommerce, household ranges — the default when the brief sells many items). Grid 1fr 1.15fr. Left: the headline plate on paper — stamp, h1, lede, one slab CTA scrolling to the offer grid. Right: a 2x2 crate grid at gap 3px where the gaps are INK showing through from the container behind (the welded grid), each tile a photograph with a paper caption strip along its bottom carrying name and price, and ONE tile spanning two rows so the grid has hierarchy instead of a metronome. The oversized tile carries a stamp.
3. THE POSTER (phone-first merchants, RTL pages). One column on a saturated block: opening stamp, h1 at poster scale, price theatre block, then the product frame at width min(100%,26rem) breaking OUT of the block's bottom edge by -3.5rem so it sits half on the block and half on the paper below, then the CTA row on paper. The only hero where copy may be centre-aligned, and even here the price block stays start-aligned.

EVERY HERO TERMINATES IN THE PLANK RAIL, never in whitespace: a full-bleed INK or DEEP strip, padding-block 1.05rem, four uppercase micro-facts at .8rem/.14em in PAPER-ON-DEEP each preceded by a GOLD 8px diamond, gap clamp(1.4rem,4vw,3rem), space-between above 720px and a 2x2 grid at .7rem below. Real facts from the brief — delivery, payment, warranty, returns — never adjectives.

## Section seams (the bazar's own vocabulary — every boundary uses one, never the same twice in a row)
Use at least five of these eight. This world escapes the card stack CHROMATICALLY and PHYSICALLY: color area and objects crossing edges, never whitespace.
- THE STALL CUT: a hard full-bleed ground change, zero gradient, zero radius, with a 3px rule of a DIFFERENT pole sitting exactly on the boundary (GOLD between paper and DEEP; INK between paper and GOLD). Four to six ground changes per page.
- THE AWNING: a scalloped or zigzag valance 26px tall hanging from the incoming block's top edge, painted with the OUTGOING block's applicable fixed token — var(--background), var(--secondary), var(--accent) or var(--primary) — so the two interlock; repeat that token directly at every stop and never create an outgoing color property. Scallop: height 26px; a radial-gradient circle at 50% 100%, transparent 0 13px and the chosen fixed token from 13px; background-size 34px 26px; repeat-x. Zigzag: paired 135deg and 225deg linear-gradients using that same fixed token to 50% and transparent after; background-size 30px 26px. ONE variant per page, held.
- THE TICKER STRIP: a 3.1rem DEEP band holding two identical chunks in a width:max-content track, translateX(-50%) over 24s linear infinite, items in DISPLAY 800 uppercase at 1.15rem with GOLD diamond separators, padding-inline 1.6rem, the duplicate aria-hidden. The cheapest anti-stack device on earth: instead of 7rem of nothing, a moving band of offers.
- THE STAMP BRIDGE: a sticker crossing a boundary — absolute, bottom -2.2rem (mobile -1.6rem), inset-inline-start clamp(1.1rem,8vw,6rem), z-index 6, rotate 2deg. Adjacent sections keep overflow visible while html and body clip the x axis, which is what makes it safe. One or two per page.
- THE CRATE WELD: the next section starts at padding-top:0 sharing the previous ground, separated only by a 3px INK rule, so two chapters read as one stall.
- THE PRICE-TAG NOTCH: an inverted triangle cut into a block's top edge — clip-path polygon(0 0, calc(50% - 26px) 0, 50% 22px, calc(50% + 26px) 0, 100% 0, 100% 100%, 0 100%) — pointing down at the CTA directly above it. Used once, at the page's most important handoff.
- THE ROPE: a 10px full-bleed strip of the three poles repeating — repeating-linear-gradient(90deg, var(--primary) 0 22px, var(--accent) 22px 44px, var(--secondary) 44px 66px) — used to OPEN a chapter, never to close one.
- THE COUNTER PAUSE (required exactly once): one section on plain PAPER with no color block, no stamp, no ticker, no CTA — a single large photograph, one sentence at clamp(1.3rem,2.6vw,1.9rem), nothing else. The world's only quiet moment, and what makes the loud parts read as loud. A page that shouts uniformly is silent.

## Layout physics
- ONE inline-padding token: clamp(1.1rem,4.5vw,4rem). Container 84rem. Section block padding clamp(4rem,9vh,7rem) — this OVERRIDES the global generous-whitespace instinct: a market is dense, and 11vh between chapters reads as an empty stall. Internal gaps come from a five-value ladder: .6 / 1 / 1.6 / 2.4 / 3.6rem.
- RULE WEIGHTS — four, one job each: 2.5px object borders (stamps, crates, pills, inputs, buttons) · 3px full-bleed seam rules and the nav bottom · 4px hero objects (the affaire card, the order slip frame, the total row) · 6px the paper outline around photographs. This OVERRIDES the global hairline habit: there are NO 1px rgba(ink,.16) hairlines here except the stock-meter track and the 2px separators inside a spec list. A hairline whispers, and nothing here whispers.
- RADIUS VOCABULARY — var(--radius) on every slab CTA, pill and stepper (:root sets --radius: 999px) · min(var(--radius), 0px) on stamps, crates, blocks, image frames and the ticker · min(var(--radius), .55rem) on inputs, selects and the textarea, because a perfectly square input reads as broken to a phone-first buyer. These var(--radius)-derived declarations are the sanctioned corner mechanism; a uniform 16px radius anywhere is a failure.
- HARD SHADOW PHYSICS — this OVERRIDES the global "shadows only on photographs, always large-blur" rule. Two systems that never mix: (a) HARD OFFSET, zero blur, solid INK — 3px 3px on stamps and pills, 4px 4px on slab CTAs and crates, 6px 6px on the affaire card, 1px 1px on any pressed state; subtract 1px from every offset below 600px. (b) ONE SOFT SHADOW, photographs only: 0 26px 60px -34px rgba(ink,.5). A soft shadow on a button, a card or the nav is a bug.
- ROTATION VOCABULARY — SEVEN values on the whole page and not one more, split into three sealed sets: FOUR stamp angles (-4deg, -2.5deg, 2deg, 3.5deg); ONE identity angle (-1.5deg) shared by the slab word, the nav lockup and the single rotated photograph; TWO lean angles (-1deg, 1.2deg) reserved for the flanking bundle cards. No stamp is ever at 0deg, no two adjacent stamps share a value, nothing rotates past 4deg — beyond that it stops reading as placed by hand and starts reading as broken CSS.
- THE STAMP CENSUS: at most SEVEN stamps per page, with assigned slots — (1) the hero opening stamp, (2) the hero price or savings stamp, (3) the affaire card's stamp, (4) one stamp bridge on a seam, (5) the order slip's step numerals as a cluster, (6) one margin note, (7) the success stamp. An eighth means removing another.
- NO GRID IS 50/50: hero 1.08fr/.92fr · crate wall 1fr/1.15fr · story rows .88fr/1.12fr · order chapter .92fr/1.08fr (the slip wider than the summary) · FAQ .78fr/1.22fr. Column gaps clamp(1.8rem,5vw,4.5rem). At least one grid must invert expectation.
- THE AFFAIRE GRID — the signature layout and the answer to rows of same-size cards. Above 960px: grid-template-columns .82fr 1.36fr .82fr, align-items center, gap clamp(1rem,2.4vw,1.8rem). The middle card is THE AFFAIRE: 66 percent wider, margin-block -2rem so it is taller on both edges, HOT ground with PAPER-ON-DEEP text, 4px INK border, 6px 6px 0 INK shadow, rotate 0 — it stands straight while the flanking cards lean at -1deg and 1.2deg on PAPER with 2.5px borders and 4px 4px shadows. A GOLD stamp is pinned at its top inset-inline-end at -1.4rem/-1.2rem, rotate 3.5deg. Below 960px the grid becomes one column, the affaire takes order:-1 so a phone meets the best deal first, its rotation stays 0, and its size advantage becomes a 4px border plus 1.4rem of extra padding.
- MEASURE IS CAPPED IN EM: body 34em, lede 28em, hero copy 34rem, card copy 22em, FAQ answer 38em, form helper 30em.
- OVERFLOW IS A COMPOSITIONAL DEVICE. Exactly five elements break their container: the hero price stamp at -1.4rem, the affaire stamp at -1.4rem, one stamp bridge at -2.2rem, the poster hero's frame at -3.5rem, and the GOLD burst at 128 percent width.
- PHOTOGRAPHY: bright, high-key, contrasty — filter saturate(1.06) contrast(1.05); never moody, never soft-lit. Every product image gets the paper outline plus ink border. IF AN IMAGE ROLE FAILS or image generation is unavailable, the frame still ships as a designed object: keep the 6px paper outline, the 2.5px ink border, the rotation and the price stamp, and fill the picture area with a LABELLED IMAGE SLOT — PAPER-DEEP at the frame's exact aspect-ratio with one DISPLAY 700 uppercase .8rem line naming the shot ("PHOTO PRODUIT · PLEIN CADRE"). Never draw a fake product, a starburst or an illustration to plug the hole. Type over an image always gets a DEEP scrim from rgba(deep,.62) to rgba(deep,.05) at 60 percent — dark only where the type sits. Parallaxed images are overscanned: top -9 percent, height 118 percent inside an overflow:hidden parent.
- RESPONSIVE COLLAPSE: below 960px every two-column grid becomes 1fr and the affaire goes first; below 720px the plank rail becomes 2x2; below 600px every shadow offset drops 1px, every stamp rotation halves toward zero (a -4deg stamp becomes -2deg) so nothing collides in a narrow column, and the price bottoms out at 3.6rem — never smaller, because the price is the page.

## Arabic and RTL adaptation (this market ships both)
- dir="rtl" on html, lang set correctly, and EVERY spacing property written logically: padding-inline, margin-inline, inset-inline-start, border-inline-start. No left or right anywhere.
- THE LEAN MIRRORS. Define --lean:1 in a later, separate :root block and --lean:-1 under [dir="rtl"], then author every rotation as calc(-2.5deg * var(--lean)) so a stamp leaning away from the reader in LTR leans the same way in RTL. Hard shadows mirror with it: 3px 3px 0 becomes -3px 3px 0. A page that keeps its LTR lean in Arabic looks translated, not designed.
- The hand-drawn price circle gets transform:scaleX(-1) in RTL so the pen's overshoot enters from the reading side. Marquees get animation-direction:reverse.
- NEVER LETTER-SPACE ARABIC: every .14em-.22em tracking value becomes 0 under [dir="rtl"], because tracking breaks the joins — the single most common Arabic failure. Micro-labels compensate with weight 700 and the GOLD color instead, at .84rem.
- Arabic display face: a heavy Arabic display in the Cairo / Tajawal / Almarai / Rubik-Arabic territory at 700-900. Sizes go up 6 percent and line-heights up .06 against the Latin values, because Arabic needs vertical room. The slab word works unchanged, which is exactly why it exists instead of an italic.
- Phone inputs, prices and the wilaya select keep dir="ltr" on the field itself inside an RTL page.

## Motion identity (GSAP 3 + ScrollTrigger from a CDN; native scroll — Lenis optional and unnecessary here)
THE SAFETY CONTRACT COMES FIRST. Compute reduced = matchMedia("(prefers-reduced-motion: reduce)").matches, hasGsap = typeof window.gsap !== "undefined", animate = hasGsap && !reduced. EVERY hidden initial state is set with gsap.set() INSIDE the animate branch — never opacity:0 in CSS. If the CDN fails, the page is fully visible, the price is printed and the form works. Add a prefers-reduced-motion CSS block that beyond the .01ms blanket sets the ticker and crier tracks to animation:none and width:auto, stops the burst rotation and the sway, and forces the drawn circle to stroke-dashoffset:0.

gsap.defaults({ease:"power3.out", duration:.7}) — this OVERRIDES the global 1.1s default. A market moves fast and confidently.

TIMING BANDS: 120-220ms interaction feedback · .28-.42s state changes and the stamp slam · .5-.7s entrances and reveals · .9-1.2s count-ups and the drawn circle · 3.2s the single ambient loop · 20-30s marquees. Eases: power4.out for slams and masked line rises, power3.out for entrances, power2.out for counters, power2.inOut for the drawn stroke, back.out(1.7) for the success stamp, sine.inOut for the sway, none for scrub.

THE STAGGER LAW: .06 everywhere. Not .09, not .12 — .06. Quick, confident, almost simultaneous. Groups larger than eight stagger at .04 so the group still lands inside .5s. TRAVEL IS SHORT: y offsets of 14 / 18 / 22 / 26 only; scales of .96 / 1.02 / 1.08 / 1.15 / 1.18; press translate (2px,2px); hover lift translate(-3px,-3px). Nothing travels 100px.

THE MANDATORY SET:
1. HERO ENTRANCE — one timeline, overlapping positions, complete in about 1.4s. Set headline lines yPercent 112 inside overflow:hidden masks with padding-bottom .06em and margin-bottom -.06em so descenders survive; copy and CTA row autoAlpha 0, y 18; the product frame autoAlpha 0, y 26, scale .96 with its inner image at scale 1.1; every stamp autoAlpha 0, scale 1.15, rotate 0; rail items autoAlpha 0, y 14. Then tl.to(lines,{yPercent:0,duration:.62,stagger:.06,ease:"power4.out"},0).to(frame,{autoAlpha:1,y:0,scale:1,duration:.8},.16).to(frameImg,{scale:1,duration:1.2,ease:"power2.out"},.16).to(copy,{autoAlpha:1,y:0,duration:.55,stagger:.06},.26).to(stamps,{autoAlpha:1,scale:1,rotate:(i,el)=>el.dataset.rot,duration:.4,stagger:.09,ease:"power4.out"},.6).to(rail,{autoAlpha:1,y:0,duration:.5,stagger:.06},.92).
2. THE STAMP SLAM — the signature reveal, applied to EVERY sticker, at start "top 88%", once:true: from autoAlpha 0, scale 1.15, rotate 0 to autoAlpha 1, scale 1, its authored rotation (read from a data attribute), duration .4, ease power4.out. Excellent addition: tween two custom properties --sx and --sy from 0px to 3px across the same .4s so the ink shadow spreads out from under the stamp exactly as it lands.
3. THE PRICE THEATRE CHAIN — the showpiece, exactly ONCE per page (hero, or the order card if the hero has no price). Trigger "top 78%", once, about 2.1s total: (a) the old price fades in from autoAlpha 0, y 8 over .35s; (b) at +.25s its strike DRAWS — a ::after bar, height 3px, background rgba(ink,.45), at 52 percent height, width 0 to 106 percent over .3s power2.inOut, transform-origin inline-start, with a real text-decoration:line-through as the no-JS fallback; (c) at +.4s the new price COUNTS UP from 0.62 times the target over .95s power2.out via a proxy object, its wrapper scaling 1.08 to 1, every frame through the DZD formatter; (d) at +.75s the drawn circle strokes on; (e) at +1.6s the savings stamp slams. A 3800ms setTimeout fallback paints the final price and clears the dashoffset if the trigger never fires on a deep-linked load, and the true price is hard-coded in the HTML so a no-JS visitor reads truth, never 0.
4. THE DRAWN CIRCLE — an inline SVG, viewBox 0 0 260 130, preserveAspectRatio none, absolute, inset -14% -8%, width 116 percent, z-index 0 behind the numerals, pointer-events none. TWO stroked paths sharing one hand-authored d that is an IMPERFECT loop: unequal control points, a 12-unit gap where it fails to close, a 20-unit overshoot past the start so the line crosses itself — in the register of M28,66 C30,30 92,12 142,14 C196,16 240,34 238,64 C236,96 176,116 122,113 C66,110 22,96 26,64 C29,44 44,28 68,20. Both carry pathLength="1", stroke-linecap round, fill none, vector-effect non-scaling-stroke. Path one: stroke HOT, width 5.5, dasharray 1, dashoffset 1 to 0 over .62s power2.inOut. Path two: the same d translated (3,-2), width 2.2, opacity .45, drawn .12s later over .5s — the second pass of a pen. NEVER draw this with border-radius:50% on a div; the imperfection IS the device.
5. GENERIC REVEALS — mark roughly sixteen elements: gsap.set autoAlpha 0, y 22, then to autoAlpha 1, y 0, duration .6, stagger .06, start "top 88%", once:true.
6. THE BLOCK WIPE — at most TWO per page, on saturated blocks: the ground painted by a ::before at clipPath inset(0 100% 0 0) going to inset(0) over .55s power3.inOut at start "top 82%", once. Under [dir="rtl"] the inset flips sides.
7. ONE SCRUBBED MOMENT: the hero product image at yPercent -6 to 6, ease none, scrub true, trigger the hero, start "top bottom", end "bottom top" — funded by the 118 percent / -9 percent overscan.
8. ONE PINNED MOMENT, desktop only (matchMedia-gated at min-width 1024px so it never initialises on touch): THE CRATE RAIL — a horizontal track of product crates pinned for the section's height, translateX from 0 to -(track.scrollWidth - window.innerWidth), scrub 1, pin true, anticipatePin 1. Below 1024px the same track is a native scroller with scroll-snap-type x mandatory and scroll-snap-align start on each crate. If the brief sells one product only, skip this and let the scrubbed parallax carry the requirement.
9. COUNT-UPS on every number that is a fact from the brief — price, savings, pieces remaining, delivery days, wilayas served, the live total: .95s power2.out, tabular-nums, routed through the DZD formatter. Never count up an invented number.
10. THE TICKERS — CSS keyframes, never GSAP: deals band 24s linear infinite, crier bar 30s, two duplicated chunks in a width:max-content track. Pausing on prefers-reduced-motion is mandatory.
11. THE ONE AMBIENT LOOP — THE HANGING SWAY, and only one element on the page does it: a single stamp or price tag with transform-origin 12% 8% rocking between its authored angle minus 1.2deg and plus 1.2deg over 3.2s sine.inOut yoyo repeat -1. Everything else is still.

once:true on everything non-scrubbed; nothing re-animates on scroll-up. Nothing pulses, flashes, blinks or scales a CTA forever to demand attention — that is the discount-page tell this world exists to kill.

MICRO-INTERACTION KIT (all CSS, all inside the bands):
- PRESS PHYSICS, the core interaction, on every slab CTA, crate and stamp-like button: default 4px 4px 0 INK; :hover translate(-3px,-3px) with the shadow opening to 7px 7px over .18s; :active translate(2px,2px) with the shadow closing to 1px 1px over .12s. Touch devices get the active state, not the hover.
- PILLS: unchecked is PAPER, 2.5px INK border, no shadow. :has(input:checked) gives INK ground, PAPER text, a 3px 3px 0 HOT shadow (the shadow changes COLOR, not just size) and scale 1.02 over .2s.
- Nav underline: a 3px GOLD bar from scaleX(0), origin inline-start, over .2s.
- Inputs on focus change three things over .16s: border-color to HOT, box-shadow 0 0 0 3px rgba(hot,.22), and the fill lightening from PAPER-DEEP to PAPER.
- The quantity output pops scale 1.18 to 1 over .22s back.out(2) on every change.
- Validation entrance: opacity 0, y -3px to visible over .2s with min-height 1.25em reserved so NOTHING reflows.
- Accordion: grid-template-rows 0fr to 1fr over .42s with an overflow:hidden inner; the icon is two 3px INK bars, the second rotating 90deg to 0 over .28s.

## Components
- SLAB CTA (the only action-button treatment): border-radius var(--radius), 2.5px INK border, HOT ground, PAPER-ON-DEEP text, DISPLAY 800 uppercase .95-1.05rem, tracking .04em, padding 1.05em 1.7em, min-height 3.4rem, inline-flex gap .6em, 4px 4px 0 INK shadow, press physics above, full width on mobile. The secondary action is a DEEP slab of the same shape — this world has NO ghost buttons and no thin-bordered outline buttons; every action is a solid object. Disabled is opacity .42 with the shadow removed.
- PILL: border-radius var(--radius), min-height 3.2rem, min-width 3.2rem, padding .8em 1.3em, 2.5px INK border, DISPLAY 700 at .95rem. Variants, quantities, filters and the WhatsApp CTA share the theme knob with every action.
- THE CRATE (this world's card): PAPER, 2.5px INK border, radius min(var(--radius), 0px), padding clamp(1.1rem,2.4vw,1.6rem), 4px 4px 0 INK shadow, a 6px GOLD strip welded along its top edge. Inside: the photograph in its paper-outlined frame, a space-between row with the name in DISPLAY 700 and the price in DISPLAY 800 tabular-nums, a .78rem line in rgba(ink,.56), and a LOT numeral in GOLD in the corner. Grid repeat(auto-fit,minmax(15rem,1fr)) at gap clamp(1rem,2.4vw,1.8rem) — and ONE cell in every grid is oversized. On hover the crate lifts per the press physics and its top strip grows 6px to 10px over .18s.
- INPUTS: min-height 3.4rem (never smaller in a phone-first cash market), radius min(var(--radius), .55rem), 2.5px INK border, PAPER-DEEP fill, 1.05rem body face, padding .9em 1rem. Labels above at .74rem uppercase, .16em tracking, 700, rgba(ink,.56), margin-bottom .5rem. Helper .82rem.
- SELECT: the same box, appearance:none, with the chevron DRAWN as an inline SVG in a ::after on the wrapper at inset-inline-end 1rem — never a background-image arrow, because that cannot flip for RTL.
- TRUST ICONS ARE DRAWN — four inline SVGs at 26x26, stroke currentColor, stroke-width 2.2, stroke-linecap square, fill none: a delivery van (box body, cab, two wheels), a hand under a banknote, an arrow curving back into a box, a shield with a check. Each centred in a 3.2rem square with a 2.5px INK border on GOLD, radius min(var(--radius), 0px), alternating members rotated -2deg and 2deg. Never emoji, never an icon font.
- ACCORDION (FAQ): a list separated by 2.5px INK top rules, the question a full-width flex button in DISPLAY 700 at clamp(1.05rem,1.8vw,1.25rem), padding-block 1.2rem, turning HOT on hover and when open, single-open with aria-expanded maintained.
- FOOTER: a DEEP block opened by THE ROPE, a three-column info grid at gap 2.4rem with GOLD micro-cap headers and PAPER-ON-DEEP values, a WhatsApp slab, then THE MONUMENT — the wordmark in DISPLAY 900 at clamp(3.6rem,17vw,15rem), line-height .82, filled HOT, user-select none, aria-hidden, the block at overflow:hidden and the mark at margin-bottom -.18em so THE PAGE ENDS MID-LETTER. Then a 3px INK rule and a credit line at .78rem in rgba(paper-on-deep,.5).
- CRAFT DETAILS: explicit width and height on every image, fetchpriority high on the hero image and loading lazy elsewhere, descriptive alt on content images and aria-hidden on decorative ones, aria-live polite on error and total text, an output element for the quantity, sr-only labels on star rows, a skip link, and an inline-SVG data-URI favicon built from the stamp shape.

## Conversion objects (this world exists to SELL — these are its money components)
- THE PRICE THEATRE BLOCK, top to bottom: (1) the struck old price at 1.5rem/600 in rgba(ink,.45) with its drawn strike; (2) the new price at clamp(3.6rem,13vw,7.2rem) in HOT, DISPLAY 800, tabular-nums, with the currency mark AFTER the numeral in the DISPLAY face at .30em, weight 800, tracking .06em, in INK not HOT — so the numeral stays the loudest object on the page; (3) the hand-drawn circle wrapping rows 1 and 2; (4) a GOLD savings stamp at rotate -2.5deg reading the exact saved amount, computed from the brief's two real numbers and never invented. Under it, one line at .88rem saying what the buyer pays and when.
- DZD FORMATTING LAW: thousands separated by a THIN SPACE (U+202F), never a comma, never a period — 3 500 DZD, 12 900 DZD. Write ONE formatter and route every price, total, saving and count-up frame through it. tabular-nums on every number that can change. Never round a brief price, never invent a decimal.
- THE ORDER SLIP is the climax and it is a PRINTED FORM, not a card: a PAPER-DEEP block with a 4px INK frame and a 10px PAPER inset border, grid .92fr 1.08fr above 900px, one column below. Its head is a stamp reading the local phrase for "order form", rotate -2.5deg, half-crossing the frame's top edge.
- THE FIELDS, in this order, each a designed object — PHONE FIRST, always, because it is the merchant's only real channel and a half-abandoned form that still carries a number is a lead. PHONE — type="tel", inputmode="tel" (this world overrides the global inputmode=numeric suggestion: tel gives the phone keypad a buyer here expects), autocomplete tel, a real pattern, placeholder in the local format 0X XX XX XX XX, and dir="ltr" on the field itself so the digits never reverse on an Arabic page. FULL NAME (autocomplete name, the label naming who receives the package). WILAYA — a styled select; the wilaya list is geography, not a business claim, so it may be populated in full, but every delivery FEE, DELAY and zone availability shown beside it is a business fact and comes ONLY from the brief. ADDRESS — a textarea at 3 rows minimum whose helper asks for the landmark a driver would actually use. QUANTITY — a stepper. VARIANT — pills. DELIVERY CHOICE — radio slabs, and only if the brief names both options.
- STEP STAMPS: 01 / 02 / 03 in GOLD in the slip's inline-start gutter at rotate -2.5deg / 2deg / 3.5deg, one per field group. Typesetting, not claims.
- VARIANT AND QUANTITY PILLS: real radio inputs visually hidden (never display:none — keyboard focus must survive), state via :has(input:checked), min 3.2rem tall so a thumb never misses, flex-wrap at gap .6rem. Color variants carry a 1.15rem swatch dot with a 2px INK ring; size and model variants carry text only. A sold-out variant is disabled at opacity .4 with a diagonal 2px INK line across it — and only exists if the brief says it is sold out.
- QUANTITY IS A STEPPER, not a number input: an inline-flex group at border-radius var(--radius) with 3.2rem true-circle INK-bordered buttons at 50% and an output element at min-width 3rem in DISPLAY 800 at 1.3rem. If the brief states a per-order cap, enforce it and give the reason in one human sentence.
- THE LIVE TOTAL: a row welded to the slip's foot with a 4px INK border, HOT ground, PAPER-ON-DEEP text, space-between, padding 1.1rem 1.3rem — label in DISPLAY 700 uppercase .86rem, amount in DISPLAY 800 at clamp(2rem,5vw,2.8rem) tabular-nums, recomputed on every quantity, variant and delivery change with a .22s scale pop.
- THE DELIVERY LINE SITS DIRECTLY ABOVE THE TOTAL AND THE SUBMIT, never in an FAQ and never below the fold, because "combien et en combien de temps chez moi" is this buyer's first question: a 2px INK-ruled two-cell row written the moment a wilaya is chosen — the FEE on the start side and the DELAY on the end side, terms in DISPLAY 700 uppercase .76rem in rgba(ink,.56), values in DISPLAY 800 at 1.15rem tabular-nums, cross-fading over .22s on change. Every figure in it is a business fact from the brief; when the brief prices no zone, the row states the brief's single flat term and no per-wilaya number is invented.
- STICKY MOBILE ORDER BAR (required below 900px): fixed, inset-inline 0, bottom 0, height 4.6rem plus safe-area padding, z-index 130, PAPER ground with a 3px INK top rule, grid auto 1fr at gap .8rem, padding-inline var(--pad). Left: the struck old price at .78rem above the live price in DISPLAY 800 at 1.35rem in HOT. Right: the slab CTA filling the remaining width at height 3.4rem. It enters when the hero's bottom crosses the viewport top — a ScrollTrigger on the hero at start "bottom top" toggling a class that animates yPercent 100 to 0 over .32s power3.out — and it LEAVES while the order slip is in view, so it never covers the real form.
- WHATSAPP CTA — prominent, and styled to this palette: never #25D366, never a round floating green blob, never an image icon. It is a DEEP slab (or the palette's own green pole if the brief supplies one) with PAPER-ON-DEEP text, a 2.5px INK border, a 4px 4px 0 INK shadow and a 20px inline-SVG glyph you draw yourself — a rounded speech bubble with a handset inside. Two placements, both required: a pill in the nav, and a full slab beside the order slip as the second ordering path. The href is a wa.me link carrying the brief's number and a prefilled message naming the product and chosen variant, rebuilt by JS whenever the variant changes. If the brief gives no WhatsApp number, the button does not exist — a phone number is never invented.
- TRUST STRIP: a full-bleed GOLD block with 3px INK rules on both edges, four items in a flex row (2x2 below 720px) at gap clamp(1.2rem,4vw,2.6rem), each a drawn icon square beside a DISPLAY 700 .82rem uppercase label and a .8rem sub-line in rgba(ink,.62). All four are FACTS from the brief.
- STOCK AND COUNTDOWN HONESTY — the rule that separates this world from every discount template. A stock meter exists ONLY if the brief states a real remaining quantity: a 10px track in rgba(ink,.16) with a HOT fill whose width JS writes once, plus a plain-language label. It is a STATED FACT, never a bar that shrinks while you watch. A countdown exists ONLY if the brief gives a real end date or time for a real promotion; then it is a row of INK-bordered digit boxes on GOLD with tabular numerals, no red, no flashing, no pulsing, and one line saying exactly what changes at zero. No date in the brief means NO TIMER. And under no circumstance a red URGENT banner across the top — the global ban holds with full force, and this world is precisely where it is most tempting to break it.
- VALIDATION IS BLUR-GATED: keep a touched map so an error appears only after a field's first blur, never while someone is still typing. Full warm sentences, aria-live polite, space reserved.
- SUBMIT: an 800ms pending state where the label becomes a present-tense human sentence, then the slip CROSS-FADES IN PLACE into a success panel absolutely positioned over it in the same box — the slip leaves over .4s to y -10px with visibility 0s .4s so focus never lands on a hidden element; the success side arrives over .5s with a .2s delay. The panel opens on a giant success STAMP at rotate -3deg entering from scale .8 and autoAlpha 0 over .5s back.out(1.7), the order number beneath it in tabular numerals at 2.4rem, and copy echoing the buyer's own name, wilaya, variant and quantity alongside the amount they will hand to the driver. Store the order in localStorage; on return, paint the success state INSTANTLY with no animation so a buyer is never asked to order twice. And the instant validation passes — as the stamp slams — the stall calls the order back to the wandit runtime by dispatching the wandit:lead CustomEvent on document with the buyer's fields flat in detail (name, phone as typed, wilaya, commune, plus variant and quantity), while one off-canvas decoy input marked data-wandit-hp hangs in the slip, never read by the page's own script.
- CROSS-SECTION STATE LINKS: every bundle card's CTA writes its variant and quantity into the order slip, updates the total and the WhatsApp message, then smooth-scrolls to the slip — and the chosen card's stamp flips to the local word for "chosen" with a .28s stamp slam. Sections talk to each other.

## Editorial furniture (REQUIRED — this is the bazar's voice)
- THE CRIER LINE: the announce marquee written as a market call in the brief's language, made of real offers separated by GOLD diamonds.
- OFFER STAMP COPY: two to four uppercase words, always a fact — the discount, the bundle, the free delivery, the warranty. Never "BEST" or "TOP" or a decorative word.
- LOT NUMBERS: LOT 01 / LOT 02 in GOLD in every crate's corner and under every framed photograph, in the SIGN face at .74rem. Pure typesetting, invents nothing.
- THE HANGING PRICE TAG: a small inline-SVG tag — a rectangle with one notched corner and a punched hole — hanging off the inline-start edge of one product frame, carrying the price. Drawn, never an image, and it is the element that gets the single ambient sway.
- THE MARGIN NOTE: one small PAPER stamp at rotate 3.5deg carrying a single human sentence built from the brief's own facts, placed in a margin the way a shopkeeper writes on a box.
- THE SHOUT LINE: exactly one chapter opens with a single uppercase line at poster scale, no punctuation, no paragraph beneath it, alone on a color block.
- FIG-STYLE CAPTIONS: under every framed photograph, a space-between row — a descriptive phrase in rgba(ink,.56) at .78rem on the start side, the LOT number in GOLD on the end side.
- SPEC ROWS: a zero-row-gap two-column list separated by 2px INK rules, the term uppercase in GOLD at .76rem, the value in INK with its numeral promoted to the DISPLAY face.
- REVIEWS (only from the brief): the quote in DISPLAY 700 at 1.2rem inside a PAPER crate with a GOLD star row above and an uppercase .78rem citation, cards rotated -1deg and 1.2deg alternately in a grid — never a carousel.
- None of these invent a business fact. They are TYPESETTING. If the brief is thin, use fewer of them rather than making something up.

## Explicit overrides of the global builder rules (each is argued above — this is the roll-call, and every one must be declared in an HTML comment beside the code that does it)
1. Global: one dominant ground plus ONE accent. HERE: three sealed spice poles under the proportion law (58 paper · 22 deep · 12 gold · 8 hot). The discipline is the sealed jobs and the areas, not scarcity of hue.
2. Global: shadows only on photographs, always large-blur. HERE: HARD OFFSET shadows, zero blur, solid ink, on every object; exactly one soft shadow exists and it belongs to photographs.
3. Global: mid-radius rounded cards. HERE: three treatments with sealed jobs — min(var(--radius), 0px) on objects, var(--radius) on every action and pill, min(var(--radius), .55rem) on form fields only.
4. Global: 1px hairlines as the separator habit, and at most ONE hairline seam per page. HERE: four rule weights (2.5 / 3 / 4 / 6px) and effectively no hairlines at all. The STALL CUT's 3px rule is not the banned weakest seam — it sits on a hard full-bleed GROUND CHANGE and is never a rule floating in whitespace, which stays banned here as everywhere.
5. Global: generous whitespace between chapters. HERE: clamp(4rem,9vh,7rem) — a market is dense, and the seams carry the transitions instead of empty space.
6. Global motion defaults. HERE: gsap.defaults duration .7 with a .06 stagger law; interaction feedback runs 120-220ms.
7. Global: one italic word inside a big headline. HERE: no usable italic exists in a heavy poster grotesk — the SLAB WORD replaces it, and it is RTL-safe and Arabic-safe, which is why it exists.
8. Global: inputmode numeric on the phone field. HERE: inputmode tel.
9. Global: no hand-drawn SVG illustrations. HERE: the four trust icons, the WhatsApp glyph, the select chevron, the hanging price tag, the gold burst and the hand-drawn price circle are DRAWN inline SVG — they are marks and ornament in the world's own stroke language, never imagery. The ban holds absolutely for anything standing in for a PHOTOGRAPH: no drawn products, no mascots, no clipart, no illustrated scenes, no drawn logo. A missing photo becomes a labelled image slot.
10. Global: count-up numerals on stats and prices. HERE the price DOES count up once, inside the price-theatre chain, and only there — every other number is printed. The live total never counts up; it pops scale 1.08 to 1 over .22s.

## Bazar ban list (in addition to the global one)
A red URGENT banner or any alarm strip · a countdown with no real end date in the brief · a stock number, an "only 2 left" or a viewer count the brief did not state · anything that flashes, blinks, pulses forever or scales a CTA on a loop to nag · the default WhatsApp green #25D366 and the floating round green blob · gradients as decorative fills or section grounds (the rope and the awning are repeating PATTERNS, not blends; the only other gradient allowed is the type scrim over a photograph) · glassmorphism, backdrop blur, neon glows, soft ambient light of any kind · soft drop shadows on cards, buttons, stamps, pills or the nav · 1px gray hairlines and detached grays that are not alpha-of-ink · a uniform 12-16px radius as the page's only shape · rows of identical same-size cards with no oversized cell · a stamp at 0deg, a rotation beyond 4deg, more than seven stamps, or two adjacent stamps sharing an angle · a perfect border-radius:50% circle standing in for the hand-drawn one · emoji, icon fonts, clipart, starburst PNGs or a sale badge that is an image · REPROGRAPHIC FURNITURE OF ANY KIND — registration crosses, crop marks, barcode rules, halftone dot fields, photocopy grain, colour-bar strips, zine collage, outline-stroke display type (this world is a stall, not a print shop, and that drift is its nearest wrong answer) · pure #FF0000, pure #FFFF00, purple or violet in any role · a hero that is headline plus paragraph plus one button plus a photo · centred body copy anywhere except the poster hero's lede and the footer credit · testimonial carousels · per-character text splitting · more than ONE ambient loop, ONE scrubbed moment and ONE pinned rail · any hidden state authored in CSS · letter-spaced Arabic.

## Intensity
This world fails in two directions and both are easy. Pull back and it becomes a beige page with an orange button: every stamp straightened, every shadow softened, the price shrunk to 2rem, the color blocks replaced by white sections with hairlines. Push carelessly and it becomes the discount flyer it exists to replace: a red banner, a fake clock, three saturated colors fighting at equal area, a pulsing CTA.

The 100 percent version sits precisely between them and is unmistakable — warm paper with a real tooth, a stripe of saturated blocks reading down the page like an awning, a headline with one word slabbed in ink-bordered color, a price at 7rem with a crooked pen circle drawing itself around it as you arrive, offer stamps landing at four fixed angles with their ink shadows spreading out beneath them, ONE bundle physically larger than its neighbours and standing straight while they lean, a ticker of real offers running the page's width, thumb-sized pills, a printed order slip with stamped step numbers, and a hot total row that recomputes with a small confident pop. It looks like the best stall in the market: the one run by someone who knows their prices are good and prints their signs properly. Push INTO the specificity. Every number above is load-bearing.`,
	energy: "loud",
	family: "bazar",
	id: "bazar",
	industries: [
		"ecommerce",
		"gadgets",
		"tools",
		"auto",
		"home-goods",
		"kitchen",
		"appliances",
		"fashion",
		"accessories",
		"beauty",
		"baby",
		"toys",
		"food",
		"delivery",
	],
	kind: "product",
	mood: ["loud", "saturated", "hand-stamped", "generous", "market-warm"],
	name: "Bazar",
	preview: {
		ground: "#F8EEDA",
		ink: "#241A0E",
		accent: "#D63A1E",
		fontFamily: "Archivo Black",
		sampleWord: "BAZAR",
	},
	priceFeel: "accessible",
	tagline:
		"Spice-hot color blocks on warm paper, offer stamps slammed on at an angle like a stall's hand-painted signs, and your price so big it gets a crooked ink circle drawn around it — a page that shouts the deal and still looks made by hand.",
};
