import type { DesignWorld } from "./types";

/**
 * CARGO — the drop. Streetwear release energy for single-product COD pages:
 * a condensed wordmark cropped by the viewport edge, product plates tilted off
 * the grid, stamps and shipping-label furniture, duotone lookbook frames on one
 * scrubbed horizontal rail, and an order form typeset as a shipping manifest
 * that ends with a stamp. The loud, accessible pole of the COD library.
 * The doc is appended VERBATIM to the builder system prompt.
 */
export const cargo: DesignWorld = {
	avoidFor: [
		"law",
		"notary",
		"medical",
		"luxury-classic",
		"wedding",
		"funeral",
		"insurance",
		"spa",
	],
	doc: `# DESIGN WORLD: CARGO — the drop

## Philosophy
This page is a DROP, not a product page. It has the physics of release day: a poster pasted at 4am, a shipping label printed at 5, a locker door covered in stickers, a size run going out of stock in public. The product is not presented — it is RELEASED, with a code, a date, a run size, and a strike through whatever is gone.

Four devices generate the world; everything else follows.
- THE CROP — the name set at a scale the viewport cannot contain and cut by the edge of the screen. A letterform sliced mid-stroke is the loudest, cheapest statement available here.
- THE TILT — plates, stamps and stickers off the grid at a small authored angle. The grid is real and rigid; exactly the right things break it.
- THE TAPE — var(--primary) shipping tape carrying repeated mono text slapped across section boundaries. Seam, ornament and marquee at once.
- THE MANIFEST — codes, barcodes, weights, dates and lot numbers as editorial furniture, ending in a cash-on-delivery form typeset as a shipping manifest.

The failure this world kills is the generic sneaker landing page: a centred product on a soft gradient, three rounded cards with icons, a size dropdown, a green WhatsApp bubble, the word "collection". The loudness is DISCIPLINED — ONE TAPE hue, TWO type registers, ZERO radius on containers, SIX legal rotations, ONE horizontal rail, snap timings under 200ms. One idea repeated thirty times reads as a brand; thirty ideas read as a mess.

SIX GLOBAL BUILDER RULES ARE DELIBERATELY OVERRIDDEN HERE — declare each before writing CSS:
- Overrides the global timing bands: feedback 120-180ms, state 220-300ms, entrances 320-480ms. Only one closing move (600ms), the image settles (900ms) and the marquees exceed 480ms. A 1.2s entrance is a correctness bug in this world.
- Overrides "count-up numerals on view": the price NEVER counts, it lands in one hit. Only an honest claimed-units number from the brief may count, and it counts on SCROLL, not on a clock.
- Overrides the global tolerance for mid-radius containers: every CTA, size pill and chip consumes var(--radius); containers, plates, frames and form fields cap it at 0; progress tracks cap it at 2px; true status dots use 50%.
- Overrides the global shadow discipline in the strictest direction: NO shadows at all — no blur, and no hard offset either (that belongs to another world). Depth is OVERLAP, z-index and tape. Any box-shadow that is not a focus ring or the autofill neutraliser is a bug.
- Overrides the global editorial-italic emphasis: condensed faces have no usable italic and Arabic has none. Emphasis is one of three devices named in Typography — pick ONE per page.
- Overrides the seam vocabulary in one direction: ZERO whitespace-plus-hairline seams (the global rule allows one). Hairlines exist only INSIDE tables and spec rows, never as a boundary.

## The vibe
Release-day. Fast, flat, in-the-know, never trying to be liked. The merchant is not selling a lifestyle; they are telling you what exists, how many, in what sizes, and when it goes. Copy rules, non-negotiable — they carry 40 percent of this design:
- HEADLINES ARE 2-5 WORDS, uppercase, and either a NAME, a COMMAND or a FACT: "DROP 001." / "TOUT EST LÀ." / "PLUS QUE 40 PIÈCES." / "TU PAIES À LA LIVRAISON." Never a subordinate clause, never a benefit sentence.
- EVERY OBJECT HAS A CODE — LOT 02 / NOIR / 120 PIÈCES. The format is typesetting; the facts inside it come only from the brief. Dates are stamps (14.03 · 18H00), never "bientôt disponible"; no date in the brief means no date on the page.
- SIZES ARE A RUN: XS S M L XL XXL, with anything the brief says is gone STRUCK THROUGH, not hidden. Honest scarcity is the voice; invented scarcity is banned.
- Micro-copy is STENCILLED: PAIEMENT À LA LIVRAISON · 58 WILAYAS · ÉCHANGE 7 JOURS · POIDS 480 G. Validation errors are blunt and human, four words maximum: "Numéro incomplet. 10 chiffres." / "Il manque ta taille."
- Banned in every language: solutions, expérience, élégance, premium, luxe, seamless, elevate, transform, révolutionnaire, "n'hésitez pas", "notre équipe est à votre écoute". Exclamation marks: maximum TWO on the page — the type already shouts.
- Write in the brief's language. In Arabic the voice is carried by weight, var(--primary) and the stamp furniture, never by letter-spacing.

## Visual signatures (what makes it instantly recognizable)
- THE CROPPED WORDMARK: the product or brand name in a condensed face at clamp up to 16vw, on one line, bled past ONE viewport edge so the last letter is cut mid-stroke. Not centred, not contained, not "responsive-safe".
- THE MISPRINT: display type carrying one off-register TAPE ghost — text-shadow .035em -.035em 0 var(--primary) — as if the second screen-print colour landed a millimetre off. Two elements per page, never three.
- TILTED PLATES at one of six legal rotations, sitting over rules and over each other; full-bleed var(--primary) TAPE of repeated mono text crossing boundaries at a slight angle.
- STAMPS AND STICKERS drawn in SVG and always overlapping something: a circular DROP roundel with text on a path, a rotated rectangular date stamp, a SOLD OUT strike. BARCODES AND LABELS as furniture: a drawn barcode rule, a FROM/TO label block, a perforated tear line.
- DUOTONE LOOKBOOK — every lifestyle frame in two tones, ink in the shadows and var(--primary) in the highlights. Full colour exists only on the product cut-out and merchant logos.
- A SIZES TICKER at the hero's floor, and a bordered grid of size pills at border-radius var(--radius), with struck sold-out states. Those pills share the page's token-borne round silhouette with CTA slabs.
- The page ends mid-letter: the closing wordmark clipped by the bottom of the document, a barcode above it.

## Color physics (route the brief's palette through the fixed tokens — the physics is law)
FIXED TOKEN MAP — ASPHALT or BOX→--background · the opposite type pole→--foreground · TAPE→--primary · the dark pole→--primary-foreground · GROUND-2→--secondary · the inverted-ground pole→--accent · type colour at 56%→--muted · type colour at 14%→--border · 999px→--radius · DISPLAY→--font-heading · BODY→--font-body. These are the only CSS color/type/radius variables: every pole below is a prose role, literal register hexes belong only in these :root values, and every sibling or alpha step is a color-mix(in srgb, var(--foreground) N%, transparent), substituting the mapped fixed token for that pole, or a color-mix between two mapped fixed-token references. Every unmapped role below MUST reuse the nearest mapped token or such a mix; it never gets another custom property or literal. Non-color mechanics may keep their own custom properties. Any rgba(POLE, a) notation below is design shorthand for that color-mix, never emitted CSS.
TWO POLES AND EXACTLY ONE TAPE HUE. Build eight tonal roles from the fixed tokens, never a ninth hue. Pick the variant from the brief's palette and COMMIT — one ground plus inverted chapters, never a light half and a dark half.
- ASPHALT (default): the dark pole as ground, shifted 3-6 RGB points off black so it reads as printed surface, not void (the #101013 / #0E0F12 register). Never pure #000. BOX (alternative, strong for kraft-feeling brands): the lightest pole warmed toward packaging card (the #EDE9E0 / #E8E3D7 register). Never #FFFFFF.
- INK: on BOX, a near-black carrying the palette's temperature (#141310 register) drawing all type and rules. PAPER: the light tone used for ALL type on dark grounds (#F2F0EA register) — white is never used for text anywhere on this page. GROUND-2: a second ground 4-7 RGB points off the first, for section alternation and input interiors.
- ALPHA STEPS OF THE TYPE COLOUR do every secondary job — no detached grey exists: headings 1 · body .78 · secondary .56 · disabled and sold-out .34 · table hairlines .14 · strong internal rules .28. Any #888 / #666 / slate value is a Pass-1 correctness bug.
- TAPE (var(--primary)): exactly ONE hyper-saturated hue — safety orange, hazard yellow, acid lime, hot red, or electric blue register, minimum 78 percent saturation; a pastel from the brief keeps its hue and gains saturation. Never purple or violet in any variant (global ban, restated because this world attracts it). TAPE-DEEP is a 14-18 percent color-mix from var(--primary) toward var(--foreground) for pressed states and the second tape. ALERT introduces no tone: validation uses a 3px var(--primary) bar plus full-strength var(--foreground) type.
- ON A TAPE FIELD THE TYPE IS ALWAYS THE DARK POLE, never paper, never white — tape is printed with black ink. Every var(--primary) use must clear 4.5:1 against the dark pole.
- var(--primary)'s jobs, at least ten of them: tape bands · the nav's bottom rule · the misprint ghost · the size-pill checked fill · the sold-out strike · the drop roundel · barcode TAPE bars · ticker separators · the rail's progress fill · the price currency mark · ::selection · :focus-visible · the manifest's step numerals · the WhatsApp glyph · the sticky bar's top rule. A primary hue that appears only on buttons is a failed palette, whatever the hex.

DUOTONE IS A COLOUR RULE, NOT A FILTER PRESET. Every lookbook frame: wrapper at position relative, isolation isolate, overflow hidden, background the applicable dark fixed pole (var(--background) in ASPHALT, var(--foreground) in BOX); img at object-fit cover with filter grayscale(1) contrast(1.24) brightness(1.03); a ::before at inset 0 repeats that dark fixed pole with mix-blend-mode lighten (clamps blacks up); an ::after at inset 0 uses var(--primary) on hero and rail frames, or the applicable light fixed pole (var(--foreground) in ASPHALT, var(--background) in BOX) on portraits, with mix-blend-mode multiply (clamps whites down). Do not create duo-shadow or duo-light color properties. @supports not (mix-blend-mode: multiply) falls back to grayscale(1) contrast(1.28) plus a 3px primary frame. THE PRODUCT CUT-OUT IS NEVER DUOTONED — a full-colour object on a two-tone page is why the object reads as the point.

GROUND SEQUENCE — hard cuts, never whispers. A ten-scene page runs: ground, TAPE, ground-2, INVERTED chapter, TAPE, ground, duotone full-bleed, ground-2, var(--primary) manifest header, ground, INVERTED footer. Never two identical grounds adjacent; TAPE fields plus inverted chapters cover 25-40 percent of the vertical run. Declare color-scheme (dark on ASPHALT, light on BOX) and a theme-color meta matching the ground.

## Typography system
TWO REGISTERS DO NINETY PERCENT OF THE WORK; a third exists only for prose. At most three families, only the weights used. Never Inter, Roboto or Open Sans (global ban).
- DISPLAY — a CONDENSED grotesk with a real 700-900 (the Archivo Narrow / Oswald / Anton / Bebas Neue / Saira Condensed / Barlow Condensed territory; a variable width axis held at 72-82 percent is better still). UPPERCASE ONLY and only above 1.6rem: wordmark, scene titles, product name, plate names, monument. It never sets a sentence.
- MONO — the UTILITY FACE and the signature of this world (Space Mono / DM Mono / JetBrains Mono / Martian Mono / IBM Plex Mono territory), 400/500/700, true tabular figures. It owns every code, size, price, date, lot number, form label, table cell, caption, ticker item, tape string and button label. A price or a size set in anything but mono is a bug here.
- BODY — a workhorse grotesk at 400/600 (Archivo, Public Sans, Space Grotesk territory) for the two or three actual paragraphs the page contains. If the copy is short enough, drop this family and ship two.

SCALE — all clamp, ratio about 22:1, the middle deliberately empty:
- Hero wordmark clamp(3.6rem, 16vw, 15rem) / .82 / -.03em / 800. A name of 8 characters or fewer may go to 18vw; a long name drops to 12vw and breaks onto TWO lines rather than shrinking below 10vw.
- Scene title clamp(2.4rem, 7vw, 5.6rem) / .86 / -.025em / 800 at 13ch · statement line, the only mid-size type on the page, clamp(1.35rem, 2.6vw, 2rem) / 1.18 / -.005em at 26ch · plate product name display 700 at clamp(1.1rem, 1.9vw, 1.5rem) / 1.05.
- Price mono 700 clamp(2.4rem, 5.6vw, 3.8rem) / 1 / -.02em tabular-nums · body 1.0625rem / 1.56 at 40ch · lede 1.15rem / 1.45 at 32ch · mono micro-labels .68-.78rem uppercase at .16-.26em, never the opening element of a hero · closing monument clamp(4rem, 19vw, 18rem) / .78 / -.03em.
- TRACKING IS A FUNCTION OF SIZE: -.03em above 8rem · -.025em at 3-6rem · -.01em at 1.6-3rem · 0 at body · +.16 to +.26em on mono micro-labels. NEVER add positive tracking to condensed display type to make it breathe — that turns a drop page into a tech page in one line.

OUTLINE TYPE IS A MATERIAL, used two or three times per page (a ghost lot number, one word in a title, optionally the monument): color transparent plus -webkit-text-stroke, AND THE STROKE SCALES WITH THE SIZE — 1.5px under 4rem, 2px at 4-8rem, 3px at 8-12rem, 4px above 12rem. A 1px stroke on a 15rem word disappears; that is the most common execution error here. Fill and outline may be MIXED INSIDE ONE HEADLINE, line by line.

EMPHASIS — pick ONE device and repeat it, never two: (a) THE KNOCKOUT, the word inside a var(--primary) slab at zero radius, padding .06em .18em, dark-pole type; (b) THE OUTLINE, the word switching to transparent fill plus stroke while its neighbours stay filled; (c) THE CORRECTION, the word struck with a 3px var(--primary) line and the replacement immediately after it in var(--primary) (at most twice per page).

PROMOTE EVERY NUMBER: a quantity inside a sentence is a mono 700 span at 1.1em in full-strength type while the sentence sits at .78 alpha. NEVER LET A DISPLAY HEADLINE AUTO-WRAP — break it into explicit block-level line spans so the rag is AUTHORED, and reuse those spans as the animation stagger targets.

## Page chassis
- THE NAV IS A MANIFEST BAR, not a navbar: position fixed, inset 0 0 auto 0, z-index 100, height 60px, the ground at FULL opacity (no blur, no glass, no transparency), border-bottom 3px solid var(--primary), grid auto 1fr auto, padding-inline var(--pad). START: the wordmark in display 800 at 1.25rem/.01em uppercase. CENTRE (hidden below 900px): a mono line of real facts only — "DROP 001 · EN LIGNE" or "LOT 02 · 120 PIÈCES" — at .68rem/.22em in the .56 step, with an 8px var(--primary) status dot only if the brief supports it. END: a CTA SLAB FLUSH TO THE VIEWPORT EDGE at full nav height, zero margin, border-radius var(--radius), var(--primary) background, dark-pole label in mono 700 at .76rem/.14em. It touches the edge of the screen; that decision alone stops this being a template navbar.
- SCROLL: past 220px the bar compresses to 48px over .2s and its var(--primary) rule grows to 4px; past 560px on scroll-down it leaves with translateY(-102%) over .24s power3.out and returns instantly on scroll-up (ScrollTrigger self.direction), suppressed while the menu or a select is open. SCROLL PROGRESS is drawn ON its bottom edge: a 3px TAPE-DEEP line at scaleX(0), transform-origin left (right in RTL), scrubbed to document progress at ease none.
- MENU (below 900px): a burger of three bars at 26px / 16px / 26px width, 3px tall, 5px apart, in var(--primary); open rotates the outer two into an X over .16s while the middle scales X to 0 over .1s. The panel is a full-screen ground takeover entering with a clip-path inset wipe from the top over .32s, holding numbered mono links (01 / 02 / 03) beside display 800 labels at clamp(2rem, 9vw, 4rem) staggered .045, a tape strip pinned to its floor.
- BASE: html and body at overflow-x clip (MANDATORY — tilted plates, tape and the cropped wordmark all overflow by design); scroll-behavior smooth; scroll-padding-top and scroll-margin-top 4.6rem on every anchored scene; a skip link slamming from top:-4rem to top:0 over .15s.
- RADIUS LAW (override): var(--radius) on every CTA slab, size pill and chip (:root sets --radius: 999px) · min(var(--radius), 0px) on every container, plate, frame and form field · min(var(--radius), 2px) on progress tracks · 50% on true status dots — these var(--radius)-derived declarations are the sanctioned mechanism; adding another radius treatment means the page has drifted. SHADOW LAW (override): no box-shadow except the focus ring and the autofill neutraliser.
- TEXTURE, one only: a fixed GRAIN layer (inline SVG feTurbulence fractalNoise, baseFrequency .9, numOctaves 2, tiled 220px, inset -40px, z-index 60, pointer-events none, opacity .05 on ASPHALT / .08 on BOX) or a SCANLINE layer (repeating-linear-gradient of the type colour at .045 alpha, 1px line every 4px). Never both.

## Hero forms (pick the one the drop calls for — never the marketplace split)
1. THE BLEED (default, and what this world is built for). min-height 100svh, content floor-anchored (flex column, justify-content flex-end, padding-bottom clamp(2rem,6vh,3.6rem)).
  - The PRODUCT NAME as the cropped wordmark at 16vw on ONE line, container at width max-content and margin-inline-end calc(var(--pad) * -1 - 8vw) so the last letter is cut by the viewport edge by 6-12 percent of the word's width, carrying the MISPRINT ghost. The loudest object on the page is TYPE, not an image.
  - The PRODUCT CUT-OUT overlapping it: a full-colour knocked-out image at width min(46vw, 30rem), rotated -3deg, z-index 3, covering 15-25 percent of the letterforms. Overlap is the depth model — never a photo in a slot beside the text.
  - THE DROP ROUNDEL hanging off the cut-out's top-start corner at -1.8rem / -1.4rem: a 6.4rem SVG circle with textPath micro-type at 8.5px/.26em naming the drop and date, one small var(--primary) square at the path origin, rotated 4deg, 4.8rem below 600px. It does NOT spin — a sticker is stuck, not a carousel.
  - A mono SPEC COLUMN in the opposite corner: three or four space-between rows at .7rem/.2em in the .56 step, max-width 12rem, hairline-separated — LOT, MATIÈRE, POIDS, PIÈCES.
  - The PRICE in the mono formula (see Conversion objects), on the ground between the wordmark and the floor, never inside a card.
  - CTAs: exactly TWO slabs side by side with a 3px var(--primary) gap between them — a filled primary (COMMANDER) and an outline secondary (WhatsApp or VOIR LES TAILLES). No third button, no ghost link.
  - THE HERO TERMINATES IN THE SIZES TICKER welded to the floor at full bleed. Never whitespace, never a bouncing chevron.
2. THE LABEL (weak image budget, or one photo and strong facts). The whole hero is one giant shipping label: a 3px-bordered block at max-width 62rem, margin-inline auto, rotated -1.5deg, holding a header row (border-bottom 3px) with the drop code on the start side and the date stamp on the end side; a FROM / TO field pair split by a 1px hairline, the TO reading "VOTRE WILAYA"; the product name in display 800 at clamp(2.4rem,8vw,5rem); a four-fact mono spec strip; the drawn BARCODE at full label width; and the price slab sticking out past the bottom-end corner by -1.2rem, rotated 2.5deg. Any single photo becomes a duotone plate tucked behind the top-start corner at -2rem, tilted -3deg. Zero photographs is a legitimate, strong outcome here.
3. THE LOCKER (several colourways; also the strongest RTL form). A two-panel split at 1.12fr .88fr with NO gap — the panels touch and a 3px var(--primary) rule is the only thing between them. The wide panel carries the wordmark stack (three lines alternating filled and outlined, each indented further than the last by clamp(1.2rem,5vw,5rem)); the narrow panel is a full-bleed duotone frame at full viewport height, overscanned to 112 percent. Across the seam at 62 percent height, a sticker cluster — roundel, tilted date stamp, one struck SOLD OUT chip — overlapping both panels. Below 820px the image takes order:-1 at 48vh and the var(--primary) rule stays.

## Section seams (CARGO's own vocabulary — never the same twice in a row; at least five per page)
- THE TAPE (the signature; two or three per page): a full-bleed var(--primary) band at height clamp(2.4rem, 5vh, 3.4rem), rotated -2deg or 2.5deg, width 108vw with margin-inline -4vw so its cut ends never enter the viewport, at the boundary with margin-block calc(var(--tape-h) * -0.5) so it OVERLAPS both scenes. Inside, a width max-content flex track of TWO identical chunks translating -50 percent over 22s linear infinite, mono 700 uppercase at .74rem/.26em in the dark pole, items separated by a 6px TAPE-DEEP square; long edges take a 2px dark-pole border. Two tapes lean in OPPOSITE directions at different speeds (22s and 18s).
- THE HARD CUT: ground inversion at zero transition — no gradient, no fade, no rounded joint — the whole type system flipping in the same instant. Two or three per page.
- THE STICKER OVERLAP: an element crossing the boundary — a tilted plate, a roundel, a chip cluster, a struck SOLD OUT mark — pulled by margin-block -2.4rem to -4rem at z-index 4, with the incoming scene's opaque ground behind it.
- THE SIZE RUN: a 3rem ticker band, border-block 3px var(--primary), carrying the size run in mono 700 at 1.05rem/.2em with 2.4rem gaps, sold-out sizes struck at .34 alpha, travelling 16s linear infinite. Instead of 7rem of nothing between scenes, a moving list of what is left.
- THE PERFORATION: a 1px-tall tear line whose background is repeating-linear-gradient(to right, currentColor 0 6px, transparent 6px 12px) at .3 alpha, with two 12px half-circles knocked out of the section edges at each end via radial-gradient masks. Used exactly once, always immediately above the manifest — the page tears here and the order slip comes off.
- THE BARCODE RULE: a full-bleed 44px strip carrying the drawn barcode at 100 percent width and 34px height with its code line beneath in mono at .62rem/.28em. Once or twice per page, always once above the footer monument.
- THE SLAM STACK: the next scene pulled up with margin-top between -3rem and -7rem, carrying a 3px var(--primary) top edge and its own opaque ground, landing ON the previous one. THE WELD: one scene at padding-top 0 so it fuses to the previous one, used when a duotone full-bleed frame runs straight into the plates grid.
ZERO whitespace-plus-hairline seams. A drop page has no soft transitions.

## Layout physics
- NON-COLOR MECHANICS in a later :root block: --pad clamp(1.15rem, 4.5vw, 4rem) · --shell 92rem · --rule 3px · --hair 1px, coloured with var(--border) (tables and spec rows ONLY) · --tape-h clamp(2.4rem, 5vh, 3.4rem) · --tilt-a -3deg · --tilt-b 2.5deg.
- THE TILT LAW: rotation may only be one of SIX values — -3deg, -2deg, -1.5deg, 1.5deg, 2.5deg, 4deg. Never outside that set, never more than FOUR rotated elements in one viewport, never a rotated block of running prose. Every tilted element declares its transform-origin, and any mono code inside a tilted plate is counter-rotated to 0 so numbers stay readable.
- SCENE RHYTHM: block padding clamp(4rem, 10vh, 7rem) standard, clamp(5.5rem, 13vh, 9rem) on the rail and the manifest, clamp(1.8rem, 5vh, 2.6rem) on a band; mobile floor 3.4rem. The middle term is vh so pacing survives a laptop and a 4K panel.
- NEVER 50/50. Ratios argued from content weight: hero split 1.12fr .88fr · plates against a spec column 1.32fr .68fr · manifest against the sticky object 1.14fr .86fr · lookbook caption against frame .34fr 1.66fr. Column gap clamp(1.6rem, 4vw, 4rem) — except welded grids, whose gap is exactly 3px and is var(--primary) showing through from the container behind.
- PLATES, NOT CARDS. The product unit is a PLATE: an image frame at aspect-ratio 4/5 (1/1 for accessories), zero radius, zero shadow, zero background, a 3px var(--primary) rule on ONE edge only (alternate which edge down the grid), a mono spec row welded beneath (border-top 1px hairline, space-between, name in display 700 on the start side, price in mono 700 tabular on the end side) and a .7rem/.2em micro-line under that. Grid repeat(auto-fit, minmax(15rem, 1fr)) at gap clamp(1.4rem, 3vw, 2.4rem). ALTERNATE frame ratios (4/5 and 1/1.12) so the grid is never a metronome, and TILT exactly one plate per row to -1.5deg or 1.5deg. A plate lifts NOTHING on hover.
- THE SCRUBBED LOOKBOOK RAIL is the page's ONE showpiece and its only horizontal axis: a section pinned for the width of its track, holding five or six duotone frames at width clamp(17rem, 34vw, 28rem) and aspect-ratio 3/4 — with ONE frame at 16/9 and double width to break the metronome — at gap 3px so the ground shows as a welded line. Each frame carries a mono FIG number (01 / 06) in var(--primary) at its top-start corner and a caption of at most six words at its floor. Along the section's bottom edge, a 2px track at the .14 step whose var(--primary) fill scales X 0 to 1 across the scrub, plus a mono counter reading the current frame. Under 860px the rail is NOT pinned: it becomes a native overflow-x auto strip with scroll-snap-type x mandatory and scroll-snap-align start, keyboard-reachable, same welded gaps.
- OVERFLOW IS COMPOSITION. Exactly FIVE elements break their container per page: the cropped wordmark past the viewport edge · the roundel past its plate corner · the tape past both page edges · one price slab past a label corner · the monument clipped by the document bottom. Safe only because overflow-x clip sits on html and body and overflow clip on every scene containing a piercing element.
- THE GHOST LOT NUMBER: each scene's number as an outlined mono numeral at clamp(7rem, 20vw, 16rem), stroke color-mix(in srgb, var(--primary) 14%, transparent), z-index 0, half outside its column, content at z-index 2 over it.
- MEASURE IS CAPPED IN CH (body 40, lede 32, caption 30, statement 26, title 13). IMAGES ARE HARD FRAMES: no radius, no shadow, no rounded mask; parallaxed frames overscan to 116 percent inside an overflow hidden parent; explicit width and height on every image, fetchpriority high on the hero, loading lazy below the fold.
- IMAGE BUDGET: ONE full-colour product cut-out on transparency, shot with hard direct light and a crisp edge, reused in the hero, the sticky object column and the success slip; then four or five lookbook frames shot as ONE series (same light, same distance family, worn or carried, cropped tight and off-centre, motion blur welcome, never smiling at the camera). Zero lifestyle stock. If image generation fails, a frame is never left empty — build the plate as a flat var(--primary) field carrying the drawn barcode, an outlined lot numeral at 3px stroke and the spec line.
- MOBILE COLLAPSE IS SURGICAL: two-column grids become 1fr; the wordmark drops to 18vw on two lines and STILL crops at the edge; tape keeps its rotation and drops to one band; the rail becomes the snap strip; the plates grid goes to two columns keeping its 3px welded gutters; the nav's centre line and one link disappear; the sticky order bar appears.
- THE CLOSING MOVE: the brand name as the monument at clamp(4rem, 19vw, 18rem), positioned so THE LOWER THIRD OF THE LETTERFORMS IS CLIPPED by the end of the document, the barcode rule directly above it and one mono fact line between them. The page ends the way a delivery ends — abruptly.

## Motion identity (GSAP 3 + ScrollTrigger via CDN; Lenis optional and constrained)
THE SAFETY CONTRACT COMES FIRST. animate = (typeof window.gsap !== "undefined") && !matchMedia("(prefers-reduced-motion: reduce)").matches. EVERY hidden initial state — every autoAlpha 0, y, clip-path start, rail offset — is set with gsap.set INSIDE that branch; nothing is hidden in CSS. If the CDN fails the page is a complete, converting poster: the rail is a horizontal snap strip, counters show their real hard-coded values, the manifest submits, the WhatsApp link works.

TIMING — this world OVERRIDES the global bands because a drop is fast and physical. gsap.defaults({ ease: "power4.out", duration: .38 }).
- HARD SNAP FEEDBACK 120-180ms: hovers, presses, size-pill states, chip toggles, focus rings. This band carries the world's identity — if interactions feel smooth, they are wrong.
- COMPONENT STATE 220-300ms · ENTRANCES 320-480ms · ONE LONG MOVE at 600ms (the monument) · IMAGE SETTLES at 900ms, the only slow move, because the frame arrives fast and the picture inside keeps travelling · MARQUEES 14-26s linear: ticker 16s, tape 22s and 18s, footer 26s.
- Shared CSS easing token cubic-bezier(.2,.86,.16,1), used by roughly twenty transitions. GSAP: power4.out for slams and line rises, power3.inOut for clip wipes, expo.out for the rail's snap-back, none for anything scrubbed.
- STAGGERS ARE TIGHT: .04 micro rows and pills, .055 headline lines, .07 plates and frames. NEVER above .08. TRAVEL IS SHORT: y 38 / 22 / 12 as three depth planes, yPercent 110 for masked lines, scale 1.06 to 1 on image interiors. Nothing travels 100px.

THE MANDATORY SET
1. SLAM REVEAL — the default entrance for about fifteen elements: gsap.set({autoAlpha:0, y:38}) then to({autoAlpha:1, y:0, duration:.34, ease:"power4.out"}), scrollTrigger start "top 88%", once true. On complete a 3px var(--primary) rule beneath the block scales X 0 to 1 over .22s — every impact leaves a mark.
2. MASKED LINE RISE on every display headline: each authored line inside an overflow hidden wrapper, yPercent 110 to 0, duration .4, stagger .055, power4.out, with padding-bottom .08em and margin-bottom -.08em so descenders never clip. Split at REAL wrap points, run on window.load so font metrics are final, aria-label on the parent and aria-hidden on the lines, then ScrollTrigger.refresh().
3. HERO TIMELINE — overlapping absolute positions, complete in about 1.15s. Set wordmark lines yPercent 110 in their masks; cut-out autoAlpha 0, y 38, rotation 0; roundel autoAlpha 0, scale .6, rotation -18; spec column, price and CTAs autoAlpha 0, y 22; ticker autoAlpha 0. Then tl.to(wordLines,{yPercent:0,duration:.42,stagger:.055},0) .to(cutout,{autoAlpha:1,y:0,rotation:-3,duration:.46},.16) .to(spec,{autoAlpha:1,y:0,duration:.34,stagger:.04},.34) .to(price,{autoAlpha:1,y:0,duration:.3},.46) .to(ctas,{autoAlpha:1,y:0,duration:.3,stagger:.05},.54) .to(ticker,{autoAlpha:1,duration:.3},.66), and THE STAMP at .74.
4. THE SCRUB RAIL (the showpiece and the ONLY pinned scene). Inside gsap.matchMedia("(min-width: 860px)"): gsap.to(track, { x: () => -(track.scrollWidth - window.innerWidth + 64), ease: "none", scrollTrigger: { trigger: section, pin: true, scrub: .55, anticipatePin: 1, invalidateOnRefresh: true, end: () => "+=" + (track.scrollWidth - window.innerWidth + window.innerHeight * 0.5) } }). The progress fill and the FIG counter are driven from the SAME ScrollTrigger's onUpdate (self.progress), never a second trigger. Each frame's inner image counter-parallaxes xPercent -6 to 6 at ease none on the same scrub so the pictures drift inside their frames. matchMedia returns a real teardown, and the CSS default below 860px is the snap strip — mobile is not a degraded experience, it is a different correct one.
5. THE STAMP POP — the one place a bounce is legal here, used exactly twice (the hero roundel, the success stamp): fromTo({scale:.6, rotation:-18, autoAlpha:0}, {scale:1, rotation:4, autoAlpha:1, duration:.26, ease:"back.out(2.4)"}), then a 60ms opacity settle from 1 to .92 — the ink spreading. No other element may use back, elastic or bounce.
6. THE SOLD-OUT STRIKE: wherever the brief says a size or colourway is gone, its strike draws in — scaleX 0 to 1, transform-origin the inline-start edge, duration .18, power4.out, at "top 85%", once true. It draws once and stays. OPTIONAL SCRUB COUNTER, only with a real number from the brief: a proxy tween at ease none with scrollTrigger {start:"top 80%", end:"top 34%", scrub:.35} writing Math.round(proxy.v) with a NARROW NO-BREAK SPACE separator, un-counting on scroll-up, plus a 3500ms setTimeout painting the final value if the trigger never fires. THE PRICE NEVER PARTICIPATES.
7. MARQUEES are CSS keyframes, never GSAP: a duplicated track at width max-content translating 0 to -50 percent, animation-play-state paused and width auto under reduced motion so the full text stays readable.
8. HOVER MICRO-CRAFT, all CSS, all in the 120-180ms band, inside @media (hover:hover) with :focus-visible parity: outline slabs FILL from the leading edge via a ::before at scaleX(0), transform-origin inline-start, to 1 over .16s while the label inverts on a 40ms delay so the fill lands first · size pills swap border and background in .14s with no movement · plate images swell scale(1.035) over .5s on a WRAPPER, never the element GSAP transforms, while a 3px var(--primary) frame snaps in at .12s · arrow glyphs translate 5px on their own transition · table rows grow a 3px var(--primary) tick from 0 to 12px.
9. ONE AMBIENT LOOP MAXIMUM, and only if the brief supports it: the live status dot, a true 50% var(--primary) circle at 8px running opacity 1 to .25 over 1.1s ease-in-out alternate infinite. Marquees do not count against this budget. No breathing glows, no floating blobs.
10. REDUCED MOTION: the global block PLUS designed stills — the rail as the snap strip, marquees frozen with full text visible, counters at final values, the stamp at its final rotation and full opacity, the strikes drawn.
LENIS IS PERMITTED but constrained: lerp .11, wheelMultiplier 1, no duration-based smoothing, exposed as window.__lenis, correct on native scroll; if the rail is the only scrub, shipping without it is better, because this world prefers a scroll that feels mechanical. CANVAS IS NOT REQUIRED and should normally be skipped; if the concept truly demands one, the same shape is authored as inline SVG and hidden only AFTER the context is created, the loop is gated by an IntersectionObserver at threshold .05 and paused on visibilitychange, reduced motion draws one static frame, devicePixelRatio capped at 1.5.

## Components
- SLABS (this world's buttons): border-radius: var(--radius), padding 1.05em 1.9rem, mono 700 uppercase at .78-.86rem with .14em tracking, line-height 1, inline-flex at gap .7em. PRIMARY uses a var(--primary) fill with dark-pole type; SECONDARY is transparent with a 3px var(--primary) border, filling from the leading edge on hover. PRESSED: scale(.985) plus the TAPE-DEEP fill over .1s — no shadow to collapse, because this world has none. Disabled at .34 alpha. Never full-width on desktop; the ONE legal full-width slab is the manifest's submit.
- SIZE SELECTOR — a DESIGNED OBJECT and one of this world's signatures. Never a native select, never a dropdown.
  - A fieldset with a visually-hidden legend, a mono label row above (space-between: "TAILLE" on the start side, a "GUIDE DES TAILLES" text link on the end side), and radio inputs with visually-hidden inputs and styled labels.
  - Grid repeat(auto-fit, minmax(3.6rem, 1fr)) at gap .5rem, max-width 26rem. Each pill: min-height 3rem, border-radius var(--radius), border 2px solid at the .28 step, background transparent, mono 700 at .84rem/.06em, display grid place-items center, transition 140ms with the shared ease.
  - FOUR STATES, all authored. HOVER: border-color var(--primary), background color-mix(in srgb, var(--primary) 8%, transparent), no movement. CHECKED (:has(input:checked)): background var(--primary), border var(--primary), dark-pole label, plus a 2px var(--primary) ring at 3px offset drawn with outline, never a shadow. FOCUS-VISIBLE: a 3px var(--primary) outline at offset 2px. SOLD OUT: opacity .34, cursor not-allowed, aria-disabled true, pointer-events none, plus a STRIKE — an ::after at 60 percent width, 2px tall, background currentColor, rotated -20deg, centred, scaling X from 0 on entrance.
  - SOLD-OUT STATES COME ONLY FROM THE BRIEF. With no stock facts in the brief, every size is available and no strike is drawn anywhere on the page. Inventing a sold-out size is inventing a business fact and is banned.
  - NO SIZE RUN? THE OBJECT STAYS, THE AXIS CHANGES. A cap, a bag, a belt, a gadget has no XS-XXL: the identical pill grid then carries the product's REAL variant axis from the brief — colourway, capacity, pack size, length — with the same four states, the same strike for whatever is gone, the same cross-section wiring, and only the label row rewritten (COULEUR / CONTENANCE / PACK instead of TAILLE). A genuinely single-variant product DROPS the control entirely and the manifest loses row N° 05; shipping one decorative pill with nothing to choose is worse than shipping none, and the sizes ticker then carries the spec line instead of a run.
  - The chosen size writes itself into three places at once: the sticky bar's chip, the manifest's TAILLE row, and the WhatsApp prefilled message. THE SIZE GUIDE is an inline ruled table, never a modal — a details/summary or grid-template-rows 0fr to 1fr expansion over .26s holding 1px hairlines, mono headers at .68rem/.2em and tabular values, and only if the brief supplies measurements.
- INPUTS (the manifest fields): background the type colour at .04 alpha, border 2px solid at the .28 step, radius min(var(--radius), 0px), padding .85em 1rem, mono 1.02rem, min-height 52px, caret-color var(--primary). FOCUS changes three things together over .14s: border-color to var(--primary), background to .07 alpha, and a 4px var(--primary) bar growing from scaleY(0) on the inline-start edge. Labels ABOVE in mono uppercase .68rem/.22em at the .56 step; placeholder at .32 alpha showing a real format, never an instruction. Autofill is neutralised with box-shadow inset 0 0 0 100px on the field background. SELECT matches the inputs exactly, appearance none, with a DRAWN 10x6 var(--primary) chevron at the inline-end (stroke 2, butt caps) rotating 180deg on focus over .16s — never the browser default arrow.
- CHIPS: var(--radius), 1px border at the .28 step, mono .66rem/.14em uppercase, padding .3em .8em. TABLES AND SPEC ROWS are the only place hairlines exist — 1px rules at the .14 step, mono tabular values, uppercase .68rem/.2em headers at the .56 step, a 3px var(--primary) left edge on the row the page wants read first. ACCORDION rows are separated by 3px var(--primary) rules, the head a grid of auto 1fr auto at align-items baseline (mono index, display 700 question at clamp(1.05rem, 2vw, 1.4rem), a plus of two 3px bars), opening by rotating the vertical bar 90deg over .16s and expanding grid-template-rows 0fr to 1fr over .28s, never max-height, aria-expanded in sync, single-open.
- ICONS ARE DRAWN, NEVER FONTS OR EMOJI: inline SVG on a 24px viewBox, stroke-width 2, fill none, and — the signature — stroke-linecap butt with stroke-linejoin miter. That pair of attributes keeps the icon set from softening into a wellness page.
- THE DRAWN BARCODE (reused four times: the label hero, the barcode rule, the manifest header, the success slip): inline SVG at viewBox "0 0 300 40", aria-hidden true, filled with the current type colour, about 44 rects whose widths cycle through 3,1,1,2,1,4,1,1,3,2,1,1,5,1,2,1,3,1,1,2 with a 2px gap after each, one or two bars swapped to var(--primary), and a mono code line beneath at .62rem/.28em. Decorative typesetting; it never claims to be scannable.
- ::selection uses var(--primary) with dark-pole text · :focus-visible uses a 3px var(--primary) outline at offset 2px on every interactive element · a visually-hidden utility · aria-live polite on validation and status regions · real alt text on content images, alt empty plus aria-hidden on decorative duplicates · FAVICON an inline SVG data URI, the ground as a filled square with three var(--primary) barcode bars.

## Editorial furniture (REQUIRED — this is CARGO's voice)
Typesetting devices, not business claims. Invent the format, never the facts; fill them from the brief.
- THE DROP CODE: DROP 001 / LOT 02 / RÉF. CG-0142 in mono var(--primary) at .68rem/.26em, at the top-start corner of at least three scenes.
- THE DATE STAMP: a rotated rectangular stamp — 2px border, padding .4em .7em, mono 700 at .7rem/.18em, rotated -3deg, in var(--primary) — carrying a real release date or delivery window, or absent. THE DROP ROUNDEL: the circular SVG textPath sticker, twice per page maximum, and it never spins.
- THE SHIPPING LABEL BLOCK: a 3px-bordered block with a header row, a FROM / TO pair split by a hairline, a SERVICE / POIDS / PIÈCES spec strip and the drawn barcode at its foot. Used as a hero form, a trust block, or the success slip.
- SPEC LINES under every plate and rail frame: MATIÈRE — COUPE — POIDS, mono .7rem/.2em, em-dash separated, in the .56 step. FIG NUMBERS on lookbook frames: 01 / 06 in var(--primary), mono .66rem/.24em.
- THE STRIKE: anything the brief says is gone is struck and LEFT VISIBLE. Hiding sold-out sizes is a lie of omission; striking them is the honest — and louder — move.
- CARE MARKS (only with real care facts): four drawn 20px glyphs on a mono row — a tub with a numeral, a triangle, an iron, a circle. A CLOSING FACT LINE above the monument: address, pickup hours or the merchant's real handle in mono at .72rem/.2em. Never a slogan.

## Conversion objects (this world SELLS, cash on delivery, and these are its money components)
- PRICE TYPOGRAPHY — the page's second-loudest object after the wordmark:
  - The numeral in MONO 700, tabular-nums, clamp(2.4rem, 5.6vw, 3.8rem), letter-spacing -.02em, full-strength type colour.
  - THOUSANDS ARE SEPARATED BY A NARROW NO-BREAK SPACE, written as the entity &#8239; so it survives copy-paste and never wraps: 4&#8239;500 renders as 4 500. Never a comma, never a period, never a plain space — a hard formatting law applying to the price, the total, the sticky bar and every promoted numeral.
  - The DZD mark as a mono 700 span at .34em of the numeral, uppercase, .18em tracking, in var(--primary), baseline-aligned in a flex row at gap .45em with align-items baseline. Never a symbol glued to the numeral in the display face.
  - A struck was-price only if the brief has one: mono 400 at .9rem in the .56 step, line-through with text-decoration-color var(--primary) at thickness 2px. NEVER a percentage-off starburst, never a red badge. Beneath it the COD note in mono at .7rem/.16em in the .56 step, stating what happens next and what it costs today: "PAIEMENT À LA LIVRAISON · LIVRAISON 58 WILAYAS".
  - THE PRICE DOES NOT COUNT UP. It arrives with the hero timeline in one hit (y 14 to 0, autoAlpha 0 to 1, 180ms, power4.out) and never moves again.
- THE MANIFEST (the COD order form) — the climax of the page and the reason this world is a COD world. It sits on an inverted chapter directly beneath THE PERFORATION, on a 1.14fr .86fr grid with a STICKY OBJECT COLUMN at top 5.2rem holding the cut-out at 60 percent scale, the chosen size as a chip and the price in miniature; below 900px the object column comes first and becomes static.
  - The form is a 3px-bordered block, radius min(var(--radius), 0px), padding clamp(1.4rem, 3.5vw, 2.4rem), max-width 36rem, with a HEADER ROW at border-bottom 3px var(--primary): BON DE COMMANDE (or the brief's language equivalent) in display 800 at 1.4rem on the start side, the drop code plus the drawn barcode at 120x18 on the end side.
  - FIELDS ARE NUMBERED ROWS, each a grid of 2.6rem 1fr with a 1px hairline beneath and the mono numeral in var(--primary) in the left gutter:
    N° 01 NOM COMPLET — text, autocomplete name, minlength 3.
    N° 02 TÉLÉPHONE — type tel, inputmode tel, autocomplete tel, pattern [0-9 ]{9,14}, mono placeholder showing the local format. THIS WORLD OVERRIDES the global "inputmode numeric" hint for the phone field specifically: inputmode tel raises the keypad this market expects.
    N° 03 WILAYA — a native select carrying all 58 wilayas, styled identically to the inputs with the drawn var(--primary) chevron. Never free text, never a datalist.
    N° 04 ADRESSE — a 2-row textarea plus an optional landmark line at a smaller measure ("REPÈRE / POINT DE LIVRAISON").
    N° 05 TAILLE — the size pill grid repeated inline, pre-selected from whatever the visitor chose earlier.
    N° 06 QUANTITÉ — a stepper, never a number input: an inline-flex group of two 2.8rem SQUARE slabs at 2px border with an output element between them at min-width 3rem, mono 700, 1.15rem, tabular-nums; the buttons invert to var(--primary) over .14s on hover and drop to .34 alpha when disabled. Any cap is stated and REASONED in the hint line.
  - DELIVERY CHOICE as RULED ROWS, not cards: full-width label rows at padding .9rem 0 with 1px hairlines, driven by :has(input:checked) — the checked row takes a color-mix(in srgb, var(--primary) 7%, transparent) background, a 3px var(--primary) bar on its inline-start edge, and a 1.05rem SQUARE check box whose inner var(--primary) square pops scale(0) to scale(1) over .14s. Squares, never circles — round shapes here belong to the size pills.
  - THE TOTAL ROW: border-top 3px var(--primary), padding-top 1.2rem, space-between — the label TOTAL À LA LIVRAISON in mono .7rem/.24em at the .56 step, and the total in the price formula at 2rem with tabular-nums and thin-space thousands. It recomputes on every quantity, size and delivery change with a 140ms opacity blink from 1 to .4 to 1 — a hard flicker, NOT a count-up.
  - VALIDATION IS BLUR-GATED: a touched map so an error appears only after a field's first blur, never while someone is typing into a fresh field. Errors are four-word mono sentences prefixed with a 3px var(--primary) bar, in a region with min-height 1.15em reserved so nothing reflows, with aria-invalid, aria-describedby and aria-live polite wired properly.
  - SUBMIT: the one legal full-width slab, filled with var(--primary), mono 700 at .9rem/.16em, min-height 56px, label COMMANDER. It holds a deliberate 700ms pending state with the label replaced by a present-tense human sentence ("ENVOI…"), then the STAMPED SUCCESS STATE.
- THE STAMPED SUCCESS STATE — this world's signature conversion moment.
  - The form fades to opacity 0 over .22s and takes visibility 0s .22s so focus never lands on a hidden control, while a panel absolutely positioned over it INSIDE THE SAME BOX fades in over .3s with a .18s delay. The block's height is never animated; both states live in the same box.
  - The panel is the buyer's order printed as a SHIPPING SLIP: a mono header (COMMANDE ENREGISTRÉE), a hairline-ruled definition list echoing their own words back — NOM, WILAYA, TAILLE, QUANTITÉ, TOTAL — the drawn barcode at full panel width, and the order number beneath in mono 700 at clamp(1.8rem, 4vw, 2.6rem) with tabular-nums.
  - THE STAMP lands across it: a 7.5rem circular SVG with a 2px var(--primary) ring, an inner 1px ring, and textPath micro-type at 8.5px/.26em carrying the merchant's name and the date, rotated 4deg, overlapping the slip's end edge by -1.2rem. It animates with THE STAMP POP, then settles to opacity .92 — ink soaking in. No confetti, no green tick, no bouncing checkmark.
  - Beneath the slip: what happens next and when in one mono sentence, plus the WhatsApp slab. PERSIST IT — store the order in localStorage and on return paint the success state INSTANTLY with no animation, so a returning buyer is never asked to order twice. The form never pretends to have reached a server — but the instant validation passes, as the stamp lands, the page hands the manifest over by dispatching the wandit:lead CustomEvent on document with the buyer's fields flat in detail (name, phone as typed, wilaya, commune, plus taille, quantité, delivery choice), and the slip carries one off-canvas decoy input marked data-wandit-hp that the page's own script never touches.
- THE STICKY MOBILE ORDER BAR (below 820px, mandatory on this world's pages): position fixed, inset-inline 0, bottom 0, z-index 95, height 64px plus env(safe-area-inset-bottom) as padding-bottom, the ground at full opacity, border-top 3px solid var(--primary), radius min(var(--radius), 0px), NO shadow and NO backdrop blur. Grid 1fr auto, padding-inline var(--pad). START: the price in the mono formula at 1.15rem with its var(--primary) DZD mark, and beneath it a .64rem mono line carrying the chosen size and colourway (or "CHOISIS TA TAILLE" until one is chosen). END: a var(--primary) slab CTA at border-radius var(--radius), full bar height and FLUSH TO THE END EDGE with zero margin. It enters translateY(105%) to 0 over .24s power4.out on a ScrollTrigger fired at the hero's "bottom top", AND IT RETREATS: when the manifest is in view it slides back out over .22s, because a bar must never cover the field a thumb is typing into. Tapping it scrolls to the manifest and focuses the first empty field; it never opens a modal.
- THE WHATSAPP CTA, styled to the world and NEVER a green bubble: the outline slab with a 3px var(--primary) border carrying a hand-drawn inline SVG glyph at 18px (stroke 2, butt caps, miter joins — a circle outline with a small tail triangle at its lower-start corner and a handset path inside) and a mono uppercase label. The href is a wa.me link built from the brief's REAL number with a prefilled message in the page's language naming the drop code and the chosen size. No number in the brief means NO component — never invent one.
- THE TRUST STRIP: a welded grid of four cells (container background var(--primary), gap 3px, children on the ground) so var(--primary) shows as 3px grid lines. Each cell: a 24px inline SVG icon YOU draw — stroke 2, fill none, butt caps, miter joins — then a mono uppercase micro-label at .68rem/.22em and a .78rem fact line at the .56 step. Draw exactly these four: 1. PAIEMENT À LA LIVRAISON, a 16x10 banknote rectangle with a 3-radius circle centred inside and a 4-unit check beside it. 2. LIVRAISON 58 WILAYAS, a truck — a 13x7 body box, a 6x5 cab welded to its end, two 2.2-radius wheels beneath. 3. ÉCHANGE 7 JOURS, two 3-unit chevron-headed arrows curving in opposite directions around an 8-radius circle. 4. TAILLES, a ruler — an 18x6 rectangle with four 3-unit ticks descending from its top edge at uneven depths. The fact lines are FACTS from the brief, never adjectives — and a cell whose fact the brief does not support DOES NOT EXIST: drop it and run three cells at the same 3px welded gutters (or two, welded the same way). A drawn icon promising an exchange window the merchant never offered is an invented business fact, exactly like an invented sold-out size.
- CROSS-SECTION LINKS: hero CTAs, plates, rail captions and the sticky bar all scroll to the manifest with scroll-margin-top 4.6rem respected. A size chosen anywhere pre-selects it in the manifest AND rewrites the sticky bar AND rewrites the WhatsApp message — a button in scene two rewrites scene eight before travelling to it.

## Arabic and RTL adaptation
- dir="rtl" on the html element and the whole chassis on logical properties (padding-inline, margin-inline, border-inline-start, inset-inline-end) so every asymmetric grid mirrors for free. The nav's CTA slab moves to the LEFT viewport edge and still touches it.
- THE CROP MIRRORS: the wordmark bleeds past the LEFT edge in Arabic — always the reading-exit edge. THE TILT SET MIRRORS: multiply every rotation by -1 for the whole page so plates and tape still lean with the reading direction; magnitudes unchanged, only the sign flips.
- ARABIC IS NEVER LETTER-SPACED — it breaks the joining of the script and is the most common failure on Arabic pages. Every tracking value in this document (.14em, .18em, .2em, .22em, .24em, .26em) drops to 0 under html[lang="ar"] and text-transform uppercase is REMOVED. The utility register is carried instead by three substitutions: size +2px, weight +100, and the .56 alpha step becoming var(--primary). Line-height goes UP: body 1.85, spec rows 1.7, manifest labels 1.6.
- FACES: an Arabic display in the Almarai / Cairo / Noto Kufi Arabic bold territory for the wordmark and titles, an Arabic text face for the paragraphs, and the SAME Latin mono for all codes, sizes, prices and phone numbers. Never artificially condense an Arabic face to imitate the Latin display.
- Numerals stay LTR inside RTL lines (a span with dir="ltr" and unicode-bidi isolate) so prices, phone numbers and sizes never scramble; keep tabular-nums and the narrow no-break space. Marquee direction flips with the text direction; the barcode, roundel and perforation are symmetric and mirror for free. Because this world uses no italics anywhere, the Arabic page is structurally identical to the French one — a deliberate decision, not an accident.

## CARGO ban list (in addition to the global one)
Box-shadows of any kind, blurred OR hard-offset (focus rings and the autofill neutraliser excepted) · any radius treatment outside the sanctioned var(--radius)-derived set · rotations outside the six legal values · more than four tilted elements in one viewport · rotated running prose · gradients as decoration (only the perforation, a legibility ramp over full-bleed photography, and a 2px progress fill) · glassmorphism and backdrop-filter · a second TAPE hue · purple or violet in any variant · light or regular display weights · italic type anywhere · prices or sizes set in the display or body face · a price that counts up · countdown timers, "STOCK LIMITÉ" without a real number, percentage-off starbursts, fake urgency of any kind · invented sold-out sizes · hidden sold-out sizes (strike them, never remove them) · a size dropdown instead of the pill grid · emoji as icons, icon fonts, filled icons, rounded stroke caps · three-icon feature grids and rows of identical rounded cards · untreated full-colour stock lifestyle photography · the product photographed on a soft gradient · whitespace-plus-hairline as a section seam · a bouncing chevron scroll cue · testimonial carousels · more than ONE pinned scene · more than ONE ambient loop · more than ONE scrub besides the rail and the nav progress line · back, elastic or bounce eases anywhere except the two stamps · staggers above .08s · entrances longer than 480ms · a green WhatsApp bubble · a hero without a price · any hidden state authored in CSS.

## Intensity
This world has exactly one failure mode and it is HEDGING. A wordmark at 9vw that fits neatly inside the container. A tilt of 1deg that reads as a rendering error rather than a decision. A 12px radius smuggled into the plates. A grey border where a var(--primary) rule belongs. A size dropdown because it was faster. A 900ms entrance because it felt smoother. Each is individually defensible, and together they rebuild precisely the generic product page this world exists to replace.

Executed at 100 percent — a name cut in half by the edge of the screen with a TAPE ghost a millimetre off register, a full-colour object tilted three degrees over the letters with a sticker hanging off its corner, tape running across every boundary carrying the same six words forever, a size run with two of them struck through in public, six duotone frames dragged sideways by the visitor's own scroll, and an order form that prints their name onto a shipping slip and stamps it — the page reads like something that was released, not something that was uploaded. Push INTO the crop, the tilt and the tape. Every number above is load-bearing, and the tilt is one of six values every single time.`,
	energy: "loud",
	id: "cargo",
	industries: [
		"streetwear",
		"fashion",
		"sneakers",
		"apparel",
		"caps",
		"accessories",
		"skate",
		"urban",
		"ecommerce",
		"gadgets",
		"music",
		"events",
		"delivery",
	],
	kind: "cod",
	mood: ["loud", "street", "graphic", "kinetic", "irreverent"],
	name: "Cargo",
	priceFeel: "accessible",
	tagline:
		"Your product name at the width of the whole screen and cut in half by the edge of it, the object tilted three degrees over the letters with a sticker on its corner, tape slapped across every seam, and an order form that prints the buyer's name on a shipping slip and stamps it.",
};
