import type { DesignWorld } from "./types";

/**
 * FORGE — industrial confidence for the COD library. Steel-dark ground, ONE
 * safety-signal accent, stencil caps over mono numerals, and the product's key
 * spec (Nm, W, bar, RPM) set larger than the headline and counting up as the
 * page lands. Blueprint grammar throughout: technical grid, true dimension
 * lines measured onto the product shot, one pinned SECTION SWEEP that cuts the
 * object open behind a travelling cut plane, ruled spec and warranty tables,
 * part-number furniture, diamond-plate texture, and a caution stripe spent
 * exactly ONCE. Built for tools, auto parts, hardware, machines, outdoor gear.
 * The doc is appended VERBATIM to the builder system prompt.
 */
export const forge: DesignWorld = {
	avoidFor: [
		"beauty",
		"spa",
		"wedding",
		"kids",
		"baby",
		"luxury-fashion",
		"jewelry",
		"patisserie",
		"florist",
		"nightclub",
	],
	doc: `# DESIGN WORLD: FORGE — the workshop wall

## Philosophy
This page is a SPEC PLATE riveted to a workshop wall — written by the person who actually torqued the thing on a bench and stamped a number on it. Its whole argument is a NUMBER: the one measurement that decides whether this tool, this part, this machine is the right one. Everything else exists to make that number believable — ruled tables, real dimensions measured onto the object, a section through it, a part reference, a warranty line, a photograph shot under hard raking light on a surface with real wear.

The register is CONFIDENCE, not aggression. Not gaming, not energy drink, not a tuning shop with flames. Calm, exact, high-contrast, entirely uninterested in charming you. Steel-dark ground everywhere, one high-visibility safety colour used the way a real workshop uses one — sparingly, only where it matters. If the page feels like it is shouting, the accent has spread and the world is broken.

Structurally this is a straight vertical scene stack with exactly ONE pinned moment. The distance from a generic dark product template is not animation budget — it is forty load-bearing decisions: radius zero everywhere, a mono face owning every digit, a blueprint grid under the whole document, hairlines carrying structure instead of gaps, ruled data instead of feature cards, real dimensions measured onto the product, one drawing cut open by a travelling section plane, and a checkout that reads like a work order. At sixty percent this is a dark SaaS page with a drill on it. Push into the specificity.

## The vibe
Somebody who knows the trade is selling you the thing they use. Copy rules, non-negotiable — they carry a third of this design:
- HEADLINES ARE SHORT AND FLAT: three to six words, uppercase, no metaphor, no turn. "COUPLE MAXIMUM. 340 Nm." / "CONÇU POUR TENIR." / "PIÈCES D'ORIGINE, PRIX D'ATELIER." A clever headline here reads as marketing and kills the claim of accuracy.
- EVERY CLAIM CARRIES A NUMBER OR A CONDITION. Not "puissant" but "1 050 W en charge continue". Not "résistant" but "boîtier IP54, testé 6 h". Where the brief gives no number, state a fact — never an adjective.
- MICROCOPY IS INSTRUMENT LANGUAGE, in mono, terse: "mesuré à 18 V", "hors accessoires", "livraison 58 wilayas", "stock atelier".
- VALIDATION SPEAKS LIKE A MACHINE THAT WANTS TO HELP: "Numéro incomplet — il manque 2 chiffres." / "Choisissez une wilaya pour calculer la livraison." No apology, no joke.
- Banned words: solutions, seamless, révolutionnaire, expérience, premium, ultime, transformer, and their Arabic equivalents. "Professionnel" is allowed once, and only if the brief claims a professional grade.
- Write it in the brief's language. In Arabic the same rules hold and the display system changes shape — the RTL section is a hard requirement, not a note.

## The single idea — THE KEY SPEC AT DISPLAY SCALE (build this FIRST; without it this world does not exist)
Pick the ONE number from the brief that decides the purchase: torque in Nm, power in W, pressure in bar, RPM, capacity in L or T, runtime in h, range in km, load in kg. It becomes the LARGEST TYPOGRAPHIC ELEMENT ON THE PAGE apart from the footer wordmark — larger than the h1 by a factor of at least 2.6.
- The numeral: MONO 700, tabular-nums, clamp(5.5rem, 22vw, 17rem), line-height .78, letter-spacing -.02em. Mono numerals at display scale are the ONE place in this world where tracking goes negative.
- The unit sits BESIDE it, not after it: a stacked block aligned to the numeral's cap height, mono 700 uppercase at .16em of the numeral's size, tracking .1em, in SIGNAL, with a 28px 1px signal rule above it.
- Under the pair, one mono caption at .6875rem / .14em at mill .52 stating the brief's measurement condition: "couple max · mesuré à 18 V, batterie pleine". If the brief gives no condition, the caption names the spec instead and invents no test.
- It COUNTS UP: a proxy tween 0 to target over 1.2s power2.out, onUpdate writing Math.round to textContent, at "top 85%" once, plus a 4000ms setTimeout fallback painting the final value in case the trigger never fires on a deep-linked load. Tabular-nums keeps the block from reflowing. The unit never animates.
- It reappears twice at smaller scale — as a spec chip in the ruled table and in the sticky bar's start cell — so the number is the motif that travels.
If the product genuinely has no headline number (a hand tool, a jacket), use the strongest hard fact: a gauge, a thickness, a load rating, a warranty in months. A page here that opens on an adjective has failed by the second scene.

## Visual signatures (what makes it instantly recognizable)
- Steel-dark ground with a faint TECHNICAL GRID across the whole document — drawn on engineering paper, not painted.
- Radius ZERO on every rectangle, plus a 10px machined CHAMFER cut from one corner of every major plate. No world in this library is more squared.
- Stencil-weight condensed caps tracked POSITIVE against a mono face that owns every digit — two voices, never mixed.
- The key spec at 17rem with its unit stacked beside it in the safety colour.
- True DIMENSION LINES drawn onto the product photograph the way a drawing office draws them — extension lines, 45-degree end ticks, the measurement sitting in a gap in the line — drawing themselves at constant speed on scroll.
- LA COUPE: the product cut open by a hazard-coloured plane travelling across it on scroll, standing hatched and dimensioned behind the cut — the page's one pinned moment, and a section view, never an exploded one.
- Ruled spec and warranty tables with zebra rows and shared hairlines — real data, not feature cards.
- Diamond-plate texture at .05 in exactly three places, and a caution stripe spent exactly ONCE.
- ONE light scene in a dark page: the spec sheet on blueprint paper, where everything inverts.
- The page closes on an outlined stencil wordmark at 18vw with a 1.5px signal stroke over diamond plate.

## Color physics (route the brief's palette through the fixed tokens — the physics is law)
FIXED TOKEN MAP — STEEL-900→--background · MILL→--foreground · SIGNAL→--primary · STEEL-900→--primary-foreground · STEEL-800→--secondary · BLUEPRINT→--accent · mill at 52%→--muted · mill at 18%→--border · zero→--radius · DISPLAY→--font-heading · BODY→--font-body. These are the only CSS color/type/radius variables: every pole below is a prose role, literal register hexes belong only in these :root values, and every sibling, texture or alpha step is a color-mix(in srgb, var(--foreground) N%, transparent), substituting the mapped fixed token for that pole, or a color-mix between two mapped fixed-token references. Every unmapped role below MUST reuse the nearest mapped token or such a mix; it never gets another custom property or literal. Non-color mechanics may keep their own custom properties. Any rgba(POLE, a) notation below is design shorthand for that color-mix, never emitted CSS.
Nine tonal roles from the fixed tokens, never a tenth hue. This world is COOL: in every steel role B is greater than or equal to G, and G is greater than R. A warm black, brown or beige anywhere is a correctness bug.
- STEEL-900 — GROUND: the palette's darkest cool pole, near-black with a blue-green cast (the #14181A relationship). Never #000, never #111.
- STEEL-800 — PLATE: one tonal step up (the #1C2124 relationship, 6-10 RGB points) for panels, the order terminal, focused inputs and the alternating scene.
- STEEL-700 — RAISED: a second step (the #262C30 relationship) for plate head rows, stepper buttons and dark zebra.
- MILL: text on dark ground, a cool off-white (the #E6EAE9 relationship). White is NEVER used for text on this page.
- MILL AT ALPHA — the rule that makes this read as machined metal instead of UI: body rgba(mill,.74) · captions rgba(mill,.52) · quiet notes rgba(mill,.34) · ALL hairlines rgba(mill,.12) · strong rules and input borders rgba(mill,.18) to .28 · placeholders rgba(mill,.32) · tracks rgba(mill,.10) · texture fills rgba(mill,.05). No independent gray hex exists.
- SIGNAL: the brief's one high-visibility accent — hazard yellow (#F2B705 register), safety orange (#F0621B register) or hi-vis lime (#C8F02A register). ONE hue. If the brief hands two, the second becomes a mill alpha and is never seen as colour.
- SIGNAL-DEEP: a sibling roughly 18 percent darker, for pressed states and the button's bottom edge.
- BLUEPRINT: the lightest cool pole for the ONE inverted scene (the #DEE3E2 relationship — cool paper, never warm, never white). On it text is STEEL-900 and every alpha rule re-derives against ink.
- ALERT is not another hue: validation and a real out-of-stock state use a contrast-safe color-mix between var(--primary) and var(--foreground).
THE SIGNAL'S FOURTEEN JOBS — use at least ten, never a fifteenth: the unit block · the eyebrow rule · the section index · the primary button fill · its signal-deep bottom edge · the caution stripe · dimension lines, their end ticks and the section cut plane · the rail's scroll-progress rule · the focus ring · ::selection · the rule above the total · trust-strip icon strokes · the stock square · the footer wordmark stroke. Signal is NEVER a paragraph background, NEVER a section ground, NEVER a gradient.

## The blueprint ground (exact recipe — build this before any content)
Three fixed layers behind the document, pointer-events none, below z-index 0.
1. FINE GRID: repeating-linear-gradient(0deg, rgba(mill,.022) 0 1px, transparent 1px 8px) crossed with the same at 90deg — an 8px lattice, barely there.
2. MAJOR GRID: the same at 64px in rgba(mill,.05). Together they read as engineering paper. On the BLUEPRINT scene both re-derive against ink at .04 and .08 and become that scene's background — which is what makes the light scene a drawing sheet rather than a white block.
3. DIAMOND PLATE: an inline-SVG data-URI pattern on an 88x88 tile — four rhombi, 34 units long and 11 wide, rotated plus and minus 32 degrees in a checker, filled rgba(mill,.05), no stroke, background-size 88px. NOT a page-wide wallpaper: exactly three hosts — the footer band, the sticky order bar, the trust strip. Ceiling opacity .06; a fourth use is a bug.
4. CHEVRON (optional second texture): a 24x24 tile with two 3px chevrons at 45 degrees in rgba(signal,.09). Two legal hosts only — the caution band's dead cells and behind a ghost section index. Ceiling .10.
No other pattern, no other texture, no photograph used as a background fill.

## Typography system
THREE families, three non-overlapping jobs. Load only the weights used.
- DISPLAY / STENCIL (700, 800): headlines, section heads, button labels above 1rem, the footer wordmark, product names. A CONDENSED industrial grotesk — the Archivo Condensed / Oswald / Barlow Condensed / Anton territory, or a true stencil face when the brief allows. UPPERCASE ONLY; there is no lowercase display type in this world.
- MONO (400, 500, 700): EVERY number without exception — prices, specs, totals, quantities, phone digits, table data, indices, references, dates — plus every micro-label, form label, caption, chip and the whole order terminal. The JetBrains Mono / IBM Plex Mono / Space Mono / Roboto Mono territory, with tabular-nums set globally on the face.
- TEXT (400, 500): paragraphs, lede, list items, FAQ answers. A workhorse grotesk with a large x-height — the Archivo / Public Sans / Barlow / Manrope territory. Never Inter, Roboto or Open Sans.
A number in the TEXT face is a bug. A paragraph in the MONO face is also a bug — mono is data and labels, never reading.

TRACKING IS INVERTED HERE. Where an editorial page tightens display type, Forge OPENS it: stencil caps need air or they smear.
- Hero h1: clamp(2.6rem, 6.4vw, 5.4rem) / .92 / +.045em / 800 / uppercase.
- Key spec numeral: clamp(5.5rem, 22vw, 17rem) / .78 / -.02em / mono 700 — the only negative tracking on the page.
- Section h2: clamp(1.9rem, 4vw, 3.2rem) / .98 / +.04em / 700 / uppercase.
- Sub-head h3: clamp(1.15rem, 1.9vw, 1.5rem) / 1.2 / +.06em / uppercase.
- Body: 1rem / 1.62 / 0 — never uppercase, never tracked. Lede: clamp(1.0625rem, 1.3vw, 1.1875rem) / 1.55 / 0, capped 28em.
- Mono micro-label .6875rem / .16em · mono data cell .8125rem / 1.4 / .02em · mono note .625rem / .12em at mill .34.
- Price: clamp(2.2rem, 4.4vw, 3.4rem) / mono 700 / tabular / .01em. Footer wordmark: clamp(3.5rem, 18vw, 15rem) / .82 / +.06em / stencil 800.
Target a display-to-micro ratio of at least 24:1 — 272px against a .625rem note is 27:1, where a generic dark page sits at 4:1. That ratio IS the world.
NEVER LET A DISPLAY HEADLINE AUTO-WRAP: break every h1 and h2 into explicit block-level line spans so the rag is AUTHORED, and reuse those spans as stagger targets. Cap the h1 at three authored lines.
EMPHASIS has three legal forms and italic is not one: the SIGNAL colour on one word, a 700-to-800 weight step, or a face change from stencil to mono (a model number inside a headline goes mono). Underline is a button device, never emphasis.

## Page chassis
- SPEC STRIP (optional, excellent): a 32px full-bleed strip above the rail on STEEL-800, mono .625rem / .14em, centred, carrying three real facts separated by signal slashes — "PAIEMENT À LA LIVRAISON / 58 WILAYAS / GARANTIE 24 MOIS". It states the commerce register in the page's first 32 pixels and gives the rail something to sit against.
- THE RAIL (this world's navbar — a rail, not a bar): position sticky, top 0, z-index 100, height 60px desktop / 56px mobile, background STEEL-900 SOLID always, border-bottom 1px rgba(mill,.14). No transparency, no backdrop-filter, no scrolled-state colour change — a rail does not fade in and out. Its only state is a 2px SIGNAL scroll-progress rule on its bottom edge, scaleX 0 to 1 driven by a document ScrollTrigger at scrub .3 with transform-origin inline-start.
- WORDMARK IS A LOCKUP: stencil 800 at 1.125rem tracked .12em uppercase, beside a mono sub-code at .5625rem / .18em at mill .5 carrying the trade line ("OUTILLAGE PRO"), never a slogan, separated by a 20px 1px rgba(mill,.2) vertical rule with 12px either side.
- Rail row: flex, align-items stretch, max-width 1360px, padding-inline var(--pad). Links mono .75rem / .1em uppercase at mill .7 going to 1 over .16s. The end cell is a squared SIGNAL action at full rail height, min-width 132px, mono 700 / .12em. Below 860px the links disappear and the end cell becomes a 56px square carrying the phone glyph — no burger, no overlay. This world does not need a menu; it needs a phone number.
- Global base: html and body overflow-x clip · scroll-behavior smooth · antialiased · color-scheme dark · meta theme-color equal to STEEL-900. ::selection is SIGNAL with STEEL-900 text. :focus-visible is a 2px SIGNAL outline at offset 2px, radius min(var(--radius), 0px). A skip link sliding top:-48px to top:8px on focus over .2s.
- THE COORDINATED NUMBERS, derived from the measured strip plus rail and never guessed separately: hero min-height calc(100svh - 92px) with the spec strip, calc(100svh - 60px) without; sticky column offset top 84px; scroll-margin-top 76px on every anchored section.
- THE 8PX LADDER IS LAW: every padding, margin, gap, height and offset is a multiple of 8 (4 only inside 1px-adjacent details like a tick). Inline padding token clamp(20px, 4.5vw, 64px). Container max-width 1360px. Section block padding clamp(72px, 10vh, 128px), never below 64px on mobile.

## Hero forms (pick what the product calls for — every one is LOADED, and every one carries the key spec)
1. THE SPEC PLATE (default). Grid 1.1fr / .9fr, gap clamp(32px, 5vw, 72px), align-items center, min-height calc(100svh - 92px), overflow clip.
LEFT COLUMN, max-width 34rem, carries seven differentiated pieces: a mono eyebrow at .6875rem / .16em preceded by a 28px 1px SIGNAL rule with 12px of space; the authored stencil h1 in two or three line spans; THE KEY SPEC BLOCK immediately under it — it belongs to the COPY column, not the photograph, because it is an argument, not decoration; a price row (baseline flex, gap 16px) with the mono price, the currency span and a real del element only when the brief states a previous price; a CTA row holding the primary signal button and the WhatsApp cell at gap 12px; a mono reassurance line at .6875rem / .12em at mill .52 stating exactly what happens on submit; and three spec chips carrying the next three most important numbers.
RIGHT COLUMN IS A PLATE, NOT A PHOTO SLOT: STEEL-800, 1px rgba(mill,.10) border, radius min(var(--radius), 0px), a 10px chamfer cut from its top-inline-end corner via clip-path polygon, padding 32px, holding the duotoned product photograph capped at width min(100%, 34rem) — the plate's margin IS the composition, never a bleeding slab. Over the photograph the DIMENSION OVERLAY — a DRAWING CONVENTION, not an annotation layer: an absolutely positioned inline SVG at inset 0, pointer-events none, aria-hidden true, viewBox matched to the photograph's aspect, vector-effect non-scaling-stroke on every path. THREE dimensions, never more than four, each built the drafting way and never any other way: two 1px EXTENSION LINES standing 6px off the object's edges and running 14px past the dimension line · between them the DIMENSION LINE at 1px in rgba(signal,.55), BROKEN BY A GAP in its middle holding the measurement in mono .625rem / .12em at full mill · at each end a 6px tick at 45 degrees, never an arrowhead. Every measure is a real dimension from the brief with its unit. A LEADER pointing at a part and terminating in a floating label plate is a different drawing grammar and belongs to a different world — do not draw one here: this page MEASURES the object, it does not annotate it. A mono FIG. line sits under the plate.
THE HERO TERMINATES IN THE TOOL RAIL, never in whitespace: full-bleed, 64px, border-block 1px rgba(mill,.14), STEEL-800, four mono micro-facts at .6875rem / .14em with SIGNAL slash separators — power, weight, warranty, delivery, all real. Below 720px it becomes a 2x2 grid at .625rem with gap 0 and shared hairlines.
2. THE STENCIL SLAB (single column; phone-first merchants, RTL pages, and whenever a demonstration video exists). A full-bleed duotone photograph or the demonstration loop at height min(88svh, 720px) with the directional scrim; the stencil h1 in the lower inline-start at clamp(2.4rem, 8vw, 6rem); THE KEY SPEC tucked to the inline-end at 22vw in SIGNAL at .92, deliberately clipped by the scene edge so the last glyph's counter bleeds off — legal only because overflow-x is clipped. Welded under it at padding-top 0, a solid STEEL-900 plate with the price row, the CTA row and the condition caption, then the tool rail. No CTA sits on the photograph.
3. THE PARTS COUNTER (three to six references). Grid .88fr / 1.12fr. Left: eyebrow, h1, one lede at 28em, the key spec at the reduced register clamp(4.5rem, 14vw, 11rem) — still the largest element in its column — then price and CTA row. Right: a gap-0 two-column grid of PLATES sharing 1px rgba(mill,.12) hairlines, never cards, never shadows, each with a duotone thumbnail at 4/3, a mono REF line, the name in stencil .9375rem uppercase and one spec chip. No outer border; the hairlines run to the grid's edges. One column below 720px.

## Section seams (Forge's own vocabulary, named — every boundary uses one, never the same twice in a row, at least five per page)
- THE CAUTION CUT — the page's ONE heavy accent event and THE ACCENT'S INDUSTRIAL JOB (the signature seam is the dimension seam below). It is a STRIPE FIELD, never a printed tape: no text ever rides it, it is never rotated, and it never overlaps the scenes it separates. A full-bleed 14px band: repeating-linear-gradient(135deg, SIGNAL 0 22px, STEEL-900 22px 44px), border-block 1px rgba(mill,.14). It CRAWLS: background-position 0 to 62px over 12s linear infinite via CSS keyframes, stopped under prefers-reduced-motion. USE IT EXACTLY ONCE PER PAGE, at the single most important boundary — normally the cut into the order terminal, or between the demonstration and the proof scene. A second band destroys the device and the world with it. Never a background, never a card border, never behind text.
- THE TACK WELD — this world's butt-join: the next scene starts at padding-top 0 and the joint is drawn as a 2px tack line, repeating-linear-gradient(90deg, rgba(mill,.22) 0 6px, transparent 6px 12px), full-bleed. Two plates welded, not two sections spaced.
- THE DIMENSION SEAM — THE SIGNATURE, and the boundary this world reaches for first; two or three per page. A boundary drawn as a technical dimension line — a full-bleed 1px rgba(mill,.22) rule with 8px vertical end ticks at the container edges and a GAP in its middle holding a centred mono measure label at .625rem / .18em: "SECTION 04 · 3 OUTILS".
- THE INDEX SHOULDER: the section index in stencil at clamp(3rem, 7vw, 5.5rem) in rgba(mill,.07), straddling the boundary — half above, half below — with the section head beside it. The ghost numeral is the only element allowed to cross a scene edge.
- GROUND INVERSION TO THE SPEC SHEET: the page's ONE light scene, entered on a hard cut with no gradient — STEEL-900 to BLUEPRINT in a single row of pixels. Inside, every token re-derives against ink: text STEEL-900, hairlines rgba(ink,.12), grid rgba(ink,.04) and .08, zebra rgba(ink,.03), and SIGNAL stays the identical hue (a safety colour reads on both grounds — that is its job). This scene holds the spec table and the warranty table and nothing else. Exactly one per page.
- THE OVERSCAN PLATE: a full-bleed duotone photograph whose bottom 22vh dissolves through a scrim whose final gradient stop IS the next scene's ground, so the image never ends — it becomes the page.
- THE FACT RIBBON: a 56px STEEL-800 band between two chapters holding a width:max-content mono marquee of real facts, two duplicated chunks translating -50 percent over 26s linear infinite, items at .6875rem / .14em with SIGNAL slash separators. Instead of 96px of nothing, a band of moving data.

## Layout physics
- NO GRID IS 50/50. Skew every two-column grid and argue it from content weight: hero 1.1fr/.9fr · spec sheet .8fr/1.2fr (the TABLE is wider) · proof scene 1.2fr/.8fr · order terminal .92fr/1.08fr (the form is 17 percent wider) · FAQ .72fr/1.28fr (the heading column is the small one). Gaps clamp(32px, 5vw, 72px). At least one grid must invert expectation.
- MEASURE IS CAPPED IN EM: body 32em, lede 28em, spec note 26em, table value 30em, form sub-copy 34em, FAQ answer 36em.
- GAP ZERO PLUS SHARED HAIRLINES is this world's grouping mechanic and OVERRIDES the global "gap between every row of siblings" for six objects: the spec table, warranty table, trust strip, tool rail, parts-counter grid and how-it-works row. Gaps still govern everywhere else.
- PLATES, NOT CARDS. A plate is STEEL-800, 1px rgba(mill,.10) border, radius min(var(--radius), 0px), a 10px chamfer via clip-path polygon(0 0, calc(100% - 10px) 0, 100% 10px, 100% 100%, 0 100%), padding clamp(20px, 3vw, 32px), a mono index in the top-inline-start, and a 1px rgba(mill,.14) rule under its head. No shadow, no radius, no hover lift. Every plate cuts the SAME corner — mixed chamfer directions read as an accident.
- REGISTRATION: at 1024px and above every column edge snaps to a 12-column grid with 24px gutters. Elements break the grid by a full column, never by 17 pixels.
- OVERFLOW IS COMPOSITIONAL and exactly three elements may break their container: the ghost section index, the key spec's last glyph in the Stencil Slab, and the footer wordmark. Safe only because overflow-x is clipped on html and body and overflow clip sits on every scene containing a breaking element.
- IMAGE OVERSCAN FUNDS MOTION: any parallaxed or scrubbed image is top -10 percent and height 120 percent inside an overflow-hidden parent, so travel never exposes an edge.
- RESPONSIVE COLLAPSE: below 1024px two-column grids become 1fr and sticky becomes static; below 900px the pinned scene un-pins and plays as one slam; below 720px the tool rail and the trust strip become 2x2 with shared hairlines and the parts counter becomes one column. Tap targets never below 44px; the order action never below 56px.
- RHYTHM: quiet, loud, quiet. The demonstration scene and the key-spec hero are the loud ones. The spec sheet is deliberately the quietest thing on the page — dense, ruled, silent — and that contrast is what makes the data feel true.

## Motion identity (GSAP 3 + ScrollTrigger via CDN; native scroll — Lenis optional and unnecessary; no canvas)
THE SAFETY CONTRACT COMES FIRST. Compute reduced = matchMedia("(prefers-reduced-motion: reduce)").matches, hasGsap = typeof window.gsap !== "undefined", animate = hasGsap && !reduced. EVERY hidden initial state — autoAlpha 0, y offset, clip-path inset, stroke-dashoffset — is written with gsap.set() INSIDE the animate branch. Never author opacity:0 or visibility:hidden in CSS for an animated element. If the CDN fails or motion is reduced, the page is fully visible, the section drawing sits fully cut, hatched and dimensioned, and every conversion element works. Add a prefers-reduced-motion block that, beyond the blanket .01ms override, sets the caution crawl and the fact ribbon to animation:none and width:auto.

THIS WORLD MOVES LIKE A MACHINE, NOT LIKE A CURTAIN — everything arrives decisively and stops dead. Timing bands, which override the global narrative band:
- 140-220ms interaction feedback (hover invert, focus, chip, caret) · 340ms component state (accordion, stepper, sticky bar, total cross-fade) · 500-800ms THE SLAM: every entrance, reveal, headline line and plate, replacing the global .9-1.4s band entirely · 1.2s the count-ups, the only reveals above .8s besides the 1.1s image counter-scale · 6s the single ambient loop · 12s caution crawl and 26s fact ribbon in CSS keyframes.
EASES ARE LAW: NO BOUNCE, NO ELASTIC, NO BACK, NO OVERSHOOT OF ANY KIND. Entrances power4.out · state power2.out · clip wipes power3.inOut · scrub none · the single settle expo.out. One shared CSS token, cubic-bezier(.16,.84,.24,1), used by roughly twenty transitions. An element that passes its resting position and returns has broken the world.
TRAVEL IS SHORT AND VERTICAL: y offsets of 12, 24 and 40 only — three distances encoding three depth planes inside one hero. Scales of .94, .96, 1.06, 1.08. Nothing travels 100px and nothing travels horizontally on entrance.

THE MANDATORY MOTION SET:
1. THE HERO SLAM — one timeline, overlapping positions, complete in about 1.5s. Set: h1 line spans inside overflow-hidden wrappers at yPercent 110 (padding-bottom .06em, margin-bottom -.06em so descenders survive the mask); the key-spec block autoAlpha 0, scale .94, transform-origin left center; copy stack and CTA row autoAlpha 0, y 24; the product plate clip-path inset(0 0 100% 0) with its inner image at scale 1.08; dimension and extension paths at full stroke-dashoffset; tool rail items autoAlpha 0, y 12. Then tl.to(lines, {yPercent:0, duration:.58, stagger:.07, ease:"power4.out"}, 0) .to(keySpec, {autoAlpha:1, scale:1, duration:.62, ease:"expo.out"}, .22) .to(copy, {autoAlpha:1, y:0, duration:.5, stagger:.06}, .34) .to(plate, {clipPath:"inset(0% 0% 0% 0%)", duration:.7, ease:"power3.inOut"}, .3) .to(plateImg, {scale:1, duration:1.1, ease:"power2.out"}, .3) .to(dims, {strokeDashoffset:0, duration:.6, stagger:.08, ease:"none"}, .95) .to(railItems, {autoAlpha:1, y:0, duration:.5, stagger:.05}, 1.1). The count-up starts at position .3 on the same timeline. Under each h1 line a 1px SIGNAL underline sweeps scaleX 0 to 1 over .34s at position .18 — that sweep IS the slam's sound.
2. THE COUNT-UPS — the key spec plus at most three benchmarks in the spec table, all proxy-object tweens at 1.2s power2.out, tabular so nothing reflows, once:true at "top 85%", each with its own 4000ms setTimeout fallback.
3. LA COUPE — THE SECTION SWEEP: the page's ONE pinned, scrubbed moment and its signature drawing. NOTHING FLIES APART ON THIS PAGE. A product that separates into floating annotated components belongs to a bench world; this is a drawing office, and a drawing office answers the same question by CUTTING THE OBJECT OPEN. A scene pinned with end "+=110%", scrub 1, anticipatePin 1, invalidateOnRefresh true.
   THE DRAWING: one STROKE-ONLY inline SVG on a 0 0 240 160 viewBox at 1.25px in rgba(mill,.6), vector-effect non-scaling-stroke. GROUP A is the object's outline in orthographic elevation. GROUP B sits exactly on top of it and is the same outline PLUS its internal geometry — bore, wall thickness, thread, bearing seat, or for a non-mechanical product the material's layer stack — with every enclosed area filled by a HATCH: a 6-unit pattern tile of 1px 45-degree lines in SIGNAL at .5, defined once in defs and referenced, never redrawn per shape. GROUP B is clipped by a rect whose width the scrub drives.
   THE SCRUB, one timeline on normalized progress: 0 to .62 the CUT PLANE travels from the inline-start edge at ease none — a 1px SIGNAL vertical line the full height of the frame with an 8px tick at each end and a mono "A—A" label riding it — and the clip rect's width follows it exactly, so everything the plane has passed stands revealed IN SECTION behind it. .62 to 1 the three DIMENSION LINES draw across the opened section at ease none, stagger .1, in the drafting geometry specified for the hero overlay, each carrying one real measurement from the brief. Nothing rotates, nothing translates, nothing overshoots — the only movement is a plane crossing an object and lines drawing at constant speed.
   BELOW 900px AND ON TOUCH THE PIN IS REMOVED: at "top 78%" the clip rect opens to full width over .8s power4.out and the dimensions draw once at stagger .08, no pin, no scrub. FALLBACK CONTRACT: the clip rect is authored at FULL width in the markup and only the animate branch collapses it, so with a failed CDN or reduced motion the plate renders fully cut, hatched and dimensioned and reads as a finished drawing. This scene is never empty and never half-drawn.
4. GENERIC SLAM REVEALS: roughly sixteen elements marked with a reveal attribute — gsap.set({autoAlpha:0, y:24}) then to({autoAlpha:1, y:0, duration:.5, ease:"power4.out"}), start "top 88%", once:true, stagger .06 within a group.
5. THE DIMENSION DRAW: every dimension line, extension line, dimension seam, how-it-works rule and spec-sheet head rule draws via stroke-dashoffset or scaleX over .6s ease "none", stagger .08. Technical lines draw at CONSTANT SPEED — an eased dimension line looks like decoration.
6. THE ONE AMBIENT LOOP, diegetic: the stock square pulsing opacity .35 to 1 over 6s sine.inOut yoyo repeat -1, a status LED on a machine. If the page carries a demonstration video THAT is the ambient loop and the square stays static. Never both.
7. THE TOTAL CROSS-FADE: when the total, delivery fee or quantity changes, the old numeral leaves autoAlpha 0 y -6 over .14s and the new arrives from y 6 over .18s. Numbers here REPLACE; they never roll and never count inside a form.
8. HOVER IS AN INVERSION, NOT A LIFT — a global override. Nothing floats. The primary button flips to SIGNAL-DEEP fill with STEEL-900 text over .16s; the secondary inverts its inset border to full mill; plates do not move, their photograph swells scale(1.04) over .6s inside its clipped frame and their mono index turns SIGNAL. The only travel in the whole interaction kit is :active on the primary — translateY(2px) while its 4px signal-deep bottom edge collapses to 2px, a real button being pressed.
once:true on EVERYTHING non-scrubbed. Nothing re-animates on scroll-up.

## Components
- BUTTONS ARE RECTANGLES. Border-radius: var(--radius) (:root sets --radius: 0), no pills anywhere on this page. Min-height 52px desktop / 56px mobile, padding 16px 28px, mono 700 uppercase .8125rem / .14em, line-height 1, inline-flex, gap 12px. PRIMARY: SIGNAL fill, STEEL-900 text, box-shadow inset 0 -4px 0 SIGNAL-DEEP as a physical bottom edge. SECONDARY: transparent with box-shadow inset 0 0 0 1px rgba(mill,.28) — UI here uses inset box-shadow as its border so borders never affect layout — inverting to inset 0 0 0 1px MILL over a STEEL-800 fill on hover. TERTIARY: a mono text link with a 1px SIGNAL underline sweeping scaleX 0 to 1 from the inline-start over .2s. Disabled: opacity .4, cursor not-allowed, no edge, no press.
- SPEC CHIPS: mono .625rem / .12em uppercase, padding 6px 10px, 1px rgba(mill,.16) border, radius var(--radius), transparent fill, the numeral at 700 in MILL and the unit at .5 alpha. Twelve or more per page — they are this world's texture the way captions are an editorial world's.
- RULED TABLES (spec and warranty — the feature-card replacement): gap 0, every row border-bottom 1px hairline, min-height 52px, grid-template-columns minmax(9rem, .8fr) 1.2fr, padding-block 14px, the term in mono .6875rem / .16em uppercase at .52 and the value in mono .8125rem tabular at full alpha. Every second row carries MILL at .022 (ink at .03 on blueprint) — real zebra, like a real datasheet. Head row in STEEL-700 with mono .625rem / .18em labels. Benchmark values count up; plain facts do not. Below 600px each row becomes a two-line stack, hairlines preserved.
- THE FAQ ACCORDION: a hairline-topped list, each item hairline-bottomed, the question a full-width flex button in stencil .9375rem uppercase .06em, padding-block 20px, turning SIGNAL on hover and while expanded. Body opens grid-template-rows 0fr to 1fr over .34s with an overflow-hidden inner. The icon is a 14px plus of two 1.5px rules; opening collapses the VERTICAL rule scaleY 1 to 0 over .28s so a plus becomes a minus. Nothing rotates. Single-open, aria-expanded maintained, role region plus aria-labelledby on panels.
- SHADOWS: exactly ONE exists, only ever under a floating PHOTOGRAPH — 0 24px 60px -32px color-mix(in srgb, var(--background) 85%, transparent). Zero shadows on plates, buttons, inputs, the rail, the sticky bar, chips or tables. Depth comes from tonal steps and hairlines, as it does from paint and metal on a real machine.
- THE STOCK STATE: an 8px var(--primary) SQUARE (not a circle — this world squares everything except drawn SVG) beside a mono .625rem / .14em label carrying the brief's real stock fact. Out of stock switches the square to the alert mix of var(--primary) and var(--foreground) and the label to the honest sentence. This is the only element that pulses.
- CRAFT DETAILS: explicit width and height on every image · fetchpriority high on the hero image, loading lazy elsewhere · descriptive alt on content images, alt empty plus aria-hidden on decorative SVG · aria-live polite on the total and validation · an output element for quantity · a skip link · an inline-SVG data-URI favicon · one h1 only.

## Conversion objects (this world SELLS — these are its money components, never afterthoughts)
- THE WORK ORDER is the climax of the page: the COD form presented as a real bon de commande. A STEEL-800 plate with the chamfered corner on its own scene, a CAUTION CUT above and a DIMENSION SEAM below, grid .92fr / 1.08fr with the FORM as the wider column, one column below 900px. Its head is a ruled row — mono "BON DE COMMANDE" on the start side, mono "PAIEMENT À LA LIVRAISON" on the end, a 1px rgba(mill,.14) rule beneath — and under that a three-step PROGRESS TRACE: three mono step labels joined by a 1px rgba(mill,.14) rule whose SIGNAL fill advances scaleX 0 to .33 to .66 to 1 over .34s power2.out as each step validates. That trace is the only thing in the form that moves.
- FIELD ORDER IS LAW: PHONE FIRST, then name, then wilaya, then address, then quantity. NO email. NO account. NO password. Ever.
- GLOVED-THUMB METRICS, because the buyer may be standing in a workshop: every input min-height 56px desktop and 60px mobile, font-size 17px (never below 16px — iOS zooms), padding 16px, background STEEL-900, box-shadow inset 0 0 0 1px rgba(mill,.18), radius min(var(--radius), 0px). Labels ABOVE in mono .6875rem / .16em uppercase at mill .52, margin-bottom 8px, each preceded by a 14px 1px SIGNAL rule with 8px of space. Focus changes THREE properties together over .16s: inset border to 1px SIGNAL, an added inset 0 0 0 2px rgba(signal,.28), and the background lifting to STEEL-800. No glow, no blur, no scale.
- PHONE: type tel, inputmode tel, autocomplete tel, a real pattern for a leading 0 then 5, 6 or 7 then eight digits, the VALUE in mono with tabular-nums at .06em, a mono hint reading "05 · 06 · 07", and live grouping into 0X XX XX XX XX as the visitor types — never blocking a keystroke, never rejecting a paste.
- NAME: the TEXT face, autocomplete name, one field, no separate first and last. ADDRESS: a textarea at 3 rows, autocomplete street-address, identical metrics.
- WILAYA IS A PARTS PICKER: a NATIVE select (never a JS dropdown) at the same 56px metrics in the MONO face, appearance none, with a custom caret drawn as an inline-SVG data-URI chevron at 1.5px stroke in SIGNAL positioned inline-end 16px. Every option carries the WILAYA CODE BEFORE THE NAME, exactly like a parts catalogue — "16 — ALGER", "31 — ORAN", "09 — BLIDA" — and all 58 are listed. On change the fee and delay write immediately into a two-cell ruled mono readout directly above the submit, never into an FAQ and never below the fold.
- QUANTITY IS A SQUARED STEPPER, never a number input: three cells sharing 1px hairlines, 56px square minus and plus buttons on STEEL-700 whose glyphs are two 1.5px rules, and an output element at min-width 48px in mono 700 at 1.25rem tabular. It has a cap and THE CAP IS GIVEN A REASON in the mono hint ("max 3 par commande — stock atelier").
- VALIDATION IS BLUR-GATED: a touched map so an error appears only after a field's first blur, never while someone is typing into a fresh field. One mono line at .75rem in the alert mix of var(--primary) and var(--foreground) with min-height 1.25em reserved so nothing reflows; the field's inset border and its label take that same mix in one 160ms beat; aria-invalid, aria-describedby and aria-live polite wired for real. Messages name the exact defect, never a mood.
- THE TOTAL READOUT above the submit is a ruled block, gap 0, shared hairlines: subtotal row, delivery fee and delay row from the wilaya select, a 1px SIGNAL rule, then the TOTAL in mono 700 at clamp(1.9rem, 3.4vw, 2.6rem) tabular with the currency in mono at .38em in mill .55. It recomputes on every quantity, variant and wilaya change and CROSS-FADES per the motion rule.
- SUBMIT: full-width, min-height 60px, SIGNAL fill, STEEL-900 text, mono 700 uppercase .14em, with the 4px signal-deep bottom edge. A deliberate 700ms PENDING state — the label becomes a present-tense sentence and a 2px STEEL-900 rule sweeps the bottom edge scaleX 0 to 1 ease none over .7s — and double submit disabled. Then the plate CROSS-FADES IN PLACE into a STAMPED WORK ORDER inside the same box (success in over .5s with a .18s delay, form out over .34s to y -10 with visibility switching at .34s so focus never lands on a hidden element). The success state is a printed document: a mono ORDER REFERENCE inside a 1px SIGNAL plate, the buyer's own name, wilaya, quantity and total echoed back as ruled mono rows, and the next step stated as a fact — "on vous appelle pour confirmer" ONLY if the brief promised a call. Persist it in localStorage and on return paint it INSTANTLY with no animation, so a returning buyer is never asked to order twice. The instant validation passes — as the work order stamps in — the page routes the buyer's data down the line by dispatching the wandit:lead CustomEvent on document with the fields flat in detail (name, phone as typed, wilaya, commune, plus quantity and variant), and the form carries one off-canvas decoy input marked data-wandit-hp that the page's own script never reads or validates.
- STICKY ORDER BAR — the default mobile pattern, permitted on desktop as a slim variant. It appears once the hero leaves the viewport: translateY(100%) to 0 over .34s power4.out, no bounce. Height 68px plus env(safe-area-inset-bottom), background STEEL-900 at .97 with diamond plate at .05, border-top 2px SIGNAL, split by ONE vertical 1px rgba(mill,.14) hairline. START CELL: the KEY SPEC in mono .625rem / .14em at mill .52 above the price in mono 700 at 1.15rem tabular. END CELL: the SIGNAL order action at full cell height, minimum 44px tap, mono uppercase. It hides autoAlpha 0 over .2s while the work order is in view, so it never covers the form it points at.
- PRICE TYPOGRAPHY: mono 700, tabular-nums, THIN-SPACE thousands (U+202F): 12 900 DZD / 12 900 دج. The currency is a mono span at .38em uppercase / .1em in mill .55, on the baseline 8px after the numeral — BEFORE it in RTL. A struck previous price sits beneath in a real del element at .9375rem in mill .5 with text-decoration-color SIGNAL at 1.5px, and ONLY when the brief states a real previous price. THIS WORLD OVERRIDES the global "count-up numerals for stats and prices": THE PRICE NEVER ANIMATES — a spinning price reads as a slot machine and this world sells accuracy — while the key spec and the benchmarks always do.
- WHATSAPP CTA STYLED TO THIS WORLD — never green, never a floating round bubble. A squared secondary cell at border-radius var(--radius), box-shadow inset 0 0 0 1px rgba(mill,.28), holding a 20px inline-SVG WhatsApp glyph drawn STROKE-ONLY at 1.5px in SIGNAL (the same drawn set as the trust icons), a mono uppercase label, and beneath it one mono line at .625rem in mill .34 giving the merchant's real hours. On hover the border and glyph go full SIGNAL over a STEEL-800 fill in .16s. On mobile it may take a secondary cell in the sticky bar or sit directly beneath the submit.
- TRUST STRIP WITH DRAWN SVG ICONS: a full-bleed ruled row of four cells, gap 0, sharing 1px rgba(mill,.12) vertical hairlines, padding 24px, diamond plate at .04 behind. Each cell holds a 24px inline SVG, a mono .6875rem / .14em label and one line of mill-.52 detail. The icons are STROKE-ONLY geometric primitives on a shared 24-unit viewBox at 1.5px, butt caps, miter joins, SIGNAL stroke, and they are DRAWN, never fetched: a banknote rectangle crossed by a diagonal (paiement à la livraison) · a crate outline with a routed arrow leaving it (livraison, 58 wilayas) · a shield built from five straight segments and no curve (garantie) · a hex-head bolt drawn as a hexagon with an inscribed circle (pièces d'origine). Labels state ONLY what the brief promised — no icon exists for a promise the merchant did not make.
- HOW IT WORKS AS A DIMENSION LINE: three or four 12px squares sitting ON a 1px rgba(mill,.22) horizontal rule with 8px end ticks, each with a mono index above and one line beneath — commande, appel de confirmation, livraison, paiement à la réception. It draws on scroll via dashoffset at "top 82%", once, and is never pinned; the section sweep owns the page's only pin.
- HONEST URGENCY ONLY: real stock counts and real end dates, stated as facts in mono. Countdown clocks, fake "plus que 3" counters and invented review totals are banned outright and destroy this world faster than any visual error, because the whole page is a claim to accuracy.

## The demonstration slot (this world's one moving image)
Exactly ONE scene may carry video, and it earns more than any animation: the tool IN CONTEXT. Call animate_image on the hero or demonstration still with a motion prompt describing a small, real, looping action — the bit biting into wood and throwing a thin curl of dust, the jack rising a centimetre, the lamp panning across a bench, the wheel taking one slow turn. Rules: a single full-bleed plate at height min(78svh, 640px); the video autoplay muted loop playsinline with the still as poster and object-fit cover; the same duotone treatment as every photograph; the directional scrim; ONE line of stencil copy and ONE mono caption over it; and NO button on the video — the CTA lives in the welded plate beneath. If animate_image is unavailable or fails, keep the still and give it a 12s scale 1 to 1.04 alternate CSS loop with the same scrim; the scene must never depend on it. Never a video in the hero AND in the demonstration scene.

## Photography direction (rugged duotone — every image passes through this)
- Shot on a real working surface: bench, plate, concrete, truck bed. Hard directional key at roughly 35 degrees with deep shadow opposite. Visible wear, dust, grain, tool marks. Never a floating cutout on white, with ONE exception — the spec-sheet scene, where a clean cutout on blueprint paper is correct because that scene is a drawing.
- THE DUOTONE RECIPE, three layers on every figure: the img at filter grayscale(1) contrast(1.18) brightness(.84); a ::after at inset 0 in the SIGNAL hue at opacity .16 with mix-blend-mode overlay, pushing highlights toward the safety colour; and a ::before at inset 0 with linear-gradient(200deg, rgba(steel-900,.55), rgba(steel-900,.08) 62%) — a DIRECTIONAL scrim placing darkness where the type sits. Type over an image never sits on raw image.
- Every framed photograph gets a mono FIG. caption beneath, and where it is the product, the dimension callout overlay above.

## Workshop furniture (REQUIRED — this is Forge's voice)
- THE REFERENCE LINE: the page names its subject once in mono with a real reference from the brief — "RÉF. FG-2041" — under the h1 or in the plate head. WHEN THE BRIEF SUPPLIES NO REFERENCE the page does not invent one: it carries the category and the year instead, or nothing. A fabricated part number is a lie a workshop customer will catch.
- SECTION HEADS instead of centred h2s: a baseline-aligned flex row — the mono index "04" in SIGNAL, a 20px 1px SIGNAL rule, the stencil h2, a flex-1 rgba(mill,.12) hairline filling the remaining width, and an end-aligned mono aside carrying a count or a date. The flex hairline IS the border. This is the only section-head form on the page.
- FIG. NUMBERS on every plate, photograph, table and diagram, sequential across the page, never repeated: "FIG. 03 — Mandrin 13 mm, serrage automatique."
- SPEC CHIPS as recurring texture, twelve or more.
- THE GUARANTEE STAMP: a rectangular outlined plate, 1px SIGNAL, mono .625rem / .18em uppercase, holding one real promise — "GARANTIE 24 MOIS". Placed once near the work order, never rotated, never repeated.
- MEASUREMENT NOTES: a mono line at .625rem in mill .34 beneath any benchmark stating how the number was obtained — present ONLY when the brief supplied the condition, omitted entirely otherwise, never invented.
- THE COLOPHON in the footer: a mono row of the merchant's real trade facts — hours, address, registration if given — set as data, not as a paragraph.
- ALL OF THIS IS TYPESETTING, NOT INVENTION. Every value comes from the brief; where the brief is silent the furniture describes the PAGE itself (figure numbers, section indices, the count of parts drawn) or it is omitted. Fabricating one spec to fill a chip destroys the world.

## Arabic and RTL adaptation (this market ships both)
- html dir rtl lang ar, and the layout genuinely mirrors: padding-inline, margin-inline, border-inline-start and end, inset-inline throughout. No physical left or right property appears anywhere in the stylesheet.
- NEVER LETTER-SPACE ARABIC — tracking breaks the joins and is the commonest failure in this market. It is severe here because the ENTIRE display system is tracked uppercase, so in Arabic the display signature is rebuilt from other parts: the Arabic display face at 700-800, size increased 8 percent, tracking exactly 0, preceded by a 48px 3px SIGNAL rule sitting 12px above the headline. Rule plus weight plus size IS the stencil signal in Arabic. Arabic has no uppercase and no italic; do not simulate either.
- KEEP THE MONO FACE for Latin numerals, units, references, table data, prices, the key spec and the order reference even on an Arabic page — that is exactly what preserves the instrument texture. Choose ONE numeral system (Western or Eastern Arabic) and hold it everywhere, including the total and the sticky bar.
- Arabic families: the IBM Plex Sans Arabic / Almarai / Cairo / Rubik territory for text, the Changa / Tajawal territory for display. Arabic body line-height 1.85, size plus 1px, every measure cap loosened by 2em.
- THE CAUTION STRIPE mirrors: its gradient angle becomes 45deg so the stripes still lean into the reading direction.
- THE DIMENSION OVERLAY carries type and MUST be re-authored in local coordinates — mirroring it with scaleX(-1) would reverse every measurement. Its extension lines and measure gaps are re-laid from the inline-end. The section sweep's cut plane always travels from the inline-start edge, so it reverses for free with dir; the hatch stays at 45 degrees, because a mirrored hatch is still a hatch.
- Underline sweeps, rule draws and the progress trace take transform-origin right. The sticky bar's cells swap so the action stays under the thumb. The currency span moves before the numeral.
- French runs about 15 percent longer than English: drop the body measure to 30em, allow one extra authored headline line, and re-check that the stencil h1 has not become four lines.

## Explicit overrides of the global builder rules and of the defaults a dark product page reaches for (declare each in an HTML comment beside the relevant code, then obey it)
1. Global: rounded cards and 12-16px radii. HERE: buttons, CTAs, chips and steppers consume var(--radius) directly (:root sets --radius: 0); every other rectangle uses min(var(--radius), 0px) without exception. Depth is a 10px machined CHAMFER plus a tonal plate step. At the required token value, the only curves on the page live inside drawn SVG.
2. Global: gap between every row of siblings. HERE: the spec table, warranty table, trust strip, tool rail, parts counter and how-it-works row use gap 0 with SHARED HAIRLINES. Gaps still govern everywhere else.
3. Global: entrance and narrative reveals at .9-1.4s. HERE: .5-.8s SLAMS; only the count-ups (1.2s) and the hero image counter-scale (1.1s) exceed .8s.
4. Global: hover lift translateY(-2px). HERE: nothing floats. Hover INVERTS colour; the only travel is :active pressing the primary button 2px down against its collapsing 4px bottom edge.
5. Global: count-up numerals on view for stats AND prices. HERE: the price never animates; the key spec and the benchmarks always do.
6. Global: soft box-shadows as a depth device. HERE: exactly ONE shadow exists, 0 24px 60px -32px color-mix(in srgb, var(--background) 85%, transparent), only under floating photography. Zero shadows on UI of any kind.
7. Global: one italic word inside a big headline. HERE: no italic and no serif exist anywhere; emphasis is the signal colour, a weight step, or a stencil-to-mono face change.
8. Global: a blurred translucent sticky nav. HERE: backdrop-filter and translucency are banned outright; the rail is solid steel with a hairline and a 2px signal progress rule.
9. Global: at most ONE hairline seam per page. HERE: hairlines are the world's STRUCTURE — table rules, trust dividers, dimension lines, section heads — but a naked 1px rule with nothing but whitespace either side is still banned as a scene boundary; boundaries use the named seams.
10. Global: mobile section padding at least 48px. HERE: at least 64px, snapped to the 8px ladder.
11. Global: pills and rounded CTAs. HERE: there is not one pill on the page — not a button, chip, badge or stepper.

## Forge ban list (in addition to the global one)
Warm blacks, browns and beiges (this steel is COOL) · pure #000 or #fff · any gray that is not an alpha of mill or ink · a second accent hue, a red-and-blue "sport" pair, chrome or metallic gradient fills · glassmorphism and backdrop-filter · any radius above 0 on a rectangle · soft shadows on plates, buttons, inputs, the rail or the sticky bar · carbon-fibre, hexagon mesh, brushed-metal or rivet WALLPAPER — diamond plate and chevron are the only textures, each with a named opacity ceiling and a fixed list of hosts · the caution stripe used more than once, used as a fill, or placed behind text · flames, sparks, skulls, lens flares, bloom, energy-drink "beast" energy · italic, serif and script type · lowercase display headlines · centred body copy and centred section heads · three-icon feature grids and icon cards · emoji and icon fonts · a floating round green WhatsApp bubble · testimonial carousels · countdown timers, fake stock counters, invented review totals · fabricated part numbers, torque figures, certifications or warranty terms · an exploded or disassembled product view with parts floating apart on annotation leaders (this world CUTS its object, it never takes it apart) · 3D tilt cards on mouse move · particle backgrounds, WebGL and canvas of any kind · bounce, elastic and back eases and any overshoot whatsoever · per-character text splitting · more than ONE pin, ONE ambient loop, ONE light scene, ONE video · any hidden state authored in CSS.

## Intensity
This world fails in one direction: it goes SOFT. Radii creep back to 12px, plates grow drop shadows, the safety colour spreads onto a section background and stops meaning danger, the mono face gives way inside a table, the key spec shrinks to a normal h2, specs turn into adjectives, and the caution stripe gets used three times until it is just a pattern. At sixty percent that page is a dark template with a drill photographed on it, and it converts nothing, because it promises precision and delivers mood. At one hundred percent — a cool steel wall on engineering paper, one hazard colour marking exactly the fourteen things that matter, a stencil headline slamming into place over a 272px torque figure counting itself up beside its unit, three real dimensions drawing themselves onto the product at constant speed, the object cut open by a hazard-coloured plane travelling across it as you scroll, its hatched section and three dimensions landing behind the cut, a ruled datasheet on blueprint paper you could argue with, and one caution stripe cutting the page open right before a work order with 56px inputs and a wilaya picker that lists codes like a parts catalogue — it looks like a page built by somebody who has actually used the thing they are selling. That is the entire sale. Every number above is load-bearing.`,
	energy: "medium",
	id: "forge",
	industries: [
		"tools",
		"hardware",
		"auto",
		"auto-parts",
		"machinery",
		"construction",
		"industrial",
		"gadgets",
		"electronics",
		"outdoor",
		"camping",
		"agriculture",
		"workwear",
		"services",
	],
	kind: "cod",
	mood: ["rugged", "engineered", "utilitarian", "high-contrast", "no-nonsense"],
	name: "Forge",
	priceFeel: "accessible",
	tagline:
		"A steel-dark workshop wall drawn on engineering paper, one safety-yellow line marking only what matters, and the number that actually sells your tool — 340 Nm — set bigger than the headline and counting itself up as the page lands.",
};
