import type { DesignWorld } from "./types";

/**
 * FOURNIL — warm artisan-food world: the bakehouse board.
 * Flour-dust paper, butter/crust/ember poles, hand-drawn inline-SVG strokes as
 * the traveling motif, ruled menu tables with dotted leaders as the design
 * centerpiece, and a pinned rising-dough oven journey as the showpiece. Every
 * number below is committed and executable. The doc is appended VERBATIM to the
 * builder system prompt.
 */
export const fournil: DesignWorld = {
	avoidFor: [
		"law",
		"finance",
		"banking",
		"insurance",
		"medical",
		"clinic",
		"pharmacy",
		"tech",
		"saas",
		"crypto",
	],
	doc: `# DESIGN WORLD: FOURNIL — the bakehouse board

## Philosophy
This page is THE BOARD ABOVE A COUNTER, hand-lettered before opening — not a website. A neighbourhood fournil at 05:40: flour dust on brown paper, warm light raking off a crust, a slate propped against the till with today's four things chalked on it, crossed with a properly typeset menu card and a baker's log book. It must make a stranger hungry inside one and a half screens and answer "what do you sell and what does it cost" without a click.

Two facts are load-bearing; everything else serves them.
FIRST: THE MENU IS THE CENTREPIECE, not a block near the footer. The page is composed around ruled menu tables the way a magazine is composed around its feature well — dish names and DZD prices typeset as MOMENTS, display face, dotted leaders running across the row, tabular numerals. A price list set as a paragraph, or as a grid of identical cards, is the failure mode of this entire world.
SECOND: EVERYTHING DRAWN IS DRAWN. Wheat stalks, steam curls, whisk arcs, crumbs, score marks, arrows, underlines, even the outline of the ghost button — inline SVG strokes with round caps and honest irregularity. Never an icon set, never clipart, never emoji, never a perfectly geometric badge. That drawn stroke is the motif that TRAVELS across every scene and stitches the page into one object.

Structurally this is a vertical page with one pinned showpiece, and that is fine. The distance between this and a takeaway template is not animation budget — it is forty small decisions: leader dots, hand-cut seams, irregular strokes, margin notes in a real hand, price typography, short springy timing, and copy written by the person who gets up at four.

## The vibe
The baker talking across the counter while wrapping something in paper. Proud of the flour, bored by marketing, funny in one line out of six. Copy carries 40 percent of this design:
- Headlines SHORT and PHYSICAL: the thing plus one true detail, two to six words. "Le pain qui sort à 6h." "Beurre, farine, temps." Never a benefit statement, never an adjective stack.
- One word per big headline takes the crust accent with a hand-drawn underline squiggle beneath it — never a straight rule, never an italic. This world's emphasis is DRAWN.
- HANDWRITTEN MARGIN NOTES carry the personality: five per page maximum, always a fact about the MAKING, never a slogan — "pétri à 5h du matin", "on en fait 40, pas un de plus", "levain de 2019".
- Every constraint gets a reason: not "6 max par client" but "Six par personne, pour qu'il en reste à midi." Errors are full sentences in the same voice: "Il me faut ton numéro pour confirmer la commande."
- Banned words: solutions, expérience, incontournable, révolutionnaire, premium, transformer, "authentique" as an adjective about itself. Name the ingredient, the hour, the temperature or the quantity instead.
- Write in the brief's language. Facts (dishes, prices, hours, phone, address) come ONLY from the brief; voice and furniture are yours.

## Visual signatures (what makes it instantly recognizable)
- Flour-dusted warm paper ground, tinted bone/oat — never white, never a cool gray anywhere.
- Fat, soft, low-contrast display type at weight 650-800, cropped tight (line-height .88-.94) so words sit like loaves on a rack. Hairline display type is banned here.
- Ruled MENU TABLES with dotted leaders and DZD prices, at least twice, once as a full chapter.
- Hand-drawn SVG doodles at least nine times, in currentColor, rotated off-axis, drawing themselves in on scroll, one of them crossing a seam.
- WAVY SEAM EDGES: full-bleed photographs and colour bands end on an asymmetric hand-cut wave, never a straight line.
- A charcoal CHALKBOARD PLATE (du jour) leaning on a photograph, slightly rotated, with an inset chalk hairline and chalk dust.
- A moving TICKER of product names between two chapters, over a fixed full-viewport FLOUR DUST grain at 14 percent, multiply.
- Macro warm photography — crumb, steam, hands, sugar — welded into the layout, never a rectangle in a slot.
- The page closes on a solid fat edge-to-edge wordmark with a drawn wheat stalk across its baseline.

## Color physics (route the brief's palette through the fixed tokens — the physics is law)
FIXED TOKEN MAP — FARINE→--background · ENCRE→--foreground · CROÛTE→--primary · FARINE→--primary-foreground · FARINE-SOFT→--secondary · CHARBON→--accent · ink at 56%→--muted · ink at 14%→--border · 999px→--radius · DISPLAY→--font-heading · BODY→--font-body. These are the only CSS color/type/radius variables: every pole below is a prose role, literal register hexes belong only in these :root values, and every sibling, glow or alpha step is a color-mix(in srgb, var(--foreground) N%, transparent), substituting the mapped fixed token for that pole, or a color-mix between two mapped fixed-token references. Every unmapped role below MUST reuse the nearest mapped token or such a mix; it never gets another custom property or literal. Non-color mechanics may keep their own custom properties. Any rgba(POLE, a) notation below is design shorthand for that color-mix, never emitted CSS.
Build EIGHT tonal roles from the fixed tokens, never a ninth hue.
- FARINE (ground): the lightest warm pole, flour-tinted paper in the #F6EFE1 register. Never #fff, never #fafafa, never a cool off-white.
- FARINE-SOFT: a second ground 3-6 RGB points darker and a notch warmer (#EFE4D0 register), ONLY for chapter alternation and the transactional chapter.
- ENCRE (ink): a warm dark brown where R is greater than G is greater than B (#2E2013 register). Never #111, never #333, never slate.
- INK AT ALPHA — the rule that makes this read as paper rather than UI: body rgba(ink,.76) · captions and descriptions rgba(ink,.56) · ALL hairlines rgba(ink,.14) · leader dots rgba(ink,.30) · placeholders rgba(ink,.34) · tracks rgba(ink,.10). No independent gray hex exists; a #888 or #6b7280 here is a Pass-1 correctness bug.
- BEURRE (butter): the warm light accent (#F3CB80 register). A FILL, NEVER TEXT ON PAPER — its contrast against farine is about 1.4:1. Jobs: doodle fills, the ticker band, a highlight behind a du-jour word, the trust band, the menu-row hover wash at rgba(beurre,.28), the oven glow's inner stop.
- CROÛTE (crust): the mid warm pole (#C1743A register), PRIMARY accent and the page's second voice. Use at least ten jobs: the accented headline word, the drawn underline, every doodle stroke on light grounds, menu section rules, featured price marks, the primary pill, the ghost button's drawn outline, ::selection, :focus-visible, the nav and sticky-bar strokes, ticker separators, batch numerals, margin-note ink, the progress rule.
- BRAISE (ember): the deep hot pole (#A0361A register), the RARE accent capped at EIGHT appearances — the du-jour star and price, the primary button's hover fill, the oven glow's hot stop, the live open dot, validation errors. Ember everywhere stops meaning hot.
- CHARBON (dark pole): a warm near-black-brown (#241A11 register) for the chalkboard, the one inverted chapter, the ticker variant and the footer. Its companion CRAIE (chalk) is a warm off-white (#EFE6D3 register) used for ALL text on charbon — pure white never sets text here. Hairlines on charbon are rgba(craie,.18).
GRADIENTS ARE RATIONED TO FIVE NAMED JOBS: the hero photo scrim · the flour-dust seam dissolve · the oven glow · the ticker band's 4rem end fades · a 165deg raking sheen at rgba(craie,.05) on the du-jour plate. A sixth is decoration and is banned. Declare color-scheme:light and a theme-color meta matching farine; the inverted chapter does not change it.

## Typography system
THREE families, three sealed jobs. Territories, not mandates — commit to one pairing, load only the weights used, never Inter/Roboto/Open Sans.
- DISPLAY: a SOFT SLAB or rounded low-contrast serif with real weight — Recoleta / Fraunces (soft optical setting) / Bitter / Zodiak territory. Weights 600 and 700 only, 800 for the closing wordmark. Never below 500, never sets a paragraph. Jobs: h1-h3, dish names, prices, all numerals above 1rem, batch numbers, wordmark, ticker, button labels.
- BODY: a warm humanist sans with a generous x-height — General Sans / Hanken Grotesk / Cabinet Grotesk / Satoshi territory, 400/500/600. Jobs: paragraphs, dish descriptions, micro-caps, labels, inputs, captions, hours. Never above 1.35rem except one lede.
- HAND: ONE handwriting face — Caveat / Kalam / Gochi Hand territory. ONLY margin notes and chalk annotations; never a heading, button or price; never above 1.25rem; never more than five instances; ALWAYS rotated -4deg to +3deg. A second handwriting face is a bug.

Scale, all clamp, all committed: hero h1 clamp(3.4rem,9.2vw,8.4rem) / .88 / -.028em / 700 · h2 clamp(2.35rem,5.4vw,4.4rem) / .94 / -.022em / 700 / max-width 13em · h3 and dish names clamp(1.12rem,1.9vw,1.42rem) / 1.18 / -.008em / 600 · lede clamp(1.05rem,1.45vw,1.22rem) / 1.58 / 30em · body 1.0625rem / 1.62 / 0 · dish description .875rem / 1.5 / rgba(ink,.56) / 42ch · menu price clamp(1.05rem,1.5vw,1.28rem) / 600 / tabular-nums · block price moment clamp(2.4rem,4.6vw,3.6rem) / 700 / -.02em · micro-caps .72-.8rem uppercase, .18-.26em tracking, 600, rgba(ink,.56) · margin note .98-1.15rem / 1.28 · closing wordmark clamp(4.2rem,18vw,16rem) / .82 / -.03em / 700-800, SOLID FILL (this world never outlines its wordmark — outlined type reads cold here). Display-to-micro ratio near 11:1; do NOT generate 1.6rem / 2rem intermediate headings, the empty middle is what stops a page looking automated. TRACKING IS A FUNCTION OF SIZE: -.028em above 100px, -.022em at 45-80px, -.008em at 18-24px, 0 at body, +.18em to +.26em at 11-13px uppercase.

CROP THE DISPLAY TIGHT: line-height .88-.94 plus an optical crop of margin-block-start:-.1em to eat the face's internal leading; inside masked line-rise wrappers add padding-bottom:.06em with margin-bottom:-.06em so descenders survive. NEVER LET A DISPLAY HEADLINE AUTO-WRAP — break it into explicit block-level line spans so the rag is AUTHORED, and reuse those spans as stagger targets.

THE DRAWN EMPHASIS replaces the italic accent word: wrap one word per headline in a crust span at position:relative and absolutely place a hand-drawn underline under it — viewBox 0 0 200 14, preserveAspectRatio="none", one path of two overlapping strokes (3.2px, plus 1.8px offset 2px down and 6 percent shorter), round caps, crust at .85, width 104 percent, left -2 percent, bottom -.18em. It draws itself on; three per page maximum.

PROMOTE NUMERALS: inside prose, wrap quantities in a span carrying the display face at 1.3em weight 600 with tabular-nums, so "cuit 18 min à 240 degrés" has display numerals inside a body sentence. That one rule is most of the baker's-log effect.

## The drawn language (the traveling motif — build this library FIRST, before any markup)
Author SIX glyphs as inline SVG symbols in a hidden sprite, then instance them with use. Never an icon font, never a pasted Feather/Heroicons path.
1. ÉPI, a wheat stalk: one stem cubic plus seven paired grains, each pair NOT mirrored (4-8 percent length difference, 3-5deg angle difference). 2. VAPEUR, steam: three S-curves at 100 / 74 / 58 percent length rising at different angles, the shortest starting highest. 3. FOUET, a whisk: five arcs converging into a handle, the outer two crossing. 4. MIETTES, crumbs: nine dots and two tiny ellipses at authored (never random) positions, radii 1.1 to 2.6 — the only glyph that uses fill. 5. LAME, the score: three parallel slashes at -62deg, different lengths, 1px lateral jitter. 6. FLÈCHE, the margin arrow: a hand-curved shaft with a two-stroke head whose barbs are unequal. Plus two utility strokes: the UNDERLINE squiggle above, and the SÉPARATEUR, a 14px grain used between ticker items.

DRAWING LAW — what separates drawn from clipart: viewBox 0 0 64 64 (48 for small ones), fill:none except MIETTES, stroke:currentColor · stroke-linecap and stroke-linejoin round, always · stroke widths VARY WITHIN one glyph (primary 2.4, secondary 1.7, tertiary 1.15 — one uniform weight is the tell of an icon set) · vector-effect:non-scaling-stroke so 3.4em and 1.1em instances share an honest line · nothing symmetric or axis-aligned, no perfect circles, no right angles, C and Q curves wherever a curve is possible · sized in em (1.05em inline, 1.6-2.2em in section heads, 3.2-5.4em as scene ornaments) so doodles scale with type · rotated between -8deg and +8deg, never 0 · colour inherited via currentColor, so one glyph is crust on paper and craie on the chalkboard — that inheritance IS the traveling motif · every path carries pathLength="1" so the draw-on tween is trivial · MINIMUM NINE instances across at least five scenes, one absolutely positioned across a seam at z-index 4, half on photo and half on paper.
NO CANVAS in this world. Every mark is SVG or CSS, so there is no 2D-context fallback contract to write.

## Page chassis
- BANDEAU (optional, excellent for a shop): a full-bleed charbon strip above the nav, 2.4rem tall, centred, body face .8125rem, .07em tracking, craie text, a .4rem status dot (ember closed, warm-shifted crust open) and crust middot separators, carrying hours or today's batch. It also gives the nav a dark plate to detach from.
- NAV — THE COUNTER RAIL, triple-stated. position:sticky, top:0, z-index:100, padding .95rem var(--pad). Default fully transparent over the hero with ink text. Past 40px: background rgba(farine,.93), backdrop-filter blur(12px), and instead of a hairline a 4px DRAWN BASELINE — a repeating inline-SVG data-URI wavy stroke in crust at 24 percent, repeat-x, background-position bottom, background-size 120px 4px. A 1px border here is a failure.
- WORDMARK IS A LOCKUP: display face 1.4rem weight 700 at -.01em, preceded by the ÉPI at 1.15em rotated -7deg in crust, with a baseline-aligned sub-label in the body face at .6rem, .26em tracking, uppercase, rgba(ink,.5) — the trade word from the brief. Nav links: body .92rem weight 500, gap 1.9rem, rgba(ink,.72) to full ink over .22s, each with a 1.5px crust ::after growing from right:100% to right:0 over .28s. Primary pill on the end side.
- Below 860px the links collapse into LE TABLEAU: a full-screen farine overlay whose links are typeset AS A MENU TABLE — same component, same leader dots, anchor on the start side, a doodle where the price would sit. Open with a .42s power2.out clip-path circle wipe from the burger's coordinates; the burger is TWO strokes of unequal length (26px and 19px) crossing into an X over .3s.
- FLOUR DUST: position:fixed, inset:-40px, z-index:80, pointer-events:none, opacity:.14, mix-blend-mode:multiply, an inline-SVG data URI of feTurbulence fractalNoise baseFrequency 0.72 numOctaves 3 stitchTiles stitch, desaturated with feColorMatrix saturate 0, on a 220x220 rect at opacity .55. Coarser than film grain on purpose — this is flour.
- Base: html,body{overflow-x:clip} · scroll-behavior:smooth · ::selection crust at .9 with farine text · :focus-visible 2px crust outline at offset 3px · a skip link sliding top:-4rem to top:1rem on focus over .3s.
- THE COORDINATED NUMBERS, derived from the measured bandeau+nav stack and never guessed separately: hero min-height calc(100svh - 7.4rem), sticky offset top:6.2rem, scroll-margin-top:5rem on anchored sections.

## Hero forms (pick the one the shop calls for — all three are LOADED)
1. L'ÉTAL (the display counter — default). The photograph is the ground of the TOP of the screen only: full-bleed macro at height clamp(46svh,58svh,64svh), its BOTTOM edge cut by LA CROÛTE, scrimmed with linear-gradient(to bottom, rgba(charbon,.34), rgba(charbon,.02) 46%, rgba(charbon,0)). Over it, top-start, a -3deg margin note in the hand face and a chip with today's batch or the hours. BELOW the wave, on paper, the h1 is pulled UP by margin-top:-3.2rem at z-index:3 so its first line overlaps the wave and the rest lands on paper — one headline, two grounds; position the crest so that line falls in the photo's dark region, and only if contrast still fails add 0 1px 22px rgba(charbon,.35). Then: a lede at 30em · a THREE-ROW MENU TEASER built from the real menu component with three actual dishes and prices, never a paragraph, with a text link under it carrying a 1.5px crust underline · the CTA row (primary pill plus drawn-outline ghost) · the trust rail welded at padding-top:0. A VAPEUR doodle at 3.4em rises out of the h1's first line and crosses the wave into the photograph — the motif crossing a seam on screen one.
2. L'ARDOISE (the chalkboard hero — a shop whose offer changes daily). Full-viewport charbon with chalk dust (the grain re-tinted: feTurbulence at .09, mix-blend-mode:screen). The h1 in craie at full hero scale, one word in beurre with a chalk underline. Under it a real menu table of four items in the chalk token set — craie names, rgba(craie,.34) leader dots, beurre prices — and a hand-written date line. Doodles are chalk: craie at .78 opacity with a 0 0 1px blur. The first photograph arrives only in scene two, as a weld. NO CTA button in this hero; the nav pill and sticky bar carry the action, and the scroll cue is a drawn arrow that redraws itself every 2.6s.
3. LE COMPTOIR (the loaded split). Grid 1.08fr .92fr, gap clamp(2rem,5vw,4.5rem), min-height calc(100svh - 7.4rem). Left: h1, lede, a five-row menu teaser with prices, the CTA row, a -3.5deg margin note with a FLÈCHE pointing at the top-priced row. Right is a STACK, not a slot: a tall 4/5 frame at radius min(var(--radius), 2.2rem) with a wave-masked bottom edge, a square detail plate (aspect 1/1, radius min(var(--radius), 1.4rem), width 42 percent) overlapping at margin-top:-3rem and margin-inline-start:-2.6rem with 0 26px 56px -30px rgba(ink,.4), and a FOUET at 5.4em drawn BEHIND both at z-index:0 in crust at .35, overflowing the column by 2rem. Never a single full-bleed photo slab in the right column.
EVERY hero terminates in a RAIL, never in whitespace: a full-bleed strip, border-block 1px rgba(ink,.14), padding 1.05rem var(--pad), four uppercase micro-labels at .76rem/.2em each preceded by a 1.05em doodle — real facts from the brief (levain naturel, livraison Alger, paiement à la livraison, ouvert 6h-20h), never adjectives. Below 600px a 2x2 grid at .68rem.

## Section seams (the fournil's own vocabulary — every boundary uses one, never the same twice in a row)
Use at least FIVE of these seven per page.
- LA CROÛTE (the hand-cut wave — the signature). Any full-bleed photograph or colour band ends on an asymmetric wave. TECHNIQUE, exactly: do NOT use clip-path with pixel coordinates, it will not stretch. Use a mask — an inline-SVG data URI, viewBox="0 0 1440 120", preserveAspectRatio="none", one black path of cubic curves with THREE crests at x 258 / 676 / 1138 and amplitudes 64 / 38 / 52, closed down to y=120 — applied as mask-image plus -webkit-mask-image with mask-size:100% 100% and mask-repeat:no-repeat on the OUTGOING block, so its own edge becomes the wave and the next ground shows through; the incoming section takes margin-top:-1px to kill the sub-pixel hairline. Prepare THREE amplitudes — tall (120 of 1440), medium (84), shallow (44) — swapped at 1024px and 640px, so the wave never eats more than 22px of a phone screen. A second path with crests at 190 / 742 / 1092 and amplitudes 44 / 70 / 30 exists so no two waves share a rhythm. Flip with transform:scaleY(-1) inside the SVG when the wave bites into the TOP of the incoming section. NEVER a symmetric sine, a CSS-triangle diagonal, or a smooth blob.
- LA SOUDURE (the weld). The next chapter starts at padding-top:0 directly against a full-bleed bake photograph, so the photo belongs to the joint rather than either scene; the incoming scene's first element — a margin note, a menu section head, a pulled-up plate — sits ON it over a scrim.
- LE TAPIS (the conveyor — the ticker interlude). A band 3.4-4.4rem tall: charbon with craie text, or beurre with ink text. A width:max-content flex track of TWO identical chunks animated translateX(0) to translateX(-50%) by CSS keyframe over 28s linear infinite. Items in the display face 500 at 1.12rem, .03em tracking, padding-inline 1.5rem, product names from the brief, separated by the 14px SÉPARATEUR in crust. Both ends take a 4rem mask fade to the band colour; prefers-reduced-motion sets animation:none and width:auto. ONE per page is the default and the safe choice; a SECOND is permitted only if it runs the opposite direction at 34s, sits at least three scenes away, and takes the other ground (charbon if the first was beurre). Never a third, never two adjacent.
- LA FARINE (the dust dissolve). An 18-22vh gradient carrying the outgoing ground into the incoming one, plus 22 AUTHORED (never JS-random) drawn crumbs at fixed percentage positions, sizes 2-7px, opacities .10 to .28 in crust and ember, densest at the seam and gone within 14vh. The quietest seam; use it once.
- LE FOUR (the oven — ground inversion). Exactly ONE chapter flips to charbon and the type system flips with it: craie text, rgba(craie,.18) hairlines, beurre accents instead of crust, chalk-weight doodles, warmer photo scrims. Enter on LA CROÛTE and leave on LA SOUDURE so the inversion is never announced by whitespace.
- LA PLANCHE (the board overlap). A menu plate, the du-jour board or a quote card pulled UP onto a full-bleed photograph at margin-top -4rem to -7rem, z-index:3, with a doodle overhanging the plate's own top edge by 1.2rem — a double overlap.
- LE PLI (the fold). A butt-join where one DRAWN LINE leaves the last element of scene A and re-enters at the top-start of scene B, absolutely positioned across the boundary at z-index:4. Use once, on the otherwise weakest seam.
A page whose every boundary is whitespace plus a hairline has ignored this world entirely.

## Layout physics
- ONE inline-padding token: clamp(1.15rem,4.2vw,4rem). Container max-width 82rem — tighter than a corporate canvas, because a menu wants a readable measure. Section block padding clamp(4.5rem,10vh,7.5rem); a welded section takes 0 on the welded side. MEASURE CAPPED IN EM: body 34em · lede 30em · dish description 42ch · margin note 16ch · pull-quote 19em.
- NO GRID IS 50/50: hero split 1.08fr/.92fr · story .86fr/1.14fr (the media column is the narrow one because it is sticky) · menu chapter 1fr/1fr ONLY as two independent menu columns with a gutter rule, never text-plus-image · transactional .9fr/1.1fr · hours-and-address 1.2fr/.8fr. Gaps clamp(2.2rem,5.5vw,5rem). At least one grid must invert expectation.
- GUTTER RULES, NOT CARD EDGES, above 1024px: adjacent siblings take border-inline-start 1px rgba(ink,.14), padding-inline-start clamp(1.8rem,3vw,3rem), margin-inline-start calc(clamp(2.2rem,5.5vw,5rem) * -.5), so the rule sits in the MIDDLE of the gutter. Below 1024px they stack at gap 2.6rem, max-width 34rem.
- SHAPE IS SOFT AND FAMILIED — this world overrides the global suspicion of border-radius. :root sets --radius: 999px for buttons, pills and chips. Everything else caps that knob: min(var(--radius), 2.2rem) large photo frames · min(var(--radius), 1.6rem) plates and the du-jour board · min(var(--radius), 1.4rem) small plates and textareas · min(var(--radius), .9rem) inputs. BUT no two ADJACENT frames may share both the same radius and the same aspect ratio, and at least one frame per page must have a WAVE-MASKED edge instead of a radius. Twelve identical 16px-radius cards is a failed page regardless of colour.
- OVERFLOW IS COMPOSITIONAL: exactly five elements break their container — the hero headline over the wave (-3.2rem), the detail plate (-3rem / -2.6rem), the FOUET behind the hero stack (+2rem), one doodle crossing a seam, the du-jour board rotated out of its column. Safe only because overflow:clip sits on every section containing a piercing element, plus overflow-x:clip on html and body.
- ONE STICKY ANCHOR at top:6.2rem so a single macro photograph serves a whole chapter while three ledger rows pass it. Any parallaxed image is top:-11% and height:122% inside an overflow:hidden parent, so travel never exposes an edge.
- A PRODUCT RANGE is a bento with hierarchy, never a uniform grid, and the tiling must be EXACT — an under-filled bento auto-places into a ragged extra row and reads as a mistake. grid-template-columns:repeat(6,1fr), gap clamp(1rem,2.2vw,1.8rem), three rows: the lead item spans columns 1/5 and rows 1/3 (4 wide, 2 tall), two items span columns 5/7 at rows 1 and 2 respectively (2 wide, 1 tall each), and a fourth spans columns 1/7 on row 3 as a wide plate carrying a caption. Eighteen cell units, eighteen used, no holes. Below 780px 1fr with the lead keeping a taller aspect.
- RESPONSIVE COLLAPSE: below 1024px every two-column grid becomes 1fr, sticky becomes static, the hero stack narrows to min(100%,27rem), the showpiece unpins, the menu grid becomes one column. Below 600px wave amplitudes drop to the shallow mask, margin notes move inline under what they annotate (still rotated, arrow hidden), the trust rail becomes 2x2.

## The menu system (the centrepiece — build this component before anything else)
- Container: ul, list-style:none, padding:0. Each li: display:grid, grid-template-columns:auto 1fr auto, align-items:baseline, column-gap:.7rem, padding-block:.95rem, border-top:1px solid rgba(ink,.14); the last also takes border-bottom. ZERO background, ZERO radius, ZERO shadow on a menu row — it is typesetting, not a card.
- Column 1, the name block (a div, so a description can sit under the name without breaking baseline alignment): the dish name in the display face at clamp(1.12rem,1.9vw,1.42rem) weight 600, then optionally a description in the body face at .875rem/1.5 in rgba(ink,.56), 42ch, margin-top .28rem. Optional inline chips after the name: .66rem uppercase, .14em tracking, padding .2em .62em, radius var(--radius), background rgba(crust,.12), colour crust ("chaud", "sans gluten"; "épuisé" in rgba(ink,.4) with the whole row at opacity .55).
- Column 2, THE LEADER — the most characteristic device here and the one almost no generated page has: a span at height:1px, align-self:baseline, transform:translateY(-.3em), margin-inline:.3rem, background-image:radial-gradient(circle, rgba(ink,.30) 1px, transparent 1.2px), background-size:6px 1px, background-repeat:repeat-x, background-position:0 100%. Dots every 6px across the whole free width. Never a solid rule, never a dashed border.
- Column 3, the price: display face 600, tabular-nums, clamp(1.05rem,1.5vw,1.28rem), full ink, with the currency mark in a nested span at .62em, .06em tracking, rgba(ink,.55), margin-inline-start .3em, translateY(-.06em). Thousands separated by a NARROW NO-BREAK SPACE (U+202F) so it reads 3 500 DZD and never wraps.
- THE DU JOUR ROW: an ember MIETTES-or-star doodle at .9em absolutely placed at inset-inline-start:-1.35rem, the name at weight 700, the price in ember. One per menu block maximum.
- MENU SECTION HEAD, a running head and never a centred h2: an inline-flex baseline row of [doodle at 1.6em in crust] [uppercase micro-label .76rem/.24em] [flex:1 leader-dot rule at rgba(ink,.2)] [right-aligned factual aside, body face .8rem, rgba(ink,.5)], margin-bottom 1.15rem.
- MENU CHAPTER: at least ONE full-width chapter that is nothing but menu — two columns above 900px separated by a gutter rule, each with two or three section heads, on farine-soft, LA CROÛTE seams top and bottom, and ONE large macro photograph welded into the flow spanning both columns, wave-masked, with a Plat caption. This chapter earns the page its living; give it the hero's level of attention.
- HOVER (desktop, interactive rows only): background washes to rgba(beurre,.28) over .22s, the name translates 4px along the inline axis, the price turns crust, the leader dots shift background-position by 3px — four coupled changes inside .25s.
- THE HOURS TABLE reuses the identical component: day, leader dots, hours in tabular-nums, today's row at weight 600 in crust with an ember dot if open. One component, three jobs — menu, nav overlay, hours.

## Photography direction
MACRO AND WARM ONLY: crumb structure, a torn loaf, steam off a cup, sugar dust, hands working dough, a tray coming out. Shallow depth, 3200-3600K, raking side light, at least one shot with HANDS in frame and one with steam or flour in the air. BANNED: wide empty interiors, white-background packshots, smiling stock staff, flat overheads, anything cool-toned. Every photograph is wave-masked, welded, or in a radius-familied frame with a caption — a plain 16px-radius rectangle is the failure state. A photo fighting the palette gets linear-gradient(rgba(crust,.10), rgba(braise,.06)) at mix-blend-mode:multiply plus filter:saturate(1.04) contrast(1.02); type over one always gets a scrim whose final stop equals the ground it dissolves into. Explicit width and height on every img, fetchpriority="high" on the hero, loading="lazy" below the fold, real descriptive alt.

## Motion identity (GSAP 3 + ScrollTrigger from a CDN)
SAFETY CONTRACT FIRST. animate = typeof window.gsap !== "undefined" && !matchMedia("(prefers-reduced-motion: reduce)").matches. EVERY hidden initial state is set with gsap.set() INSIDE that branch — never opacity:0, visibility:hidden or a hiding stroke-dashoffset in CSS. If the CDN fails the page is fully visible, every doodle fully drawn, every menu row, price, tel link and form working. The reduced-motion block also sets the ticker to animation:none;width:auto and stops the steam.

THIS WORLD OVERRIDES THE GLOBAL MOTION DEFAULTS: gsap.defaults({ease:"power2.out", duration:.75}). Reveals are SHORT and slightly springy; a 1.1s power3 reveal here feels like the bread went cold.
- BANDS: .2-.35s interaction · .45-.6s component state · .6-.9s narrative reveals (the signature band) · 1.2-1.5s image wipes with the inner image counter-scaling over 1.6s (de-synced) · 3.2-4.4s ambient steam · 28s ticker · the showpiece is scrubbed.
- EASES: power2.out by default · back.out(1.6) RESERVED for SMALL objects only (chips, doodle pops, the du-jour star, the success stamp), travel capped at 14px and duration at .5s — never bounce a headline, a photograph or a section · power3.inOut for clip and mask wipes · power1.inOut for doodle draw-ons · sine.inOut for steam · none for scrub.
- TRAVEL IS SHORT: y offsets of 12 / 22 / 34 only, scales .94 / .97 / 1.04 / 1.12, hover lift translateY(-2px). Nothing travels 100px.

THE MANDATORY SET:
1. HERO ENTRANCE — one timeline, overlapping positions, done in about 1.5s. Set photo wrapper autoAlpha 0 with inner img scale 1.12; headline lines yPercent 108 in their masks; lede, teaser, CTA row and rail autoAlpha 0 y 22; margin note and chip autoAlpha 0 y 12 rotate -8deg. Then tl.to(photo,{autoAlpha:1,duration:.7},0).to(img,{scale:1,duration:1.5},0).to(lines,{yPercent:0,duration:.72,stagger:.07},.18).to(copy,{autoAlpha:1,y:0,duration:.62,stagger:.08},.52).to(note,{autoAlpha:1,y:0,rotate:-3.5,duration:.5,ease:"back.out(1.6)"},.86). The .07 stagger overrides the global .09-.14; lines land like trays going onto a rack.
2. THE DOODLE DRAW-ON — the motif's own motion, and what makes the page feel hand-made. gsap.set(paths,{strokeDasharray:1,strokeDashoffset:1}) then gsap.to(paths,{strokeDashoffset:0,duration:1.05,ease:"power1.inOut",stagger:.12,scrollTrigger:{trigger:glyph,start:"top 82%",once:true}}). ÉPI and FOUET take 1.3s; MIETTES pops instead with back.out(1.7) at .42s stagger .04, because dots cannot be drawn; underline squiggles draw at .55s.
3. MASKED LINE RISES on every display block: yPercent 108 to 0, .72s power2.out, stagger .07, start "top 86%", once. Split at REAL browser wrap points (compare offsetTop), preserve accent spans with a class, run on window.load so font metrics are final, aria-label on the parent and aria-hidden on the lines, then ScrollTrigger.refresh().
4. IMAGE WIPES: clipPath inset(0 0 100% 0) to inset(0) over 1.3s power3.inOut while the inner img counter-scales 1.12 to 1 over 1.6s power2.out, both at position 0, then clearProps; start "top 88%", once. On wave-masked images animate a wrapper's clip-path so the mask survives.
5. MENU ROW REVEALS — the most repeated tween on the page and it must be tight: autoAlpha 0 y 12 to autoAlpha 1 y 0, duration .5, stagger .045, start "top 88%", once. Twelve rows at 1s each reads as a loading screen.
6. ONE AMBIENT LOOP: LA VAPEUR. Three steam curls, each gsap.to({y:-8, opacity:"+=.3", duration:3.2 / 3.8 / 4.4, ease:"sine.inOut", yoyo:true, repeat:-1, delay:0 / .4 / .8}), over something genuinely hot — steam on a cold pastry is a lie and is banned.
7. ONE SCRUBBED PARALLAX besides the showpiece, on the welded photograph: gsap.fromTo(img,{yPercent:-6},{yPercent:6,ease:"none"}), start "top bottom", end "bottom top", scrub:true.
8. COUNT-UPS on stats only, via a proxy over 1.2s power2.out, once, start "top 88%", with a 4000ms setTimeout fallback painting the final value. PRICES NEVER COUNT UP — a price is set in type, not animated.
9. The ticker runs on CSS keyframes; the sticky bar on its own trigger. once:true on EVERYTHING non-scrubbed; nothing re-animates on scroll-up.

MICRO-INTERACTIONS (CSS): the primary pill lifts 2px and fills crust to braise over .25s with a DECOUPLED .25s translateX(4px) on its arrow — two transitions, not one · the ghost button's drawn outline cross-fades to a second wobble over .2s so the line looks REDRAWN · inputs change three properties together on focus over .28s (border-color crust, box-shadow 0 0 0 3px rgba(crust,.18), background lightening) · nav links grow a 1.5px crust underline from the inline start over .28s · the du-jour board straightens from rotate(-.6deg) to 0 over .5s on hover.

LENIS IS OPTIONAL AND OFF BY DEFAULT. If the brief asks for it: lerp .085, expose window.__lenis, wire lenis.on("scroll", ScrollTrigger.update) plus gsap.ticker.add((t)=>lenis.raf(t*1000)) with gsap.ticker.lagSmoothing(0). If you cannot wire it correctly, do not add it.

## The showpiece: LA POUSSE (the rise — the oven timeline)
One pinned, scrubbed scene with three times the ambition of any other, narrating the making — rest, shape, bake, counter. The STAGES come from the brief; the FORM is yours.
- Chassis: ScrollTrigger {trigger:section, start:"top top", end:"+=" plus 3.2 times window.innerHeight, pin:true, scrub:1, anticipatePin:1, invalidateOnRefresh:true}. Inside, a 100svh grid at .88fr/1.12fr: stage copy on the start side, the dough stage on the other.
- THE DOUGH: a div at width min(30vw,26rem), aspect-ratio 1, background radial-gradient(circle at 38% 32%, beurre, crust 68%, braise 108%), with an organic border-radius tweened across FOUR strings of identical structure so GSAP interpolates safely: "48% 52% 56% 44% / 52% 46% 54% 48%", "44% 56% 52% 48% / 58% 42% 56% 44%", "50% 50% 46% 54% / 46% 56% 44% 56%", "46% 54% 50% 50% / 54% 46% 52% 48%". Simultaneously scale .58 to 1.02, y 34 to 0, filter saturate(.82) brightness(1.06) to saturate(1.1) brightness(.94) — pale and small becomes dark and full. The rise and the bake in one tween.
- THE OVEN GLOW: radial-gradient(circle, rgba(braise,.55), transparent 62%) at width 150 percent behind the dough, opacity 0 to .9 and scale .8 to 1.2 across the LAST 32 percent of the timeline only, so heat arrives late.
- THE READOUT: a tabular-nums display figure counting the brief's start temperature to its bake temperature (or a clock across its hours), written by an onUpdate on the same scrubbed timeline, beside a micro-label naming the current stage that cross-fades over .3s at each tick. THE PROGRESS RULE: a 2px crust rule, transform-origin left, scaleX 0 to 1 across the scrub, with four tick marks whose labels go rgba(ink,.32) to full ink and whose doodles go ember as the playhead passes. PHOTOGRAPHY: four macro stills absolutely stacked, cross-fading with autoAlpha over 22 percent of the timeline each, each with a Plat caption that swaps with it.
- FALLBACK CONTRACT, mandatory: the CSS default layout is the STACKED one; the pin is opt-in inside gsap.matchMedia("(min-width: 900px)") with a proper teardown. Below 900px, with reduced motion, or with no GSAP, the four stages render as four ruled rows — doodle, stage label, time, photo, one line of copy — each revealed once at "top 86%" with the standard .5s row tween, and the dough is a single static shape at its final border-radius. Nobody ever sees a broken pin.

## Components
- BUTTONS. Primary: pill at border-radius var(--radius) (:root sets --radius: 999px), crust background, farine text, padding 1.02em 1.75em, display face 600 at .96rem, inline-flex gap .6em with a drawn arrow; hover fills braise and lifts 2px. Ghost: the same var(--radius) silhouette with NO CSS border — a ::before at inset:0 carrying a DRAWN ROUNDED-RECT outline as an inline-SVG data URI (preserveAspectRatio="none", background-size:100% 100%, stroke crust, stroke-width 2.4, corners drawn as slightly unequal cubics so the shape wobbles), cross-fading to a second wobble on hover over .2s. Small variant .78em 1.3em at .86rem; disabled at opacity .45. NEVER a full-width solid rectangle button.
- SHADOWS: only under PHOTOGRAPHS, the du-jour board, floating chips and the sticky bar, always large-blur, negative-spread, hue-tinted — 0 30px 70px -34px rgba(ink,.42) large frames · 0 20px 44px -24px rgba(ink,.34) small plates · 0 26px 60px -30px rgba(charbon,.5) under the du-jour board. ZERO shadow on menu rows, buttons, chips in flow, nav or inputs.
- THE DU JOUR BOARD: charbon, radius min(var(--radius), 1.6rem), padding clamp(1.6rem,3.6vw,2.6rem), rotate(-.6deg), a ::before at inset:.55rem with border 1px rgba(craie,.22) and radius min(var(--radius), 1.1rem) (the chalk frame inside the frame), the chalk-dust layer, the 165deg raking sheen, the heading in craie with a beurre chalk underline that draws on, a menu table in the chalk token set, and a hand-face date line at the bottom end rotated 2deg. It sits as LA PLANCHE, overlapping a photograph.
- INPUTS: background color-mix(in srgb, var(--background) 62%, transparent), border 1.5px solid var(--border) — real borders are legal here, they are ink lines — radius min(var(--radius), 1.4rem) on textareas and min(var(--radius), .9rem) on single-line fields, padding .95em 1.1em, body face 1rem. Labels above at .74rem weight 600 uppercase, .18em tracking, var(--muted); hints .78rem. Selects identical, with a drawn chevron as a background data URI. CHIPS: var(--radius), padding .22em .68em, .68rem uppercase .14em weight 600, background color-mix(in srgb, var(--primary) 12%, transparent), colour var(--primary); hot variant color-mix(in srgb, var(--primary) 14%, transparent) with a var(--primary)/var(--foreground) mix for text.
- ACCORDION: a hairline list, questions in the display face at clamp(1.02rem,1.6vw,1.24rem) weight 600, padding 1.3rem 0, turning crust when open; panels animated grid-template-rows 0fr to 1fr over .5s with an overflow:hidden inner, icon the LAME doodle rotating 0 to 90deg over .45s, single-open, aria-expanded maintained.
- FOOTER: charbon, entered on LA CROÛTE, craie type, an hours table and address on the start side, a drawn-doodle contact row on the end side, then THE MONUMENT — the wordmark at clamp(4.2rem,18vw,16rem), line-height .82, weight 700-800, SOLID in rgba(craie,.9), with an ÉPI at 6em rotated -12deg laid across its baseline at rgba(beurre,.5), user-select:none, aria-hidden. Under it a hairline row of links at .85rem rgba(craie,.7) and a credit at .8rem rgba(craie,.45).
- CRAFT: tabular-nums on every price, total, hour and counter · unicode-bidi:isolate on price spans · an inline-SVG data-URI favicon drawn from the ÉPI · aria-live="polite" on error and status text · sr-only text on icon-only links · every phone number a real tel: link.

## Conversion objects (this market is cash-on-delivery and WhatsApp — these are the money components)
- PRICE TYPOGRAPHY: display face, 600-700, tabular-nums, thousands separated by U+202F narrow no-break space (3 500 DZD), currency mark in a .62em span at rgba(ink,.55) with .06em tracking. A struck was-price sits at .78em in rgba(ink,.5) with text-decoration-color crust at 1.5px. A featured price takes ember; everything else stays ink.
- WHATSAPP CTA: the WhatsApp glyph inline as SVG at 1.05em in currentColor, inside THIS world's crust pill. The brand green is BANNED — a green blob fighting warm paper is the fastest way to make the design look assembled. The link is a real wa.me URL built from the brief's number with a pre-filled message in the page's language naming the shop and the item.
- STICKY MOBILE ORDER BAR: below 860px, fixed bottom, height 4.6rem, background rgba(farine,.94) with backdrop-filter blur(14px), a 3px DRAWN wavy top edge (the nav's repeating data URI, crust at .3), padding-inline var(--pad), padding-bottom max(.7rem, env(safe-area-inset-bottom)). Start side: item or shop name at .8rem rgba(ink,.6) over the price in the display face at 1.15rem. End side: the primary pill. Enters on a ScrollTrigger at the hero's bottom via gsap.fromTo(bar,{yPercent:110},{yPercent:0,duration:.45,ease:"power2.out"}); the footer takes padding-bottom:5.4rem below 860px so it never covers the last section.
- THE ORDER SLIP (bon de commande) — the transactional chapter's centrepiece, on farine-soft with LA CROÛTE seams, grid .9fr/1.1fr with the slip on the wider side. It is a TICKET: farine ground, radius min(var(--radius), 1.4rem) on the bottom corners only, and a PERFORATED TOP EDGE via -webkit-mask-image:radial-gradient(circle 7px at 7px 0, transparent 96%, var(--foreground) 100%); mask-size:14px 100%; mask-repeat:repeat-x — half-circles bitten out every 14px. Inside: a header row with the shop name and a batch number, a dotted-leader order summary using the same leader component, then the fields.
- FIELDS, in this order: nom complet (autocomplete="name") · téléphone, type="tel" inputmode="tel" autocomplete="tel", a real pattern for the local format and a hint naming what the call is for · wilaya, a select styled identically to the inputs, listing the brief's delivery zones with the fee beside each · adresse (textarea, 3 rows) · quantité as a STEPPER, not a number input — an inline-flex group at border-radius var(--radius) with 2.8rem true-circle buttons at 50% and an output at min-width 2.4rem in the display face at 1.2rem, with a cap AND A REASON FOR THE CAP in the hint · delivery as radio TICKETS driven by :has(input:checked), the 1.5px hairline going crust plus box-shadow 0 0 0 1px crust plus a rgba(beurre,.22) wash over .3s, with a drawn check that draws itself in over .35s.
- FOOT OF THE SLIP: a border-top hairline row, space-between, padding-top 1.5rem — a live TOTAL in the display face at 1.9rem weight 700 tabular-nums under a .8rem/.18em uppercase label, recomputing on every quantity and delivery change — beside the submit pill, with a .8rem line stating exactly what happens next, from the brief's facts. VALIDATION IS BLUR-GATED: a touched map so an error appears only after a field's first blur; errors in ember, full sentences in the baker's voice, min-height:1.2em reserved so nothing reflows.
- SUBMIT: a 700ms pending state with a human present-tense label, then the slip CROSS-FADES IN PLACE into a success panel absolutely positioned over it in the same box (success in over .6s with .2s delay; form out over .4s to translateY(-8px) with visibility 0s .4s so focus never lands on a hidden element). The panel opens on a DRAWN STAMP — a hand-drawn circle-and-text SVG rotated -8deg scaling from .82 with autoAlpha 0 to 1 over .5s back.out(1.7), the order number in tabular display numerals inside it, the copy echoing the buyer's own name and choices. Persist in localStorage and restore the success state instantly on return.
- TRUST STRIP: four items, each a drawn 1.6em doodle (scooter, coin, clock, phone) in THIS world's stroke language — irregular, round-capped, varied widths, never a Feather icon — over a .76rem/.2em uppercase micro-label and a .82rem body line. Between hairlines on farine, or with no rules at all on a beurre band. The one block whose cells may be centred.
- Forms never pretend to POST to a server — though the moment validation passes, as the stamp lands, the page passes the order over the counter by dispatching the wandit:lead CustomEvent on document with the buyer's fields flat in detail (name, phone as typed, wilaya, commune, plus quantité and delivery choice), and the slip carries one off-canvas decoy input marked data-wandit-hp that the page's own script never touches. The WhatsApp link and the tel: link work with JavaScript completely disabled.

## Editorial furniture (REQUIRED — this is the fournil's voice)
- MARGIN NOTES in the hand face, five maximum, rotated -4deg to +3deg, crust at .9, max-width 16ch, absolutely placed in a gutter with a FLÈCHE pointing at what they annotate (inline below 900px, arrow dropped). Always about the making — an hour, a quantity, a temperature, a person.
- BATCH NUMBERS instead of section numerals: "Fournée 01", "Fournée 02" in the display face at .82rem, .16em tracking, crust, in every section head's leading gutter.
- PLAT CAPTIONS under photographs: a space-between row, a descriptive line in rgba(ink,.56) at .78rem on the start side, "Plat 03" in crust on the end side.
- THE HOURS TABLE typeset with the menu component's leader dots, today's row weighted and dotted; ONE INGREDIENT LINE in the body face at .92rem in rgba(ink,.6), what goes in and nothing else, strictly from the brief.
- ONE OWNER PULL-QUOTE in the display face at clamp(1.5rem,2.6vw,2.1rem) weight 600 / 1.25, laid over a photograph as LA PLANCHE, with a drawn quote mark overhanging its top-start corner by 1.1rem and a .78rem/.18em uppercase citation beneath.
- A CHALK DATE LINE on the du-jour board in the hand face rotated 2deg, plus PROMOTED NUMERALS wherever the brief gives a real quantity. These invent no business fact — they are TYPESETTING.

## Arabic and RTL adaptation
- dir="rtl" with the right lang, and the whole chassis built on logical properties (padding-inline, margin-inline, border-inline-start, inset-inline-start) so it mirrors with zero overrides. THE MENU ROW mirrors for free because it is grid auto/1fr/auto with logical gaps: name on the right, leader dots through the middle, price on the left — verify the leader's background-position still reaches both edges.
- NO ITALICS EXIST. The accent word is carried by colour plus the drawn underline, this world's native emphasis anyway, so nothing is lost.
- The HAND face must be an Arabic hand — Aref Ruqaa / Lemonada / Rakkas territory. If none is credible, set margin notes in the body face at weight 500 in crust, rotated -2deg, and KEEP the drawn arrow. Never set Arabic in a Latin handwriting face.
- Arabic display takes +6 percent size, +.06 line-height and letter-spacing:0 — NEVER negative tracking on Arabic; the .88 crop becomes .98 so descenders and diacritics survive.
- Prices and phone numbers stay LTR: wrap in bdi or set unicode-bidi:isolate, keep the U+202F separator, keep the currency mark after the numeral.
- Mirror the wave masks with transform:scaleX(-1) so an Arabic page's crest rhythm is not a carbon copy, mirror doodle rotations (-7deg becomes +7deg), and reverse the ticker so it reads with the language.

## Global rules this world overrides (state them, then do them)
1. gsap.defaults({ease:"power2.out", duration:.75}) replaces power3.out/1.1, and the reveal band is .6-.9s not .9-1.4s. 2. Masked line-rise stagger is .07-.10 and the rise is yPercent 108. 3. back.out(1.6) is permitted, under strict caps (small objects, 14px, .5s). 4. Soft border-radius is NATIVE here in a family of five values; the ban on uniform card grids still holds in full. 5. Real 1.5-2.4px borders are legal and encouraged — they are ink lines. 6. A ticker is REQUIRED once, at 28s. 7. Centred text is permitted in exactly three places: trust-strip cells, the du-jour board's head, the closing wordmark. 8. Gradients are rationed to the five named jobs. 9. Lenis is permitted with its wiring contract; native scroll is the default.

## Fournil ban list (in addition to the global one)
Pure white grounds or pure white text · neutral or cool grays · hairline or sub-400 display type (this world's display is FAT) · a three-card grid of "Petit-déjeuner / Déjeuner / Dîner" with icons on top · icon sets of any kind (Feather, Heroicons, Font Awesome, Material) and perfectly geometric badges · emoji anywhere, especially as food icons · a green WhatsApp blob · prices set inside body paragraphs instead of menu rows or price blocks · a menu row with a background, a radius or a shadow · a hero that is a wide shot of empty tables or a smiling stock team · white-background packshots · symmetric sine-wave dividers, CSS-triangle diagonals and blob dividers (the wave is HAND-CUT and asymmetric or it does not exist) · more than one handwriting face · more than five margin notes · more than eight ember appearances · steam over something cold · countdown timers and fake urgency · a full-width solid rectangle button · box-shadows on buttons, chips in flow, nav or menu rows · bouncing chevron scroll cues · per-character text splitting · more than one ambient loop · canvas · any hidden state authored in CSS · a page where the menu is a small block near the footer.

## Intensity
This world fails by being merely pleasant. Warm colours and a rounded font buy a nice-looking takeaway template in twenty minutes — exactly the thing this world exists to beat. The difference lives in the parts a hurried build skips: leader dots running to every price, a wave genuinely hand-cut and different at every seam, six drawn glyphs with varied stroke weights that draw themselves in, five notes in a real hand pointing at real facts, a menu chapter designed with as much care as the hero, and a pinned rise that turns "we bake fresh daily" into something you watch happen. At 60 percent this is a beige page with a nice font. At 100 percent — flour dust over warm paper, a fat crust-coloured headline cropped tight with a drawn line under one word, a chalkboard leaning on a photograph, a conveyor of product names running past, and a menu you could actually order from — it looks like a shop that has fed the same street for twenty years and finally got a page worth its bread. Push INTO the warmth and INTO the specificity. Every number above is load-bearing.`,
	energy: "medium",
	family: "boulange",
	id: "fournil",
	industries: [
		"bakery",
		"patisserie",
		"cafe",
		"coffee",
		"restaurant",
		"street-food",
		"food",
		"delivery",
		"traiteur",
		"pizzeria",
		"juice",
		"ice-cream",
		"grocery",
		"events",
	],
	kind: "website",
	mood: ["warm", "handmade", "appetizing", "generous", "playful"],
	name: "Fournil",
	preview: {
		ground: "#F6EFE1",
		ink: "#2E2013",
		accent: "#C1743A",
		fontFamily: "Fraunces",
		sampleWord: "Le fournil",
	},
	priceFeel: "accessible",
	tagline:
		"Flour-dusted warm paper, a fat rounded serif you almost want to bite, hand-drawn wheat and steam curling across every seam, and your menu typeset like a real board with dotted lines running to each DZD price — the page smells like the shop at six in the morning.",
};
