import type { DesignWorld } from "./types";

/**
 * HÉRITAGE — story-first artisan lineage, sold on a sewn page.
 * A COD world that refuses to show the product first: scene one is a manifesto
 * in huge sub-400 serif on kraft-dark, and the reveal is earned. Its ruled
 * system is dashed (thread), its traveling motif is a stitch that sews every
 * scene boundary, and its money components are a workshop docket and a swing
 * tag. The doc is appended VERBATIM to the builder system prompt.
 */
export const heritage: DesignWorld = {
	avoidFor: [
		"tech",
		"gaming",
		"gadgets",
		"crypto",
		"saas",
		"nightclub",
		"hard-discount",
	],
	doc: `# DESIGN WORLD: HÉRITAGE — the sewn record

## Philosophy
This page is a MAKER'S RECORD that takes orders at the end. Not a shop, not a landing page — a record: who made this, in which town, with which hands, over how many generations, and what it costs to do it honestly. Think a museum-of-popular-arts didactic wall, a leather house's private catalogue, and a field notebook from an ethnographer who stayed a season.

FIRST LAW — THE PAGE OPENS COLD. Scene one shows NO product, NO price, NO button, NO photograph of the thing being sold. It is a manifesto — three to seven words of huge thin serif on a kraft-dark ground — filling the first screen. The product appears in scene TWO as a REVEAL the manifesto has earned. Every other world in this library opens on the object; this one opens on the reason. If your draft shows the product above the fold, you have built a generic page with brown colours, not Héritage.

SECOND LAW — THE PAGE IS SEWN. The ruled system is not solid hairlines but DASHED 1px thread, everywhere, and a thread line physically crosses each scene boundary as an inline SVG path, so the page reads as panels stitched together rather than blocks stacked. That thread is the traveling motif every build owes; here it is literal.

THIRD LAW — DELIBERATE TIME. Nothing snaps. Reveals run 1.0-1.6s, plate settles 1.9s, and the showpiece is a pinned craft journey scrubbed slowly enough that a visitor feels the workshop's pace in their scroll wheel. Speed is the enemy of this world's claim.

## The vibe
Made by a family, priced by a person who can defend the price. Warm, dark, patient, slightly severe. The merchant does not sell — they show, and they name things. Copy rules, non-negotiable, they carry 45 percent of this design:
- THE MANIFESTO FORMULA, exactly two sentences, each ending in a full stop, the second shorter than the first: [a COUNT of lineage]. [ONE thing that never changed]. "Trois générations. Un seul geste." / "Quarante ans de mains. Une seule couture." / "Depuis 1963, la même odeur d'atelier. Le même point." Never a verb-led slogan, never a benefit, never a question.
- EVERY headline elsewhere is two clauses with a turn, and the turn clause is carried by the LEATHER accent colour plus a thread underline — NEVER by italic. This world has no italic anywhere (see the type section): it makes the French and Arabic pages structurally identical.
- VERBS OF THE HAND ONLY in process copy: couper, coudre, poncer, cirer, teindre, tendre, nouer, plier. Never "créer", never "concevoir", never "réaliser".
- EVERY number is given its unit and its reason: not "48h" but "48 heures de séchage, parce que le cuir boit lentement."
- Validation errors are full sentences from the workshop: "Il nous faut votre nom — c'est celui qu'on écrira sur l'étiquette." / "Un numéro joignable, pour vous prévenir avant de partir."
- Banned words on the page: solutions, seamless, elevate, experience, transform, revolutionary, authentique (as a self-applied adjective), unique, exceptionnel, and the phrase "fait main" used more than ONCE (once it is a fact, twice it is marketing).
- Write it in the brief's language. In Arabic the same rules hold, set in a naskh at 400 (the Amiri / Noto Naskh Arabic / Aref Ruqaa territory): the "thin" impression comes from SIZE and from parchment at .86 alpha, never from weight. Full RTL contract in Layout physics.

## Visual signatures (what makes it instantly recognizable)
- A kraft ground — real cardboard tone, fibrous, never bone-white, never a neutral gray — alternating with a kraft-DARK near-black brown. The page opens dark, turns to kraft at the reveal, and inverts three or four more times.
- STITCHED HAIRLINES: every rule is a 1px dashed line, dash 7px, gap 6px, built from a repeating-linear-gradient (see Layout physics) so the geometry is exact rather than UA-decided. A solid 1px rule appears nowhere.
- THE THREAD: an inline SVG path crossing every scene boundary, drawn progressively on scroll, with a 5px needle dot travelling along it. Once per page two threads CROSS into an X — the signature seam.
- Captioned plates: every image carries a Fig. number and a material caption ("Fig. 01 — Tannage végétal · cuir pleine fleur").
- A PROVENANCE MAP drawn as inline SVG: a simplified regional outline, one marked origin point, a breathing ring, a coordinate line in mono micro-caps.
- A numbered craft journey — 01 découpe · 02 couture · 03 finition — as the page's ONE pinned, slowly scrubbed showpiece.
- A SWING TAG: the price hangs from the product plate's corner on a drawn thread, rotated -4deg, like the kraft tag tied to a finished piece.
- The page closes on the wordmark STITCHED: SVG text, no fill, dashed leather stroke, drawn by the scroll.
- No weight above 500 exists anywhere. Nothing is bold. Emphasis is colour, size and thread.

## Color physics (route the brief's palette through the fixed tokens — the physics is law)
FIXED TOKEN MAP — KRAFT→--background · INK→--foreground · LEATHER→--primary · KRAFT→--primary-foreground · KRAFT-DEEP→--secondary · DARK→--accent · ink at 56%→--muted · stitched ink at 30%→--border · 2px→--radius · DISPLAY→--font-heading · BODY→--font-body. These are the only CSS color/type/radius variables: every pole below is a prose role, literal register hexes belong only in these :root values, and every sibling, thread or alpha step is a color-mix(in srgb, var(--foreground) N%, transparent), substituting the mapped fixed token for that pole, or a color-mix between two mapped fixed-token references. Every unmapped role below MUST reuse the nearest mapped token or such a mix; it never gets another custom property or literal. Non-color mechanics may keep their own custom properties. Any rgba(POLE, a) notation below is design shorthand for that color-mix, never emitted CSS.
Build nine tonal roles from three poles the brief supplies: KRAFT, LEATHER, THREAD. Route them through the fixed tokens and never introduce a tenth hue.
- DARK: the palette's dark pole, a smoked kraft brown-black where R is greater than G is greater than B (the #1E1912 relationship). The cold open, the inverted chapters, the sticky order bar and the footer live here. Never #111, never #1a1a1a. DARK-SOFT is one step up (#2A231A relationship) for panels inside dark chapters.
- KRAFT: the light pole and the daylight ground — a genuine cardboard tone in the #DCCBB0 register, warm and slightly desaturated. Never #fff, never #faf9f7; if the brief's light pole is paler, warm it toward kraft, never toward white. KRAFT-DEEP is 3-5 RGB points darker (#D1BE9F relationship), used only for scene alternation and the breath scene.
- INK: a warm near-black for type on kraft (the #241E17 relationship). PARCHMENT: a dedicated ivory (#EDE1CB register) for ALL text on dark grounds — pure white appears nowhere, not once.
- LEATHER: the tanned-hide accent (#8F5C2C / #A97236 register), plus LEATHER-LIGHT one step brighter (#C08A4A) for accent text on dark grounds.
- ALPHA STEPS ONLY — no independent gray hex exists: body rgba(ink,.76), captions and micro-caps rgba(ink,.56), placeholders rgba(ink,.34), stitched rules rgba(ink,.30). On dark: rgba(parchment,.78) / .54 / .32.
- ERROR is not another hue: validation uses a contrast-safe color-mix between var(--primary) and var(--foreground), nowhere else.

THE DASH ALPHA OVERRIDE — this world overrides the global hairline band of .10-.16: a dashed rule carries half the ink of a solid one, so at .14 it disappears. Stitched rules live at .26-.32 and read as the same visual weight. Do not darken them further, and never make them solid.

THREAD TAKES THE COLOUR OF ITS GROUND — the world's most important colour rule. On dark grounds the thread is PARCHMENT at .55; on kraft it is LEATHER at .48. Never a third hue, never white or black. It is also how the eye reads an inversion as intentional: the seam changes colour mid-crossing, exactly at the boundary.

The leather accent's twelve jobs — use at least nine: the turn clause in every headline · Fig. numbers · the journey numerals · the map origin dot and ring · the thread on kraft grounds · ::selection · the focus ring · the swing-tag knot · the dashed strike on a was-price · the stitch-cross check mark · the burnished edge band (the one full-strength leather fill) · the stitched closing wordmark.

## Typography system
THREE families, three jobs, zero overlap. Load only the weights used.
- SERIF DISPLAY (200 or 300, and 400 — nothing higher, ever): the manifesto, every headline, the price numerals, the breath line, the colophon's lead. Territory: a text-figure serif with a REAL optical light — the Newsreader / Cormorant Garamond / Lora / Marcellus / EB Garamond register (never Fraunces, which the global font ban excludes as a display face). The requirement is a genuine sub-400 weight and a large size range, not a 400 pretending to be thin. If the brief's serif has no sub-400 weight, use 400 and gain the thinness with SIZE and with ink at .88 alpha.
- BODY SANS (400/500 only): paragraphs, labels, form inputs, buttons' fallback. An unassuming humanist sans in the Archivo / Public Sans / Karla / Work Sans territory. Never Inter, Roboto or Open Sans.
- MONO (400/500): Fig. numbers, coordinates, micro-caps, journey numerals, the docket number, dimensions, the currency mark, all captions. A technical mono in the JetBrains Mono / IBM Plex Mono / Space Mono territory. The mono is what makes the page read as a RECORD rather than a brochure — it is present on every screen.

Scale (all clamp, all measured):
- Manifesto h1: clamp(3.4rem,10.5vw,9.5rem) / line-height .94 / letter-spacing -.018em / serif weight 300 (or 200). Two authored lines, one sentence each. Max-width 15ch.
- Section h2: clamp(2.05rem,4.6vw,3.9rem) / 1.07 / -.012em / weight 300 / max-width 17em.
- h3: clamp(1.28rem,2.2vw,1.75rem) / 1.22 / -.004em / weight 400.
- Journey numeral: clamp(3.6rem,8vw,7.4rem) / .9 / weight 300, in the SERIF, leather.
- Price: clamp(2.6rem,5.2vw,4.4rem) / .95 / -.015em / weight 300 / font-variant-numeric tabular-nums.
- Body: 1.0625rem / 1.68 / 0. Kraft is a textured ground; it needs the extra leading.
- Mono micro-caps: .72-.8rem, uppercase, letter-spacing .18-.26em, weight 400.
- Fig. caption: .74rem mono, .1em tracking, ink at .56.
- Closing stitched wordmark: clamp(3.4rem,15vw,13rem), drawn as SVG stroke, letter-spacing +.05em.

TRACKING IS A FUNCTION OF SIZE: -.018em above 110px, -.012em at 40-80px, -.004em at 28px, 0 at body, +.18em to +.26em at 11-13px mono uppercase. Display-to-micro ratio must exceed 9:1.

NO ITALIC EXISTS IN THIS WORLD — this overrides the global "one italic word inside a big headline" device. Emphasis is (a) the leather colour on the turn clause, and (b) a THREAD UNDERLINE: background-image repeating-linear-gradient(to right, leather 0 6px, transparent 6px 11px), background-size 100% 1px, background-position 0 100%, background-repeat repeat-x, padding-bottom .12em. Pick both, use them together, and never a third emphasis device.

NEVER LET A DISPLAY HEADLINE AUTO-WRAP. Break every h1 and h2 into explicit block-level line spans so the rag is authored — and reuse those spans as the mask-reveal targets.

PROMOTE NUMERALS THE OTHER WAY. This world SHRINKS numbers and mono-sets them inside sans sentences: a spec row sets "Longueur — 42 cm" with the value in mono at .86rem / .06em inside a .98rem line. Only three numerals on the page are large: the price, the journey steps, and the founding year if the brief gives one.

## Page chassis
- NOTHING SITS ABOVE THE MANIFESTO. No announce bar, no promo strip, no cookie band, no breadcrumb. The first painted pixel is DARK and the first word is the manifesto's. Anything else destroys the cold open.
- THE LATE NAV — the chassis is a designed absence for the first screen. Header position fixed, top 0, z-index 90, height 4.4rem. ITS HIDDEN STATE IS NEVER AUTHORED IN CSS: the markup ships the header visible, and only inside the animate branch does JS add a .is-stowed class that sets translateY(-100%) (the transition itself lives in CSS on the base class); a ScrollTrigger on the manifesto (start "bottom 80%") then removes it, returning the header to translateY(0) over .8s cubic-bezier(.24,.62,.2,1). If the CDN fails or motion is reduced, the class is never added and the nav is simply present from the first pixel — a header that only exists when GSAP loads is a broken page, not a designed absence. It carries the maker's mark on the start side and ONE quiet mono micro-caps link on the end side (the brief's word for "Commander") with a thread underline that wipes in on hover. No link list, no burger, no pill. Ground rgba(dark,.92) with backdrop-filter blur(10px), bottom edge a stitched rule in thread-on-dark. It stays dark-plated for the whole page whatever scene is beneath — the maker's mark is a stamp, not a chameleon.
- KRAFT TEXTURE IS TWO FIXED LAYERS, both pointer-events none: (1) GRAIN — inset -40%, z-index 80, opacity .12, mix-blend-mode multiply, an inline SVG data URI of feTurbulence type fractalNoise baseFrequency .92 numOctaves 3 stitchTiles stitch, desaturated via feColorMatrix saturate 0. (2) FIBRE — inset 0, z-index 79, opacity .5, repeating-linear-gradient(74deg, color-mix(in srgb, var(--foreground) 3.5%, transparent) 0 1px, transparent 1px 5px). Grain alone reads digital; grain plus a directional fibre reads as card stock.
- Global base: html and body overflow-x clip; color-scheme dark; a theme-color meta matching DARK (the page opens dark and the browser chrome must agree); text-rendering optimizeLegibility. ::selection leather on parchment. :focus-visible a 2px leather outline at offset 3px, radius min(var(--radius), 2px). A skip link sliding from top -4rem to 1rem over .3s.
- THE COORDINATED NUMBERS, all derived from the 4.4rem nav: scroll-margin-top 5.6rem on anchored sections, sticky offset top 6rem, manifesto min-height 100svh (svh, not vh — the cold open must not be cut by mobile chrome), reveal scene min-height 92svh.
- THE PAGE SCORE (the default arc; reorder only for a stated reason): I Manifeste (dark) · II Révélation (kraft, the product earned) · III La Matière — plates and material honesty (kraft-deep) · IV La Provenance — the map (dark) · V Le Chemin — the pinned journey (kraft) · VI Le Silence — the breath (kraft-deep) · VII Le Juste Prix (dark) · VIII La Parole — reviews or the maker's word (kraft) · IX Le Bon de Commande — the order docket (kraft-deep) · X Questions (kraft) · XI Colophon and footer (dark). Scene numerals in Roman, mono, .72rem, .26em tracking, in the outer gutter — that is the page's running head.

## Hero forms — the DIPTYCH (scene one is fixed law; pick one form for scene two)
SCENE ONE — LE MANIFESTE, mandatory on every Héritage build:
Full-bleed DARK, min-height 100svh, the copy block sitting at 58-64 percent of the height — not centred; the type hangs low with the emptiness above it. Contents, in order, and nothing else: the two manifesto sentences as authored line spans; a stitched rule 5.5rem by 1px under them with margin-block 2.2rem; ONE mono micro-caps line at .74rem / .24em in parchment-at-.56 giving place and year from the brief ("Atelier fondé à Tlemcen · 1963" — facts only, never invented); and at the bottom edge the DESCENDING NEEDLE cue — a 1px dashed vertical thread 4.5rem tall with a 5px leather dot travelling it, offset-distance 0 to 100 percent over 2.6s ease-in-out infinite, opacity fading at both ends. No button, no product, no photograph — with ONE exception: a hands-at-work macro as a GHOST, position absolute inset 0, object-fit cover, opacity .14, mix-blend-mode luminosity, scrim linear-gradient(to bottom, rgba(dark,.55), rgba(dark,.9)). If used, it carries the page's one scrubbed parallax (yPercent -6 to 6).
Three permitted typesettings: (a) STACKED — both sentences flush inline-start, the second indented 2.5em; (b) HUNG — the first flush start, the second flush END of a max-width 34rem block, so the pair reads as a diagonal; (c) COLOPHON-FLANKED — flush start with a 9rem outer-gutter column of three mono lines (matière, lieu, année) separated by stitched rules, above 1200px only.

SCENE TWO — the reveal. Pick ONE:
1. LA RÉVÉLATION (default). Welds to the manifesto at padding-top 0 and INVERTS to kraft at the seam. The product plate is centred at width min(100%,32rem), aspect-ratio 4/5, radius min(var(--radius), 2px), unmasked by clip-path inset(0 0 100% 0) to inset(0) over 1.35s cubic-bezier(.2,.65,.2,1) as the seam thread finishes drawing — the claim being that the thread stitched the object into being. No eyebrow above the headline (the global eyebrow-first pattern is banned here): the plate carries its Fig. caption row beneath, the h2 sits BELOW the plate at max-width 20ch, the swing tag hangs from the plate's top-end corner, one mono reassurance line follows, then one plaque CTA.
2. L'ÉTABLI (the workbench — when the brief has three or more images). Grid 1.08fr .92fr, gap clamp(2.5rem,6vw,5.5rem), align-items start. Start column: h2, a 32em lede, the price block with its honesty ledger, the plaque CTA, a 4-item stitched spec list. End column is a PLATE CLUSTER, never one photo: a lead plate at 4/5; a hands-macro plate at 1/1 offset margin-top -3.5rem, margin-inline-start -4rem, z-index 2; a material-macro plate at 5/4 below at 62 percent width. Each has its own Fig. caption, and a 1px dashed leather SVG line runs from the lead plate's corner to the macro plate's corner, drawn on reveal.
3. LE PORTANT (the rack — traditional wear, carpets, anything that hangs). Single column, the object plate at aspect-ratio 3/4, width min(100%,38rem), justify-self centre, with a drawn thread rising 3.5rem from its top edge to a leather knot dot pinned to the scene's top rule: the object hangs from the seam above it. The h2 and price sit in the inline-start outer margin on desktop, below the plate on mobile; the swing tag hangs from the lower-end corner.

Every reveal form ENDS IN A STITCHED RAIL, never in whitespace: a full-bleed band with a stitched top rule and four mono micro-labels at .74rem / .2em (matière · façon · délai · livraison — real facts from the brief) separated by leather middots, padding-block 1.15rem. Below 600px, a 2x2 grid at .68rem.

## Section seams (Héritage's own vocabulary — every boundary uses one, never the same twice in a row, at least five per page)
- LA COUTURE (the running seam, the workhorse). A full-bleed 7rem-tall band containing one inline SVG (preserveAspectRatio none, viewBox 0 0 1200 84) whose path crosses the boundary as a shallow S: M0 62 C 260 62, 300 20, 600 20 S 940 62, 1200 62. Stroke = the thread token, stroke-width 1.25, stroke-dasharray "7 6", stroke-linecap butt, fill none. It is DRAWN on scroll (see Motion) and carries a 5px leather needle dot on offset-path. The band's background is a hard 50/50 split of the two adjoining grounds, so the thread visibly sews one colour to the other.
  THE THREAD IS ALWAYS A CURVE: every seam path is built from cubic curves only, and NO 90-degree corner, no orthogonal segment and no via or node ever appears on it — a routed line is a circuit, not a stitch, and the difference is the whole claim of this world. The single exception is the point croisé, whose two paths are straight because a cross-stitch is straight.
  AND EVERY STITCHED RULE ON THE PAGE SHARES THE THREAD'S PHASE: dash 7, gap 6, and background-position 0 0 measured from the container's inline-start edge, so rules in different sections line up dash-for-dash as the eye travels down. A stitched rule that does not share the phase reads as a dotted border, and dotted borders are exactly what this world is not.
- LE POINT CROISÉ (the signature seam — EXACTLY ONCE per page, at the manifesto-to-reveal boundary). Two threads enter from opposite margins and cross at 38 percent of the width, never the centre: paths M0 20 L1200 64 and M0 64 L1200 20, a 9px leather knot dot at the intersection, and 1.4rem to its trailing side the scene numeral "II" in mono at .72rem / .26em. Both draw over the seam's scrub range; the knot pops scale(0) to scale(1) at 92 percent progress. This is where the page turns from story to object — the quietest, most deliberate 7rem on the page.
- LE RETOURNEMENT (chromatic inversion). Kraft to dark or back, at a HARD cut, no gradient. The type system flips with it: ink to parchment, leather to leather-light, thread from leather to parchment. Four to five inversions across the score.
- LE RABAT (the weld). The next scene starts at padding-top 0 while the previous scene's last plate crosses the boundary by margin-bottom -4.5rem at z-index 2, so both read as one folded sheet. Once per page, never adjacent to the point croisé.
- LA PLANCHE (the full-bleed plate interlude). One edge-to-edge photograph at height min(88vh,52rem), conscious object-position, scrim linear-gradient(to top, rgba(dark,.72), rgba(dark,.06) 58%), and in the trailing bottom corner the Fig. number plus one caption line in mono parchment-at-.56. No heading, no CTA.
- LA TRANCHE (the burnished edge). A full-bleed 3px band of LEATHER at full strength — the only full-strength leather fill on the page — optionally doubled with 10px of ground between. It announces the price scene and the docket scene, and nothing else. At most twice.
- LE REPÈRE (the coordinates strip). A 2.8rem full-bleed band on kraft-deep, stitched rule top and bottom, one centred mono line at .72rem / .24em: origin · matière · année, separated by leather middots. It does NOT move — marquees and tickers are banned here.
- LE SILENCE (the breath). No heading, no eyebrow, no CTA: one serif line at clamp(1.5rem,3vw,2.4rem) weight 300, max-width 24ch, on kraft-deep, block padding clamp(7rem,16vh,12rem), a stitched rule 3.4rem wide 2.4rem below. One sentence in the maker's voice from the brief. A generic builder puts three feature cards here. Do not.

A boundary announced by whitespace alone — or by a solid rule — is a bug in this world, not a style choice.

## Layout physics
- ONE inline padding token: clamp(1.25rem,4.5vw,4.5rem). Container max-width 88rem. Section block padding clamp(5.5rem,12vh,9rem).
- THE STITCH UTILITY (memorize this — every rule on the page uses it). A horizontal stitched rule is NOT border-top: 1px dashed. It is: background-image repeating-linear-gradient(to right, RULECOLOR 0 7px, transparent 7px 13px); background-size 100% 1px; background-repeat repeat-x; background-position 0 0; height 1px. Vertical rules use (to bottom, ...) with background-size 1px 100%. A fully stitched BOX (buttons, inputs, radio cards, the docket) uses four such gradients in one declaration: background-image four repeating-linear-gradients; background-size 100% 1px, 100% 1px, 1px 100%, 1px 100%; background-position 0 0, 0 100%, 0 0, 100% 0; background-repeat no-repeat. Dash 7, gap 6, always. This is why the page looks sewn instead of dotted: the dash geometry never varies across elements or browsers.
- MEASURE IS CAPPED IN EM: body 34em, lede 32em, manifesto 15ch, breath line 24ch, caption 40em, docket sub-copy 30em.
- NO GRID IS 50/50. Hero variants 1.08fr/.92fr; story .9fr/1.1fr (the MEDIA column narrower, because it is sticky and the text is three long stanzas); map scene 1.2fr/.8fr; docket scene .84fr/1.16fr (the form 38 percent wider than its companion plate); questions .78fr/1.22fr. Column gaps clamp(2.5rem,6vw,5.5rem).
- THE OUTER GUTTER IS ALIVE. Above 1200px reserve a 9-11rem inline-start outer column for the page's furniture: scene Roman numerals, Fig. numbers, margin notes, coordinates. Margin notes are position absolute, inline-start -12rem, width 9.5rem, mono .72rem, ink-at-.5, stitched border-inline-start, padding-inline-start .9rem. Below 1200px they fall inline under their paragraph at .7rem with a stitched rule above. Empty margins throw away half this world.
- IF AN IMAGE ROLE FAILS or image generation is unavailable, the plate still ships and the scene keeps its shape: hold the plate's ratio and its Fig. caption row, and fill the picture area with a LABELLED IMAGE SLOT — kraft-deep (or dark-soft on dark scenes) with one mono .74rem / .2em line naming the shot ("PHOTO · LES MAINS SUR LE CHEVALET"). Never draw a fake object, a scissors-on-a-table cliché or an illustrated hand to plug the hole — the global ban on invented imagery holds, and the manifesto scene needs no photograph at all, so a thin image budget costs this world less than any other.
- PLATES, NOT CARDS. Every image is a PLATE: radius min(var(--radius), 2px), overflow hidden, NO shadow, NO border, followed by a caption row — space-between flex, Fig. number in mono leather on the start side, material or dimension in mono ink-at-.56 on the end side, padding-top .7rem, stitched rule ABOVE the row. Ratios alternate 4/5, 1/1, 5/4, 3/4 — three adjacent plates sharing a ratio is a failure.
- RADIUS LAW: buttons consume var(--radius) directly (:root sets --radius: 2px); plates, inputs and the docket use min(var(--radius), 2px); rules, bands and slabs cap it at 0; true map, needle and status dots use 50%. These var(--radius)-derived declarations are the sanctioned mechanism; adding another corner treatment means the page has drifted.
- SHADOWS EXIST IN EXACTLY TWO PLACES (overrides the global permissiveness): under the SWING TAG (0 10px 22px -14px color-mix(in srgb, var(--foreground) 55%, transparent)) and under the sticky mobile order bar (0 -12px 30px -20px color-mix(in srgb, var(--foreground) 60%, transparent)). Plates none, buttons none; cards do not exist.
- LEDGERS, NOT FEATURE GRIDS, for specs, materials, care and the price breakdown: grid-template-columns auto 1fr, gap 1.2rem, padding-block clamp(.9rem,2vw,1.25rem), separated by stitched rules, term in mono uppercase .74rem / .2em ink-at-.56, value in the sans 400 aligned to the end. Below 600px the value falls under the term.
- Exactly one STICKY ANCHOR: a media column at top 6rem in the material scene, so one plate serves three stanzas of scrolling. Any parallaxed image is top -10 percent, height 120 percent, inside an overflow hidden parent.
- RESPONSIVE COLLAPSE below 1000px: every two-column grid becomes 1fr, sticky becomes static, the plate cluster restacks with the macro plate at 78 percent width and no negative offsets, the pinned journey becomes the vertical stitched list, the gutter furniture folds inline.
- ARABIC / RTL ADAPTATION (a first-class layout, not a mirror hack): dir="rtl" and lang="ar" on the html element; every offset written with logical properties (padding-inline, margin-inline-start, border-inline-start, inset-inline) so the outer gutter, the ledgers and the docket flip for free. The SEAM SVGs mirror by transform: scaleX(-1) on their wrapper only — the needle then travels start-to-end correctly. Three things NEVER mirror: the provenance map (geography is not reversible), the Fig. numbering direction, and the journey's step order, which stays 01 to 03 running from the start edge. Numerals may be Western or Arabic-Indic per the brief, but only ONE system on the page, and tabular-nums stays on prices and totals. Type sizes go up 8-12 percent, body line-height to 1.8, and micro-caps tracking DROPS to .06-.1em because Arabic letterforms connect — wide tracking breaks words apart. The manifesto keeps its two-sentence shape.

## Motion identity (GSAP 3 + ScrollTrigger from a CDN; Lenis optional at lerp .085 — if used, expose it as window.__lenis)
THE SAFETY CONTRACT COMES FIRST AND IS NON-NEGOTIABLE. Compute reduced = matchMedia("(prefers-reduced-motion: reduce)").matches, hasGsap = typeof window.gsap !== "undefined", animate = hasGsap && !reduced. EVERY hidden initial state is set with gsap.set() inside the animate branch. Every SVG mask path is authored in markup with stroke-dashoffset 0 (fully drawn) and set to 100 by JS before animating. THE SAME RULE GOVERNS THE TWO STOWED CHASSIS ELEMENTS: the late nav and the sticky mobile order bar ship VISIBLE in markup and are stowed by a JS-added class inside the animate branch, never by a CSS translateY authored on the base class — so a failed CDN gives a page with a permanent header and a permanent order bar rather than a page missing both. If the CDN fails, the page is a complete, fully sewn, fully legible record with its price, its docket and its order bar all reachable. Add a prefers-reduced-motion block that stops the needle dot loop and the map ring breathing.

gsap.defaults({ ease: "power2.out", duration: 1.2 }) — this world overrides the global power3.out / 1.1s default. power3 has a sharper deceleration than this world's hands.

TIMING BANDS — every duration belongs to one: .3-.45s interaction feedback · .6-.8s component state · 1.0-1.6s narrative reveals (the world's home band) · 1.9s plate settle · 2.6s the needle loop · 4.5s the map ring breath · scrub for the seams and the journey. Eases: power2.out for entrances and settles, cubic-bezier(.2,.65,.2,1) as the shared CSS token used by roughly eighteen transitions, power2.inOut for clip wipes, sine.inOut for the two ambient loops, back.out(1.4) for the two pops (the knot dot, the success stamp), none for everything scrubbed.

TRAVEL DISTANCES ARE SMALL AND SLOW: y offsets of 12 / 22 / 38 only. Scales of .94 / 1.1 / 1.12. Hover lift translateY(-1px) — one pixel, because heavy things do not jump. Nothing on this page travels 100px.

The mandatory motion set:
1. THE MANIFESTO ENTRANCE — the page's most important 2.4 seconds; a curtain, never a bounce. Wrap each line in an overflow hidden mask with padding-bottom .06em and margin-bottom -.06em so descenders survive. Set lines to yPercent 112, the stitched rule to scaleX 0 with transform-origin 0 50 percent, the mono place-line and needle cue to autoAlpha 0 y 12, the ghost image to autoAlpha 0 scale 1.06. Then tl.to(ghost,{autoAlpha:.14,scale:1,duration:2.2},0).to(lines,{yPercent:0,duration:1.35,stagger:.16},.25).to(rule,{scaleX:1,duration:1.1},1.25).to(furniture,{autoAlpha:1,y:0,duration:.9,stagger:.12},1.5). The second sentence lands a third of a second after the first — that pause is the voice of the world.
2. THE SEAM DRAW (the traveling motif, on every couture and the point croisé). The visible path is dashed, so a plain stroke-dashoffset tween slides the dashes instead of revealing them. Use the TWO-PATH MASK: inside the SVG, a mask containing a copy of the same path with stroke white, stroke-width 6, pathLength 100, stroke-dasharray 100, stroke-dashoffset 100; apply that mask to the visible dashed path. Then gsap.to(maskPath,{strokeDashoffset:0, ease:"none", scrollTrigger:{trigger:seam, start:"top 92%", end:"bottom 55%", scrub:.5}}). The needle dot is a 5px circle with CSS offset-path: path("...the same d..."), offset-rotate 0deg, offset-distance tweened 0 to 100 percent on the same scrub. If offset-path is unsupported the dot is simply absent — it is decorative and aria-hidden.
3. THE PLATE REVEAL — clipPath inset(0 100% 0 0) to inset(0) over 1.25s power2.inOut while the inner image counter-scales 1.1 to 1 over 1.9s power2.out at the same position, then clearProps both. The caption row follows at autoAlpha 0 y 8 over .7s at +0.35s. Start "top 86%", once true. Alternate the wipe direction per plate (inline-start, then bottom via inset(100% 0 0 0)) so the page never metronomes.
4. THE SHOWPIECE — LE CHEMIN DE L'ATELIER, the pinned craft journey, desktop only (min-width 900px). ScrollTrigger {trigger: section, start:"top top", end:"+=2600", pin:true, anticipatePin:1, scrub:.6}. Inside a 100svh grid: the start column holds the step numeral (serif 300, leather), its title and a 26em line of process copy; the end column holds the step plate. A horizontal thread crosses the pinned viewport at 62 percent height, drawn by the same two-path mask across the FULL scrub, with N stitched ticks along it that fill leather as the needle passes. Each step runs autoAlpha 0 to 1 and y 22 to 0 over .18 of the timeline, holds .14, then leaves to autoAlpha 0 y -14 while its plate wipes. Three steps minimum (01 découpe · 02 couture · 03 finition, from the brief's real process), four maximum. MANDATORY MOBILE AND REDUCED-MOTION FALLBACK: no pin — the steps become a vertical stitched list with the thread running down the inline-start gutter, each step revealed at "top 85%" once, the gutter thread drawn on a 40vh scrub per step. Author the fallback; never let it be an accident of the pin failing.
5. TWO AMBIENT LOOPS ONLY: the needle scroll cue (2.6s ease-in-out infinite, CSS) and the map's origin ring (gsap.to(ring,{scale:1.18, opacity:.25, duration:4.5, ease:"sine.inOut", yoyo:true, repeat:-1})). Both are diegetic — a needle passing through, a place still breathing. A floating decorative blob is banned.
6. GENERIC REVEALS — roughly fourteen elements marked with a reveal attribute: gsap.set({autoAlpha:0, y:22}) then to({autoAlpha:1, y:0, duration:1.05, stagger:.1}) at start "top 90%", once true.
7. ONE COUNT-UP, and only one: the lineage numeral (generations, years, or the founding year) via a proxy object over 1.6s power2.out, with a 4000ms setTimeout fallback painting the final value. PRICES DO NOT COUNT UP — this world overrides the global "count-up numerals for stats/prices": a price that spins reads as a slot machine, and this workshop is not gambling with its number.
8. THE STITCHED WORDMARK — the closing monument: SVG text, fill none, stroke leather at .7, stroke-width 1.25, stroke-dasharray "7 6", masked and drawn by the same two-path technique over a scrub from "top 80%" to "bottom bottom".

SCRUB BUDGET: the seam draws (up to six), the pinned journey, and the manifesto ghost parallax. Nothing else scrubs. once:true on everything non-scrubbed — nothing re-animates on scroll-up.

MICRO-INTERACTION KIT (all CSS, all inside the bands):
- THE TRAVELING STITCH on hover: any stitched box or underline shifts its background-position by 6.5px over .4s with the shared ease, so the dashes appear to advance like thread being pulled. This is the world's universal hover. Use it on buttons, links, radio cards and the docket's submit.
- Plaque button: translateY(-1px) plus the traveling stitch, .38s; its mono label letter-spacing goes .16em to .19em over .4s.
- Links: the thread underline wipes in via background-size 0 100% to 100% 100% over .45s.
- Inputs on focus change three things over .32s: the stitch colour to leather, an outer box-shadow 0 0 0 1px leather at .35, and the ground lightening 3 percent.
- Radio cards driven by :has(input:checked): the stitch turns leather, the ground lightens, and the STITCH-CROSS check mark draws — two 1.4px dashed SVG strokes forming an X, scale(.7) to scale(1) over .32s with back.out(1.4).
- Accordions: grid-template-rows 0fr to 1fr over .6s, overflow hidden inner. The icon is not a chevron: it is a 14px vertical thread and a 14px horizontal thread; the vertical one scaleY 1 to 0 over .45s on open.
- Validation entrance: opacity 0 and translateY(-3px) to visible over .32s, with min-height 1.25em reserved so nothing reflows.

## Components
- BUTTONS ARE PLAQUES, NEVER PILLS: rectangular, border-radius: var(--radius), padding 1.05em 1.9em, label in MONO uppercase .78rem / .16em weight 500, line-height 1. PRIMARY: leather fill, parchment text, plus a stitched pseudo-element box at inset 4px in rgba(parchment,.4) — a plaque with a sewn border inside it. SECONDARY: transparent ground, the four-gradient stitched box in the rule colour, label in the ground's ink. TERTIARY: mono micro-caps with a thread underline. Disabled at opacity .42, cursor not-allowed, no stitch travel.
- INPUTS AND SELECTS: ground rgba(kraft,.5) on kraft scenes, rgba(parchment,.06) on dark; the four-gradient stitched box; radius min(var(--radius), 2px); padding 1em 1.05em; 1rem in the sans. Labels ABOVE in mono uppercase .72rem / .2em ink-at-.56, margin-bottom .55rem. Hints .76rem sans at .5. The select's arrow is a drawn 1.4px inline-SVG chevron data URI, never the UA default.
- THE SWING TAG: a small kraft slab (kraft on dark scenes, kraft-deep on kraft scenes), width 8.5rem, padding .85rem .9rem, radius min(var(--radius), 2px), rotate(-4deg), transform-origin top centre, stitched box, a 4px punched hole at the top drawn as a pseudo-element circle of the parent ground, and a 3.2rem SVG thread rising from the hole to a leather knot dot on the plate's corner. It carries the price: serif 300 at 1.9rem tabular-nums with the currency in mono .72rem beneath. Hovering the plate swings it rotate(-4deg) to rotate(-1.5deg) over .7s. Use it exactly once, in the reveal scene.
- MAP: inline SVG, viewBox 0 0 420 520, the region as a SIMPLIFIED outline of 10-24 anchor points (an illustration — never a geodata trace, a screenshot, or a world map), stroke ink-at-.3 or parchment-at-.32 at 1.25, fill the same colour at .04. The origin is a leather circle r 4.5 inside a ring r 15, fill none, stroke leather-at-.5, stroke-dasharray "5 4", breathing on the ambient loop. A 1px dashed leader runs from the dot to a mono label naming the town from the brief; coordinates appear only if the brief states the place — never invent coordinates or addresses. A mono micro-caps heading above, a stitched ledger of three provenance facts below.
- ACCORDION for questions (motion in the micro-kit): stitched-topped list, items stitched-bottomed, the question a full-width flex button in the serif at clamp(1.1rem,1.7vw,1.35rem) weight 400, padding 1.5rem 0, turning leather when open. Single-open, aria-expanded maintained, role region and aria-labelledby on panels.
- CRAFT DETAILS: width and height on every image; fetchpriority high on the LCP plate; loading lazy below the fold; alt text naming the gesture ("les mains du tanneur lissant une peau tendue sur le chevalet"); aria-hidden on the ghost image, threads, needle and stitched wordmark; aria-live polite on validation; an output element for the quantity; a skip link; an inline-SVG data-URI favicon of the knot dot; theme-color DARK.

## Conversion objects (this world SELLS — these are its money components, and they are typeset, not bolted on)
- LE JUSTE PRIX — the price is a SCENE, not a badge, and it lives on a dark ground announced by the TRANCHE. Its heading is mono micro-caps ("Le juste prix" / the brief's language). The number is serif 300 at clamp(2.6rem,5.2vw,4.4rem) with font-variant-numeric tabular-nums and THIN-SPACE thousands using U+202F (3 500, never 3,500 and never 3.500), followed by the currency in MONO at .74rem / .22em, vertical-align .95em, parchment at .6. A was-price, if the brief gives one, sits at 1.15rem with text-decoration line-through, text-decoration-style DASHED, text-decoration-color leather, thickness 1px — the strike is thread too.
- THE HONESTY LEDGER, directly under the price and mandatory: three or four stitched ledger rows that say what the price PAYS FOR, filled ONLY from the brief's facts (matière, temps de façon, finition, garantie, livraison). Term in mono micro-caps, value in the sans. It ends with one sans line at .86rem stating exactly what happens on submit and when payment occurs ("Vous payez à la livraison, en main propre."). This ledger is the world's entire conversion argument: the merchant is not discounting, they are explaining.
- LE BON DE COMMANDE — the order form as a WORKSHOP DOCKET, on a kraft-deep scene at grid .84fr/1.16fr. The docket sits inside one four-gradient stitched box at radius min(var(--radius), 2px), padding clamp(1.6rem,3.5vw,2.6rem), with a header row above a stitched rule: "Bon de commande" in mono micro-caps on the start side, "N° ——" plus today's date in mono .72rem ink-at-.5 on the end side. Fields in this order, each with a mono uppercase label, and the PHONE LEADS — the workshop's docket opens on the number because it is the only channel the merchant actually has, and a half-filled docket carrying a number is still a lead: TÉLÉPHONE (type tel, inputmode="tel", autocomplete tel, a real pattern for the local format, min-height 3rem so the tap target clears 48px, dir="ltr" on the field itself so the digits never reverse on an Arabic page, and a hint naming when you will call — this world uses inputmode="tel" rather than the global inputmode="numeric", because the call-shaped keypad is the right affordance for a number typed from memory) · NOM COMPLET (type text, autocomplete name, required, its label naming that this is the name written on the label) · WILAYA (a styled select carrying the brief's delivery zones, all 58 when the brief says national, matching the inputs exactly, with the drawn chevron; choosing one writes the delivery FEE and DELAY into a stitched two-cell row directly above the total and the submit — never into an FAQ, never below the fold — both values facts from the brief, and where the brief prices no zone the row states its single flat term and invents nothing) · ADRESSE DE LIVRAISON (a 3-row textarea in the same stitched box) · VARIANTE, colour or size or finish (RADIO CARDS with :has(input:checked), the stitch turning leather and the stitch-cross check mark drawing) · QUANTITÉ (a stepper at border-radius var(--radius), never a number input: two 2.8rem square stitched buttons at the same token radius and an output at min-width 2.6rem in the serif at 1.35rem; if the brief caps it, the cap is stated with its reason) · NOTES POUR L'ATELIER (optional, with a hint inviting a real sentence — "Un prénom à graver, une préférence de teinte…" — only where the brief supports that offer).
- VALIDATION IS BLUR-GATED: keep a touched map so an error appears only after a field's first blur, never mid-typing. Errors are full sentences in the workshop voice, in the error mix of var(--primary) and var(--foreground), at .8rem, with min-height reserved.
- THE FOOT OF THE DOCKET: a stitched-topped row, space-between, padding-top 1.5rem — a live TOTAL in the serif at 2rem with tabular-nums under a mono .74rem label, recomputing on every quantity and variant change, beside the primary plaque. Below it, one mono line at .72rem repeating the payment terms.
- SUBMIT HAS AN 800ms PENDING STATE with a human present-tense label ("On note votre commande…"), then the docket CROSS-FADES IN PLACE into a success panel absolutely positioned inside the same box: the panel transitions opacity, transform and visibility over .75s with delays .25s, .25s, 0s; the form leaves over .45s to translateY(-10px) with visibility 0s .45s so focus never lands on a hidden node. The success panel opens on THE STAMP: an inline SVG circle r 46, stroke leather 1.4, stroke-dasharray "7 6", rotated -7deg, with a textPath carrying the workshop name and the word for "commandé" in mono at 8.5px / .26em, plus the order number in mono at 2.2rem in the centre. It arrives with gsap.fromTo({scale:.86, autoAlpha:0},{scale:1, autoAlpha:1, duration:.8, ease:"back.out(1.4)"}), and the docket's stitched frame redraws around it over 1.2s. The copy echoes the buyer's own name, wilaya and choices back to them, and states when they will be called. And at the instant validation clears — as the stamp arrives — the docket is handed to the wandit runtime by dispatching the wandit:lead CustomEvent on document with the buyer's fields flat in detail (name, phone as written, wilaya, commune, plus variante and quantité), while one off-canvas decoy input marked data-wandit-hp sits in the docket, never read by the page's own script.
- PERSIST IT: store the order in localStorage; on return, show the success state INSTANTLY with no animation so a returning buyer is never asked to order twice.
- STICKY MOBILE ORDER BAR (below 860px, mandatory): position fixed, bottom 0, height 4.6rem, ground DARK, a stitched top rule in thread-on-dark, padding-inline the page token, plus the sticky bar's one permitted shadow. Start side: the price in serif 300 at 1.5rem with the mono currency, and above it a .66rem mono micro-caps line ("Paiement à la livraison"). End side: the primary plaque at the small size. It ships visible in markup and is stowed by the same JS-added class as the nav, so it survives a dead CDN; with GSAP alive it is stowed on load, arrives once the reveal scene has passed (ScrollTrigger onEnter translateY(100%) to 0 over .55s) and it HIDES AGAIN while the docket is in view (onEnter of the docket returns it to translateY(100%)), because a bar covering the form it points to is a bug. Add padding-bottom 4.6rem to the body below 860px so the footer clears it.
- WHATSAPP CTA — styled entirely to this world: a SECONDARY plaque (stitched box, no fill) whose glyph is a hand-drawn 1.4px-stroke WhatsApp mark in leather (or parchment on dark), gap .7em, label in mono micro-caps in the brief's language ("Écrire à l'atelier"). The WhatsApp brand green is BANNED here; so is any filled green blob. The href is a wa.me link built from the brief's number with a prefilled message naming the product. It appears twice: once beside the docket's submit as the quiet alternative, once in the colophon.
- TRUST STRIP — four items on a stitched-ruled band, each an inline SVG line icon DRAWN BY YOU in the world's stroke language (stroke-width 1.4, stroke-linecap round, fill none, and the outline dashed "6 5" so the icons look sewn), 26px square, above a mono micro-caps label at .72rem / .2em and one .78rem sans line of detail from the brief: (1) two hands carrying a wrapped parcel — livraison 58 wilayas; (2) an open palm with a coin — paiement à la livraison; (3) a needle threading back through a loop — échange sous X jours; (4) a small stamped seal — garantie de l'atelier. Never emoji, never an icon font, never a downloaded icon set. Four items, grid on desktop, 2x2 below 600px, each separated by vertical stitched rules in the gutters.

## Editorial furniture (REQUIRED — this is Héritage's voice)
- FIG. PLATES: every image gets "Fig. 01 — [what the hand is doing]" in mono leather, with the material or dimension on the trailing side. Number them sequentially across the whole page, never restarting per section.
- SCENE NUMERALS: Roman numerals I through XI in the outer gutter, mono .72rem / .26em ink-at-.45, aligned to each scene's first baseline. The page's running head.
- LE REGISTRE: the provenance ledger under the map — lieu, matière, année, main (who) — as stitched rows, values from the brief only.
- MARGIN NOTES: two or three per page, mono .72rem in the outer gutter, written as the maker's aside ("On laisse reposer une nuit. Le cuir décide."). They invent no business fact; they narrate what the page itself shows.
- LE COLOPHON: the closing block before the footer — a stitched definition list giving matière, façon, atelier, année, and the maker's name, then the maker's word in one serif line at 1.2rem, then the stitched wordmark monument.
- THE GESTURE NUMERALS: 01 / 02 / 03 in the serif, leather, at clamp(3.6rem,8vw,7.4rem) in the journey — the only place large numerals appear besides the price.
- REVIEWS, if the brief has them: no stars, no cards, no carousel. A stitched row per review: the quote in serif 300 at clamp(1.05rem,1.5vw,1.22rem)/1.55, and beneath it a mono attribution at .72rem / .18em giving the first name and the wilaya. Nothing else.
- These invent no business fact — they are TYPESETTING. Fill them from the brief; where the brief is silent, drop the line rather than inventing it.

## Explicit overrides of the global builder rules (each is argued above — this is the roll-call, and every one must be declared in an HTML comment beside the code that does it)
1. Global: the hairline separator habit at .10-.16 alpha. HERE: every rule is a DASHED stitch built from a repeating-linear-gradient at .26-.32 alpha, because a dashed rule carries half the ink of a solid one. A solid 1px rule appears nowhere on the page.
2. Global: rounded containers and mid-radius cards. HERE: var(--radius) on buttons and the stepper; min(var(--radius), 2px) on plates, inputs and the docket; 0 on rules, bands and slabs; 50% only on the map dot, needle dot and status dot.
3. Global: pills as the friendly button shape. HERE: buttons are PLAQUES — rectangles at border-radius var(--radius) with a sewn inner border.
4. Global tolerance for shadows. HERE: exactly two, the swing tag and the sticky order bar. Plates and buttons carry none.
5. Global: one italic word inside a big headline. HERE: no italic exists at all — emphasis is the leather colour on the turn clause plus a thread underline, which is what makes the French and Arabic pages structurally identical.
6. Global motion defaults. HERE: gsap.defaults power2.out at 1.2s, with narrative reveals living at 1.0-1.6s and a 1.9s plate settle. power3's sharp deceleration is faster than this world's hands.
7. Global: count-up numerals on stats and prices. HERE: exactly ONE count-up, the lineage numeral. The price never animates.
8. Global: inputmode numeric on the phone field. HERE: inputmode tel.
9. Global: no hand-drawn SVG illustrations. HERE: the thread, the needle dot, the stitch-cross, the four trust icons, the WhatsApp mark, the select chevron, the stamp and the provenance MAP are DRAWN inline SVG in one stroke language — they are marks and diagrams, not imagery. The ban holds absolutely for anything standing in for a PHOTOGRAPH, and for the map it holds twice: a SIMPLIFIED 10-24-point outline is an illustration of a region, never a claim of geographic precision, never a screenshot, never a coordinate the brief did not state. No drawn products, no mascots, no drawn logo.
10. Global: an eyebrow micro-label opening a hero. HERE: the page opens COLD on the manifesto, and an eyebrow above any headline is banned outright.
11. Global: ambient loops at 3-4s, including a 4s breathing glow behind the product. HERE: there is no glow at all — the two loops are a 2.6s needle passing down the scroll cue and a 4.5s breath on the map's origin ring, both diegetic, both outside the band on purpose because this world's pulse is a hand's, not a device's.

## Héritage ban list (in addition to the global one)
A product, a price or a button in the first screen · a solid 1px rule anywhere (every rule is stitched) · neutral grays and pure white or pure black · italic type of any kind · any font weight above 500 · pills and 999px buttons · card grids, icon-and-heading feature trios, bento boxes · box-shadows outside the swing tag and the sticky bar · a uniform border-radius as the page's only shape · tickers, marquees, carousels and horizontally-scrolling galleries (the ONE horizontal move is the pinned journey) · countdown timers, "stock limité" counters and any manufactured urgency · a green WhatsApp blob · emoji, icon fonts, downloaded icon sets · gradients as decorative fills (the only gradients are the plate scrims and the two texture layers) · glassmorphism · a hero eyebrow micro-label as the opening element · stock "artisan" clichés: a lone burning candle, a generic mason jar, an unrelated pair of scissors on a white table · maps that are screenshots, world maps, or claims of geographic precision · more than one pinned scene · more than two ambient loops · any hidden state authored in CSS · sans-serif headlines · centred body copy (only the breath scene and the closing wordmark are centred).

## Intensity
This world fails by warming up too fast. Every wrong decision here is an impatience: showing the product in scene one because "people want to see it", solid rules because dashed felt fussy, a 16px radius because 2px felt severe, .6s reveals because 1.3s felt slow, a pill button because plaques felt old. Executed at 60 percent, Héritage is a brown template with a nice photograph. Executed at 100 percent — a dark screen that says only "Trois générations. Un seul geste.", a thread that stitches its way down through every scene and crosses itself once at the moment the object finally appears, plates numbered like a museum's, a map with one point on it that breathes, a journey you scroll through at the pace of a hand, a price that explains itself, and a docket stamped with a seal at the end — it reads as a house that has been quietly right for forty years. The slowness IS the product. Push into it. Every number above is load-bearing.`,
	energy: "medium",
	family: "heritage",
	id: "heritage",
	industries: [
		"crafts",
		"leather",
		"carpets",
		"ceramics",
		"pottery",
		"textiles",
		"traditional-wear",
		"fashion",
		"jewelry",
		"home-decor",
		"furniture",
		"food-artisan",
		"cosmetics",
		"wedding",
	],
	kind: "product",
	mood: ["storied", "tactile", "earthen", "slow", "handmade"],
	name: "Héritage",
	preview: {
		ground: "#DCCBB0",
		ink: "#241E17",
		accent: "#8F5C2C",
		fontFamily: "Newsreader",
		sampleWord: "Héritage",
	},
	priceFeel: "premium",
	tagline:
		"The page opens on your story in huge thin serif over dark kraft — no product yet — then a sewing thread stitches its way down the screen, joining scene to scene, until the object is finally revealed, priced honestly and ordered on a workshop docket stamped like a piece of leather.",
};
