import type { DesignWorld } from "./types";

/**
 * LABORATOIRE — the spec-first tech bench, for single-product COD pages.
 * Near-black cool ground, ONE LED accent that behaves like an emitter, and the
 * signature EXPLODED VIEW: the product's shots layered and scrubbed apart into
 * annotated parts, then reassembled. Benchmarks count, circuit traces route
 * between scenes, and the order form is a checkout terminal. The doc is
 * appended VERBATIM to the builder system prompt.
 */
export const laboratoire: DesignWorld = {
	avoidFor: [
		"crafts",
		"wedding",
		"events",
		"food",
		"street-food",
		"bakery",
		"restaurant",
		"spa",
		"baby",
	],
	doc: `# DESIGN WORLD: LABORATOIRE — the spec-first tech bench

## Philosophy
This page is a TEST BENCH, not an ad. The product sits on a near-black surface under one instrument light, and the page proves it: parts, tolerances, measured numbers, a comparison you could argue with, and a purchase terminal at the end. The promise is never "amazing quality" — it is "here is the object, here is what it does, here is the number, here is the price."

The persuasion mechanism is DISCLOSURE. A generic gadget page hides the product behind adjectives; this one takes it apart in front of the visitor. Everything soft is removed — glass, purple gradients, floating cards with drop shadows, neon wallpaper — and replaced with instrument matter: hairlines, routed traces, spec chips, ruled tables, tabular numerals, one glowing LED. Depth comes from a raised ground step and a 1px border, never blur. Light comes from ONE source and it is the product's own indicator. A scene carrying no fact does not belong.

## The vibe
An engineer who is also a good salesperson. Confident, unhurried, proud of the object. Copy law, non-negotiable — it carries 40 percent of this world:
- HEADLINES STATE A CAPABILITY WITH A NUMBER IN OR BESIDE THEM, never an aspiration: "Douze heures. Sans recharge." / "45 dB de moins, mesures à l'appui." / "Il pèse 280 g. C'est le sujet."
- Sub-copy is two or three declarative sentences, each carrying one concrete fact. No sentence survives swapping the product name.
- A number beats an adjective; a unit beats a promise. Write 47,3 % — never "presque 50 %".
- A claim with a measurement condition states it in a mono note ("mesuré à 1 m, volume 50 %") — but ONLY when the brief supplies the condition. A test that was not run is never described.
- Validation speaks precisely, never cutely: "Numéro incomplet — il manque 2 chiffres."
- Banned page-wide: révolutionnaire, incroyable, solutions, expérience, ultime, magique, premium as an adjective about itself, and their Arabic and English equivalents.
- Write in the brief's language. Arabic follows the same law with the RTL adaptation below; darija phrasing is welcome where the tone allows, but the numbers stay exact.

## The single idea — THE EXPLODED VIEW (build this FIRST; without it this world does not exist)
One scene per page, and it is what people remember: the product separates into layered parts as the visitor scrolls, holds apart while annotated callouts name real specs, then reassembles. It is the SHOWPIECE and gets three times the ambition of any other scene.

CONSTRUCTION — two legal builds, chosen by what the shot list gave you:
- PARTS BUILD (preferred). 3 to 5 layers, never more. Layer 0 is the assembled product shot; layers 1 to N are separately generated shots of its real components on the same bench ground (case, driver, cable, tip, battery, propeller, mount, charger). Each is an absolutely positioned img at inset 0, 100% by 100%, object-fit contain, inside one position-relative STAGE at width min(100%, 46rem), aspect-ratio 1 (4/5 for tall objects).
- BAND BUILD (fallback when parts cannot be generated, legal anywhere). ONE image repeated three times in the stage, each copy clipped by clip-path inset() into a horizontal third (0/67/0/0, 34/34/0/0, 67/0/0/0), so the object splits into three slabs. It reads as a cutaway and it is honest — it is the same object.

THE OFFSETS, in percentages of the stage so they survive every viewport: layer 1 x -14 % y -9 % rotate -4deg scale 1.04 · layer 2 x 17 % y 12 % rotate 3deg scale .96 · layer 3 x -6 % y 21 % rotate -1.5deg scale .92 · layer 4 x 12 % y -18 % rotate 5deg scale .88. Depth is encoded twice — by scale and by a filter brightness step of 1 / .94 / .88 / .82 — so drifted parts read as leaving the light.

THE SCRUB. ScrollTrigger on the section: start "top top+=58", end "+=220%", pin the stage wrapper (never the svg or the images), scrub 1.05, anticipatePin 1, invalidateOnRefresh true. One timeline in three acts on normalized progress: 0 to .42 the parts travel to their offsets with ease none · .42 to .58 THE HOLD, nothing moves, the callouts are live and readable — this beat is the whole point and cutting it kills the scene · .58 to 1 everything returns to translate(0) rotate(0) scale(1). The LED glow behind the assembled position does NOT travel, so the parts visibly leave the light and return to it. At reassembly the glow takes one pulse — scale 1 to 1.1 to 1, opacity +.12, .6s sine.inOut — fired once past progress .985.

THE CALLOUTS (the annotation layer, bound to real geometry):
- Each callout targets a layer and carries data-callout-x and data-callout-y as percentages of the stage for its anchor ON the part, plus data-callout-side (start or end) for where the label parks.
- ONE svg per stage: absolute, inset 0, 100% by 100%, overflow visible, pointer-events none, aria-hidden true, z-index 6, preserveAspectRatio none, with vector-effect non-scaling-stroke on every path so 1px stays 1px under non-uniform scaling.
- THE LEADER has exactly TWO segments and no curve: a 38-degree diagonal from the anchor to a landing point, then a horizontal SHOULDER of 34px toward the label, ending on the part in a 3px filled signal dot. Stroke 1px signal at .6, butt caps, miter joins.
- THE LABEL is mono .625rem uppercase, .14em, glass .82, with 6px of bench-coloured backing so the shoulder passes behind the text; the numeral tabular-nums at glass 1, the unit glass .52 at .82em. Format: 45 dB · 12 h · 280 g — three facts, middot-separated, never a sentence.
- MEASURE, NEVER GUESS: coordinates are read after window load via getBoundingClientRect on the stage, then recomputed in a ResizeObserver and a 120ms-debounced resize. Never hard-coded as pixels.
- LEADERS DRAW inside the hold: pathLength 1, dasharray 1, dashoffset 1 to 0 over .45s power2.out, stagger .08, each label following its leader with autoAlpha over .25s at +=.15. Past .58 they leave with autoAlpha 0 over .25s.
- BUDGET: 3 minimum, 6 maximum, never more than 3 legible at once. Below 760px: 2 callouts, no layer rotation, offsets at 60 percent of desktop.
- HONESTY, ABSOLUTE: every callout states a spec the brief supplied, with its unit. Two specs means two callouts. Inventing one number to fill a leader is the unforgivable failure in this world.

FALLBACK CONTRACT, non-negotiable. The callout labels live in the DOM as a real mono definition list under the stage, visible by default; only inside the animate branch does JS promote them to absolute positions and draw the leaders. CSS renders every layer assembled at translate(0) scale(1) opacity 1. With a failed CDN, JS off, or reduced motion the visitor gets a clean product photograph plus a legible spec list, and nothing is hidden. Pin and scrub live inside gsap.matchMedia("(min-width: 820px)"); below that the explode plays ONCE as a 1.6s timeline at "top 72%" (out, hold .4s, back) with no pin. NO CANVAS — SVG, CSS and img only, so the page survives with JS off and stays crisp at any zoom.

## Visual signatures
- A near-black COOL bench lit by one soft overhead wash, with a dot lattice you have to hunt for.
- Exactly ONE luminous accent, the LED — the only thing on the page permitted to glow, breathing at 4s behind the product.
- The exploded product with hairline leader lines and mono spec labels.
- Spec chips in mono, 20 or more per page, and enormous tabular benchmark numerals with small mono units counting up once on view.
- A ruled comparison table stating facts in both columns — never ticks and crosses.
- CIRCUIT TRACES: a 1px routed line with 90-degree bends and small vias travelling between scenes, exiting one seam where it enters the next, finally soldering into the footer wordmark.
- Exactly ONE inverted scene, the DATASHEET, where the bench becomes cool paper and the type system flips with it.
- An order form that looks like the terminal at a till.

## Color physics (route the brief's palette through the fixed tokens — the physics is law)
FIXED TOKEN MAP — BENCH→--background · GLASS→--foreground · SIGNAL→--primary · BENCH→--primary-foreground · BENCH-RAISED→--secondary · DATASHEET ground→--accent · glass at 52%→--muted · glass at 14%→--border · 3px→--radius · DISPLAY→--font-heading · BODY→--font-body. These are the only CSS color/type/radius variables: every pole below is a prose role, literal register hexes belong only in these :root values, and every sibling, glow or alpha step is a color-mix(in srgb, var(--foreground) N%, transparent), substituting the mapped fixed token for that pole, or a color-mix between two mapped fixed-token references. Every unmapped role below MUST reuse the nearest mapped token or such a mix; it never gets another custom property or literal. Non-color mechanics may keep their own custom properties. Any rgba(POLE, a) notation below is design shorthand for that color-mix, never emitted CSS.
Nine tonal roles from the fixed tokens, never a tenth hue.
- BENCH: the palette's darkest cool pole, near-black with B sitting 6 to 12 points above R (the #0B0D10 / #0E1116 relationship). Never #000, never warm, never navy.
- BENCH-RAISED: one step up, 4 to 7 RGB points (the #14181E register) — the anodized panel surface. This step, not a shadow, is how a panel detaches.
- BENCH-DEEP: one step down (the #07080B register) — the void behind the exploded stage, the inside of inputs, the sticky bar, the locked nav.
- GLASS: a cool near-white carrying ALL text on the bench (the #E6EAF0 register). PURE WHITE IS NEVER USED FOR TEXT ANYWHERE.
- THE GLASS ALPHA LADDER — what makes this read as an instrument rather than a dark UI kit: display and figures 1 · body .74 · secondary, captions and mono labels .52 · disabled and test conditions .34 · structural hairlines .14 · panel borders .10 · table row rules .08 · the lattice .045. No detached gray hex exists; any #888 or slate value is a Pass-1 correctness bug.
- SIGNAL: exactly ONE saturated luminous hue — the LED. No lighter sibling, no darker sibling; hover is the same hue plus a glow, pressed is the same hue at 88 percent alpha. SIGNAL-WASH (signal at .06) has three uses only: the "this product" table column, the selected spec chip, the hovered table row.
- DATASHEET tokens for the ONE inverted scene: ground the palette's cool light pole (the #ECEEF1 register, never #FFF); ink the BENCH colour itself, so the inversion is literal; hairlines bench .16; row rules bench .09; the signal is unchanged and reads hotter on paper.
- ALERT is not another hue: validation text, invalid borders and a real stock warning use a contrast-safe color-mix between var(--primary) and var(--foreground).

THE LED PHYSICS LAW — this world's own, and what keeps a dark page from vibrating: the signal appears at FULL strength only on areas smaller than roughly 2.5 percent of the viewport (buttons, chips, dots, 1-3px rules, icon strokes, callout dots). On anything larger it may appear ONLY as a radial glow at .28 alpha or below, or as a 1px stroke. A signal-filled panel, a signal section background, or signal body text is banned. Coverage stays near 4 percent of painted area; if three separate things are signal-coloured in one viewport, remove one. THE ONE EXEMPTION, and it is deliberate: the PRIMARY ORDER ACTION — the hero button, the form's submit, the sticky bar's action cell — is signal-filled at whatever width it needs, because it is the page's single most important target and the LED law must never make the buy button quieter than a chip. Nothing else above 2.5 percent takes a signal fill, ever.

THE GLOW BUDGET — signal light is rationed by an exact census, and this is a hard count. Exactly ONE filter: blur() exists on the whole page: the diegetic product glow at blur(8px). Beyond it, SIX box-shadow glows are legal and no seventh may be invented: (1) the nav power dot, 0 0 8px signal at .55 · (2) the input focus halo, 0 0 12px signal at .18 · (3) the primary button hover, 0 0 16px signal at .28 · (4) the WhatsApp cell hover, 0 0 14px signal at .2 · (5) the active segmented/tab cell, 0 2px 10px signal at .25 · (6) the selected spec-chip dot, a 6px signal glow. Every one of them is an INTERACTIVE STATE on an element under 2.5 percent of the viewport. A glow on a panel, a plate, a card, the rail, the sticky bar or any static ornament is a bug, and a seventh glow anywhere is a bug.

THE SIGNAL'S TWELVE JOBS — use at least eight and count them before shipping: the glow behind the product · callout leaders and anchor dots · the circuit trace and its vias · the nav power dot · the scroll progress rule · the section index numeral · the unit beside a benchmark · the selected chip's border and dot · the comparison table's "this" column edge · the focus ring · ::selection · the order button fill and the sticky bar's top rule. Declare color-scheme dark and a theme-color meta matching BENCH; the meta never animates.

## The bench ground (exact recipe)
body background BENCH. One fixed layer, inset 0, pointer-events none, z-index 0; every section position relative, z-index 1, background transparent, so the page reads as objects on one continuous surface. It stacks three things: THE LATTICE — radial-gradient(circle at 1px 1px, rgba(glass,.045) 1px, transparent 0) at background-size 28px 28px · THE LAMP — radial-gradient(120% 70% at 50% -12%, rgba(glass,.055), transparent 62%), one soft overhead wash so the top of the page is lit like a workbench · GRAIN — an inline-SVG data-URI feTurbulence, fractalNoise, baseFrequency .9, numOctaves 2, desaturated with feColorMatrix saturate 0, opacity .05, mix-blend-mode overlay. Below 640px raise the lattice cell to 36px. The DATASHEET scene paints its OWN opaque ground on a ::before with an INVERTED lattice (bench dots at .05 on light), occluding the fixed layer — the only second ground on the page.

## Typography system
TWO families, two non-overlapping jobs. A third is forbidden. Load only the weights used.
- DISPLAY / TEXT (400 / 500 / 600): a technical grotesk with squarish counters and a large x-height — the Space Grotesk, Archivo, Chivo, Geist or Basis Grotesque territory. This world's display is HEAVY and TIGHT: 600 with strongly negative tracking, the register of a product launch, not of a draughtsman's note. Nothing exceeds 600.
- MONO UTILITY (400 / 500 / 700): a drafting-grade monospace — the JetBrains Mono, IBM Plex Mono, Space Mono or Martian Mono territory — carrying every label, unit, chip, caption, figure number, table header, button label, form label, callout and readout, and never prose longer than one line. The global display-font ban still holds; a mono is a utility face, not a display face, so it is legal.

THE SCALE (all clamp, display-to-micro ratio near 12:1): hero h1 clamp(2.9rem,7.4vw,6.2rem) / 600 / .96 / -.032em / 14em with AUTHORED breaks · h2 clamp(2rem,4.2vw,3.4rem) / 600 / 1.03 / -.026em / 16em · h3 and part titles clamp(1.15rem,1.8vw,1.45rem) / 500 / 1.2 / -.01em · lede clamp(1.0625rem,1.35vw,1.2rem) / 1.58 / glass .74 / 33em · body 1.0625rem / 1.62 / 32em · MONO SPEC LABEL .6875rem uppercase / .16em / 500 / glass .52, 25 or more instances per page · MONO CHIP .75rem / .06em / 500 / tabular-nums · CALLOUT LABEL .625rem uppercase / .14em · BENCHMARK FIGURE clamp(3.6rem,9vw,8.4rem) / 500 / .88 / -.04em / tabular-nums · PRICE clamp(2.2rem,4.4vw,3.4rem) / 600 / -.025em · footer wordmark clamp(3.4rem,15vw,12rem) / 600 / .84 / -.03em.

TRACKING IS A FUNCTION OF SIZE: -.04em above 110px, -.032em at 60-110px, -.026em at 34-59px, -.01em at 18-33px, 0 at body, +.16em on mono labels, +.22em on the two or three widest micro-labels. Line-height: .88 figures, .96-1.03 display, 1.2 subheads, 1.4 mono rows, 1.62 body.

MANDATORY: no display headline auto-wraps — break every h1 and h2 into explicit line spans and reuse them as motion targets · text-wrap balance on headings, pretty on body · tabular-nums on every number in a column, counter, price, table or readout · ONE word per headline may take the signal, colour only, in at most two headlines page-wide · NO ITALIC EXISTS IN THIS WORLD, which overrides the global "one italic word inside a big headline" device — emphasis is the signal colour or a 500-to-600 weight step, never a slant, which also makes the Arabic page structurally identical to the French one · mono labels sit ABOVE their content with 10px of space, except in table headers and the colophon · nothing is centred except a callout label and the footer wordmark.

## The spec system (numbers are this world's photography)
Where another world places a decorative image, Laboratoire places a measured figure.
- A BENCHMARK FIGURE is three parts: the numeral at benchmark size in weight 500 with tabular-nums; a UNIT in mono at .28em of the numeral, uppercase, signal, on the baseline with an 8px gap; a mono LABEL above at .6875rem .16em glass .52. Optional fourth: a TEST CONDITION beneath at .625rem glass .34, only when the brief states it.
- BENCHMARK ROWS: 3 or 4 figures in one ruled row, gap 0, divided by 1px glass-.10 vertical hairlines (border-inline-start on every cell after the first), padding-inline 28px. Never a card grid, never a shadow.
- THOUSANDS USE A THIN SPACE (U+202F narrow no-break space; U+2009 acceptable) — never a comma, never a period: 12 900 · 58 000 · 1 250 000. Correct French typography, correct for DZD.
- NEVER ROUND A NUMBER THE BRIEF GAVE YOU. 47,3 % persuades where "presque 50 %" does not, and 11,5 h is not 12 h.
- SPEC CHIPS are the connective tissue: inline-flex, mono .75rem, padding 7px 12px, radius var(--radius), 1px glass-.16 border, background glass .04, tabular-nums, numeral at glass 1, unit at glass .52 and .82em. Four to six in the hero, three to four under each plate, six to ten in the spec sheet.
- INLINE MICRO-DATA: every real number inside body copy is wrapped in a span switching to mono at .92em, tabular-nums, glass 1, so a paragraph visibly carries data.
- UNITS ON EVERYTHING measurable: dB, h, g, mm, mAh, W, Hz, km/h, IP, DZD. A number without a unit looks unfinished here.

## Page chassis
- THE BENCH RAIL replaces the nav: fixed, top 0, height 58px desktop and 54px mobile, z-index 60, transparent over the hero. Past 40px it locks to SOLID bench-deep with a border-bottom 1px glass .12. THIS WORLD DOES NOT USE GLASS — backdrop-filter is banned here and everywhere; an instrument bezel is opaque.
- PROGRESS RULE: a 1px signal rule at .55 on the rail's bottom edge, transform-origin inline-start, scaleX 0 to 1 scrubbed against document progress with ease none. The only animated element in the chassis.
- START CELL: a 7px POWER DOT — a signal circle with box-shadow 0 0 8px signal at .55, breathing on the same 4s loop as the product glow — then the wordmark in display 600 at 1.06rem, -.02em, over a mono sub-label at .625rem .18em glass .5 carrying a REAL fact (city, category, model line). Two type registers in one mark.
- MIDDLE: mono links at .6875rem .14em, glass .52 to 1 over .18s, each drawing a 1px signal underline from the inline-start via background-size 0% 1px to 100% 1px over .22s.
- END CELL: the order action — squared, radius var(--radius), signal fill, bench text, mono .6875rem .12em weight 700, padding 12px 20px, min-height 44px — and beside it a mono price readout at .625rem tabular-nums when the brief supplies one.
- MOBILE: links collapse into one mono MENU cell with a 12px plus drawn from two 1px rules. The overlay is a full-screen BENCH-DEEP panel with its own 36px lattice, opening clip-path inset(0 0 100% 0) to inset(0) over .45s power3.inOut, holding 64px ruled rows — mono index, link in display 500 at 1.5rem, mono target label on the end side, each border-bottom 1px glass .12.
- BASE: overflow-x clip on html and body · ::selection signal with bench text · :focus-visible outline 1px signal at offset 3px, radius min(var(--radius), 3px) · a skip link sliding from top -3rem to 12px over .25s.
- THE COORDINATED NUMBERS, all derived from the 58px rail and never guessed independently: hero min-height calc(100svh - 58px) · sticky offsets top 82px · scroll-margin-top 82px on every anchored section · the exploded pin starting at "top top+=58" so the rail never covers the stage. Below the mobile breakpoint the rail is 54px, so restate the derived numbers in the SAME media query that changes it — hero min-height calc(100svh - 54px), sticky offsets and scroll-margin-top 78px — rather than leaving a 4px lie in the layout.

## Hero forms (pick what the product calls for — every one is LOADED; a centred headline with two buttons is banned)
1. THE BENCH (default, and the split hero done properly). Grid .94fr / 1.06fr — the STAGE is the wider column, because the object is the argument. Gap clamp(2rem,5vw,4.5rem), align-items center, min-height calc(100svh - 58px), overflow clip.
START COLUMN, max-width 34rem, carries seven differentiated pieces of the offer: a mono DESIGNATION line at .6875rem .18em glass .52 (product name plus a real code or year) preceded by a 20px 1px signal rule · the hand-broken h1 with at most one signal word · a lede at 30em · a SPEC CHIP ROW of four to six chips, wrapping, gap 8px · the price block with its struck previous price if one is real · a CTA pair, the filled signal order button plus a mono text link with a leading 10px drawn arrow · a reassurance line at .8125rem glass .52 naming the payment method and the delivery window, both facts from the brief.
END COLUMN IS A BENCH, NOT A PHOTO SLOT — four layers, object CAPPED at width min(100%,34rem), justify-self center; a full-bleed photo slab as the hero column is banned here. z0 THE GLOW: absolute, left 50%, top 46%, width 128%, aspect-ratio 1, translate(-50%,-50%), radial-gradient(circle, rgba(signal,.26) 0%, transparent 64%), filter blur(8px) — the page's ONLY filter blur, per the glow budget. z1 THE PLINTH: a 2px-tall radial-gradient ellipse under the object at width 62%, rgba(glass,.14) to transparent — a contact shadow drawn as light, not a box-shadow. z2 THE PRODUCT: the LCP image, fetchpriority high, explicit width and height, object-fit contain. z3 TWO LIVE CALLOUTS already drawn at rest, using the exploded scene's leader geometry, so the signature is legible in the first screenful.
The hero TERMINATES ON A SEAM, never whitespace: a PIN HEADER, or a full-bleed FACT RAIL of four ruled mono cells (gap 0, 1px glass-.10 dividers, padding-block 18px) carrying warranty, coverage, delivery window and payment method — a 2x2 grid at .625rem below 600px.
2. THE INSTRUMENT PANEL (audio, batteries, drones, e-mobility — products whose value is measured). The h1 spans columns 1-8 with 96px of bench above it; directly beneath, a full-bleed BENCHMARK ROW of three ruled cells counting up on load, each with unit and mono label; beneath that the product full-bleed at 62svh, its lower edge dissolving into the next ground through a HEAT SCRIM; price and CTA welded to the bottom as a two-cell ruled row. Almost no prose: the numbers are the hero.
3. THE UNBOXING SPREAD (kits and bundles — smart home, tools, e-mobility accessories). A 12-column grid, gap 24px, where the box contents are a FLAT LAY of framed plates at deliberately unequal spans (5, 3, 4, 3), each a 1px glass-.12 frame with corner notches, a mono part label above and a spec chip below. ONE cell is TYPE-AS-PART: instead of an image it holds the h1, so the words sit in the grid like a component. The last cell is a bench-raised panel holding price, CTA and payment line. No hero photograph at all — the assembly IS the photograph.

## Section seams (Laboratoire's own vocabulary — every boundary uses one, never the same twice in a row, at least five per page)
- THE TRACE (the traveling motif and the world's signature seam — at least three per page). A full-bleed inline SVG, height 92px, viewBox 0 0 1440 92, preserveAspectRatio none, vector-effect non-scaling-stroke on every path so the stroke stays exactly 1px. The path is ROUTED: 5 to 7 alternating horizontal and vertical segments, every bend a true 90-degree corner with a 4px radius, stroke 1px signal at .38. At each direction change of the long run sits a VIA — an r3.5 circle, 1px signal stroke at .5, bench fill. It terminates in a SOLDER PAD — a 10x6 rect at radius 1px, fill signal .18, stroke 1px signal .5. ROUTING LAW: the trace enters each seam at the x-position where it exited the previous one, so across the page it reads as ONE continuous circuit stitching the scenes together, its last pad landing on the footer wordmark. It draws on scroll: pathLength 1, dasharray 1, dashoffset scrubbed 1 to 0, start "top 92%", end "top 46%", scrub .6, ease none.
- BUS BAR (the one heavy seam): a full-bleed 3px rule at signal .22 with eight 1px vertical pins descending 6px at irregular intervals, plus one mono label astride it at 22 percent of the width, never centred, with 12px of bench padding each side so the bar passes behind the text.
- GROUND INVERSION — THE DATASHEET. Exactly ONE per page, on a HARD cut with no gradient: the bench stops on a 1px signal rule and the cool light ground begins. Every token flips, the lattice inverts, and the scene holds the page's most factual content — the full spec sheet, the comparison table, or both. It is the brightest moment and it must be the most honest.
- PANEL WELD: the next scene starts at padding-top 0 against a shared full-bleed BENCH-RAISED panel with a 1px glass-.10 top border and 9px corner notches cut by clip-path polygon, so two scenes read as one chassis.
- HEAT SCRIM: the outgoing scene's image dissolves over a 20vh gradient whose final stop IS the next scene's ground, with one faint signal radial at .10 sitting at 30 percent of the width — heat leaving a component. An image never simply ends.
- RIBBON: a full-bleed 44px band of 6 to 9 mono micro-cells divided by 1px glass-.12 vertical hairlines, gap 0, each a real fact (IP54 · 12 H · 58 WILAYAS · GARANTIE 12 MOIS). STATIC — this world does not scroll text.
- PIN HEADER: a chapter opened with no heading — 14 to 20 vertical 1px glass-.16 strokes, 14px tall, standing on a 1px glass-.12 baseline rule spanning the container, with one mono label at the inline-start end.

## Layout physics
- THE GRID IS REAL: 12 columns, column-gap 24px, padding-inline clamp(18px,3.4vw,52px), max-width 1360px. Every block declares its span; nothing sits 3px off.
- ONE VERTICAL LADDER: 8, 16, 24, 40, 64, 96, 128, 176 — nothing else. Section block-padding clamp(80px,10vh,152px), both ends on the ladder. Mobile minimum 64px; this world overrides the global 48px floor, because an instrument needs margin.
- NO 50/50 GRID, EVER: .94fr/1.06fr for the hero, 7/5, 5/7, 8/4, .8fr/1.2fr for the sticky split. At least one grid must invert expectation — the heading column narrower than the list it introduces.
- PANELS, NOT CARDS. A panel is BENCH-RAISED background, 1px glass-.10 border, radius min(var(--radius), 3px), padding clamp(20px,2.4vw,36px), ZERO box-shadow: depth is the ground step plus the border. Exactly ONE panel per scene takes CORNER NOTCHES — a 9px triangle cut from the top-inline-start and bottom-inline-end corners via clip-path polygon — and that notched panel is the scene's most important object.
- RADIUS LAW: var(--radius) on every button, CTA, chip and stepper (:root sets --radius: 3px); min(var(--radius), 3px) on panels and fields; min(var(--radius), 2px) on progress tracks; 50% on true dots. These var(--radius)-derived declarations are the sanctioned mechanism; another corner treatment means the page has drifted.
- SHARED HAIRLINES INSTEAD OF GAPS in five places — benchmark rows, the fact rail, the ribbon, the trust strip, every table: gap 0, each cell taking border-inline-start 1px glass .10, the container taking the outer edges. THIS OVERRIDES the global "gap on every row of siblings" rule; gaps still govern everywhere else.
- THE COMPARISON TABLE, built whenever the brief supplies comparable facts. A real table, border-collapse collapse, three columns: the criterion as a mono label on the start side, THIS PRODUCT, the generic alternative. The "this" column carries a 1px signal border-inline-start and a signal-wash background; the generic column stays glass .52. th mono .6875rem .16em glass .52, padding-block 14px, border-bottom 1px glass .22; td .9375rem, tabular-nums on numeric cells, padding-block 18px, border-bottom 1px glass .08. Row hover: signal-wash plus a 2px signal edge over .18s. BOTH COLUMNS CARRY FACTS WITH UNITS — a tick-and-cross table is banned here because it is unfalsifiable, and the generic column never names a competitor the brief did not name. Below 720px an overflow-x auto wrapper with a mono hint; no gradient fade masks.
- IMAGES ARE PLATES: a 1px glass-.12 frame, radius min(var(--radius), 3px), aspect-ratio 4/3 or 1/1, object-fit cover, FOUR CORNER TICKS (8px L-shaped pairs of 1px signal rules at .7, 1px outside each corner), and a caption row beneath at border-top 1px glass .10 — mono figure number start side, description end side. IF AN IMAGE ROLE FAILS or image generation is unavailable, the plate still ships: keep the frame, the corner ticks and the caption row, and fill the picture area with a LABELLED IMAGE SLOT — BENCH-DEEP at the plate's exact aspect-ratio with one mono .6875rem .16em glass-.52 line naming the shot ("PHOTO PRODUIT · 3/4 · FOND BANC"). Never draw a fake product or an illustration to plug the hole; the exploded view degrades to the BAND BUILD, and if even the base shot is missing, to the spec list alone.
- STICKY SPLIT for any process or feature sequence: .8fr / 1.2fr, the start column sticky at top 82px with the section head, a lede and a live mono STEP COUNTER (02 / 05, tabular); the end column stacking ruled rows at border-top 1px glass .12, padding-block 40px, index in the gutter. As a row crosses 55 percent of the viewport its index turns signal and a 2px signal tick appears on its inline-start edge (scaleY 0 to 1 over .3s, origin top) while the counter updates.
- OVERFLOW IS A DEVICE, used exactly four times: the glow at 128 percent width, the callout labels leaving the stage, the corner ticks, the footer wordmark. Safe only because overflow-x clip sits on html and body and overflow clip on every scene containing a piercing element.
- RESPONSIVE COLLAPSE below 900px: every multi-column grid becomes 1fr, sticky goes static, the explode plays once without a pin, callouts drop to 2, benchmark figures drop one size step, the ribbon becomes a 2-column grid, the comparison table scrolls in its own wrapper.

## Motion identity (GSAP 3 + ScrollTrigger via CDN; native scroll — smooth-scroll libraries are unavailable; no canvas)
THE SAFETY CONTRACT COMES FIRST. Compute once: reduced = matchMedia("(prefers-reduced-motion: reduce)").matches; hasGsap = typeof window.gsap !== "undefined"; animate = hasGsap && !reduced. EVERY hidden initial state — autoAlpha, y, clip-path, dashoffset — is set with gsap.set INSIDE the animate branch; nothing is opacity 0, visibility hidden or clipped in CSS. If the CDN fails or motion is reduced, the page is fully visible, fully legible, and every conversion element still works. The reduced-motion CSS block, beyond the .01ms blanket, stops the LED breath and the power dot and leaves every trace fully drawn.

GLOBAL FEEL: gsap.defaults({ ease: "power3.out", duration: .9 }).

TIMING BANDS — this world overrides the global interaction band on the fast end, because an instrument answers instantly: 120-220ms interaction feedback (hover, press, focus ring, chip select, label colour) · .3-.45s component state (accordion, tab, total recompute, sticky bar entry) · .6-.9s entrance reveals · 1.2-1.6s counters and the spec-sheet build · 4s exactly for the LED breath · scrub for the explode and the traces. ONE shared CSS easing token, cubic-bezier(.2,.62,.2,1), carrying roughly twenty transitions.

EASES: power3.out entrances · power4.out masked line rises · power2.out counters and leader draws · power3.inOut clip wipes and the mobile menu · expo.out the sticky order bar · sine.inOut the breath · none everywhere scrubbed. BOUNCE AND ELASTIC ARE BANNED. Exactly ONE overshoot exists on the page: back.out(1.6) at .28s on the spec-chip selection dot, because a switch has a detent. TRAVEL IS TINY: y of 12, 18 and 28 only; x of 10 for mono labels arriving along a rule; scales of .96, .98, 1.02, 1.08. The exploded view's percentage offsets are the only large travel, and they are scrubbed.

THE ENTRANCE VOCABULARY IS POWER-ON, NOT FADE-UP — four verbs, and every reveal uses one. BOOT: autoAlpha 0 to 1 over .5s while a 1px signal rule beneath draws scaleX 0 to 1 from the inline-start over .7s — the element gets current. RASTER WIPE: plates, panels and the datasheet arrive clip-path inset(0 0 100% 0) to inset(0) over .85s power3.inOut at "top 86%", the inner image counter-scaling 1.08 to 1 over 1.2s so the wipe carries parallax inside it. LINE RISE: display headings rise yPercent 110 to 0 out of overflow-hidden masks, stagger .08, .7s power4.out, with padding-bottom .06em and margin-bottom -.06em so descenders survive the mask. CHIP CASCADE: mono chips arrive autoAlpha 0, y 12, scale .96, stagger .04, .38s.

THE MANDATORY SET:
1. HERO POWER-ON, one timeline, overlapping positions, about 1.7s. Set: glow scale .8 autoAlpha 0 · product autoAlpha 0 with clip-path inset(0 0 100% 0) and inner scale 1.08 · headline line spans yPercent 110 · lede, chips, price, CTA row and fact rail autoAlpha 0 y 18. Then tl.to(glow,{scale:1,autoAlpha:1,duration:1.2},0).to(product,{autoAlpha:1,clipPath:"inset(0%)",duration:.85,ease:"power3.inOut"},.3).to(productImg,{scale:1,duration:1.4,ease:"power2.out"},.3).to(lines,{yPercent:0,duration:.7,stagger:.08,ease:"power4.out"},.18).to(lede,{autoAlpha:1,y:0,duration:.6},.55).to(chips,{autoAlpha:1,y:0,scale:1,duration:.38,stagger:.04},.7).to(furniture,{autoAlpha:1,y:0,duration:.55,stagger:.07},1.05), the hero's two callout leaders drawing last at 1.3. The light comes up, the object resolves, the facts power on.
2. THE LED BREATH — the world's ONE ambient loop, diegetic: gsap.to(glow,{scale:1.09, opacity:.78, duration:4, ease:"sine.inOut", yoyo:true, repeat:-1}). The nav power dot shares the tween so the page has one heartbeat. A second ambient loop anywhere is banned.
3. THE EXPLODED VIEW — the page's ONLY pin, specified in full above.
4. TRACE SCRUBS at every seam — pure dashoffset, scrub .6, no pin.
5. BENCHMARK COUNTERS: a proxy object tweened over 1.5s power2.out, onUpdate rewriting the value with the thin space and the brief's exact decimal precision, ScrollTrigger "top 86%", once true — PLUS a 4000ms setTimeout painting the final value in case the trigger never fires on a deep-linked load.
6. COMPARISON TABLE BUILD: the "this" column's 1px signal edge draws scaleY 0 to 1 from the top over .5s, then each row's cells BOOT at stagger .05 from y 12.
7. STICKY SPLIT row ticks and step counter, per-row triggers with onEnter and onEnterBack; micro-interactions on every interactive element, all CSS, all 120-220ms.
once true on EVERYTHING non-scrubbed. Nothing re-animates on scroll-up.

SMOOTH-SCROLL LIBRARIES ARE UNAVAILABLE in this runtime — native scroll only. Every ScrollTrigger on the page works directly on native scroll; do not load Lenis or any other smooth-scroll script.

## Components
- BUTTONS, border-radius: var(--radius), three forms. PRIMARY: signal fill, bench text, mono .6875rem .12em uppercase 700, padding 14px 22px, min-height 48px on mobile; on hover it keeps the hue and gains box-shadow 0 0 16px signal at .28 over .16s (glow 3 of the budget's six) — it gets brighter, it never lifts. SECONDARY: transparent, 1px glass-.22 border, glass text, identical metrics; hover turns border and label signal over .16s. TEXT LINK: mono with a leading 10px inline-SVG arrow (never an icon-font glyph) translating x 4px. No pills for actions, no icon-only buttons, no full-width solid rectangles except the submit and the sticky bar action.
- SPEC CHIPS, static as specified above; INTERACTIVE (variant, bundle, colour) is a radio card on :has(input:checked): border 1px signal, background signal-wash, a 5px signal dot popping scale 0 to 1 over .28s back.out(1.6) with a 6px glow. The label always names the variant AND its differentiating spec AND its price delta, so choosing is a spec decision.
- INPUTS, the terminal look: height 54px, radius min(var(--radius), 3px), background BENCH-DEEP, border 1px glass .14, padding-inline 14px, value 1rem. LABEL above in mono .6875rem .16em glass .52 with 8px below; hint beneath in mono .6875rem glass .34. Typed values use the TEXT family — except the phone field, which is mono with tabular-nums, because a phone number is data. FOCUS changes three things in one 160ms beat: border-color signal, box-shadow 0 0 0 1px signal, and box-shadow 0 0 12px signal at .18 (glow 2 of the budget's six), while the mono label turns signal. SELECTS match exactly, native arrow removed, a 10px chevron drawn from two 1px glass rules.
- SEGMENTED CONTROL AND TABS: squared cells sharing 1px hairlines, gap 0, radius min(var(--radius), 0px); the active cell takes a 2px signal border-block-end plus a 0 2px 10px signal-at-.25 line and glass-1 text, inactive glass .52. Colour and edge only — this world does not slide a thumb.
- ACCORDION: ruled rows, question in display 500 at 1.15rem, padding-block 20px, grid-template-rows 0fr to 1fr over .4s with an overflow-hidden inner, the plus drawn from two 1px rules with the vertical one scaleY 1 to 0 over .3s. Single-open, aria-expanded maintained, panels with role region and aria-labelledby.
- FOOTER — THE COLOPHON PLATE, required. A full-width ruled table of five or six cells divided by vertical hairlines, each a mono label with a REAL value: seller name, city, phone, hours, delivery coverage, return window. Beneath it the WORDMARK at clamp(3.4rem,15vw,12rem) weight 600 filled in BENCH-RAISED so it reads embossed rather than shouted, with a 1px signal underscore across its full width and the page's final trace soldering into a pad at its end. Then a hairline row with the legal line in mono .625rem glass .34.
- CRAFT DETAILS: explicit width and height on every image · fetchpriority high on the LCP product image, lazy elsewhere · descriptive alt on content images, aria-hidden and empty alt on every drawn ornament and duplicated explode layer · aria-live polite on validation and total readouts · an output element for the stepper · a skip link · an inline-SVG data-URI favicon built from the power dot · a theme-color meta matching BENCH · a visually-hidden text equivalent listing every spec drawn as a callout.

## Conversion objects (this world SELLS — these are its money components, designed objects, never afterthoughts)
- THE ORDER TERMINAL is the climax of the page: a BENCH-RAISED panel with corner notches, 1px glass-.12 border, radius min(var(--radius), 3px), on its own scene with TRACE seams above and below. Grid .8fr / 1.2fr on desktop — the form column is the wider one — collapsing to one column below 900px. Its head is a mono terminal line (COMMANDE · PAIEMENT À LA LIVRAISON) plus a PROGRESS TRACE: three mono step labels joined by a 1px glass-.14 rule whose signal fill advances scaleX 0 to .33 to .66 to 1 over .45s power2.out each time a step validates. That trace is the world's progress state and the only thing in the form that moves.
- FIELD ORDER IS LAW: PHONE FIRST, then name, then wilaya, then address, then quantity. NO email. NO account. NO password. Ever.
 - PHONE: type tel, inputmode tel, autocomplete tel, a real pattern for a leading 0 followed by 5, 6 or 7 and eight digits, mono tabular-nums value, a mono hint reading 05 · 06 · 07, and live grouping into 0X XX XX XX XX as the visitor types — never blocking a keystroke, never rejecting a paste.
 - NAME: text family, autocomplete name, one field, no split first and last. ADDRESS: a textarea at 3 rows, autocomplete street-address, same metrics.
 - WILAYA: a native select styled identically to the inputs, listing the real 58. When the brief supplies per-wilaya fees or delays, choosing one WRITES them into a ruled two-cell mono readout directly above the submit — never into an FAQ, never below the fold.
 - QUANTITY: a stepper, never a number input — an inline-flex group at border-radius var(--radius) with 44px buttons at the same token radius carrying a plus and a minus drawn from two 1px rules, and an output element at min-width 2.4rem in display 600 tabular-nums. It has a cap, and THE CAP IS GIVEN A REASON in the mono hint.
- VALIDATION IS BLUR-GATED AND PRECISE: a touched map means an error appears only after a field's first blur, never while someone is typing into a fresh field. The message is one mono line at .75rem in the alert mix of var(--primary) and var(--foreground) with min-height 1.25em reserved so nothing reflows; border and mono label take that same mix in one 160ms beat; aria-invalid, aria-describedby and aria-live polite wired for real. Messages name the exact problem: "Numéro incomplet — il manque 2 chiffres."
- THE TOTAL READOUT sits above the submit as a ruled block: row one the subtotal, row two the delivery fee and delay from the wilaya select, then a 1px signal rule, then the TOTAL in display 600 at clamp(1.8rem,3vw,2.4rem) with tabular-nums and the currency in mono signal. It recomputes on every quantity, variant and wilaya change, and the numeral CROSS-FADES rather than jumping: old value out autoAlpha 0 y -8 over .16s, new in from y 8 over .2s.
- SUBMIT: a full-width signal button at min-height 54px, mono uppercase .12em 700, with a deliberate 700ms PENDING state — the label becomes a present-tense sentence while a 2px signal rule sweeps the button's bottom edge scaleX 0 to 1, ease none, over .7s — and double-submit disabled. Then the panel CROSS-FADES IN PLACE into a success state inside the same box (success in over .55s with a .2s delay, form out over .4s to y -10, visibility switching at .4s so focus never lands on a hidden element). The success state is a PRINTED RECEIPT: a mono ORDER REFERENCE inside a 1px signal-bordered plate, the buyer's own name, wilaya and chosen variant echoed back as mono rows, and the next step stated as fact — "On vous appelle pour confirmer" ONLY if the brief promised a confirmation call. At the instant validation passes — as the receipt prints — the page logs its one reading by dispatching the wandit:lead CustomEvent on document with the buyer's fields flat in detail (name, phone as typed, wilaya, commune, plus the canonical order keys product, quantity, price, delivery and total when collected, and variant under its own key), and the form carries one off-canvas decoy input marked data-wandit-hp that the page's own script never reads.
- STICKY ORDER BAR — the default mobile pattern, permitted on desktop as a slim variant. It appears once the hero leaves the viewport: translateY(100%) to 0 over .42s expo.out. Height 66px plus env(safe-area-inset-bottom), background BENCH-DEEP at .96, border-top 1px signal at .3, split by ONE vertical glass-.12 hairline into two cells. START CELL: the KEY SPEC in mono .625rem .14em glass .52 — the one number that sells this product, 45 dB or 12 h or 25 km/h — above the price in display 600 at 1.15rem tabular-nums. END CELL: the signal order action at full cell height, 44px minimum tap target, mono uppercase. It hides with autoAlpha 0 over .25s while the order terminal is in view, so it never covers the form it points at.
- PRICE TYPOGRAPHY: display 600, tabular-nums, THIN-SPACE thousands (U+202F): 12 900 DZD / 12 900 دج. The currency is a mono span at .34em uppercase, glass .52, on the baseline 8px after the numeral — before it in RTL. A struck previous price sits beneath in a real del element at .9375rem glass .52 with text-decoration-color signal at 1.5px, and ONLY when the brief states a real previous price. THIS WORLD OVERRIDES the global "count up numerals for stats and prices": PRICES NEVER ANIMATE — a spinning price reads as a slot machine — while benchmarks always do.
- WHATSAPP CTA STYLED TO THIS WORLD — never green, never a floating round bubble. A squared secondary cell at border-radius var(--radius) with a 1px glass-.16 border, holding a 20px inline-SVG WhatsApp glyph drawn STROKE-ONLY at 1.4px in the signal (the same drawn set as the trust icons), a mono label, and beneath it a mono line at .625rem glass .34 stating the merchant's real hours. On hover border and glyph go full signal and a box-shadow 0 0 14px signal at .2 appears over .16s (glow 4 of the budget's six). On mobile it may take a secondary cell in the sticky bar or sit directly beneath the submit.
- TRUST STRIP WITH DRAWN SVG ICONS: a full-bleed ruled row of four cells sharing 1px glass-.10 vertical hairlines, gap 0, padding 22px, each holding a 22px inline SVG, a mono .6875rem .14em label and one line of glass-.52 detail. Icons are STROKE-ONLY geometric primitives on a shared 24-unit viewBox at 1.4px, butt caps, miter joins, signal stroke: a banknote rectangle crossed by a diagonal (paiement à la livraison) · a package outline with a routed trace leaving it (livraison, 58 wilayas) · a circle with an inscribed returning arrow (échange) · a shield of four straight segments and no curve (garantie). Labels state ONLY what the brief promised — no icon exists for a promise the merchant did not make.
- HOW IT WORKS AS A TRACE DIAGRAM: three or four nodes — 10px squares, 1px glass-.3 stroke, bench fill — joined by the routed trace with 90-degree bends, each node carrying a mono step index and one line: commande, appel de confirmation, livraison, paiement à la réception. It draws on scroll via dashoffset at "top 80%", once, never pinned; the exploded view owns the page's only pin.
- HONEST URGENCY ONLY: real stock counts and real offer end dates, stated as facts in mono. Countdown clocks, fake "only 3 left" counters and invented review totals destroy this world faster than any visual error, because the whole page is a claim to accuracy.

## Arabic and RTL adaptation
- html dir rtl lang ar, and the layout genuinely mirrors: padding-inline, margin-inline, border-inline-start and end, inset-inline throughout. No physical left or right property appears anywhere in the stylesheet.
- Arabic-first is the DEFAULT for mass-market COD gadgets unless the brief says otherwise. French runs about 15 percent longer than English, so drop the body measure to 30em and allow one more headline line.
- NEVER LETTER-SPACE ARABIC — tracking breaks the joins and is the commonest failure. The mono label's job is carried instead by the Arabic body family at weight 500, .8125rem, tracking 0, glass .52, preceded by a 16px 1px signal rule with 10px of space. Arabic has no uppercase, so rule plus weight plus colour IS the label signal.
- KEEP THE MONO FACE for Latin numerals, units, model codes, spec chips, table data, callout figures and the order reference even on an Arabic page — that is what preserves the instrument texture. Choose ONE numeral system (Western or Eastern Arabic) and hold it everywhere, including inside callouts and the total.
- Arabic body: line-height 1.85, size +1px, every measure cap loosened by 2em, Arabic-capable families only — the IBM Plex Sans Arabic, Almarai, Rubik, Cairo territory for text, Changa or El Messiri for display. The weight-600 display ceiling holds.
- THE TRACE mirrors as pure geometry and carries no text, so scaleX(-1) on the trace svg alone is legal. THE CALLOUT LEADERS carry labels and must be re-authored in local coordinates; mirroring them with a transform would reverse the type. The exploded view is direction-neutral — only the callout side tokens flip, and shoulders point inward from the inline-end.
- RULE-DRAW and underline origins become inline-end; the progress rule's transform-origin becomes right; the sticky bar's cells swap so the action stays under the thumb.

## Bench furniture (REQUIRED — this is the world's voice)
- THE DESIGNATION LINE: the page names its subject once in mono — product name plus a real code, model line or launch year from the brief. When the brief supplies no code, the designation carries the category and the year, or nothing. A fabricated SKU is a lie.
- SECTION HEADS instead of centred h2s: a baseline-aligned flex row — mono index 03, an 18px 1px signal rule, the mono section label at .6875rem .2em, a flex-1 hairline at glass .12, an end-aligned mono aside. The flex rule IS the border, and this is the only section-head form on the page.
- FIG. NUMBERS on every plate, diagram and table, sequential across the page, never repeated: FIG. 04 — Vue éclatée, 5 pièces.
- SPEC CHIPS as recurring texture, 20 or more per page.
- BENCH NOTES: a superscript marker in signal inside body copy resolving to a mono note at the section foot above a border-top 1px glass .12, at .6875rem glass .52. Once or twice per page, on a claim whose measurement condition the brief actually supplied.
- TEST CONDITION LINES beneath benchmark figures, mono .625rem glass .34, saying how the number was obtained. Omitted entirely when the brief is silent, never invented.
- THE COLOPHON in the footer, and the RIBBON of real facts between two chapters.
- ALL OF THIS IS TYPESETTING, not invention. Every value comes from the brief; where the brief is silent the furniture describes the PAGE (figure numbers, section indices, the count of parts drawn) or it is omitted. Fabricating one spec to fill a chip destroys the world.

## Explicit overrides of the global builder rules
1. Global: gap between every row of siblings. HERE: benchmark rows, the fact rail, the ribbon, the trust strip and every table use gap 0 with SHARED HAIRLINES. Gaps still govern everywhere else.
2. Global: rounded cards and 12-16px radii. HERE: var(--radius) on buttons, chips and steppers; min(var(--radius), 3px) on rectangles; min(var(--radius), 2px) on tracks; 50% on true dots — and panels get CORNER NOTCHES rather than large radii.
3. Global: no hand-drawn SVG illustrations. HERE: circuit traces, callout leaders, the process diagram and the four-icon stroke set are the native language. Mascots, doodles and drawn LOGOS remain banned.
4. Global: count-up numerals on view for stats and prices. HERE: prices never animate; benchmarks always do.
5. Global: interaction feedback .25-.45s. HERE: 120-220ms — an instrument answers instantly. The other bands stand.
6. Global: a blurred translucent sticky nav is a common pattern. HERE: backdrop-filter and glass are banned outright; the rail locks to solid bench-deep with a hairline and a signal progress rule.
7. Global: mobile section padding at least 48px. HERE: at least 64px, snapped to the 8px ladder.
8. Global: one italic word inside a big headline. HERE: no italic exists; emphasis is the signal colour or a 500-to-600 weight step.
9. Global suspicion of glow and blur. HERE: ONE filter blur (the diegetic product glow) plus the SIX enumerated box-shadow glows of the glow budget, every one of them an interactive state on a sub-2.5-percent element. A seventh glow, or any glow on a static panel, plate or bar, is a bug.
10. Global: at most ONE hairline seam per page. HERE: the TRACE is a recurring MOTIF, not a boundary made of whitespace plus a rule — a naked 1px line separating two scenes with nothing else is still banned.
11. Global: inputmode numeric on the phone field. HERE: inputmode tel — the call-shaped keypad is the affordance this market expects for a number typed from memory. The rest of the global COD form contract (phone first, no email, no account, styled wilaya select, inline validation) is obeyed exactly as written.

## Laboratoire ban list (in addition to the global one)
Glassmorphism, backdrop-filter and translucent panels · box-shadow as a depth device on panels, cards, buttons, the rail or the sticky bar (the only legal shadows are the drawn plinth radial and the six enumerated interaction glows) · any radius above 3px on a rectangle · gradients as decorative fills (only the LED radial, the heat scrim, the bench lamp and a 2px progress fill exist) · a second accent hue, a "cyber" secondary, or purple and violet in any role · neon everywhere instead of one LED · carbon fibre, hexagon mesh, matrix rain or circuit-board WALLPAPER — the trace is a LINE, not a texture · lens flares, light streaks and bloom · 3D tilt cards on mouse move · particle backgrounds, WebGL and canvas of any kind · tick-and-cross comparison tables · countdown timers, fake stock counters and invented review totals · marquees and scrolling tickers · italic type · serif type · centred body copy and centred section heads · a full-bleed photo slab as the hero column · pills as primary actions · a floating round green WhatsApp bubble · emoji and icon fonts · more than ONE pin, ONE ambient loop, ONE inverted scene · per-character text splitting · bounce and elastic eases and any overshoot beyond the single named detent · fabricated specs, a callout pointing at nothing, a benchmark with no source, or a comparison against a competitor the brief did not name.

## Intensity
This world fails in exactly the ways a dark tech page always fails: a purple gradient creeps in, panels grow 16px radii and drop shadows, the accent spreads to three hues, the specs become adjectives, the exploded view becomes a photo that fades up, and the comparison table becomes ticks and crosses. At 60 percent that is a dark SaaS template with a product photo on it, and it converts nothing, because it promises measurement and delivers mood. At 100 percent — a cool near-black bench under one lamp, one LED breathing at 4 seconds behind the object, the product flying apart into annotated parts as you scroll and clicking back together, three benchmark numbers counting up with their units, a ruled table you could argue with, a circuit trace routing you from scene to scene and soldering into the wordmark, and a checkout terminal that validates like a device — it looks like a page built by people who actually measured the thing they are selling. That is the entire sale. Push INTO the precision: every number above is load-bearing.`,
	energy: "medium",
	family: "laboratoire",
	id: "laboratoire",
	industries: [
		"gadgets",
		"electronics",
		"audio",
		"drones",
		"smart-home",
		"e-mobility",
		"tech",
		"tools",
		"auto",
		"accessories",
		"appliances",
		"photography",
		"ecommerce",
	],
	kind: "product",
	mood: ["technical", "engineered", "dark", "precise", "confident"],
	name: "Laboratoire",
	preview: {
		ground: "#0E1116",
		ink: "#E6EAF0",
		accent: "#2CFF7A",
		fontFamily: "Space Grotesk",
		sampleWord: "Laboratoire",
	},
	priceFeel: "premium",
	tagline:
		"Your product on a near-black workbench under one glowing LED — it flies apart into its own parts as the visitor scrolls, every piece tagged with a real measured number, and the order form validates like the terminal at the till.",
};
