import type { DesignWorld } from "./types";

/**
 * NID — trust-first softness for the nursery aisle.
 * A page for the person who checks the label twice: cloud-soft pastel paper,
 * safety credentials DRAWN as SVG seals, texture macros of the actual cotton,
 * oversized friendly age numerals, a care table with hand-drawn symbols, and a
 * cash-on-delivery form written to calm a tired parent at 23h. Mid-radius is
 * native here and lullaby motion is law. Appended VERBATIM to the builder.
 */
export const nid: DesignWorld = {
	avoidFor: ["gaming", "auto", "industrial", "nightlife", "crypto", "tools"],
	doc: `# DESIGN WORLD: NID — the nest, and the label you read twice

## Philosophy
This page sells to somebody who is buying for a person who cannot complain. That single fact rewrites everything. A parent shopping for a newborn is not looking for excitement, a discount clock or a lifestyle — they are looking for PROOF that this thing is safe, soft, the right size, and returnable if it is not. So this world is built on two materials only: SOFTNESS you can see, and FACTS you can check. Every square centimetre of the page is one or the other, and the design job is to make the facts feel as gentle as the fabric so the page never turns into a pharmacy leaflet.

The organising idea is CLOUD-SOFT PAPER WITH HARD FACTS PRINTED ON IT. The ground is a warm milk-white with pastel weather in it. Content sits on PLATES — soft rounded panels with two-layer shadows that look like paper laid on a folded blanket. Nothing on this page has a corner under 14px, nothing moves faster than half a second, nothing is louder than a lullaby, and nothing is claimed that the brief did not state. The credentials — the norm, the cotton origin, the age range, the wash temperature — are DRAWN as line-SVG seals and typeset like a certificate, because a drawn seal reads as considered where an emoji reads as a shrug.

Structurally this is a vertical stack of plates joined by cloud seams and paper overlaps, with one pinned growth moment and a cash-on-delivery chapter that is the largest, calmest object on the page. There is no dark chapter anywhere in this world — the page never goes below the milk-to-pastel range. Chromatic inversion here means a PASTEL chapter, not a black one. That constraint is the whole discipline: with no dark to hide behind, quality has to come from shape, shadow, spacing, drawn detail and copy.

The failure mode of this world is BLANDNESS DRESSED AS KINDNESS: a pastel background, a rounded card grid, a smiling stock family and three icons. Softness is not the absence of decisions. It is fifty of them.

## The vibe
A small shop that folds the clothes before it wraps them, and answers the phone itself. Careful, warm, slightly maternal, allergic to hype. The register is ACCESSIBLE — real prices for real families, worn without apology and without discount theatre.

Copy rules, non-negotiable, they carry 40 percent of this world:
- Headlines are SHORT and physical, eight words maximum, and they name a material, a size or a gesture — never a feeling: "Du coton, et rien d'autre." / "Taillé pour les premiers mois." / "Lavé avant d'être plié." A headline that could sit on a furniture page has failed.
- EVERY claim is welded to a checkable fact from the brief: not "matière de qualité" but "coton peigné 220 g, lavé à 30 degrés avant expédition". If the brief has no fact for a claim, the claim is deleted, not softened.
- REASSURANCE MICROCOPY IS A DESIGN ELEMENT, NOT A LEFTOVER. Every form field, every price, every size choice, every CTA carries one line at .82rem in ink at 60 percent that answers the unasked question: "Le livreur demandera ce nom à la porte." / "On appelle une seule fois pour confirmer, jamais avant 9h." / "Si la taille ne va pas, on échange — dites-le au livreur." Count them: a finished page has at least TWELVE. This is the single most recognisable thing about Nid.
- Validation errors are gentle full sentences with a reason, never a red bark: "Il nous manque le numéro — c'est le seul moyen qu'on a de vous prévenir avant de passer."
- ONE unexplained soft line somewhere on the page: two lines of voice on a bare pastel plate, no heading, no button, no explanation.
- Banned words everywhere: solutions, expérience, révolutionnaire, transformez, premium, magique, exclusif, and their English and Arabic equivalents. Also banned as a claim: hypoallergénique, dermatologiquement testé, bio, anti-bactérien — unless the brief states the certification, in which case it is quoted with its reference and drawn as a seal.
- Write in the brief's language. In Arabic the rules hold identically; Arabic has no italic, so accented fragments are carried by the accent colour plus a heavier display weight.

## The plate law (do this FIRST — every other rule in this world sits on top of it)
NOTHING ON THIS PAGE FLOATS ON A BARE BACKGROUND. Content lives on PLATES, and the plate is a single reusable token you build once:
- background: the LIFT ground (one step LIGHTER than the ground it sits on — the plate is lifted, never sunken; a plate darker than its ground is a bug in this world).
- border-radius: min(var(--radius), 1.15rem) standard. No border by default.
- box-shadow: TWO layers, always, always tinted with the ink hue and never black — 0 18px 40px -28px rgba(ink,.42) for the lift, and 0 2px 5px -2px rgba(ink,.14) for the contact. One-layer shadows look printed; two-layer shadows look placed.
- padding: clamp(1.3rem,3vw,2.1rem) as the floor. A plate with tight padding reads as a card, and cards are banned here.
Variants: CHIP and PILL (var(--radius), every button, chip and size pill) · PLATE (min(var(--radius), 1.15rem)) · GRANDE PLAQUE (min(var(--radius), 1.25rem), shadow spread 0 26px 60px -34px) · COUSSIN (min(var(--radius), 2.6rem), a whole chapter turned into one plate) · BERCEAU (the sculpted cradle frame, 1.25rem 1.25rem 4.5rem 4.5rem).
THE RADIUS IS A SCALE OF SIX VALUES, NOT ONE VALUE. This world overrides the global suspicion of mid-radius: 14-20px is NATIVE here and correct. What stays banned is the single uniform radius applied to everything — if every rounded thing on your page is the same 16px, you have built the template this world exists to replace. In any group of plates, at least two different radii and at least one oversized cell.

## Visual signatures (what makes it instantly recognizable)
- Cloud seams: sections do not meet on a straight line. They meet on LE NUAGE — an asymmetric four-arc cloud edge drawn in SVG, spanning the full width, in the incoming section's own ground colour.
- Drawn safety seals: rounded-square plates holding 1.5px line drawings — a nest, a cotton boll, a soft shield, an age square with a numeral in it — with the certification name and reference typeset underneath like a label sewn into a collar. Never an emoji, never a badge PNG, never a shield icon from a set.
- Oversized friendly numerals: the age and size range as PILLS with a big tabular numeral (0-3m · 3-6m · 6-12m · 12-24m) and a small unit line under it. They are a real control, wired to the order form.
- A hanging mobile: one decorative element — a drawn arc bar with three shapes on 1.25px threads — hangs off a corner of the hero and rocks 2.4 degrees over 5.2 seconds, forever. It is the only rotating thing on the page and the reason the page feels like a nursery instead of a shop.
- Texture macro plates: the cotton weave, the stitch, the snap fastener, the seam — photographed close enough to read the thread, in 1.15rem plates with a stitched rule and a soft caption under them.
- A care table: the washing instructions ruled like a real label, with the five care symbols DRAWN as line SVG.
- Stitched rules: this world's hairline is a 1.5px DASHED line (dash 6, gap 7) in ink at 18 percent — a sewn seam, not a printer's rule.
- Whisper tone steps: five or six ground changes across the page, each of them 2 to 4 RGB points, so the page changes tone the way light changes in a room, never in stripes.

## Color physics (route the brief's palette through the fixed tokens — the physics is law)
FIXED TOKEN MAP — LAIT→--background · ENCRE→--foreground · ACCENT→--primary · LAIT→--primary-foreground · LAIT-DEEP→--secondary · the deepest PASTEL→--accent · ink at 50%→--muted · ink at 12%→--border · 999px→--radius · DISPLAY→--font-heading · BODY→--font-body. These are the only CSS color/type/radius variables: every pole below is a prose role, literal register hexes belong only in these :root values, and every sibling, pastel or alpha step is a color-mix(in srgb, var(--foreground) N%, transparent), substituting the mapped fixed token for that pole, or a color-mix between two mapped fixed-token references. Every unmapped role below MUST reuse the nearest mapped token or such a mix; it never gets another custom property or literal. Non-color mechanics may keep their own custom properties. Any rgba(POLE, a) notation below is design shorthand for that color-mix, never emitted CSS.
Build eleven palette roles from the fixed tokens. Never introduce a twelfth hue, never a neutral grey, never a colour that is not a fixed-token value or a mix of fixed tokens.
- LAIT (the ground): the palette's lightest warm pole, in the #FBF7F2 register. Never #ffffff, never #fafafa, never a cool white. If the brief's lightest pole is cool, warm it 2-3 points on R and G before using it.
- LAIT-LIFT: the plate ground, 2 to 3 RGB points LIGHTER than LAIT (the #FEFCF8 relationship). This is the only value on the page allowed to approach white, and it only ever appears as a plate surface, never as a full section.
- LAIT-DEEP: the whisper ground, 3 to 5 points darker (the #F5EFE7 relationship), used ONLY for section alternation.
- PASTELS — THREE siblings derived from the brief's warm poles by desaturating to S 18-32 percent and lifting to L 88-93 percent: POUDRE (the blush pole), CIEL (the cool pole), BEURRE (the yellow pole). They are GROUNDS and PLATE FILLS ONLY. Pastel is never a text colour and never a border colour in this world.
- ENCRE (ink): a warm soft-dark where R is greater than G is greater than B, in the #443A38 register, L* between 26 and 32. Never #111, never #222, never a near-black. If the brief hands you a near-black, lift it toward its own hue until it stops looking like a legal document.
- INK AT ALPHA — this is the rule that keeps the page reading as soft paper rather than as UI. Body copy rgba(ink,.78) · secondary rgba(ink,.62) · captions and units rgba(ink,.50) · stitched rules rgba(ink,.18) · plate outlines when needed rgba(ink,.12) · placeholders rgba(ink,.36) · progress tracks rgba(ink,.10) · the ghost wordmark rgba(ink,.07). NO independent grey hex exists on this page. Declaring #888 or a slate is a correctness bug.
- ACCENT: exactly ONE gently saturated hue from the brief, S 42-58 percent and L 52-62 percent — a dusty coral, a soft sage, a muted sky, a warm clay depending on the brief. It must be a colour that survives next to pastels without vibrating. Neon, fluoro and primary red are structurally wrong here.
- ACCENT-DEEP: the same hue at L 36-44 percent. THIS is the only accent value allowed for text under 1.1rem or on a pastel ground, because AA contrast is not optional on a page about safety. The light accent is for fills, dots, rules and large numerals.
- ACCENT-WASH: the accent at 8-12 percent alpha over LAIT, used for the checked state of size pills, the focus halo and the order chapter's inner plates.
- ARGILE (the error treatment) is not another hue: use a soft, contrast-safe color-mix between var(--primary) and var(--foreground). It appears exclusively in validation, and it never flashes.
Deliberately absent: there is NO dark token, NO near-black chapter, NO inverted footer. If a section needs weight, it becomes the deepest pastel with a COUSSIN radius, never a dark slab.

THE ACCENT'S FIFTEEN JOBS — use at least ten: the drawn nest mark in the wordmark · the accented word in one headline per chapter · the size-pill checked ring · the seal strokes on the safety badges · plate numerals (PL. 01) · the focus halo · ::selection · the stitched-rule knot dot · the stepper button fill on hover · the care-table temperature numeral · the accordion plus bars · the WhatsApp glyph stroke · the success-panel drawn nest · the sticky bar's CTA fill · the footer newsletter capsule. THE PRICE CURRENCY MARK IS DELIBERATELY NOT ONE OF THEM (see Conversion objects): an accent currency mark makes the price shout, and this page never shouts about money.

CONTRAST LAW, enforced before anything else ships: body text on any ground at 4.5:1 minimum, large display at 3:1 minimum. On any pastel ground, text is ENCRE or ACCENT-DEEP — never the light accent, never white. White text does not exist anywhere on this page.

## Typography system
TWO families, two jobs, zero ambiguity. A third face is allowed only for Arabic. Load only the weights used.
- DISPLAY (400/600/700): headlines, all numerals, size pills, prices, totals, the wordmark, the footer monument. Territory: a SOFT-TERMINAL geometric or humanist sans with rounded stroke ends, a tall x-height and generous open counters — the Nunito / Quicksand / Baloo 2 / Fredoka / Comfortaa territory. Pick ONE and commit. What is wrong here: a high-contrast didone, a condensed grotesk, a slab, anything with sharp spurs or a mechanical single-storey a.
- BODY (400/500/600): paragraphs, labels, microcopy, captions, inputs, nav. Territory: a warm humanist sans with round bowls and a friendly ampersand — the Karla / Work Sans / Rubik / DM Sans / Figtree territory. It must be legible at .78rem on a phone at 23h.
- ARABIC: a soft-terminal Arabic face in the Rubik / Almarai / Baloo Bhaijaan 2 / Cairo territory for both roles, at +8 percent size and +.12 line-height versus the Latin scale.
- BANNED FACES in this world specifically: any handwriting, comic, bubble or crayon face (that belongs to a different world and it destroys the credibility the safety seals are buying), any monospace outside a reference code, and the global bans (Inter, Roboto, Open Sans).

Scale — all clamp, all measured:
- Hero h1: clamp(2.5rem,6.2vw,4.8rem) / line-height 1.06 / letter-spacing -.004em / weight 600. This world's display register is STATEMENT, not POSTER: a 15vw headline shouting at a parent is the wrong volume, and the page earns its scale from the numerals instead.
- Section h2: clamp(1.95rem,4.2vw,3.1rem) / 1.12 / -.003em / weight 600 / max-width 17em.
- Plate h3: clamp(1.2rem,2vw,1.55rem) / 1.28 / 0 / weight 600.
- Age and size numerals: clamp(1.5rem,2.4vw,2.05rem) / 1 / -.01em / weight 700 / tabular-nums / font-variant-numeric lining.
- Price: clamp(2rem,3.5vw,2.9rem) / 1 / 0 / weight 700 / tabular-nums.
- Body: 1.0625rem / 1.72 / 0 — the generous leading is a world rule, not a preference. Nothing on this page is set tighter than 1.68 at body size.
- Microcopy and reassurance lines: .82rem / 1.6 / 0 in rgba(ink,.62).
- Micro-caps: .72rem to .78rem, +.12em to +.18em, weight 600. Sentence case is PREFERRED over uppercase for anything longer than three words — long uppercase strings read as terms and conditions.
- Footer monument: clamp(3.2rem,14vw,11rem) / .9 / +.01em / weight 700, FILLED in rgba(ink,.07). Never outlined: -webkit-text-stroke produces a hairline edge and this world has no hairline edges.

TRACKING LAW: this world never goes below -.006em at any size. Negative tracking tightens and hardens; softness needs air. Positive tracking only appears at micro-caps. Line-height law: 1.06 minimum at display, 1.28 at subheads, 1.72 at body, 1.6 at micro.

PROMOTE THE NUMERALS. Wherever a number appears inside a sentence (a weight in grams, a temperature, a size in centimetres, a delivery window), wrap it in a strong tag set in the DISPLAY face at 1.3em with tabular-nums and a colour of full ink inside a .98rem body line. "Coton peigné 220 g" then reads as a spec, not as a sentence. This one rule is most of the label effect, and it costs nothing.

NEVER LET A DISPLAY HEADLINE AUTO-WRAP. Break it into explicit block-level line spans so the rag is authored, and reuse those spans as the stagger targets. Target a display-to-micro ratio of at least 6:1.

## Page chassis
- SOFT ANNOUNCE STRIP (optional, excellent for COD): a full-bleed PASTEL band above the nav, centred, .82rem weight 500 in ink at 78 percent, padding .68em, with a drawn 1.5px dot separator between clauses and ONE word in accent-deep. It carries a fact from the brief (delivery zones, the exchange window) — never a promotion.
- NAV: position sticky, top 0, z-index 100, max-width 92rem, margin-inline auto. Its signature is a BOTTOM-ONLY RADIUS: border-radius 0 0 1.25rem 1.25rem, so the bar reads as a soft plate hanging from the top of the screen. Default state is transparent over the hero. Past 40px of scroll it gets background rgba(lait,.9), backdrop-filter blur(14px), and box-shadow 0 12px 30px -26px rgba(ink,.5) — transitioned over .7s with the shared ease. No border, ever.
- WORDMARK IS A LOCKUP: the drawn NEST MARK (an inline SVG at 1.45rem: two nested arcs of 1.6px stroke, round caps, with three small filled dots resting inside the lower arc, in accent) plus the shop name in display 700 at 1.3rem tracked +.005em, gap .58rem, align-items center. Under it optionally a .64rem body-face line at +.16em in ink at 55 percent.
- Nav row: flex, gap 1.8rem, padding .85rem var(--pad). Links body 500 at .95rem in rgba(ink,.72) going to full ink over .55s. A capsule CTA on the end side. Below 880px the links disappear and only the CTA remains — this world does NOT build a hamburger overlay, because on a phone the sticky order bar is the navigation.
- PAPER SPECKLE: position fixed, inset 0, z-index 90, pointer-events none, opacity .07, mix-blend-mode multiply, an inline SVG data URI of feTurbulence type fractalNoise baseFrequency 0.62 numOctaves 3 desaturated with feColorMatrix saturate 0. Much softer than a normal grain — at .16 it would look dirty against pastel.
- CLOUD WEATHER: EXACTLY TWO fixed, pointer-events-none radial layers behind the WHOLE document at z-index 0 — radial-gradient(62vw 52vw at 12% 6%, poudre at .5 alpha, transparent 64%) and radial-gradient(70vw 58vw at 88% 92%, ciel at .42 alpha, transparent 68%). They drift (see motion). Never apply filter: blur() to a full-viewport layer. AND THAT IS THE ENTIRE ATMOSPHERE BUDGET: individual sections do NOT get their own radials. Every scene ground on this page is a FLAT tone step from the eleven tokens, and the softness comes from the plate shadows, the cloud seams and the radius scale — not from stacking coloured light in every chapter. Two layers of weather behind flat paper is the world; a page where every section glows is a different one, and it goes muddy at the third scroll.
- Global base: html and body overflow-x clip, scroll-behavior smooth, antialiased. ::selection is accent-wash with ink text. :focus-visible is a 1.5px accent border PLUS box-shadow 0 0 0 4px accent at .18 alpha, with a radius matching the element — a halo, never a hard ring. Skip link that slides from top -4rem to top 1rem over .5s.
- TAP TARGETS: this world overrides the usual minimums — every interactive element is at least 3rem tall, buttons 3.25rem, the submit 3.6rem. The buyer is holding a baby with one arm.
- THE COORDINATED NUMBERS, all derived from the measured announce plus nav stack, never guessed independently: hero min-height calc(100svh - 7.4rem) using svh so mobile browser chrome does not clip it · sticky column offset top 6.2rem · scroll-margin-top 5.2rem on every anchored section · body padding-bottom 5.4rem below 880px so the sticky order bar never covers the footer.

## Hero forms (pick the one the product calls for — each is LOADED, and none of them is a headline beside a photo)
1. LE BERCEAU (default). Grid .94fr 1.06fr — the media column is the WIDE one, because the object is soft and needs air around it. Gap clamp(2rem,5vw,4.5rem), align-items center, padding-block clamp(2rem,5vh,3.5rem) clamp(3.5rem,8vh,5.5rem), min-height calc(100svh - 7.4rem), overflow clip.
COPY COLUMN (max-width 34rem) carries NINE differentiated pieces, not three: the drawn nest mark at 2.2rem with a one-line origin statement beside it (never an eyebrow-plus-rule — that is the marketplace hero and it is banned) · the hand-broken h1 with ONE word in accent-deep · a lede at clamp(1rem,1.3vw,1.12rem)/1.7 capped at 30em · THE SIZE PILL RAIL (four age pills, one pre-checked, and it is a REAL control) · the price row with its currency mark and the was-price if the brief has one · the PAIEMENT À LA LIVRAISON restatement chip · a CTA row with the accent capsule and the WhatsApp capsule · a reassurance line at .82rem naming the delivery window · and two drawn micro-seals inline (the certification and the material).
MEDIA COLUMN IS A CRADLE, NOT A PHOTO SLOT — five layers, and the object is CAPPED at width min(100%,32rem) with real space around it. A full-bleed photo slab here is a failed hero.
- z0 — the floor shadow: an ellipse at width 72%, height 3.5rem, left 50%, bottom -1.2rem, translateX(-50%), background radial-gradient(ellipse at 50% 50%, rgba(ink,.16), transparent 70%), filter none, pointer-events none. Soft objects cast contact shadows; this is what makes the product sit rather than hover.
- z1 — the cradle frame: aspect-ratio 4/5, overflow hidden, border-radius 1.25rem 1.25rem 4.5rem 4.5rem, background the deepest pastel, box-shadow 0 30px 70px -40px rgba(ink,.45), 0 3px 8px -4px rgba(ink,.14).
- z2 — the image inside at object-fit cover, scale 1.02 at rest so the settle has somewhere to go.
- z3 — LE MOBILE: hanging off the top inline-end corner at inset-block-start -2.4rem, inset-inline-end -1.6rem, width 7.6rem, an inline SVG — a horizontal arc bar (1.6px stroke, round caps) with three 1.25px threads of unequal length (2.2rem, 3.4rem, 2.8rem) each ending in a different drawn shape (a cloud, a small star outline, a filled dot in accent). transform-origin: top center. Below 640px it shrinks to 5.4rem at inset -1.4rem / -.8rem.
- z4 — THE MACRO CHIP: an 8.2rem square plate at radius min(var(--radius), 1.15rem) overlapping the frame's bottom inline-start corner by -1.8rem / -1.4rem, holding the cotton-weave macro, with its own 0 14px 30px -20px shadow and a 3px LAIT-LIFT ring (box-shadow inset 0 0 0 3px lait-lift) so it reads as a separate sheet of paper.
Under the media, a caption row: the material name in .8rem rgba(ink,.58) on the start side and PL. 01 in accent-deep on the end side.
THE HERO TERMINATES IN LA BARRE DE CONFIANCE, never in whitespace: a full-bleed LAIT-DEEP strip with a stitched rule on top, holding four drawn micro-seals in a flex row (livraison · paiement à la livraison · échange taille · un vrai numéro de téléphone), each an 1.9rem inline SVG at 1.5px stroke beside two lines of .72rem/+.12em, gap 2.2rem, padding-block 1.15rem. Below 640px it becomes a 2x2 grid at .68rem.
2. LA COUVERTURE (single column — best for phone-first merchants, one hero object, and RTL pages). Copy centred at max-width 44rem with the same nine pieces; then the object centred at min(100%,30rem) in the cradle frame with the mobile and the macro chip; then the size rail full-bleed as a scroll-snap row; then the confidence bar. Centring is permitted HERE and in exactly two other places on the page (the comptine plate and the footer monument) — nowhere else.
3. LES DEUX BERCEAUX (for a shop with a small range). Grid 1.02fr .98fr with the copy on the start side; the media column holds TWO cradle frames staggered — a tall 4/5 lead frame, and a 1/1 second frame offset by margin-top 3.4rem and margin-inline-start -2.2rem at radius 1.15rem 1.15rem 3rem 3rem, each with its own size pill chip sitting on its bottom edge. The mobile hangs off the lead frame only. The macro chip is dropped here — three overlapping objects in one column is too busy for this world.

IF IMAGE GENERATION FAILS, OR THE BRIEF CARRIES NO PHOTOGRAPH: no section is deleted and no grey box is ever drawn. A cradle frame keeps its 1.25rem 1.25rem 4.5rem 4.5rem shape and its two-layer shadow, takes the deepest pastel as its fill, and carries the drawn NEST MARK at 42 percent of its width in rgba(ink,.10), with the caption row and its PL. numeral intact. A macro plate becomes a pastel plate at the same radius holding ONE drawn care symbol or seal at 3.2rem in rgba(ink,.55) with its stitched rule and caption unchanged. The confidence bar, the seals, the size pills, the care table, the ledger and the entire order chapter are drawn, typeset and fully functional without a single photograph — this world can ship on ink and paper alone and must still look considered.

## Section seams (Nid's own vocabulary — every boundary uses one, never the same twice in a row; use at least five of the seven)
1. LE NUAGE (the signature). An inline SVG placed at the TOP of the incoming section: width 100%, height clamp(2.4rem,4.6vw,4.2rem), display block, preserveAspectRatio="none", viewBox "0 0 1440 96", margin-bottom -1px, fill = the incoming section's ground colour, and pointer-events none. The path is FOUR ARCS OF UNEQUAL RADIUS — roughly 1 : 1.65 : .8 : 1.3 — so it reads as cloud, never as a symmetric sine wave (a symmetric wave is a template freebie and is banned). Build it as: M0,96 the first arc rising to about y=28 at x=250, a shallow dip at x=560, a taller arc peaking near y=14 at x=980, a last low arc into 1440,96 and close. Mirror it with transform: scaleX(-1) on RTL pages so the asymmetry follows the reading direction. Never more than three cloud seams per page — it is a punctuation mark, not a wallpaper.
2. LE PLI (the paper overlap). The incoming chapter's first plate rises into the previous chapter by margin-block-start calc(-1 * clamp(2.2rem,5.5vw,4.5rem)), position relative, z-index 2, with its shadow deepened one notch (0 26px 60px -34px) so the overlap is legible. Requires overflow-x clip on the parent.
3. LE MURMURE (the whisper step). The ground changes by 2 to 4 RGB points and NOTHING else announces the change — no rule, no gap, no heading treatment. Five or six of these across the page. This is how Nid alternates tone without ever striping.
4. LE FIL (the stitched thread). A full-bleed 1.5px dashed rule (dash 6px, gap 7px) in rgba(ink,.18), with a single drawn KNOT — a 7px accent circle with a 1.5px ring — sitting on it at 32 percent of the width. Used once or twice, never as the page's only seam device.
5. LE COUSSIN (the full cushion). An entire chapter becomes ONE giant plate: inset by the inline padding, border-radius min(var(--radius), 2.6rem), background a pastel, box-shadow 0 40px 90px -60px rgba(ink,.4), padding-block clamp(3.5rem,8vh,6rem). The order chapter is almost always a coussin. Maximum two per page.
6. LA RESPIRATION (the breath). One chapter with no heading, no eyebrow, no CTA: a full-bleed texture macro at height min(70vh,40rem) with LE NUAGE on both edges and one soft line of voice over it on a scrim of linear-gradient(to top, rgba(ink,.42), rgba(ink,.02) 55%). A generic builder puts a headline and three cards here. Do not.
7. LES FILS SUSPENDUS (used once). Three drawn threads hang from the bottom edge of a chapter into the next one — 1.25px stroke, unequal lengths of 2.8rem, 4.2rem and 3.4rem, each ending in a small drawn shape (a cloud, a ring, a filled accent dot), static and never rotating, because the page carries exactly ONE mobile and it lives in the hero. The next chapter's first plate is positioned so the longest thread ends just above its top edge.

## Layout physics
- ONE inline-padding token: clamp(1.15rem,4.2vw,4rem). Container max-width 88rem. Section block padding clamp(4.5rem,10vh,7.5rem) — the middle term is vh so the rhythm scales with viewport height.
- MEASURE CAPPED IN EM: body 33em, lede 30em, reassurance line 34em, comptine 20em, plate copy 26em, form sub-copy 30em.
- NO GRID IS 50/50. Skew every two-column grid and argue the direction from content weight: hero .94/1.06 (media wide, it needs air) · story 1.08/.92 (copy wide, media sticky) · care chapter .78/1.22 (the TABLE is the star, the heading column is small) · sizes chapter 1.12/.88 · order chapter .92/1.08 (the FORM is 17 percent wider than the sticky order plate). At least one grid must invert expectation. Column gaps clamp(2.2rem,5.5vw,5rem).
- PLATES, NEVER CARD ROWS. Any group of plates must break the metronome: one oversized cell spanning two columns or two rows, at least two different radii in the group, and vertical stagger — apply margin-block-start of 2.2rem to the second child and 1.1rem to the fourth so the row never sits on one baseline. Three identical rounded cards in a row is the exact failure this world exists to avoid.
- BENTO FOR THE PRODUCT DETAILS: grid-template-columns repeat(6,1fr) on desktop with cells spanning 4/2, 2/4, 3/3 across three rows; gap clamp(.9rem,2vw,1.4rem). Below 900px it becomes one column with the oversized cell first.
- OVERLAP BUDGET — EXACTLY FIVE elements deliberately break their container across the whole page: the mobile at -2.4rem, the macro chip at -1.8rem, one PLI plate, one size pill straddling a frame's bottom edge at translateY(50%), and the sticky order plate's price chip. More than five and the page loses its calm. Safe only because overflow: clip sits on every containing section plus html and body.
- THE CARE TABLE is a real table element, not a grid of divs, with a caption, th scope=row and proper semantics. Rows: grid-template-columns 3.2rem 1fr auto, gap 1.1rem, align-items center, padding-block 1.05rem, separated by 1.5px dashed rgba(ink,.16). No zebra striping, no borders on the outside, no header background.
- ZERO-ROW-GAP SIZE LEDGER: the age/height/weight table as a definition list at gap 0 clamp(1.5rem,4vw,3rem), rows separated by stitched rules, each row a space-between flex — the age term in display 700 at 1.15rem tabular-nums on the start side, the value in body 500 on the end side. Below 600px the value drops under the term.
- IMAGE OVERSCAN FUNDS MOTION: any parallaxed image is inset-block-start -10% at height 120% inside an overflow hidden parent, so travel never exposes an edge.
- OVERLAY CONTENT OBEYS THE GRID: text over a macro carries the same container class as everything else and sits at bottom clamp(2rem,7vh,4.5rem).
- RESPONSIVE COLLAPSE: below 1024px every two-column grid becomes 1fr and sticky becomes static; the hero media narrows to min(100%,26rem); below 640px the size pill rail becomes a horizontal scroll rail with scroll-snap-type x mandatory, scroll-padding-inline the page pad, and a soft LAIT fade mask on the end edge — never a carousel with dots.

## Motion identity (GSAP 3 + ScrollTrigger via CDN; Lenis optional — if used, expose it as window.__lenis)
THE SAFETY CONTRACT COMES FIRST AND IS NON-NEGOTIABLE. Compute one flag: reduced = matchMedia("(prefers-reduced-motion: reduce)").matches, hasGsap = typeof window.gsap !== "undefined", animate = hasGsap && !reduced. EVERY hidden initial state is set by gsap.set() INSIDE the animate branch. Never author opacity 0, visibility hidden or a blur filter for an animated element in CSS. If the CDN fails, the page is fully visible and every conversion element still works. Add a prefers-reduced-motion block that, beyond the blanket .01ms override, sets the mobile rotation to none, the cloud drift to none and any marquee to animation none / width auto.

LULLABY TIMING — this world OVERRIDES the global bands, and the override is the concept: NOTHING ON THIS PAGE IS SHORTER THAN .5 SECONDS. Not a hover, not a focus ring, not a tooltip.
- Interaction feedback .55-.7s (global says .25-.45s — overridden).
- Component state .7-.9s.
- Entrances and reveals 1.15-1.6s.
- Image settles 2.2s.
- Ambient loops 4.6s, 5.2s, 9.4s and 11.8s — four periods, and NO ONE OF THEM IS AN INTEGER MULTIPLE OF ANOTHER, so the loops never phase-lock into a mechanical pulse. That detail is the difference between a nursery and a screensaver. (Four periods, three loops: the drift is one loop driven by two counter-phased layers at 11.8s and 9.4s.)
- Marquee, if any, 42s.
Eases: gsap.defaults({ease:"power1.out", duration:1.3}). power1.out for entrances (power3 has too much snap for this world) · sine.inOut for every loop · power2.out for settles and swaps · none for scrub. BOUNCE, ELASTIC, BACK and any overshoot are banned — a page for newborns does not spring.

The mandatory motion set:
1. LE LEVER — the entrance verb. This world has NO masked line rises (they have a hard cut edge) and NO clip-path wipes. Instead: gsap.set(el,{autoAlpha:0, y:18, filter:"blur(5px)"}) then .to({autoAlpha:1, y:0, filter:"blur(0px)", duration:1.25, stagger:.12, clearProps:"filter"}). Apply it to headline line spans, plate groups, seals, size pills — roughly sixteen reveal targets with ScrollTrigger start "top 88%", once true. THE clearProps IS LOAD-BEARING, not tidiness: a filter left declared on sixteen elements keeps sixteen compositing layers alive for the rest of the session, and this world already pays for two drifting radials and three loops.
2. HERO ENTRANCE — one timeline, overlapping absolute positions, complete in about 2.2s. Set: copy blocks autoAlpha 0, y 22, blur 5 · the cradle frame autoAlpha 0, y 34, scale .985 · the frame image scale 1.09 · the mobile autoAlpha 0, y -18, rotation -6 · the macro chip and the confidence bar autoAlpha 0, y 14. Then tl.to(copy,{autoAlpha:1,y:0,filter:"blur(0px)",duration:1.3,stagger:.11},.15) .to(frame,{autoAlpha:1,y:0,scale:1,duration:1.5},.28) .to(img,{scale:1,duration:2.2,ease:"power2.out"},.28) .to(mobile,{autoAlpha:1,y:0,rotation:-2.4,duration:1.4,ease:"power2.out"},.85) .to(furniture,{autoAlpha:1,y:0,duration:1,stagger:.12},1.25) — and the mobile's infinite rock starts onComplete of that tween, from where it landed.
3. LE MOBILE — the one rotation on the page: gsap.fromTo(mobile,{rotation:-2.4},{rotation:2.4, transformOrigin:"top center", duration:5.2, ease:"sine.inOut", yoyo:true, repeat:-1}). Its three suspended shapes each get their own micro-rock at 3.6s, 4.4s and 4.9s with rotation amplitudes 4, 3 and 5 degrees and transform-origin top center — different durations so they drift in and out of phase forever. This is the single most alive detail in the world and it costs eight lines.
4. LA DÉRIVE — the cloud drift: the two fixed weather radials tween on x and y only (never on width or filter) — gsap.to(cloudA,{xPercent:3, yPercent:-2.5, duration:11.8, ease:"sine.inOut", yoyo:true, repeat:-1}) and cloudB with 9.4s at the opposite sign.
5. LE FLOTTEMENT — the hero object breathes: y -6 over 4.6s sine.inOut yoyo repeat -1 on the cradle frame, with the floor-shadow ellipse counter-animating scaleX .96 and opacity .8 on the same timeline so the contact shadow tightens as the object rises. That coupling is what sells the float.
THREE ambient loops is this world's ceiling and its floor: the mobile, the drift and the float. A fourth is banned. Counting is unambiguous: the mobile's three suspended-shape micro-rocks belong to the mobile, and the drift's two radial layers belong to the drift — neither buys you another loop.
6. IMAGE ARRIVALS — LE FONDU, never a wipe: the image starts at scale 1.06, autoAlpha 0, blur(8px) and goes to scale 1, autoAlpha 1, blur(0) over 1.8s power2.out while its plate scales .985 to 1 over 1.4s. start "top 86%", once true, then clearProps on filter.
7. THE ONE SCRUBBED OR PINNED MOMENT (desktop only, and it must be diegetic) — LA CROISSANCE: pin the sizes chapter with end "+=120%", scrub .8, snap 1/(n-1). As the scroll advances, the active size pill changes (accent-wash fill, 1.5px accent border, scale 1.03 over .6s), the age ledger row highlights, and the product image cross-fades over .9s between the brief's images. The page literally grows the baby as you scroll. If the brief has only one product image, fall back to the simpler scrub: the RESPIRATION macro at yPercent -6 to 6, ease none, scrub true, funded by the 120 percent overscan. Never both; exactly one scrubbed moment per page.
8. NUMBER BEHAVIOUR — prices and totals do NOT count up in this world (a spinning price reads as a slot machine). They SOFT SWAP: the old value leaves opacity 1 to 0 with y -6 and blur 3 over .5s while the new value arrives from y 8, blur 3, opacity 0 over .6s with a .12s overlap. Stat numerals in an editorial context MAY count up over 1.6s power2.out with a 4000ms setTimeout fallback that paints the final value in case the trigger never fires on a deep-linked load.

MICRO-INTERACTION KIT (all CSS, all inside the lullaby bands):
- Capsule button: transform scale(1.015) and box-shadow deepening over .6s; the arrow or drawn glyph inside moves translateX(4px) on its OWN .55s transition — two transitions, not one.
- Plate hover (only on plates that are links): translateY(-3px) with the shadow growing to 0 26px 55px -30px over .7s.
- Size pill: :has(input:checked) gives accent-wash background, 1.5px accent border, and the numeral goes to accent-deep, all over .6s; a drawn check appears as an SVG path with stroke-dashoffset going to 0 over .55s. Unchecked pills dim to opacity .78 over .6s when any sibling is checked — the group tells you what you chose.
- Inputs on focus change FOUR properties over .55s: border-color to accent, box-shadow to the 4px accent halo, background to lait-lift, and the label above it to accent-deep.
- Validation entrance: opacity 0 and y -3 to visible over .55s, with min-height 1.2em reserved so nothing reflows, aria-live polite.
- Accordion: grid-template-rows 0fr to 1fr over .7s with an overflow hidden inner. Its icon is two 1.5px round-capped pseudo bars; the vertical one rotates 90deg to 0 over .6s.
- The stitched rules on hover of their section do NOT animate. Some things stay still.

## Components
- BUTTONS are capsules only at border-radius var(--radius) (:root sets --radius: 999px), min-height 3.25rem, padding 1.05em 1.9em, display face 600 at .98rem, letter-spacing .008em, inline-flex with gap .6em. PRIMARY: accent fill, LAIT text, box-shadow 0 12px 26px -16px accent at .75 alpha — a coloured shadow, tinted with the button's own hue, never black. Hover goes accent-deep with scale 1.015 over .6s. SECONDARY: lait-lift fill, 1.5px solid accent at .35 alpha, accent-deep text; hover fills accent-wash. QUIET LINK: accent-deep text with a 2px DOTTED underline at text-underline-offset .28em (a stitched underline, on brand), the dots turning solid on hover over .6s. Disabled at opacity .45, no lift, cursor not-allowed. There is never a full-width solid rectangle button on a desktop viewport; on mobile the submit and the sticky CTA are full-width CAPSULES.
- SHADOWS: always two-layer, always tinted with the ink or the accent hue, never pure black, never with a positive spread. The vocabulary is exactly four: plate 0 18px 40px -28px + 0 2px 5px -2px · grande plaque 0 26px 60px -34px + 0 3px 7px -3px · frame 0 30px 70px -40px + 0 3px 8px -4px · coloured button 0 12px 26px -16px. Nothing else.
- INPUTS ARE FILLED AND ROUNDED, and this is deliberate: background lait-lift, border 1.5px solid rgba(ink,.14), border-radius min(var(--radius), 1rem), padding 1.05em 1.15rem, font-size 1.05rem in the body face, min-height 3.4rem, color ink. LABELS ARE BIG AND SENTENCE CASE — .95rem, weight 600, full ink, margin-bottom .5rem. This world overrides the tiny-uppercase-label convention: a tired parent on a phone reads labels, not micro-caps. Under every field, the reassurance line at .82rem in rgba(ink,.62). Placeholders are real examples from the brief's market, never instructions.
- SIZE / AGE PILL (the signature control): a fieldset of radio inputs visually hidden, each label a pill at min-width 5.6rem, padding .85rem 1.2rem, radius var(--radius), background lait-lift, border 1.5px rgba(ink,.12), display grid with justify-items center and gap .15rem. Inside: the numeral line in display 700 at clamp(1.5rem,2.4vw,2.05rem) with tabular-nums and line-height 1 (0-3 · 3-6 · 6-12 · 12-24) and under it the unit at .68rem/+.14em in rgba(ink,.55) (mois · cm · kg). Checked state as specified in the motion kit. The rail is a flex row with gap .7rem, wrapping on tablet, scroll-snapping below 640px.
- THE CARE TABLE (signature): five rows maximum, from brief facts only. Left cell: a drawn SVG at 2.2rem, viewBox 0 0 24 24, fill none, stroke rgba(ink,.7), stroke-width 1.5, round caps and joins. The five drawings, exactly: LAVAGE — a tub outline (a trapezoid with a curved rim) with a small wave inside and the temperature numeral set in the display face at 8.5px in accent-deep · JAVEL — an equilateral triangle with a diagonal cross when bleach is forbidden · SÉCHAGE — a square containing a circle, with one filled dot inside for low heat · REPASSAGE — an iron silhouette with one or two dots on its face · PRESSING — a circle, empty or with a diagonal cross. Middle cell: the instruction in body at 1rem with the numeral promoted. End cell: the short value in micro-caps. If the brief carries no care data, the same ruled table becomes a MATERIALS table (matière, grammage, origine, taille, poids) with the nest, boll and shield drawings instead. Never invent a wash temperature.
- LES SCEAUX (the safety seals): each seal is a 4.4rem rounded-square plate at radius min(var(--radius), 1.15rem), background lait-lift, box-shadow inset 0 0 0 1.5px rgba(ink,.12), containing a drawn SVG at viewBox 0 0 40 40, fill none, stroke accent or rgba(ink,.68), stroke-width 1.5, round caps. The six drawings to choose from: LE NID (two nested arcs with three resting dots) · LA FLEUR DE COTON (four rounded petals around a small centre with a stem) · LE BOUCLIER DOUX (a rounded shield with a small check inside) · L'ÂGE (a rounded square with a numeral drawn inside at 11px display 700 — the minimum age from the brief) · LA GOUTTE LAVÉE (a teardrop over a wave) · LE FIL ET L'AIGUILLE (a needle with a looping thread). Under each seal: the credential name in body 600 at .78rem in full ink, then the reference line in .7rem/+.12em micro-caps at rgba(ink,.55), both capped at 10em. THE RULE THAT MATTERS: these carry ONLY facts the brief states. A norm number, a certification, a laboratory, a country of origin — quoted exactly. If the brief has none, the seals carry the merchant's OWN promises worded as promises ("échange taille sous 7 jours", "on répond au téléphone avant 20h"), which is honest and just as reassuring. Inventing a certification is the worst failure available in this world.
- MACRO PLATES: aspect-ratio 1/1 or 4/3, radius min(var(--radius), 1.15rem), overflow hidden, the image at scale 1.02 inside. Under it a stitched rule, then a two-column caption row: the descriptive text at .8rem in rgba(ink,.58) on the start side and PL. 01 in accent-deep at .72rem/+.14em on the end side. Three to five per page, at two different sizes.
- ACCORDION (the parents' questions): plate-shaped items at radius min(var(--radius), 1.15rem) with gap .8rem between them — not a hairline list. The question is a full-width flex button at border-radius var(--radius) in display 600 at clamp(1.02rem,1.6vw,1.2rem), padding 1.25rem 1.35rem, min-height 3.4rem. Single-open behaviour, aria-expanded maintained, role region plus aria-labelledby on the panels. Answers are written in the reassurance voice, and the first question is always the one about sizing.
- FOOTER: a LE NUAGE seam into the deepest pastel, a newsletter row (grid 1fr 1fr collapsing to 1fr) whose input and capsule are on the same line, then THE MONUMENT — the shop name at clamp(3.2rem,14vw,11rem), line-height .9, weight 700, FILLED in rgba(ink,.07), user-select none, aria-hidden, centred, with the drawn nest mark at 3rem sitting above it. Then a stitched rule and a row of links at .88rem in rgba(ink,.66), the phone number promoted with the display face, and a credit line at .8rem.
- CRAFT DETAILS THAT SIGNAL INTENT: explicit width and height on every image; fetchpriority high on the hero image and loading lazy elsewhere; descriptive alt on content images, empty alt plus aria-hidden on decorative duplicates and every drawn ornament; aria-live polite on validation and status text; an output element for the stepper; a real fieldset and legend around the size group; a skip link; an inline-SVG data-URI favicon of the nest mark; a theme-color meta matching LAIT; and color-scheme: light on :root (this world is light-only and says so).

## Conversion objects (this world SELLS, and it sells by removing fear — these are its money components)
- THE PRICE BLOCK: a baseline-aligned flex row at gap .85rem, flex-wrap wrap. The price in display 700 at clamp(2rem,3.5vw,2.9rem), tabular-nums, with THIN-SPACE THOUSANDS using U+202F (3 500, never 3,500 and never 3500). The currency mark — DZD on a French page, دج on an Arabic one, written exactly as the brief writes it — is a SIBLING SPAN ON THE BASELINE at .36em, +.16em tracking, weight 600, rgba(ink,.58), margin-inline-start .45em: never a superscript, which reads clinical, and never in the accent, which makes the price shout. A was-price, only if the brief states one, at 1.05rem in rgba(ink,.5) with line-through, decoration-color accent at 1.5px. Any promotion is stated IN WORDS in an accent-deep micro-caps line ("prix de la première série"), never as a red percentage badge.
- THE RESTATEMENT CHIP — the most Nid object on the page. A chip (radius var(--radius), background accent-wash, padding .6rem .95rem, gap .6rem) holding a drawn 1.5px SVG of a hand under a box and the sentence "Paiement à la livraison — vous payez au livreur, rien maintenant." in body 500 at .88rem. It appears FIVE TIMES: under the hero price, in the confidence bar, at the head of the order chapter, directly above the submit button, and inside the success panel. Repetition is the reassurance. A parent who scrolls past it four times stops worrying about it.
- THE ORDER CHAPTER is a COUSSIN: the whole chapter is one 2.6rem plate in the deepest pastel, entered through a cloud seam, with scroll-margin-top 5.2rem. Grid .92fr 1.08fr — the FORM is the wide column. The narrow column holds the STICKY ORDER PLATE at top 6.2rem: the cradle-framed product image, the price block, the chosen size echoed back as a pill, three drawn seals stacked with stitched rules between them, and the delivery window as a fact.
- THE FORM IS THREE PLATES, NOT A CARD AND NOT A NUMBERED WIZARD. Three lait-lift plates at radius min(var(--radius), 1.15rem), gap 1.2rem, each opened by a sentence-case display 600 heading at 1.25rem and closed by one reassurance line: PLATE ONE — "Comment on vous appelle" (nom, téléphone) · PLATE TWO — "Où on livre" (wilaya, adresse) · PLATE THREE — "Ce que vous recevez" (taille, quantité, total, submit). Step numerals are deliberately absent: a numbered wizard makes a three-field form feel like an administrative procedure.
  - nom complet: autocomplete name, required, minlength 3. Reassurance: the name the delivery driver will ask for at the door.
  - téléphone: type tel, inputmode tel, autocomplete tel, required, a real pattern for a ten-digit Algerian mobile (a leading zero, then 5, 6 or 7, then eight digits). Set font-size 1.15rem, letter-spacing .04em and tabular-nums on this field — it is the most important input on the page and it should look like it. Live-format as the user types into 0X XX XX XX XX groups. On RTL pages the input itself carries dir="ltr" so the number never reverses. Reassurance: one call, to confirm, never before 9h.
  - wilaya: a NATIVE select styled identically to the inputs (appearance none, a drawn 1.5px chevron with round caps at the inline end, rotating 180deg over .6s on focus), options ONLY from the brief's delivery zones. Under it a delivery-fee line at .82rem that soft-swaps over .55s whenever the selection changes, and the total recomputes with it.
  - adresse: a textarea at 2 rows on the same filled style, auto-growing to 4 rows, radius min(var(--radius), 1rem). Reassurance asks for the landmark a driver would actually use.
  - taille: the size pill group, PRE-CHECKED from the hero's choice — this is the cross-section state link, and it must be real: choosing 6-12m in the hero rewrites the order form and the sticky bar, and the choice is persisted in localStorage.
  - quantité: a stepper, never a number input — an inline-flex group at border-radius var(--radius) with 3rem true-circle buttons at 50% (1.5px border, filling accent-wash on hover over .6s) and an output element at min-width 2.6rem in display 700 at 1.3rem. It has a cap, and THE CAP IS GIVEN A REASON in the hint.
- THE FOOT OF THE FORM: a stitched rule, then a space-between row at padding-block-start 1.5rem — a .74rem/+.14em micro-caps label over the live TOTAL in display 700 at 2rem with tabular-nums, thin-space thousands and the soft swap on every change — beside the submit. The submit is a full-width capsule at min-height 3.6rem on mobile, auto-width on desktop. The restatement chip sits directly above it. Below it, one line naming what happens in the next hour.
- VALIDATION IS BLUR-GATED: keep a touched map so a message appears only after a field's first blur, never while somebody is still typing into a fresh field. Messages are gentle full sentences in the argile mix of var(--primary) and var(--foreground) at .82rem, min-height 1.2em reserved, aria-live polite. The field's border takes that same mix at 1.5px over .55s — no shake, no flash, no red fill.
- SUBMIT AND THE SOFT SUCCESS STATE WITH NEXT STEPS. A deliberate 900ms pending state in which the label becomes a present-tense human sentence ("On note votre commande…"). Then the form LEAVES over .6s to opacity 0, blur(6px), y -8, visibility 0s .6s, and the success panel — absolutely positioned over the same box so nothing jumps — ARRIVES with transition-delay .3s over 1.1s on opacity, blur 6 to 0 and y 12 to 0, so focus never lands on a hidden element. Inside the panel, in this order: the drawn NEST in SVG at 7.5rem (the two nested arcs given pathLength 100, stroke-dasharray 101, stroke-dashoffset 101 to 0 over 1.9s power1.out with a .4s delay, stroke 1.6px accent) with the order number at 2.1rem display 700 sitting inside it · a line echoing the buyer's own name, size, wilaya and total · THE NEXT STEPS as a three-row stitched list, each row a drawn 1.9rem icon plus a sentence: (1) the call to confirm, with the window from the brief, (2) the parcel leaving, with the delivery window, (3) paying the driver, with the exact total · the restatement chip · and the WhatsApp capsule for anything else. Then the page SETTLES: slow the mobile to an 8s cycle at 1.2 degrees of amplitude. No confetti, no popping check-mark, no sound, no redirect. And at the moment validation passes — as the panel begins to arrive — the page passes the order along by dispatching the wandit:lead CustomEvent on document with the parent's fields flat in detail (name, phone as typed, wilaya, commune, plus taille and quantité), while one off-canvas decoy input marked data-wandit-hp rests in the form, never read by the page's own script.
- PERSIST IT: store the order and the chosen size in localStorage; on return, restore the size selection everywhere and paint the success panel INSTANTLY with no animation, so a returning parent is never asked to order twice.
- STICKY MOBILE ORDER BAR (below 880px): position fixed, bottom 0, inset-inline 0, z-index 95, min-height 4.6rem, padding .75rem 1rem calc(.75rem + env(safe-area-inset-bottom)), background rgba(lait,.92), backdrop-filter blur(14px), border-radius 1.4rem 1.4rem 0 0, box-shadow 0 -16px 36px -26px rgba(ink,.45), grid auto 1fr, gap .9rem, align-items center. Start side: the price at 1.15rem display 700 with tabular-nums and the .36em currency mark, and above it a .66rem line reading paiement à la livraison. End side: the accent capsule at min-height 3rem. It enters on a ScrollTrigger at the hero's bottom, translateY(112%) to 0 over .8s with the shared ease, and a second ScrollTrigger on the order chapter sends it back out while the form is on screen so it never covers a field.
- WHATSAPP IS THE SECOND PATH, STYLED TO THE WORLD: a lait-lift capsule with a 1.5px accent-at-.4 border and accent-deep text, carrying a HAND-DRAWN inline SVG handset-in-bubble at 1.1rem, stroke 1.5px, round caps, fill none. Never the filled green mark, never a floating green circle, never a bouncing bubble. Hover fills accent-wash over .6s. It appears exactly twice on the page — beside the hero's primary CTA and at the foot of the order chapter — plus once inside the success panel, with a pre-filled message built only from brief facts (the product name, the chosen size).
- TRUST STRIP WITH DRAWN SVG ICONS (four, from brief facts only): the confidence bar under the hero, repeated once more before the footer with different wording. Each item is a 1.9rem drawn line icon (the delivery van drawn as a rounded box on two circles · the hand-under-box for cash on delivery · two arrows curving into a soft loop for the exchange · a handset for the human line) plus two lines at .72rem/+.12em capped at 9em. Separated by gutter space, never by borders.
- CTAs anywhere else on the page: the accent capsule or the stitched-underline text link. Nothing else is ever a call to action.

## Editorial furniture (REQUIRED — this is Nid's voice, and it invents no business fact)
- LA NOTE: the reassurance line, at least twelve of them, under fields, prices, size choices, CTAs, plates and the care table. .82rem, rgba(ink,.62), max-width 34em. Each one answers a question the parent did not ask out loud.
- PL. 01 / PL. 02: plate numerals in accent-deep on every macro caption row.
- LA COMPTINE: one two-line couplet on a bare pastel plate — display 400 at clamp(1.35rem,2.3vw,1.85rem), line-height 1.55, max-width 20em, centred, no heading, no CTA, no explanation. It is one of only three centred moments on the page.
- LE CARNET DE TAILLES: the age / height / weight ledger with promoted numerals, filled strictly from the brief's size chart. If the brief has no chart, this becomes the composition ledger (matière, grammage, entretien, origine) with the same typesetting.
- LA FICHE D'ENTRETIEN: the care table with its drawn symbols and a footnote naming who tested the wash.
- LES SCEAUX: the drawn credential seals with their reference lines.
- LE MOT DE L'ATELIER: a short signed paragraph on a plate — three sentences, written in the first person, ending on a small human promise. Facts from the brief only; the voice is the merchant's.
- Micro-caps everywhere are .72rem at +.12em to +.18em, sentence case beyond three words.
- These devices invent nothing. They are TYPESETTING. Fill them from the brief, and if a fact is missing, drop the device rather than invent it.

## Global rules this world overrides (declare each in an HTML comment near the relevant code, then obey it)
1. MID-RADIUS IS NATIVE. The global caution about 12-16px radius does not apply: this world lives at 14-20px. What replaces it is the token-borne control radius plus capped plates — chip, pill and button var(--radius); plate min(var(--radius), 1.15rem); grande plaque min(var(--radius), 1.25rem); coussin min(var(--radius), 2.6rem); sculpted cradle 1.25rem/4.5rem. A single uniform radius everywhere remains banned.
2. CARD SHADOWS ARE MANDATORY, not banned — but always two-layer, always hue-tinted, never black, never with a positive spread.
3. Masked line rises (yPercent 112 in an overflow-hidden wrapper) are REPLACED by LE LEVER, the blur-and-lift. This world has no hard moving edges anywhere.
4. Clip-path image wipes are REPLACED by LE FONDU. Same reason.
5. Interaction feedback runs .55-.7s instead of .25-.45s, and NOTHING on the page runs under .5s.
6. Ambient loops run 4.6s, 5.2s, 9.4s and 11.8s instead of 3-4s, and THREE loops are allowed where most worlds allow one — because a nursery is never perfectly still.
7. Count-up on prices and totals is replaced by the SOFT SWAP.
8. Form labels are large and sentence case, not uppercase micro-caps.
9. Default GSAP ease is power1.out at 1.3s, not power3.out at 1.1s.
10. There is no dark chapter and no inverted footer in this world; weight comes from pastel and radius, never from darkness.
11. The hero entrance runs about 2.2s and image arrivals 1.8s, against the global entrance ceiling of about 1.6s — at lullaby speed a 1.6s arrival is a rush. Everything else stays inside the bands declared above.

## Arabic and RTL adaptation
Set dir="rtl" and lang="ar" on the html element and build the whole chassis on LOGICAL properties from the start — padding-inline, margin-inline, inset-inline, border-inline-start, text-align start — so the mirror is free rather than a rewrite. Specifics for this world: the cloud seam SVG gets transform: scaleX(-1) so its asymmetry still leads the eye in the reading direction · LE MOBILE hangs from the top inline-START corner instead of the inline-end · the size pill rail scrolls from the start edge and its fade mask flips · the telephone input, the price numerals and the total carry dir="ltr" with unicode-bidi isolate so digits never reverse, while their labels stay RTL · the currency mark sits after the numeral in the reading direction with the same .36em treatment · Arabic has no italic, so any accented fragment is carried by ACCENT-DEEP plus weight 700, never by a slant · the Arabic face runs at +8 percent size and 1.85 line-height versus the Latin body · and micro-caps letter-spacing is set to 0 for Arabic, where tracking breaks joined letterforms. The COD form, the wilaya list and the WhatsApp message are written in Arabic; the drawn seals and care symbols are language-independent and stay exactly as drawn.

## Nid ban list (in addition to the global one)
Pure white grounds or pure white text · black or near-black text and black shadows · neutral greys, slates, or any colour that is not a brief hex or an alpha of one · high-saturation candy or primary colours (this is pastel, not a toy aisle) · pink-for-girls / blue-for-boys as the entire palette logic · emoji anywhere, and especially the baby, bottle and heart emoji · cartoon clip-art babies, storks, prams, teddy bears or footprints as icons · stock photography of a laughing family on a white sofa · handwriting, comic or bubble display faces · a sharp corner under .9rem on any panel · one uniform radius applied to everything · three identical rounded cards in a row · icon triads · a dark chapter, an inverted footer or a black slab of any kind · masked line rises, clip-path wipes, or any animation with a hard moving edge · bounce, elastic, back or any overshoot · ANY transition under .5s · count-up on a price · countdown timers, "plus que 2 en stock", red percentage badges, "URGENT" banners · any invented certification, norm number, laboratory, medical or safety claim · a green WhatsApp blob · confetti or a popping check-mark on success · a hero whose media column is a full-bleed photo slab · 50/50 grids · centred body copy beyond the three allowed centred moments · glassmorphism beyond the nav and the sticky bar · a hamburger overlay · a bouncing chevron scroll cue · more than three ambient loops · more than one scrubbed or pinned moment · more than five overlapping elements · any hidden state authored in CSS.

## Intensity
This world fails quietly, which is what makes it dangerous. Every wrong decision is a comfortable default that looks fine on its own: a flat pastel background instead of weather, one uniform radius instead of a scale, a single-layer black shadow instead of two tinted ones, a 250ms hover instead of 600ms, a small uppercase label instead of a big readable one, an emoji instead of a drawn seal, a claim instead of a fact. Any four of those and the page becomes the generic baby-shop template it exists to replace — and it will still look "clean and friendly", which is exactly the trap.

Executed at 100 percent — milk paper with pastel weather drifting behind it, plates laid over cloud seams, a mobile rocking 2.4 degrees forever over a cradle-shaped frame, the cotton photographed close enough to count the threads, age numerals big enough to read across a room and wired to the order form, seals drawn by hand carrying real certifications, a care table typeset like the label sewn into the collar, and a cash-on-delivery form that says four times over that nothing is paid today — it looks like the shop a mother recommends to another mother. Every number above is load-bearing. Softness here is not the absence of decisions; it is fifty of them, taken slowly.`,
	energy: "quiet",
	family: "nid",
	id: "nid",
	industries: [
		"baby",
		"kids",
		"nursery",
		"maternity",
		"toys",
		"childcare",
		"kidswear",
		"fashion",
		"gifts",
		"crafts",
		"education",
		"photography",
		"ecommerce",
	],
	kind: "product",
	mood: ["soft", "reassuring", "tender", "rounded", "careful"],
	name: "Nid",
	preview: {
		ground: "#FBF7F2",
		ink: "#443A38",
		accent: "#F5EFE7",
		fontFamily: "Nunito",
		sampleWord: "Le nid",
	},
	priceFeel: "accessible",
	tagline:
		"Milk-white paper with pastel weather drifting behind it: a little mobile rocking over a cradle-shaped frame, the cotton photographed thread by thread, ages printed big enough to read across the room, safety seals drawn by hand — and an order form that repeats four times that you pay only when the parcel is in your hands.",
};
