import type { DesignWorld } from "./types";

/**
 * NOCTURNE — candlelight fine dining; light used as architecture.
 * One warm near-black ground for the whole page; every scene is defined by
 * WHERE THE LIGHT IS, not by a background block. The doc is appended VERBATIM
 * to the builder system prompt.
 */
export const nocturne: DesignWorld = {
	avoidFor: [
		"kids",
		"toys",
		"gym",
		"fitness",
		"street-food",
		"budget-retail",
		"discount",
		"tech",
		"gadgets",
	],
	doc: `# DESIGN WORLD: NOCTURNE — light as architecture

## Philosophy
This page is a ROOM AFTER DARK, not a website. A dining room at 21h with the overheads off: one warm near-black field from the first pixel to the last, and inside it a handful of amber pools, each placed over something worth seeing — a plate, a poured glass, a line of verse, a name in a reservation book. Nothing here is separated by a coloured block, a card or a border. Things are separated by ILLUMINATION. A scene begins when a light comes up and ends when it goes down. Content does not sit ON this page; it EMERGES FROM it, and returns.
That one decision cascades. Sections cannot paint backgrounds (the boundary would become visible, and this world has none). Contrast cannot be a global choice, because it is a function of distance from the light. Photography cannot be even, because a lit room is 60 percent shadow. Shadows cannot fall in arbitrary directions, because the key has coordinates. Motion cannot snap, because light does not. The luxury here is not restraint but ATMOSPHERE: warm, low, slightly perfumed, certain of itself. Zero restaurant-template energy — no chalkboards, no fake handwriting, no wood textures, no fork-and-knife icons, no Starters/Mains/Desserts card grid, no gold star rows.

## The lighting plan (do this FIRST — before one line of markup)
Write the page's LIGHTING LEDGER before the markup: for every scene, its source, coordinates, size, intensity, temperature. The ledger IS the page's structure. A worked seven-scene example (instantiate for the real story, keep the discipline):
- ARRIVAL (hero) — table spot, 62% 46%, 78vmin by 62vmin, .18, warm.
- THE ROOM — bar glow from the floor of the scene, 50% 92%, 130vmax by 46vmax, .12, warm, cool fill at 8% 18%, 60vmax, .05.
- THE CARTE (showpiece) — five walking spots, one per course, 54vmin, .16, centres at 28% 42% / 66% 38% / 34% 60% / 70% 55% / 48% 46%.
- THE HAND (chef, producer) — the hardest, brightest pool in the page: 34vmin at 28% 38%, .22, cool fill at 88% 74%, .04, so the face is modelled and the room behind goes black.
- THE CELLAR — near-total darkness: 26vmin at 50% 70%, .09. The page's held breath.
- THE INVITATION — the most generous light on the page, because this is the welcome: 96vmax by 60vmax at 50% 30%, .15, no fill.
- EXTINGUISH (footer) — the pool ramps to 0 across the last 30vh. The page ends in darkness; that is the final gesture and it is not negotiable.
THE THREE LAWS, enforced everywhere:
1. ONE KEY PER SCENE. One warm pool carries a scene; a second in the same viewport is a bug, not richness. The only other light is a COOL FILL at 3-6% alpha on the OPPOSITE side of the frame — never a second hue, never on text or borders.
2. NO TWO CONSECUTIVE SCENES SHARE A LIGHT POSITION. After a spot at 28% 42% comes the other half of the frame, or another altitude (a floor-level bar glow after an eye-level spot). The page's rhythm IS the light walking around the room.
3. CONTENT LIVES IN THE LIGHT. A scene's content block sits with its optical centre within 12% of viewport width and height of that scene's pool centre. Move the light, move the type. ONE counterpoint per page is allowed — the hero, where type sits in the dark half and the light falls on the photograph beside it. Elsewhere, text in the shadow is a failure.

## The vibe
An old maître d' who remembers your name and never says so. Copy is short, sensual, specific: ingredients named like places, verbs of service rather than marketing ("on ouvre à 19h", "on verse"), sentences ending in real periods. Numbers are spoken quietly — 22 couverts, service de 19h à 23h30, une cave de 140 références. Nothing shouts a discount. The confidence comes from what is withheld: no wide shot of the room, no staff line-up, no menu dumped as a table. You are shown four things very well and invited to come and see the rest.

## Visual signatures (what makes it instantly recognizable)
- ONE ground colour for the whole document, painted once on body. No section declares a background. The only thing that changes down the page is where the amber is.
- Amber radial pools that BLEED PAST their scene's edges (inset -20vh top and bottom), so lights overlap across boundaries and no section edge is ever visible.
- Photography that exists only where the light falls: full-bleed macro imagery behind a radial mask, so the frame holds real darkness rather than a dark overlay.
- The menu typeset as VERSE — dish names as poem titles, ingredient lines broken into authored 3-6 word lines with a 1.4em runover indent, prices as marginalia in AMBER (var(--primary)), never right-aligned, never with dot leaders, a course-break ornament (hairline plus glyph) between stanzas.
- Serif italics wherever the voice softens — the counter-line, the verse, wine notes, marginalia, the success message. This world is generous with italic where most dark worlds ration it.
- Steam and smoke: 2-3 inline-SVG plumes drifting on 21-29s loops at 3-5% opacity, one of them crossing a scene boundary.
- ONE jewel: the reservation action, the single AMBER-filled object on the page, shaped by var(--radius), haloed and breathing on the candle keyframe. When the nav hides, the jewel detaches and stays. The flame never goes out.

## Color physics (route the brief's palette through the fixed tokens — the physics is law)
FIXED TOKEN MAP — BASE→--background · INK→--foreground · AMBER→--primary · BASE→--primary-foreground · CELLAR→--secondary · TABLE→--accent · ink at 60%→--muted · ink at 12%→--border · 2px→--radius · DISPLAY→--font-heading · BODY→--font-body. These are the only CSS color/type/radius variables: every pole below is a prose role, literal register hexes belong only in these :root values, and every pool, sibling or alpha step is a color-mix(in srgb, var(--foreground) N%, transparent), substituting the mapped fixed token for that pole, or a color-mix between two mapped fixed-token references. Every unmapped role below MUST reuse the nearest mapped token or such a mix; it never gets another custom property or literal. Non-color light-position and pool-geometry properties may keep their own custom properties. Any rgba(POLE, a) notation below is design shorthand for that color-mix, never emitted CSS.
- GROUND: the palette's dark pole, WARMED — never neutral, never black. Enforce R greater than G greater than B by 2-6 points at every step (the #0B0907 / #100C09 / #14100C register). Three grounds 3-6 RGB points apart with named jobs: BASE (the document), CELLAR (darkest; snuff beats and footer), TABLE (highest; only under the showpiece). They change as scrubbed transitions of the body background, never as section fills.
- INK: the palette's light pole warmed to ivory (the #F2E9DC register), in FIVE color-mix steps mapping distance from the light: var(--foreground) at 95% (display inside the pool), 78% (body), 60% (penumbra: captions, marginalia, service lines), 38% (labels outside a pool), 20% (ghost glyphs). Text outside a pool may NEVER use the 95% step — the inverse-square law as a token system.
- AMBER (var(--primary)): exactly ONE warm hue from the brief — candle amber, brass, burnt honey (the #C8933F / #D9A441 / #B8763A register). At least nine jobs: every pool, price marginalia, course glyphs, roman numerals, the jewel, ::selection, the focus glow, the wick cue, the ember underline, allergen superscripts, the service icons. Never body-text colour; never a large flat fill except the jewel and the mobile bar button.
- COOL FILL: use a restrained color-mix between var(--accent) and var(--foreground), ONLY as a radial at 3-6% alpha opposite the key. Do not rotate to a new hue or create another color property. Never text, never a border. A temperature, not a palette colour.
- LINEN: the palette's light pole, warmed, used EXACTLY ONCE (the linen card). A second light surface breaks the room.
- HAIRLINES: ink at .10-.14 for structure, ink at .20 inside a pool (light catches an edge), AMBER (var(--primary)) at .34 for course rules and the jewel ring. Nothing else draws a line.
- GRADIENTS: radials are the structural material, unlimited in the pools. PAINTED linear-gradients are rationed to four jobs — an image's bottom dissolve, the ember underline, the nav's scrolled scrim, the taper rule. A fifth PAINTED one is a bug. Gradients used as mask-image (the hero's radial pool mask, hero form 3's horizontal slot) are not painted and do not count against the four: a mask is geometry, not colour.
- color-scheme:dark on :root; theme-color equals BASE. Never #000 or #fff anywhere — this world tightens the global rule rather than relaxing it. Opaque stops inside mask-image gradients use var(--foreground), never a literal. Nothing that reaches a pixel as ink, ground, border, fill or mask stop bypasses the fixed tokens.
- CONTRAST FLOOR: the 60% foreground mix only at 16px or above (1.5rem if serif); the 38% mix only for uppercase micro-labels at 11px or above, never for a sentence; the 20% mix is decoration and carries aria-hidden. Body copy never drops below the 78% mix.

## Typography system
- THREE roles. DISPLAY: a high-contrast serif with a REAL italic — the Playfair Display / Bodoni Moda / Prata / Cormorant Garamond territory. The brief's face wins, but a true italic is mandatory, because this world italicises constantly. MENU: the same serif at roman, so the page reads as one printed object. MICRO: a quiet grotesk in the Archivo / Space Grotesk / Instrument Sans territory for uppercase labels, prices, form labels and numerals. The grotesk never sets a sentence over eight words; the serif never sets a micro-label.
- DARK-GROUND OPTICAL COMPENSATION (skipping this is why most dark pages look cheap): light type on a dark field BLOOMS — thin strokes smear. So display weight sits at 400-500, never 300, unless the size clears 4rem; large display tracking OPENS +.004 to +.010em instead of going negative; body runs one notch heavier than its light-page equivalent (400 becomes 450-500 where the face allows) and never below 15.5px; -webkit-font-smoothing:antialiased globally. A Didone with extreme stroke contrast is never used below 2.6rem.
- SCALE: micro-labels 10.5-12px uppercase at .20-.30em; body 15.5-17.5px at 1.68; MENU MIDDLE 1.45-1.95rem (this world deliberately USES the middle of the scale — the menu lives there); statement display clamp(2.4rem,5.6vw,4.6rem); hero clamp(2.9rem,7.4vw,6.4rem); closing wordmark clamp(3.4rem,13vw,11rem).
- LINE-HEIGHT falls as size rises: 1.68 body, 1.55 verse, 1.15 dish name, 1.02-1.08 display, .96 wordmark. Display headlines carry max-width in em (8-13em) so every break is AUTHORED — no headline wraps where the browser chooses.
- ITALIC IS A VOICE, NOT AN EMPHASIS. Its jobs: the counter-line under a headline, the ingredient verse, wine notes, the chef's marginalia, the snuff-beat sentence, the success line. Plus, optionally, ONE AMBER (var(--primary)) italic word per headline.
- PRICES: micro grotesk, .72rem, .10em tracking, var(--primary), tabular-nums, thin-space thousands (3 500 DZD with a real narrow no-break space), currency at .62em and opacity .7 after a hair space, no decimals ever. Never bold, never larger than the dish name.
- Micro-labels recur but are NEVER a hero's opening element (global rule, upheld): uppercase, 11px, .24em, color-mix(in srgb, var(--foreground) 38%, transparent), gaining a 14px var(--primary) tick rule inside a lit scene.
- tabular-nums on hours, covers, vintages, phones, prices, course indices. Roman numerals for courses; Western Arabic digits elsewhere.

## Page chassis
- ONE gutter token: clamp(20px,5vw,88px) — page padding AND the anchor for every absolutely positioned ornament. Canvas caps at 1560px, but columns stay narrow: 640px menu, 34-46ch prose, 300-360px pairing panel.
- html,body{overflow-x:clip} is mandatory (pools bleed, plumes overflow, the linen card is rotated). Body carries the BASE ground and nothing else. scroll-behavior:smooth, scroll-padding-top 5.5rem.
- NAV: fixed, transparent over the hero, no bar, no border. Wordmark left in display serif at 1.05rem, .16em tracking, one var(--primary) period; 3-4 centre links in micro grotesk 11px .18em (below 900px they collapse behind a two-bar burger crossing into an X over .45s); the RESERVATION JEWEL right. Past 40px it gains .is-lit — rgba(BASE,.72), backdrop-filter blur(18px) saturate(1.08), bottom hairline at ink .10. Past 420px it hides on scroll-down (translateY(-104%), .5s cubic-bezier(.22,.61,.36,1)) and returns on scroll-up via ScrollTrigger self.direction, suppressed while the menu overlay is open.
- THE JEWEL DETACHES: when the nav hides, the pill stays — on desktop re-anchored to position:fixed, bottom clamp(18px,3vh,28px), right var(--gutter), z-index 90, same halo; on phones its job passes to the candle bar. The reservation affordance is never off screen.
- THE SPINE IS A SERVICE, named in the page: arrival, the room, the carte (showpiece), the hand, the cellar or bar, the invitation, extinguish. Scenes carry a micro-label with a roman numeral; TWO of the seven are SHORT (42-56vh) because a service has pauses.
- Vertical rhythm is always a clamp whose middle term is vh: clamp(5.5rem,13vh,9rem) standard, clamp(3rem,7vh,4.5rem) for a snuff beat, clamp(7rem,17vh,12rem) for the invitation, 0 for anything welded to a full-bleed image.
- TWO fixed overlays only: grain at z-index 55 (inline SVG feTurbulence fractalNoise baseFrequency .85, numOctaves 2, tiled 240px, opacity .045, inset -40px, pointer-events none) and the plumes at z-index 3 behind content. No custom cursor — the room is not a machine.

## Hero forms (pick by the photography the brief supports — never the marketplace split)
1. THE TABLE SPOT (default, and the world's signature). min-height 100svh, position relative, overflow hidden, five layers:
   (a) the BASE ground. (b) the photograph, absolute inset 0, object-fit cover, object-position chosen consciously, overscanned 112%, and MASKED: mask-image (with the -webkit- twin) radial-gradient(ellipse var(--pool-r) calc(var(--pool-r) * .8) at 62% 46%, var(--foreground) 0%, var(--foreground) 38%, transparent 76%). The photograph exists only inside the pool; everywhere else the frame is real darkness. This one declaration IS the hero. (c) the amber pool above it as an ::after at mix-blend-mode:screen — color-mix(in srgb, var(--primary) 16%, transparent), then a 6% mix at 34%, transparent at 68%. (d) the UI layer at z-index 3: flex column, min-height 100svh, padding 6rem var(--gutter) 2.2rem, justify-content:space-between. (e) grain above all.
   The display line sits in the DARK half — the ONE authorised counterpoint: clamp(2.9rem,7.4vw,6.4rem), line-height 1.02, max-width 11em, color-mix(in srgb, var(--foreground) 95%, transparent), a 1px var(--primary) underline beneath one italic word. Under it a serif-italic counter-line at 1.05-1.25rem, max-width 30ch, color-mix(in srgb, var(--foreground) 60%, transparent). At the floor, a hairline-topped DATELINE row in micro grotesk: address, hours, covers, phone — a colophon, not a contact section.
   NO CTA BUTTON IN THE HERO; the action is the nav jewel. The only affordance is the WICK: a 1px vertical var(--primary) rule 54px tall with a 3px var(--primary) dot descending it on a 2.6s cubic-bezier(.4,0,.2,1) loop, fading over the last 18% of travel.
2. CANDLE-LIT COLD OPEN (no photography). Pure ground, one 46vmin pool at 50% 58%, a single serif ITALIC sentence at clamp(2.4rem,6vw,5.2rem), line-height 1.06, max-width 13em inside the pool, entering in three authored line-groups, one plume crossing over 26s, the dateline at the floor. Use when the brief has no strong imagery — it outclasses any stock photograph.
3. THE PASS (two bands). A 38vh top band in near-darkness holding only the wordmark and dateline, and a 62vh band of full-bleed macro photography behind a horizontal SLOT mask: linear-gradient(to bottom, transparent 0%, var(--foreground) 22%, var(--foreground) 78%, transparent 100%) — light entering as a slit, like a kitchen pass. The display line sits ON the seam, half in darkness and half over the photograph, and receives the world's ONLY permitted text-shadow: 0 2px 30px var(--background), 0 0 8px var(--background). Use for chefs, counters, open kitchens.

## Section seams (Nocturne's own vocabulary — every boundary uses one, never the same twice in a row)
- LIGHT-POOL DISSOLVE (the signature; at least half the boundaries). Sections paint no background, so the boundary is invisible by construction and the only thing crossing it is light. Every scene owns a ::before, absolute, inset -20vh 0, pointer-events none, z-index 0, carrying its three-stop radial at its own --lx/--ly. Its opacity is scrubbed by TWO ScrollTriggers, both ease "none", scrub .6: a rise from 0 to its authored intensity between "top bottom" and "top 58%", and a fall back to 0 between "bottom 78%" and "bottom 12%". Because pools bleed 20vh past their edges and the ramps overlap, at any boundary the outgoing light sits near 35% and the incoming near 40% — the lights CROSS, and it reads as one continuous room. FALLBACK: with no JS the pools hold their authored CSS opacity and the page is a complete, correctly lit composition.
- SNUFF. A beat of total darkness: a short scene (42-56vh) with NO pool, on the CELLAR ground, holding one serif-italic line at clamp(1.5rem,3vw,2.4rem), color-mix(in srgb, var(--foreground) 60%, transparent), max-width 22ch, and nothing else. Two per page maximum, never adjacent. The snuff makes the next light land.
- TAPER RULE. A vertical seam in the gutter: a 1px column 220px tall, linear-gradient(to bottom, transparent, color-mix(in srgb, var(--primary) 50%, transparent), transparent), with a 2px var(--primary) dot at 62% of its height — a candle standing between two scenes. Twice at most.
- SPILL. A full-bleed macro photograph whose bottom 26vh dissolves to the exact BASE ground (so it never "ends") and whose pool is drawn on the section ABOVE it at mix-blend-mode:screen — the next scene's light leaking upward. Once, at the most confident hand-off.
- GROUND STEP. The body background tweens BASE to TABLE (or BASE to CELLAR) over a 60vh scrubbed window, ease none, 3-6 RGB points. Nobody consciously sees it; everybody feels the room change.
- SMOKE PASS. A plume that STARTS in scene N and ENDS in scene N+1, absolute across the boundary at z-index 3. Because no section paints a background, it simply crosses. Once per page.
- COURSE BREAK (an ornament, not a scene seam): 1px hairline at ink .12 flex:1, gap 3.2rem, a var(--primary) glyph in display serif at .9rem, gap 3.2rem, hairline. Glyph vocabulary, one chosen per page and held: a fleuron, an asterism, a small diamond, an ampersand, a 5px filled circle. NOTE — this world overrides the global "hairline is the weakest seam, at most one per page" rule ONLY here, because the hairline repeats as RHYTHM INSIDE the menu scene, not as a boundary. Scene boundaries always use the light vocabulary.

## Layout physics
- NEVER 50/50. The ratios: 1fr/1.35fr, .82fr/1fr, 1fr/2.4fr for a marginalia column. A column holding only a price, a roman numeral and a 14px tick rule is a complete column.
- OFF-CENTRE BY LAW. Content centres on the LIGHT, not the canvas: the 640px menu column has its centre at 38-44% of the canvas; the chef's block sits hard left under a 28% pool. Symmetry is permitted only in the invitation scene, where the pool is also centred.
- THE FAR ELEMENT. Each large scene may carry ONE decorative element in the shadow at color-mix(in srgb, var(--foreground) 20%, transparent): a giant roman numeral, a ghost word, an oversized quote glyph at clamp(7rem,16vw,15rem), line-height 1, aria-hidden, z-index 0, clipped by the scene's overflow. It must be the LAST thing noticed; if it reads before the headline, drop to a 12% mix.
- PHOTOGRAPHY LAW (art direction for every image you generate or place): macro chiaroscuro. One warm source at about 45 degrees, shadow holding 60 percent or more of the frame, deep falloff, steam or rim light on an edge, hands in motion, texture close enough to feel. Portrait 4/5 or square 1/1 framed; 16/9 or 21/9 only full-bleed. BANNED: overhead flat-lays, daylight, white plate on white cloth, the whole dining room, staff line-ups, anything evenly lit.
- EVERY IMAGE IS UNDEREXPOSED, THEN LIT. At rest filter brightness(.86) contrast(1.08) saturate(.94); on reveal it tweens to brightness(1) contrast(1.02) over 1.9s power2.out — the light coming up on the dish. Each carries a vignette ::after, radial-gradient(ellipse at 50% 45%, transparent 40%, rgba(CELLAR,.55) 100%), plus a bottom scrim ending on the ground when full-bleed. Overscan 12-18% on anything parallaxed.
- IMAGES ARE FRAMED OR THEY ARE THE FLOOR: a framed plate (width min(38vw,520px), 1px hairline at ink .12, a micro-grotesk caption naming dish and origin) or a full-bleed scene that dissolves at the bottom. Never a rounded card with a photo in it.
- THE MENU IS TYPESET AS POETRY — the world's typographic centre of gravity. Each course is a STANZA in a three-column grid: [marginalia .34fr] [verse minmax(0,1fr)] [breathing .18fr], column-gap clamp(1.4rem,3vw,2.6rem), align-items:baseline on the first row so price and dish name share a baseline. Dish name: display serif roman, clamp(1.45rem,2.6vw,1.95rem), line-height 1.15, color-mix(in srgb, var(--foreground) 95%, transparent). Beneath it the INGREDIENT VERSE: display serif italic, 1.0-1.08rem, line-height 1.55, color-mix(in srgb, var(--foreground) 78%, transparent), max-width 34ch, broken into 2-3 AUTHORED lines of 3-6 words, ragged right, never justified, second and third lines indented 1.4em — a poet's runover indent. Then optionally a producer line in micro grotesk .64rem .18em uppercase at color-mix(in srgb, var(--foreground) 38%, transparent). In the marginalia column: the price, and above it the course's roman numeral at .72rem in var(--primary). Stanza gap clamp(2.6rem,6vh,4.2rem), a course-break ornament every 2-3 stanzas. NO dot leaders, NO right-aligned price column, NO table, NO borders. Below 720px the grid becomes one column and the price moves UNDER the dish name, still primary, still left-aligned.
- SERVICE STRIP (this world's trust strip): a hairline-topped row of 3-4 items, each a 20px inline-SVG line icon you draw at stroke-width 1.2 in color-mix(in srgb, var(--primary) 70%, transparent) (a candle, a corkscrew, a clock, a key) plus a micro-grotesk label at color-mix(in srgb, var(--foreground) 60%, transparent). Never emoji, never filled icons, never boxes.
- RESPONSIVE IS A DIMMER, NOT A REFLOW. Below 900px: pools shrink to 62% of their vmin radius and their centres move toward 50% (a phone is a smaller room); the pairing column collapses into the stanzas; far elements drop to .12; one plume survives at 3%. Below 640px: hide the nav's centre links, drop the dateline's third fact, cap the hero display at 8em. Nothing becomes cards at any width.

## The showpiece — the tasting-menu scroll
The scene that earns three times the ambition of any other; every page here has one (a tasting menu, a wine list, a cocktail card, a pastry counter — the object changes, the machine does not).
- STRUCTURE: a section on the TABLE ground, two columns, minmax(0,1fr) and clamp(280px,26vw,360px), gap clamp(2rem,5vw,5rem). The left column holds the stanzas, ONE PER 100svh (min-height:100svh, display:grid, align-content:center). The right column holds one position:sticky panel at top 50% with translateY(-50%) — CSS-only pinning, so it survives a dead CDN.
- EACH COURSE DECLARES ITS OWN LIGHT via inline --lx/--ly/--lr, walking across the frame per the ledger. Scrolling the menu relights the room five times — the single most memorable thing the page does.
- THE PAIRING PANEL: every card occupies the same cell (grid-area 1/1); one is visible. Each holds a micro-grotesk label ("Accord" plus the roman numeral), a wine name in display serif at 1.2rem, a vintage in tabular numerals, a two-line italic note at color-mix(in srgb, var(--foreground) 60%, transparent), max-width 24ch, and a price in var(--primary). One ScrollTrigger per course (start "top 60%", end "bottom 40%", onEnter and onEnterBack) sets the active index. Crossfade: outgoing to autoAlpha 0, y -14, .5s power2.out; incoming from autoAlpha 0, y 14, .7s power2.out at -=.38 so they overlap. Never a hard swap.
- THE LEVEL: a 1px vertical var(--primary) rule at the panel's inline-start edge, 78% of its height, its inner fill scaling Y 0 to 1 across the whole menu, transform-origin top, ease none, scrub .4 — wine rising in the glass as you descend. Beside it the index in serif italic: current roman numeral over the total (III / V).
- MOBILE CONTRACT: the CSS default IS the mobile form — each pairing sits in its own stanza as an italic line prefixed by a 14px var(--primary) tick, and the sticky panel does not exist. The two-column machine is opt-in inside gsap.matchMedia("(min-width:900px)") with a teardown. Under reduced motion the panel still pins (it is CSS) and pairings show stacked with hairlines between them.

## Motion identity (GSAP 3 + ScrollTrigger via CDN; native scroll — smooth-scroll libraries are unavailable)
GOVERNING LAW: every hidden state is set by JS (gsap.set, gated on a .js class from an inline head script), NEVER in CSS. If the CDN dies, the page is a complete, lit, readable room. The block bails on missing gsap, missing ScrollTrigger, or prefers-reduced-motion.
Defaults: gsap.defaults({ease:"power3.out", duration:1.15}). Shared eases: power2.inOut for anything that is LIGHT (pools, brightness, masks — light never snaps), power4.out for masked type rises, power2.out for panels and cards, "none" for every scrub, cubic-bezier(.22,.61,.36,1) for every CSS transition.
FOUR DELIBERATE OVERRIDES OF THE GLOBAL MOTION CONTRACT: (1) ambient loops are NOT 3-4s — flicker 6.5s and 9.1s, smoke 21-29s, wick 2.6s; a 3s ambient loop reads as a broken GIF in candlelight. (2) interaction feedback is NOT .25-.45s but .42-.60s, because a flame answers slowly. (3) the hero entrance is NOT complete in 1.6s but in about 3.2s, because the light has to come up. (4) the global "count-up numerals on view" is CANCELLED here: nothing on this page counts. Covers, vintages, hours, the number of references in the cellar and every price are painted at their true value in the HTML and simply lit — a rolling odometer is a sales gesture and this room does not sell, it receives. The one thing that moves numerically is the menu's course index (III / V), and it changes by crossfade, never by counting. Everything else stands.
- HERO TIMELINE. t=0: the pool grows — gsap.fromTo the hero from {"--pool-r":"26vmin"} to {"--pool-r":"78vmin"} over 2.6s power2.out, while {"--pool-a":.04} goes to .18 over 3.2s; both properties are read inside the mask and the gradient, declared with @property (syntax "<length>" and "<number>") so CSS can interpolate them too. t=.45: the display line rises out of pre-authored overflow:hidden wrappers, yPercent 108 to 0, 1.3s power4.out, stagger .13, each line also running opacity .18 to 1 so lines ENTER THE LIGHT rather than slide in. t=1.1: counter-line, y 14, .9s. t=1.35: the dateline hairline scales X 0 to 1 over .9s power2.inOut, facts staggering .08. t=1.6: nav and jewel, halo scaling .6 to 1 over 1.1s. The wick starts at t=2.4.
- LIGHT-UP replaces fade-up-from-20px as the entrance verb: from {autoAlpha:0, y:18, filter:"blur(6px)"} to {autoAlpha:1, y:0, filter:"blur(0px)", duration:1.25, ease:"power2.out"} — the blur is the flame focusing. At most 14 elements per page, and NEVER on text (blurred type on dark ground turns to mud). Images, pairing cards, ornaments, the linen card and the service strip use it; text uses the masked line rise plus its opacity ramp.
- THE LIGHT TRAVELS — the motif crossing every scene. Each pool centre drifts as its scene scrolls: gsap.to(pool, {"--lx":"+=5%", "--ly":"-=3%", ease:"none", scrollTrigger:{trigger:scene, start:"top bottom", end:"bottom top", scrub:.8}}). With the dissolve ramps the light is never still and never repeats a position — this is what stitches the page into one object.
- FLICKER IS CSS, never GSAP, so it survives a dead CDN: two keyframe animations on two stacked pool layers — opacity 1 / .93 / 1.02 / .96 / 1 at 6.5s ease-in-out infinite, and 1 / .97 / 1.03 / .95 / 1 at 9.1s. Co-prime durations, so the composite never visibly repeats. Amplitude never exceeds 7 percent: a candle gutters, it does not strobe. The jewel's halo runs the 6.5s curve, so the CTA breathes with the room.
- SMOKE: 2-3 inline SVG plumes, each a blurred ellipse (feGaussianBlur stdDeviation 14) through feTurbulence baseFrequency .012 .026, numOctaves 3, distinct seeds, then feDisplacementMap scale 26. Each box caps at 340px by 520px (never full-page — displacement is expensive), aria-hidden, opacity .03-.05, animating translateY 12% to -28%, scale 1 to 1.28, opacity 0 to peak to 0 over 21s, 26s and 29s, linear infinite, negative delays so they never start together. A SMIL animate on baseFrequency, values "0.012 0.026;0.020 0.031;0.012 0.026" over 28s indefinite, adds the curl for free. FALLBACK: plumes need no JS; under reduced motion transforms freeze mid-frame and the SMIL is removed; below 700px only one renders, at 3%.
- IMAGE REVEALS: clip-path inset(16% 9% 16% 9%) to inset(0%) over 1.5s power3.inOut, the inner img counter-zooming scale 1.14 to 1.05 over 1.9s and the brightness lifting .86 to 1 over 1.9s — three de-synced durations, which is why it reads as light rather than as a wipe. Once each, start "top 82%".
- MASKED LINE RISES on every display block: split at REAL browser wrap points (compare offsetTop), preserve em/strong ancestry, run on window.load, aria-label the parent and aria-hidden the visual lines, descender-safe masks (padding-bottom .06em, margin-bottom -.06em), then ScrollTrigger.refresh() again inside document.fonts.ready.then().
- MENU STANZAS: the dish name rises (yPercent 100 to 0, .95s power4.out), verse lines stagger .06 with light-up minus the blur, and the price fades in LAST at +=.25 over .5s — it arrives after you already want the dish. Course-break hairlines scale X 0 to 1 (.8s power2.inOut, origin centre), glyph fading at +=.2.
- THE EXTINGUISH: the final pool is scrubbed 1 to 0 across the last 30vh (ease none); the footer wordmark rises out of an overflow mask (yPercent 104 to 0, 1.5s power4.out) and settles at color-mix(in srgb, var(--foreground) 60%, transparent); the grain stays. The last frame is a dark room with a name in it.
- SMOOTH-SCROLL LIBRARIES ARE UNAVAILABLE in this runtime — native scroll only. The inertia this choreography rewards comes from the tweens themselves: expo-out easing and long scrub distances on native scroll, never from a scroll library.
- REDUCED MOTION: no flicker, no drift, no smoke, no blur-lift; pools render at authored intensity; reveals become opacity .001 to 1 over .3s; all pairings stack. Plus the global block (animation-duration .01ms, iteration-count 1, transition-duration .01ms, scroll-behavior auto).
- PERF: will-change:transform on at most three elements (sticky panel, hero image layer, active plume); passive pointer listeners; filters only on transformed elements, never on a scrolling container.

## Components
- THE RESERVATION JEWEL — the only AMBER-filled object on the page. An action shaped by border-radius var(--radius) (:root sets --radius: 2px): 40px tall desktop / 38px mobile, padding 0 1.35rem, border 1px color-mix(in srgb, var(--primary) 55%, transparent), transparent, label in micro grotesk 11px uppercase .18em at color-mix(in srgb, var(--foreground) 95%, transparent), a 5px var(--primary) dot before it. Its halo is a ::before at 132% size, radial-gradient(color-mix(in srgb, var(--primary) 12%, transparent), transparent 70%), filter blur(10px), z-index -1, breathing on the 6.5s flicker curve. Hover and focus (.48s cubic-bezier(.22,.61,.36,1)): fill becomes var(--primary), label inverts to var(--background), halo grows to a 20% primary mix at 148%; active snaps it to 28% for 120ms. True stepper circles use 50%; every panel and field caps var(--radius) at its named 0-4px treatment.
- THE STICKY CANDLE BAR (mobile; appears once the hero passes, translateY 100% to 0 over .55s power2.out): fixed bottom, height 62px, background color-mix(in srgb, var(--background) 86%, transparent), backdrop-filter blur(16px), top border 1px color-mix(in srgb, var(--primary) 18%, transparent), padding 0 var(--gutter), safe-area inset padding-bottom. Left: the service line in micro grotesk .68rem at color-mix(in srgb, var(--foreground) 60%, transparent) (the brief's real hours). Right: the jewel, primary-filled here, and a 40px square WhatsApp button with a 1px var(--border) ring.
- WHATSAPP, STYLED TO THE ROOM AND NEVER GREEN: the glyph is drawn inline at 20px, stroke-only, stroke-width 1.4, stroke var(--primary), fill none, handset as one path inside the bubble. It sits in a ghost pill (1px hairline at ink .16) or the bar's square button, and opens a wa.me link with a message pre-composed in the page's language from the reservation fields — "Bonsoir, je souhaite réserver une table pour [couverts] personnes le [date] à [heure]. Nom: [nom]." Unfilled fields are omitted, never left as brackets.
- THE RESERVATION CARTE (the form, a designed object): no boxes. Each field is a ruled line — transparent, border 0, border-bottom 1px var(--border), border-radius min(var(--radius), 0px), padding .7rem 0 .55rem — its LABEL above in micro grotesk .68rem .2em at color-mix(in srgb, var(--foreground) 38%, transparent) and the INPUT in the DISPLAY SERIF at 1.15rem at color-mix(in srgb, var(--foreground) 95%, transparent), because the visitor is writing their name in the reservation book. On :focus-within rule and label turn var(--primary) together over .42s and a glow blooms under the rule (box-shadow 0 6px 18px -12px var(--primary)). Fields: name; phone (type="tel" inputmode="tel", dir="ltr" always, with a real format hint in the page's language); date (type="date", min computed from today in JS); service time (a select of the brief's real services); covers (a stepper group at var(--radius) with two 34px true-circle buttons at 50%, 1px var(--border) rings and a tabular numeral between, keyboard accessible, min 1 max 12); an optional note. Where the brief serves districts or wilayas, the select gets a chevron drawn as an inline SVG data URI in the primary, never the browser default.
- FORM VOICE: errors are full sentences in brand voice, serif italic .92rem, color-mix(in srgb, var(--primary) 82%, transparent) ("Il nous faut un numéro pour confirmer la table."). Success is not a green box: the form DISSOLVES (autoAlpha to 0, .5s) and one serif-italic line lights up in its place inside a small pool of its own, echoing the visitor's input with a locale-formatted date. At that same instant — the moment validation passes, as the line lights up — the reservation is slipped to the wandit runtime by dispatching the wandit:lead CustomEvent on document with the visitor's fields flat in detail (name, phone as written, wilaya, commune, plus date, service and couverts), while one off-canvas decoy input marked data-wandit-hp waits in the carte, never read by the page's own script. The form never pretends to POST; the WhatsApp handoff remains the human channel and the phone is always tappable as tel:.
- BUTTONS: two exist. The jewel, and the EMBER LINK — a serif-italic link whose underline is a linear-gradient (transparent, var(--primary), transparent) 1px tall, background-size 200% 1px, background-position 100% at rest sliding to 0% over .55s cubic-bezier(.22,.61,.36,1), so the ember travels along the word. Never a solid rectangle, never a ghost button with a chevron.
- THE LINEN CARD (once per page, only inside a light pool): the world's single light surface — the warmed light pole, max-width 620px, padding clamp(1.8rem,4vw,2.8rem), rotated -0.6deg, type inverted to the ground colour with its own alpha steps, carrying the private-dining note, the corkage policy or the wine-list preface. It gets a CONTACT SHADOW, where the OCCLUSION LAW applies: this world permits shadows (unlike most dark editorial worlds) but ONLY when physically motivated, and always cast AWAY from the key. Derive them from the pool — x offset = (50 minus lx) divided by 6, clamped to plus or minus 10px; y 18-26px; blur 2.4 times y; spread -0.5 times blur; rgba(CELLAR,.72); plus a 0 1px 0 rgba(CELLAR,.5) contact line. A shadow falling toward the light is a correctness bug here.
- ::selection is color-mix(in srgb, var(--primary) 22%, transparent) with color-mix(in srgb, var(--foreground) 95%, transparent) text; :focus-visible is a 1px var(--primary) outline at outline-offset 4px PLUS a 0 0 0 6px color-mix(in srgb, var(--primary) 12%, transparent) ring — a glow, because everything visible in this room is lit. FAVICON: inline SVG data URI, the var(--background) ground as a filled square with one primary flame as a single teardrop path. No raster icons, no icon fonts, no icon grids anywhere.

## Editorial furniture (REQUIRED — this is Nocturne's voice)
These invent no business fact; they are typesetting, in the page's language.
- ROMAN-NUMERAL COURSES: Service I to Service VII, display serif in var(--primary) at .72rem, .12em tracking, in the marginalia column.
- THE DATELINE, the hero's floor and echoed in the footer: address, hours, covers, phone, split by spaced middle dots, micro grotesk at color-mix(in srgb, var(--foreground) 60%, transparent).
- CHEF'S MARGINALIA: a serif-italic aside at .92rem at color-mix(in srgb, var(--foreground) 60%, transparent) in a narrow column, opened with an em dash, closed with initials — a note in the margin, never a testimonial.
- PRODUCER ATTRIBUTIONS under dish names: micro grotesk .64rem .18em uppercase, ingredient and origin split by an em dash, using only origins the brief supplies.
- WINE NOTES: serif italic, two lines maximum, vintage in tabular numerals, region in micro grotesk. THE ALLERGEN KEY: superscript letters at .58em in var(--primary) after dish names, with a hairline-ruled legend at the foot of the menu.
- SERVICE LINE: one sentence about what happens tonight, set as a snuff beat between scenes.
- THE COLOPHON FOOTER: hours as a ruled two-column list, the address as a plain block (never a map embed), the phone as a typographic moment at 1.4-2rem in display serif, one closing italic line. The wordmark rises last and the light goes out behind it.

## Arabic and RTL adaptation (this market)
- dir="rtl" and lang="ar" on html; mirror every grid, marginalia column and ornament offset with logical properties (padding-inline, margin-inline, inset-inline), not left/right.
- MIRROR THE LIGHT: every --lx becomes 100% minus its Latin value, so the key falls where the eye ENTERS the page. Mirror the ledger as a whole, not scene by scene, so the light still walks a coherent path across the page.
- NO ITALICS IN ARABIC — synthetic slant destroys Arabic letterforms. Everywhere the Latin page italicises (verse, marginalia, wine notes, snuff beats, the success line), the Arabic page drops one weight step, shifts to color-mix(in srgb, var(--primary) 82%, transparent), raises line-height to 1.9-2.05 and adds a 14px var(--primary) tick before the block. That replaces the italic voice completely.
- NO LETTER-SPACING ON ARABIC — tracking breaks the joins. Micro-labels get word-spacing .12em, a size bump to 12-13px and the same alpha treatment instead of .24em tracking.
- Faces: an Arabic serif in the Amiri / Noto Naskh Arabic territory for display and menu, a clear Arabic sans in the Almarai / IBM Plex Sans Arabic territory for micro-type. Arabic display runs 8-12 percent larger than its Latin equivalent, and measures loosen to 30-38ch.
- Prices, phones, hours and vintages stay in Western Arabic digits with dir="ltr" and unicode-bidi:isolate on their spans, so a number never reverses.
- The jewel, the candle bar and the WhatsApp handoff mirror to the opposite edge; the taper rule moves to the opposite gutter; the level rule moves to the panel's other side.

## Nocturne ban list (in addition to the global one)
Pure #000 or #fff anywhere · a neutral, non-warm dark ground · a second warm key in one viewport · a cool pool used as key, or the cool fill above 6% · any section painting its own background colour · any surface lighter than the ground except the one linen card · dot leaders, right-aligned price columns, or the menu set as a bordered table · three-column Starters/Mains/Desserts card grids · chalkboard and wood textures, script or "handwritten" faces, faux stamps, badges, ribbons, gold star rows, fork-and-knife icons, tomato-and-basil accents · overhead flat-lays and evenly-lit food shots at brightness 1 · neon or glow text-shadow on headlines (candlelight, not a nightclub; the one permitted text-shadow is hero form 3's legibility scrim) · blur filters on text · border-radius above 4px on anything but the jewel and the stepper circles · box-shadow that is not physically motivated, or that falls toward the light · marquees and tickers (this room is quiet) · testimonial carousels and star ratings · autoplaying audio, or video with sound · a green WhatsApp blob · emoji, icon fonts, three-icon feature grids · a CTA button inside the hero · display type above weight 600 · ambient loops under 4s · a page where the light never moves.

## Intensity
This world is a lighting plan or it is nothing. At 60 percent it becomes the most generic thing on the internet: a dark restaurant template with amber buttons and a photo of a steak. THREE things must be at 100 percent or do not choose it at all. (1) THE POOLS — real radial light with three-stop falloff, bleeding past scene edges, dissolving into each other on scrub, moving as you scroll; flat dark sections have failed before they start. (2) THE MENU AS VERSE — authored line breaks, runover indents, marginal prices in var(--primary), course-break ornaments; a menu set as a price table has failed. (3) THE MASKED PHOTOGRAPH — imagery that exists only where the light reaches it, so the frame holds real darkness rather than a dark overlay. Everything else (the flicker, the smoke, the roman numerals, the jewel's halo, the angle of a contact shadow) costs almost nothing and is what makes a visitor feel the temperature of the room. Push INTO the darkness. The braver the shadow, the more valuable the light.`,
	energy: "quiet",
	family: "dark-luxury",
	id: "nocturne",
	industries: [
		"restaurant",
		"fine-dining",
		"cafe",
		"wine-bar",
		"lounge",
		"rooftop",
		"chef",
		"catering",
		"food",
		"hotel",
		"events",
		"wedding",
		"spa",
		"jewelry",
	],
	kind: "website",
	mood: ["candlelit", "intimate", "chiaroscuro", "sensual", "ceremonious"],
	name: "Nocturne",
	preview: {
		ground: "#100C09",
		ink: "#F2E9DC",
		accent: "#C8933F",
		fontFamily: "Playfair Display",
		sampleWord: "Nocturne",
	},
	priceFeel: "premium",
	tagline:
		"Your dining room after dark: one warm near-black page where each scene carries a single pool of candlelight — the dish, the menu set as verse with its prices in the margin, the reservation pill glowing like the last flame on the table — and the light dissolves from one course into the next as the visitor scrolls.",
};
