import type { DesignWorld } from "./types";

/**
 * PELLICULE — the contact sheet. The world for people whose product IS an
 * image: photographers, videographers, studios, models, visual makers. Film
 * grammar as interface grammar — sprocket rails, frame counters, chinagraph
 * selection marks, shutter-blade reveals, a scrubbed filmstrip. Near
 * monochrome with one darkroom red. The doc is appended VERBATIM to the
 * builder system prompt.
 */
export const pellicule: DesignWorld = {
	avoidFor: ["law", "finance", "medical", "industrial"],
	doc: `# DESIGN WORLD: PELLICULE — the contact sheet

## Philosophy
THE WORK IS THE PAGE. This world exists for businesses whose product is an image — a photographer, a videographer, a studio, a model, a retoucher, a maker of visual things. Every other world decorates around the pictures; this one is BUILT OUT OF THEM. The interface is not a website that contains photographs, it is a CONTACT SHEET that happens to be a website: strips of frames laid on paper, each one numbered, some of them circled in grease pencil by someone who was actually choosing. The visitor is not browsing a portfolio, they are standing at the light table looking over the photographer's shoulder while the edit happens.
That single metaphor decides everything downstream. Frames sit edge to edge because film has no margins between exposures. Rows are separated more than columns because a sheet is cut strips taped in rows. Captions are frame counters, not titles. The nav is a sheet of the page's own scenes. Reveals travel horizontally because a focal-plane shutter travels horizontally. Selection restores colour because a chosen frame is the one you print. Nothing here is a metaphor applied as skin — every device is a mechanical consequence of the metaphor, and that is why it will not read as a template.
Everywhere the pictures are not, the discipline is total: two typefaces, near-monochrome, zero shadows, zero radii above 2px, zero cards, one accent used like a grease pencil six or eight times in the whole document. What little UI exists is set at 10-13px and looks like machine markings on a film edge. Screenshot any viewport of this page and you should see mostly photograph and a very small amount of extremely precise typography.

## The edit (do this FIRST — it is what makes the world work)
Before writing markup, perform the edit the way a photographer does, on paper:
1. COUNT THE FRAMES. Decide how many frames the page will hold. The floor is 14 VISIBLE FRAMES; a Pellicule page with six pictures on it is a failure state, not a minimal version. Sheets are dense — density IS the argument that this person shoots a lot.
2. HIT THE IMAGE BUDGET WITH FEWER SOURCES. The build's hard cap is SIX generated images; spend four to six here and you do not need more, because the frame count and the source count are different numbers. A roll of film is variations of the same moments — that is literally what a contact sheet shows. From 4-6 sources, build 16-24 frames by varying THE CROP, not the picture: same src, different object-position (50% 32%, 24% 50%, 76% 44%, 50% 70%, 38% 26%, 62% 58%), different aspect-ratio (3/2, 3/2, 3/2, then one 2/3 portrait), and a scale step (transform scale 1 / 1.14 / 1.28 on the inner img inside an overflow:hidden frame). Consecutive crops of one source MUST be ADJACENT on the sheet and MUST take consecutive counters (24, 24A, 25) — they are a burst. Crops of different sources never interleave. This is not a workaround; it is the grammar.
3. MARK THE SELECTS. Choose 2-4 frames on the whole page to receive a chinagraph mark. Those are the hero images of each scene. Everything unmarked sits desaturated; the marked ones carry full colour. The edit must be VISIBLE.
4. SPEND BLANKS. Blank frames are legal and free: a frame filled with the ink pole carrying nothing but its counter, or a frame holding one line of caption type. Use 2-4 per page as rests. On a real roll there are always unexposed frames.
5. If the brief supplies REAL merchant photographs, they always outrank generated ones and they always take the selects.

## The vibe
A working document, not a brochure. The voice is a photographer talking about pictures: short, concrete, unsentimental, occasionally a two-word note in the margin ("celle-ci", "this one", "on garde"). Nothing is described as beautiful, nothing is sold with adjectives — the page states what a picture shows, what the studio does, what it costs. Confidence comes from volume and numbering: a page that can afford to show 22 frames does not need to claim anything. The copy never explains the metaphor; the page never says the words "contact sheet".

## Visual signatures (what makes it instantly recognizable)
- SPROCKET RAILS: perforated film-edge strips as a structural element, drawn as one reusable SVG data URI. They cap the top of the viewport, sandwich every strip of frames, and appear full-bleed between scenes as interludes.
- FRAME COUNTERS on every single image: mono, 10px, tabular, tracking .18em, alternating the film convention 23A, 24, 24A, 25, 25A — numbered CONSECUTIVELY from the top of the page to the bottom, so scrolling reads as advancing through one roll.
- GIANT FOLIOS: outlined page numerals at clamp(6rem, 16vw, 15rem), -webkit-text-stroke .8px ink at 12-14% alpha, sitting behind and across scene boundaries.
- CHINAGRAPH MARKS: hand-drawn SVG ovals, corner crop brackets and short underscores in the accent, stroke-width 2.6px, stroke-linecap round, drawn on with a dash-offset animation so they arrive like a hand moving.
- HEAVY GRAIN: 8-10% opacity, roughly double what a normal page carries — the page is on film, not on a screen.
- Near-monochrome everywhere except inside the SELECTED frames, which are the only fully saturated objects on the page.
- Almost no chrome: no button in the hero, no nav bar, no cards, no shadows, no radii. A 30px perforated rail is the entire top-level chassis.
- Asymmetric sheet gaps — 5px between columns, 22px between rows — which no automated grid ever produces and which instantly reads as physical.

## Color physics (instantiate with the brief's hexes — the physics is law, the hexes are the brief's)
- CHOOSE A MODE, PAGE-WIDE, AND HOLD IT. SHEET MODE: the palette's light pole as ground, a fibre-paper tone, never pure white — warm or cool shifted 2-4 points toward the brief's hue (the #F1EEE7 / #EDEDEA register). LIGHTBOX MODE: the palette's dark pole as ground (the #121212 / #0F1113 register) with frames reading as lit transparencies. Sheet mode is the default and the safer one; lightbox mode is for night work, music, fashion, video. Never mix modes between scenes except for the black-frame cuts, which belong to both.
- INK: the opposite pole, never pure black — a dense neutral carrying a trace of the brief's hue. Every non-image surface in the page is either GROUND or INK. There is no third surface colour.
- FIVE ALPHA STEPS OF INK, and nothing else for text and lines: 1 for display, .78 for body, .55 for captions and counters, .34 for dim edge text, .13 for frame outlines and rules. Any grey that is not one of these five is a correctness bug.
- SILVER: exactly one real mid-tone, at roughly 62% of the ink's luminance, mixed from the ground and the ink. Its only jobs: the sheet's own paper (3-6 RGB points darker than the page ground, so a sheet reads as a print LAID ON the page), the placeholder fill behind a loading image, and the unselected-frame veil.
- ACCENT — ONE, and it is a grease pencil. The darkroom-safelight / chinagraph register (the #C8341F / #D9422A / #B4301C family). If the brief's accent is already a warm red or orange, use it verbatim. If the brief's accent is cool or green, keep the brief's hue but raise its saturation 10-14% and treat it as the pencil; do not smuggle a second hue in beside it.
- THE ACCENT BUDGET, exhaustive: chinagraph marks · the counter of a selected frame · the filmstrip progress segment · the form's focus rule · error microcopy and its 8px square bullet · ::selection · :focus-visible · the WhatsApp glyph stroke on hover · one word in the closing statement · one filled rectangle for the primary CTA. That is all. An accent that appears as a section background has broken the world.
- IMAGE POLICY, global and non-negotiable: every img on the page carries filter: saturate(.80) contrast(1.06); a SELECTED or EXPANDED frame transitions to saturate(1) contrast(1.02) over .6s cubic-bezier(.33,0,.2,1). Selection restores colour. This is the cheapest and most meaningful device in the world and it must never be skipped. In lightbox mode add brightness(.94) to the unselected state.
- GRADIENTS ARE RATIONED TO TWO ROLES, not two declarations: (1) a photograph dissolving into the page ground — the hero's 24vh bottom dissolve and its 12vh top veil under the rail are both this role, one edge each; (2) the scrim under any type that sits on a photograph. No decorative gradient exists anywhere, and no third role is invented.
- Declare color-scheme (light for sheet mode, dark for lightbox mode) on :root and a theme-color meta matching the ground exactly.

## The two textures (draw them once, reuse everywhere)
- SPROCKET TILE: an inline SVG data URI, viewBox "0 0 76 30", containing FOUR rounded rects — x = 6, 25, 44, 63; y = 9.5; width 13; height 11; rx 2.5 — filled with the GROUND tone. Store it in one custom property. Applied to any rail as background-image with background-color = INK, background-repeat repeat-x, background-size 76px 30px, background-position 0 50%. Rail height 30px desktop, 22px below 720px. URL-encode the hash of any hex inside the data URI as %23 or the background silently fails.
- GRAIN, in two layers because the page and the pictures are different materials. PAGE GRAIN: fixed, inset -60px, z-index 70, pointer-events none, an inline SVG feTurbulence with type fractalNoise, baseFrequency 1.1, numOctaves 3, stitchTiles stitch, followed by an feColorMatrix type saturate values 0; tiled at 220px; opacity .085 in sheet mode with mix-blend-mode multiply, opacity .07 in lightbox mode with mix-blend-mode screen. FRAME GRAIN: an ::after inside every image frame, baseFrequency 0.55 (coarser), opacity .06, mix-blend-mode overlay, so the photographs carry visibly more grain than the paper. Drop the frame grain below 720px to save paint; keep the page grain everywhere.

## Typography system
- TWO FAMILIES, and the MONO does more work than the grotesk — that inversion is half the world's character.
  MONO (the caption face): a technical monospace in the Space Mono / JetBrains Mono / Martian Mono / DM Mono territory. It sets EVERY counter, label, caption, edge marking, nav link, form label, price, stat and micro-note. It never sets a paragraph.
  GROTESK (the display and body face): a minimal neutral grotesk with tight caps in the Archivo / Neue Montreal / Söhne / General Sans / Suisse territory. Weights 400 and 500-600 only. It sets the few display lines and all prose. Never Inter, Roboto or Open Sans.
- SCALE, roughly 22:1, with a DELIBERATELY EMPTY MIDDLE. Micro mono: 9.5-11px, uppercase, tracking .14-.22em. Body grotesk: 15-17px at line-height 1.55, measure 28-42ch. Statement display: clamp(2.4rem, 7vw, 6.2rem). Folio and closing wordmark: clamp(5rem, 17vw, 15rem). Do not generate 1.5rem / 1.75rem / 2rem intermediate headings — that ladder is what makes a page look assembled.
- LINE-HEIGHT TIGHTENS WITH SIZE: 1.55 body, 1.05 statement, .92 folio and wordmark. LETTER-SPACING INVERTS WITH SIZE: micro opens to .14-.22em, display closes to -.02 to -.035em.
- NO ITALIC EXISTS IN THIS WORLD. This overrides the global "one italic word inside a big headline" device: photographers' captions are not italic, and the ban makes the Arabic page identical in structure to the French one. Emphasis is (a) the accent colour, (b) a chinagraph underscore drawn in SVG beneath the word, or (c) a weight step from 400 to 600. Pick ONE per page and repeat it.
- FRAME COUNTERS, exactly: mono, 10px (11px below 720px so they stay legible), uppercase, letter-spacing .18em, font-variant-numeric tabular-nums, colour ink at .55, and the letter suffix set in a span at .82em with vertical-align .1em. A selected frame's counter is accent at full alpha with the same geometry — colour is the only difference.
- ALL FIGURES ARE TABULAR — counters, prices, durations, phone numbers, the strip HUD. Never a proportional numeral in this page.
- MEASURE IN ch, never px: 30ch for the hero line, 34ch for a caption block, 42ch for the one real paragraph, 22ch for a black-frame cut line.
- EDGE TEXT: 8.5px mono, tracking .3em, ink at .34 (or ground at .5 when it sits on an ink rail), uppercase. Its vocabulary is the world's own — ROLL 03, SHEET 01/04, FRAME 24A, the business name, the page language's word for the service. NEVER invent camera bodies, film stocks, ISO or shutter values, cities or dates: those read as facts and this world does not invent facts. If the brief supplies a real stock, camera or shoot city, use it verbatim.

## Page chassis
- THE MASTHEAD IS THE FILM EDGE, NOT A NAV BAR. position:fixed; top:0; left:0; right:0; height:30px (22px below 720px); z-index:90; the sprocket rail as its background; display:flex; align-items:center; padding-inline var(--gutter); gap clamp(1rem, 4vw, 3rem). Inside that 30px it carries, in GROUND-coloured 9.5px mono at .28em: the business name on the leading edge, a LIVE FRAME COUNTER in the middle that updates as you scroll (see motion), and the single word INDEX on the trailing edge. No logo lockup, no link row, no CTA, no blur, no scrolled state, no hide-on-scroll. It never changes. It is an edge, and edges do not react.
- THE NAV IS A CONTACT SHEET OF THE PAGE ITSELF. Clicking INDEX opens a full-viewport takeover (ground, z-index 95) holding a 3-column sheet where EACH SCENE OF THE PAGE IS A FRAME: a crop from that scene's own imagery (or an ink blank), its counter, and its name in 11px mono. Clicking a frame closes the takeover and scrolls to that scene. The takeover enters with its frames wiping in on the shutter stagger (.045) and exits in .22s. Escape closes it; focus is trapped; the INDEX word becomes CLOSE. This is the chassis move nobody else has — do not replace it with a link list.
- ONE GUTTER TOKEN: clamp(16px, 3.2vw, 56px). It is the page padding, the rail padding, and the anchor for every absolutely-positioned folio. It is deliberately TIGHTER than a normal editorial page because a print runs close to the paper edge.
- Canvas is wide: sheet scenes are FULL BLEED to the gutter with no max-width. Prose scenes cap at 1180px. There is no 1440px content wrapper wrapping everything.
- html, body { overflow-x: clip } is required — the folios, the strip and the interludes all overflow.
- Two fixed overlay layers only: the rail at z-index 90 (95 for the takeover) and the page grain at z-index 70. Nothing else is fixed except the mobile bottom rail.

## Hero forms (pick one; every one of them is mostly photograph)
1. FULL FRAME (default). ONE photograph, position:absolute inset:0, object-fit cover, object-position chosen consciously, overscanned to 108%, inside a section at min-height:100svh (declare 100vh first). The only UI in the entire viewport: the fixed sprocket rail at the top, a frame counter at the floor on the leading edge, and beneath it the h1. THE H1 IS TINY AND THAT IS THE POINT: the business name in mono at 12-13px, uppercase, tracking .3em, plus one grotesk line at clamp(1.05rem, 2.3vw, 1.7rem), weight 500, max 26ch, line-height 1.25. NO display-scale headline. NO CTA button. NO paragraph. The picture is the headline and the h1 is the caption. Do not grow it — a 13px h1 over a full-bleed photograph is this world's core nerve and the single most common place a builder loses it.
   Scrim: a 12vh top veil of ink at .32 so the rail's holes stay readable, and a 24vh bottom dissolve whose final stop EQUALS the page ground exactly, so the photograph never has a bottom edge. Nothing else.
   Entrance: shutter wipe, then the 1.6s settle (see motion). Scroll cue: the word DÉFILER / SCROLL in 9.5px mono beside a 40px 1px rule with a 12px accent segment travelling through it on a 2.4s loop. Never a chevron.
2. SHEET WITH ONE ENLARGED. The first viewport is a 4-column, 3-row contact sheet filling the screen, in which THE SIXTH FRAME IS ALREADY EXPANDED — grid-template-columns 1fr 2.6fr 1fr 1fr and grid-template-rows 1fr 2.05fr 1fr, using the exact same mechanism (and the exact same arithmetic) the rest of the page uses for in-place focus: index 5, column 5 % 4 = 1, row floor(5 / 4) = 1, so the second track on each axis is the fat one. Derive the two track strings from the index rather than typing them by hand, or the enlarged cell and the enlarged tracks drift apart the moment the column count changes at a breakpoint. The eleven small frames sit at saturate(.32) opacity .66; the enlarged one is fully saturated. Every frame carries its counter. After the entrance completes, a chinagraph oval draws itself around the enlarged frame and one two-word margin note appears beside it in the accent. The h1 lives in the sheet's leading-bottom cell as mono caps plus one grotesk line, or in a 64px caption rail along the leading edge. Use this when the brief has real breadth of work — it is the loudest possible statement of "I shoot a lot".
3. LEADER (the low-imagery safety valve). The first viewport is the exposed leader of a roll: the bare ground, THREE empty frame outlines (1px ink at .13, aspect 3/2) carrying nothing but their counters, and one grotesk statement line at clamp(2.2rem, 6.5vw, 5.4rem), weight 500, tracking -.03em, max 16ch, arriving through the shutter wipe. The first photograph is scene two, welded to the hero with padding-top:0 and full-bleed. Use when the brief's imagery is thin or when the business is a video studio whose work is motion.

## Section seams (Pellicule's own vocabulary — every boundary uses one, never the same twice in a row; use at least five different ones per page)
- SPROCKET INTERLUDE: a full-bleed rail, 30px tall (22px on mobile), ink ground with ground-coloured perforations, carrying slowly drifting edge text at 9px mono .3em, ground at .5 alpha. The drift is a single CSS marquee at 60s linear infinite, translateX 0 to -50% on a duplicated track — the ONE marquee this world allows, because film edge markings genuinely run along the strip. NOTE: 60s is a deliberate override of the global 20-40s marquee band — edge markings crawl, and anything inside the global band reads as a promotional ticker, which is the exact energy this world exists to refuse. Paused under prefers-reduced-motion, with the full text still visible.
- BLACK-FRAME CUT: a full-bleed band of the INK pole, min-height clamp(34vh, 42vh, 440px), display:grid place-items:center, holding exactly ONE line — 4 to 12 words in grotesk at clamp(1.4rem, 3.4vw, 2.6rem), weight 400, ground colour, max 22ch — plus a frame counter in the leading-bottom corner and, optionally, a single accent word. This is the page's silence: the unexposed frame between two rolls. It also inverts the type system for its own height. Use it 2-3 times, always after a dense sheet.
- WELD: the next scene starts at padding-top:0 hard against a shared full-bleed image, strip or rail. Nothing separates them; the image simply becomes the next scene's ceiling.
- FRAME LINE: the inter-frame rebate — a FULL-BLEED 4px INK BAR, sometimes doubled with 9px of ground between the two bars. NOTE: this world overrides the global "hairline is the weakest seam, at most one per page" rule, precisely — the frame line is 4px, not 1px, and it is a repeating MOTIF of the film metaphor rather than a whitespace-plus-rule boundary. A genuine 1px hairline separating two scenes with nothing else is still banned here, as everywhere.
- SHEET BREAK: a giant outlined folio numeral straddling the boundary, positioned so the next scene's top edge visually cuts it in half; the next scene's background paints over its lower part.
- LEADER GAP: the next scene opens with one or two EMPTY frames — outline plus counter, no image — before its first photograph. A rest with a number on it.
- BLEED-THROUGH (once per page, maximum): the outgoing scene's photograph continues into the next scene at opacity .10-.14, sized to bleed off both edges, behind the incoming type, in sheet mode with mix-blend-mode multiply and in lightbox mode with screen. A double exposure, not a background image.

## Layout physics
- THE SHEET IS THE PAGE'S BASE UNIT, and its geometry is exact: display:grid; column-gap 5px; row-gap 22px. THE ASYMMETRY IS LAW — frames on a strip touch, strips are taped apart. Columns: 5 on the dense sheet, 4 on the standard sheet, 3 on the loose sheet at desktop; 3 at 900px; 2 at 560px. NEVER 1 COLUMN, at any width. A single-column stack of photographs is a card list and this world does not have one.
- EVERY ROW OF A SHEET IS A STRIP: the row is wrapped so that a 30px sprocket rail runs above and below it, full width of the sheet. Rails belong to strips, not to the page.
- Frame aspect: 3/2 landscape is the default and dominates; ONE portrait 2/3 frame per sheet is allowed and should sit where it breaks the rhythm. A 1/1 sheet (the 6x6 medium-format variant) may replace the 3/2 sheet in a DIFFERENT scene, never inside the same sheet.
- FRAME ATOM: figure { position:relative; overflow:hidden; background: SILVER; } img { display:block; width:100%; height:100%; object-fit:cover; aspect-ratio:3/2; filter:saturate(.80) contrast(1.06); } plus the frame-grain ::after and the counter caption in a figcaption at margin-top 6px. No border, no radius, no shadow. The frames are held apart by the grid, not by boxes.
- NEVER 1fr 1fr for a media/copy row. This world's ratios: 1fr / 2.35fr (caption rail beside a plate), 1.6fr / 1fr (plate beside a note), 2fr / 1fr / 1.4fr for a three-track editorial row. Alternate the reading order down the page with an order-swap on even rows.
- THE CAPTION RAIL: a narrow leading column of clamp(64px, 7vw, 108px) that holds ONLY a frame counter, a chinagraph tick, and — once per page — edge text rotated with writing-mode: vertical-rl and a 180deg rotation so it reads bottom-to-top. A column holding three tiny things is a complete column here.
- RADIUS LAW (overrides the global tolerance for rounded containers): border-radius is 0 on every frame, button, input, select, rail and slab. The only radii in the entire file are 2.5px inside the sprocket SVG and, optionally, 999px on ONE status dot. More than three radius declarations means the page has drifted.
- SHADOW LAW: zero box-shadow in the file. Depth comes from the ink rails and the silver sheet tone. The one permitted shadow-like effect is a 0 0 0 1px inset ink at .10 on a frame in lightbox mode to keep white images from bleeding into the ground.
- FOLIOS: absolutely positioned per scene, z-index 0 behind content, right or left aligned to the gutter token, clamp(6rem, 16vw, 15rem), colour transparent, -webkit-text-stroke .8px ink at .13, line-height .9, user-select none, aria-hidden true. Three or four per page, numbered 01 upward, and at least one must be CUT by a scene edge.
- Vertical rhythm always as a clamp whose middle term is vh: clamp(4rem, 11vh, 7.5rem) for a standard scene, clamp(2.5rem, 6vh, 4rem) around an interlude, clamp(6rem, 15vh, 11rem) for the closing scene. Sheets get LESS air than prose — a sheet is dense by definition.
- THE CLOSING MOVE: a full-bleed strip of 5-7 frames running edge to edge with no gutter at all, welded to a final sprocket rail, and beneath it the wordmark at clamp(5rem, 17vw, 15rem) weight 500 tracking -.035em rising out of an overflow mask, with the last frame counter of the page beside it. The final gesture is a number, not a link farm.
- RESPONSIVE IS RE-CROPPING, NOT RESTACKING. Below 900px: sheets go to 3 columns, the pinned strip becomes a snap-scroll strip, the caption rail collapses into a single counter line above the plate, frame grain is dropped. Below 560px: sheets go to 2 columns, rails to 22px, counters to 11px, folios to clamp(4rem, 22vw, 7rem). The composition never becomes a one-column list of pictures.

## The showpiece — the filmstrip (one per page, and it gets 3x the ambition)
A pinned horizontal strip that the visitor drives.
- STRUCTURE: a section of height 100svh, pinned; inside it a TRACK of display:flex, gap 0 (frames touch — the separation is a 4px ink bar between them, drawn as a border-inline-end on each frame), height clamp(42vh, 52vh, 560px), sandwiched between two full-width sprocket rails. Each frame is aspect-ratio 3/2 with its counter set BELOW the lower rail, aligned to the frame's leading edge. 12-20 frames.
- SCROLL SCRUB: gsap.to(track, { x: () => -(track.scrollWidth - window.innerWidth), ease: "none" }) with scrollTrigger { trigger: section, start: "top top", end: () => "+=" plus the track's scrollWidth, pin: true, anticipatePin: 1, scrub: 1, invalidateOnRefresh: true }.
- DRAG, without any paid plugin: on pointerdown (only when matchMedia("(pointer:fine)") matches), setPointerCapture, record the pointer x and the current window.scrollY, add a grabbing cursor class; on pointermove, scroll the page to startScrollY + (startX - event.clientX) * 1.15 — via window.__lenis.scrollTo(target, {immediate:true}) when Lenis is running and window.scrollTo(0, target) when it is not, because calling window.scrollTo underneath an active smooth-scroll instance makes the strip fight itself and stutter. Dragging left therefore scrolls the page forward and the pinned scrub advances the strip. No conflict with ScrollTrigger, no plugin, no touch hijack. On pointerup release the capture and remove the class. Cursor at rest inside the strip: grab.
- HUD: pinned to the strip's lower-leading corner — "FRAME 07 / 20" in 10px mono tabular, and a 120px 1px ink-at-.13 rule whose accent segment is scaleX-driven by the same ScrollTrigger's progress (transform-origin: left; in RTL, right).
- INSIDE THE STRIP, every secondary animation uses scrollTrigger containerAnimation so it fires on HORIZONTAL position: each frame's inner img drifts xPercent 6 to -6 against the travel, and each counter fades from .3 to 1 as its frame crosses the centre.
- FALLBACKS, both designed, neither degraded: below 900px and under prefers-reduced-motion, the strip becomes a native horizontally scrollable rail — overflow-x auto, scroll-snap-type x mandatory, each frame scroll-snap-align start, scrollbar hidden, with the rails and counters intact and a 9px mono hint reading the page language's "swipe". Never a vertical stack, never a dead section.

## Motion identity (GSAP 3 + ScrollTrigger via CDN; Lenis OPTIONAL — if used, expose window.__lenis; canvas is BANNED in this world, the imagery is photographic)
GOVERNING LAW: every hidden state is set in JS, never in CSS. No stylesheet in this world contains opacity:0 or a transform on content. The whole animation block is gated on GSAP and ScrollTrigger existing and prefers-reduced-motion being unset. If the CDN dies, the page is a complete, correctly composed contact sheet with every picture visible.
- gsap.defaults({ ease: "power3.out", duration: .9 }). NOTE: this world overrides the global 1.1s default — a shutter is quick. Entrances live in .38-.9s while IMAGE SETTLES live at 1.6s. That split (fast reveal, slow settle) is the world's motion signature.
- THE SHUTTER (the reveal, used on every frame, every plate, the takeover, the black-frame cuts):
  Structure: the frame wrapper is overflow:hidden and carries a BLADE — an absolutely positioned inset:0 element filled with the INK pole, z-index 3, transform: scaleX(0), transform-origin: left (right in RTL).
  Timeline per frame: (a) blade scaleX 0 to 1 over .16s power2.in; (b) at .16s flip transform-origin to right and tween scaleX 1 to 0 over .34s power2.out; (c) the img itself starts at clip-path inset(0 100% 0 0) and tweens to inset(0 0 0 0) over .50s power2.inOut starting at .12s; (d) the inner img starts at scale 1.06 and tweens to 1 over 1.6s power2.out from t=0. What the eye sees is a black blade crossing the frame and the picture arriving behind it, then breathing to rest for another second. Total blade travel .50s exactly.
  Stagger: .055 along a strip (left to right, following the blade's direction), .09 between strips. once:true, start "top 86%".
- THE BLINK (black-frame cuts): the band's caption holds for 120ms after the band enters, then appears with opacity 0 to 1 in 90ms with ease none. No movement, no fade-up. A blink, not a transition.
- COUNTERS COUNT: as a strip enters, every counter in it runs its numeral from 00 to its value via a tweened proxy over .5s power2.out with tabular figures, and the letter suffix (A) fades in at the end at .12s. The true value is hard-coded in the HTML so a no-JS visitor sees the real number.
- THE LIVE RAIL COUNTER: a ScrollTrigger on the whole document updates the masthead's middle counter to the counter of the frame nearest the viewport centre, so the film edge always says where you are. Implement with one ScrollTrigger per sheet (start "top 60%", end "bottom 40%", onToggle sets the text) — never a scroll listener doing DOM reads per frame.
- CHINAGRAPH DRAW-ON: the mark is an inline SVG path (never a border, never a CSS ellipse) with vector-effect non-scaling-stroke, stroke-linecap round, stroke-width 2.6, fill none. Set stroke-dasharray and stroke-dashoffset to the measured getTotalLength(), then tween dashoffset to 0 over .9s cubic-bezier(.34,.02,.2,1), once, start "top 78%". The oval's path must OVERSHOOT its own start by about 8% and be visibly imperfect — three or four control points, no symmetry — so it reads as a hand, not a shape tool. Crop brackets draw as two separate L paths with a .12s offset between them.
- HOVER-SCRUB PREVIEW (the interaction that sells the work): a project frame contains 3-6 stacked images, all absolutely positioned inset:0, only the active one at opacity 1 with NO transition — scrubbing is instant, like flicking frames. On pointermove over the frame, index = clamp(floor((event.offsetX / frame.clientWidth) * n), 0, n-1); swap on change only. Under the frame sits a SEGMENTED BAR: n segments, height 1px, gap 3px, ink at .16, the active segment ink at .8 (accent if the frame is a select). The counter caption updates with the index (24, 24A, 25...). On pointerleave, return to frame 0 after a 220ms timeout. TOUCH PARITY IS MANDATORY: on coarse pointers, an IntersectionObserver at threshold .6 auto-advances the frames on a 900ms interval while the card is in view and clears it when it leaves — mobile still gets the strip. Keyboard: the frame is focusable and arrow keys move the index.
- IN-PLACE FOCUS — THE LIGHTBOX IS BANNED. Clicking a frame in a sheet expands it WHERE IT IS by transitioning the grid itself. The sheet declares transition: grid-template-columns .62s cubic-bezier(.65,0,.35,1), grid-template-rows .62s cubic-bezier(.65,0,.35,1). On click, compute col = index % cols and row = floor(index / cols), then write the two track strings directly: every track "1fr" except the active column at "2.6fr" and the active row at "1.9fr". Set aria-expanded on the button-wrapped figure, add an is-open class (which lifts the frame to saturate(1), raises its counter to the accent, and reveals its caption line), and let a second click, Escape, or clicking another frame reset the tracks to all-1fr. This is pure CSS transition plus four lines of JS: it survives a dead CDN, it works with reduced motion (the tracks simply snap), and in browsers that do not interpolate fr tracks it snaps rather than breaks. The expanded frame's caption fades in at .18s delay. NEVER open a modal, an overlay, a carousel or a full-screen viewer anywhere in this world.
- SCRUB PARALLAX, subtle: alternate strips drift yPercent -4 and +4 with ease none over their own scroll range; folios drift yPercent -18 to 18. Nothing else parallaxes.
- Statement lines use the global masked line rise — yPercent 112 to 0, 1.0s power4.out, stagger .10, descender-safe padding-bottom .06em with margin-bottom -.06em — but ONLY on the 2-4 grotesk display lines in the page. Captions and counters never rise; they blink in.
- ScrollTrigger.refresh() inside document.fonts.ready.then(). Every reveal is once:true. will-change:transform on at most three elements (the strip track, the pinned wrapper, the mobile bottom rail).
- REDUCED MOTION: the shutter becomes an instant clip-path inset(0) with the blade never rendered; the settle is dropped; counters print their final value; the chinagraph marks appear fully drawn; the strip becomes the snap rail; the edge-text marquee stops. Every device has a designed still state — nothing is simply switched off into a blank.

## Components
- THE FRAME BUTTON (the only real button): a rectangle at zero radius, 1px ink border, padding .95rem 1.6rem, mono 11px uppercase at .2em, background transparent, with a 10px chinagraph corner tick drawn in the accent at the trailing-top corner (an L of two 1px lines, or one SVG path). Hover and focus over .22s cubic-bezier(.65,0,.35,1): the background fills with INK, the label inverts to GROUND, and the tick MOVES to the opposite corner via a transform. Exactly one button on the page may instead be filled with the ACCENT — the primary conversion CTA — same geometry, ground-coloured label.
- THE COUNTER LINK: a text link prefixed by its own frame number in the accent at .82em, with a 1px ink-at-.3 underline that redraws from the leading edge over .3s (transition right:100% to 0 on a ::after, mirrored in RTL). Used for every secondary action; there is no third button style.
- FORMS ARE RULED LINES ON A SHEET: label above in 10px mono uppercase at .2em ink at .55; input in the GROTESK at 1.05rem, background transparent, border 0, border-bottom 1px ink at .22, border-radius 0, padding .7rem 0 .5rem. On :focus-within the rule turns ACCENT and thickens to 2px over .24s while the label turns accent with it. Selects get a custom chevron drawn as an inline SVG data URI in the ink, appearance:none, zero radius.
- FORM VOICE: errors in 10.5px mono, accent, preceded by an 8px accent square, written as one plain sentence in the page's language. SUCCESS IS A BLACK FRAME: on valid submit the form's fields wipe out on the shutter (.34s) and the container becomes an ink block holding one caption line echoing the visitor's own input plus a frame counter — the world's own confirmation. The form never pretends to POST — but the instant validation passes, as the shutter fires, one exposure leaves the page: the wandit:lead CustomEvent dispatched on document with the visitor's fields flat in detail (name, phone as typed, wilaya, commune, plus whatever else the form collects), while one off-canvas decoy input marked data-wandit-hp sits on the contact sheet, never read by the page's own script.
- IMAGE STATES: every img has real alt text describing the scene, loading="lazy" below the fold, and a SILVER background so a slow connection shows a frame, never a hole. decoding="async" everywhere.
- ::selection is the accent at .9 with ground-coloured text. :focus-visible is a 2px accent outline at outline-offset 3px, radius 0 — the same rectangle language as everything else.
- FAVICON: an inline SVG data URI — the ink pole as a filled square with two ground-coloured rounded rects as sprocket holes. No raster icons, no icon fonts, no icon grids, no emoji anywhere in the page.

## Conversion objects (this market — COD and WhatsApp shaped, styled to the sheet)
- THE BOOKING SLIP (the form as a designed object): laid on a 1.6fr / 1fr grid inside a sheet-toned panel with no radius and no shadow, headed by a mono running head ("RÉSERVATION — SHEET 04/04") and a frame counter. Fields, all ruled lines: NAME; PHONE with type="tel" inputmode="tel" dir="ltr" and a real format hint in the page's language; WILAYA as a styled select of the brief's real coverage with the SVG chevron; DATE with type="date" and min computed from today in JS; SHOOT TYPE as a select built only from the brief's real services; and a one-line note. Field entrances stagger .07 on the shutter.
- WHATSAPP, DRAWN AND NEVER GREEN: the glyph is inline SVG at 20px, fill none, stroke 1.5px in the INK (accent on hover), handset drawn as a single path inside the bubble outline. It lives inside a frame button or a 40px square on the mobile rail, and opens a wa.me link with a message pre-composed IN THE PAGE'S LANGUAGE from the slip's own fields — for example "Bonjour, je souhaite réserver une séance [type] le [date] à [wilaya]. Nom: [nom]." Unfilled fields are omitted entirely; a bracket must never reach WhatsApp.
- PRICE TYPOGRAPHY: mono, tabular, clamp(1.6rem, 3.2vw, 2.6rem), letter-spacing -.02em, with THIN-SPACE thousands (U+202F: 18 000 DZD) and the currency set as a span at .5em, .2em tracking, vertical-align .55em, ink at .55. Packs are presented as a RULED TABLE — a grid with 1px ink-at-.13 internal dividers and rules top and bottom, one row per pack, the pack name in grotesk 500, the deliverable count in mono, the price on the trailing edge. Never as three cards. NOTE: this world overrides the global "count up prices" instruction — prices do NOT animate here (a spinning price reads as a sale, and this business is not having one). Frame counters count instead.
- THE MOBILE STICKY IS A BOTTOM FILM EDGE, not a bar: a fixed bottom element made of a 10px sprocket rail sitting on a 42px ink block (52px total plus safe-area inset padding-bottom), appearing once the hero has passed via translateY 100% to 0 over .42s power2.out. Leading side: the starting price or the service line in 11px mono, ground colour. Trailing side: the 40px WhatsApp square and one accent-filled frame button reading the brief's real CTA. It never overlaps the footer's last 120px (offset it with a ScrollTrigger at the footer).
- TRUST STRIP, only if the brief supplies real guarantees: a single ruled row of 3-4 items, each an inline SVG icon DRAWN BY YOU at 24px with stroke-width 1.4, fill none, ink at .55 — a six-blade shutter iris, a film canister, a downward arrow into a tray for file delivery, a clock — followed by 10.5px mono uppercase text. Zero fills, zero circles behind the icons, zero emoji.
- Phone numbers are always tel: links and always dir="ltr" with unicode-bidi:isolate.

## Editorial furniture (REQUIRED — this is Pellicule's voice; it invents no business fact)
- FRAME COUNTERS on every image, consecutive down the whole page, alternating N / NA in the film convention.
- CAPTION LINES: every plate carries one 6-14 word mono caption describing WHAT THE PICTURE SHOWS, never selling it. Written in the page's language.
- RUNNING HEADS: "ROLL 02 — SHEET 01/04" style indices above each scene, in 10px mono at .2em, ending in a flex:1 1px ink-at-.13 rule that eats the remaining width.
- GIANT FOLIOS: 01, 02, 03 outlined behind scenes, at least one cut by a scene edge.
- EDGE TEXT along every interlude rail.
- THE MARGIN NOTE: once per page, beside a chinagraph mark, one to three words in the accent in the page's language ("celle-ci", "on garde", "this one") — the sound of someone choosing.
- THE COLOPHON FOOTER: a mono block stating the page's own construction — sheet count, frame count, year, business name, the language of the page — plus the real address and hours as a ruled two-column list and the phone as a typographic moment in mono at clamp(1.3rem, 3vw, 2.2rem). No map embed, no social icon row (social links are counter links).
- THE KILL CROSS is permitted at most ONCE and only over a BLANK ink frame, never over a photograph of a person, a client's work, or a product the merchant sells. Crossing out a merchant's own work is a correctness bug.

## Arabic and RTL adaptation (this market)
- dir="rtl" and lang="ar" on html; every offset in logical properties (padding-inline, margin-inline, inset-inline, border-inline-end) so the rails, folios, caption rail and HUD mirror as a system.
- THE SHEET READS RIGHT TO LEFT: set direction:rtl on the sheet so grid auto-placement starts top-right, and number the frames from the top-right frame onward. The strip's pinned tween goes POSITIVE x, the drag multiplier inverts, and every transform-origin that was "left" becomes "right" (shutter blade, HUD progress rule, link underline).
- The sprocket tile is symmetric and needs no mirroring — but the edge-text marquee reverses direction and the vertical caption-rail text uses writing-mode: vertical-rl without the 180deg flip.
- NO LETTER-SPACING ON ARABIC — tracking destroys the joins. Every micro-label that was .2em tracked becomes word-spacing .1em with a size bump to 12-13px and the same alpha step. Arabic display sits 8-12% larger than its Latin equivalent, line-height 1.85-2.0, measures 30-38ch.
- Arabic monospace is effectively unavailable, so the CAPTION ROLE SPLITS: Arabic words in a caption are set in a clear Arabic sans (the IBM Plex Sans Arabic / Almarai / Readex Pro / Noto Kufi Arabic territory) at 12px, while the NUMERIC fragments — counters, ROLL 02, 24A, prices, phones, times — stay in the Latin mono inside spans with dir="ltr" and unicode-bidi:isolate. The film markings stay Latin because they are numbers, and that is exactly how real film edges look in any market.
- Display face: pair the grotesk with an Arabic grotesk of similar width and keep the two roles sealed. This world has no italic to lose, so the Arabic page is structurally identical to the French one — that is a feature of the type system, not an accident.

## Pellicule ban list (in addition to the global one)
Lightboxes, modals, full-screen image viewers and carousels of any kind (expansion is ALWAYS in place) · a one-column stack of photographs at any breakpoint · uniform gaps on a sheet (columns and rows must differ) · border-radius on frames, buttons, inputs or rails · any box-shadow · cards with a background and padding · a nav bar with logo-left and links-right, or any masthead that is not the sprocket rail · a hamburger that opens a link list instead of the index sheet · display-scale headlines in hero form 1 (the h1 is 12-17px and stays there) · a CTA button anywhere in the hero · more than one accent hue · the accent as a section background · italics anywhere · proportional numerals · detached greys outside the five ink alphas · gradients beyond the two permitted ones · fully saturated unselected images · stock-photo energy: smiling teams, handshake shots, generic laptop desks · watermarks, camera-brand logos, EXIF data or invented film stocks and ISO values · star ratings and testimonial carousels · icon grids, icon fonts, emoji · canvas, WebGL and generative art (the imagery is photographic) · autoplaying audio · a page with fewer than 14 visible frames.

## Self-audit before shipping (count these)
Visible frames: 14 minimum, 24 comfortable · sprocket rails: at least 4 instances (masthead, two strip rails, one interlude) · chinagraph marks: 2-4, never more · black-frame cuts: 2-3 · giant folios: 3-4, one of them cut by an edge · lightboxes: 0 · border-radius declarations above 2.5px: 0 · box-shadow declarations: 0 · italic declarations: 0 · gradient ROLES: exactly 2 (dissolve, type scrim) and zero decorative ones · different seams used: 5 or more, never the same twice in a row · saturated images: only the selects and the expanded frame.

## Intensity
This world is a working contact sheet or it is a photography template with a red button. At 60% it collapses instantly into the most generic page on the internet: a dark portfolio with a 3-column gallery, a lightbox, and a big headline over a photo. THREE things must be at 100% or do not choose this world at all.
(1) THE SHEET — real density, asymmetric gaps of 5px and 22px, sprocket rails on every strip, a counter under every single frame, and never one column. A uniform-gap gallery grid has already failed.
(2) IN-PLACE EXPANSION — the grid-template transition, with the selected frame regaining its colour. The moment you reach for a modal, the world is gone.
(3) TYPOGRAPHIC NERVE — a 13px h1 under a full-bleed photograph, captions at 10px, a masthead 30px tall, and no button in the hero. The temptation to grow the type is the exact temptation to destroy the world.
Everything else — the grain at 9%, the counters counting up, the chinagraph overshoot, the segmented hover-scrub bar, the margin note in grease pencil, the blank frames — costs almost nothing and is precisely what separates a page someone AUTHORED from a page something generated. Push INTO the smallness. The pictures are large; you should be invisible.`,
	energy: "medium",
	id: "pellicule",
	industries: [
		"photography",
		"videography",
		"film-production",
		"studio",
		"portfolio",
		"agency",
		"model-agency",
		"fashion",
		"wedding",
		"events",
		"music",
		"art",
		"tattoo",
		"crafts",
	],
	kind: "website",
	mood: ["analog", "photographic", "documentary", "grainy", "understated"],
	name: "Pellicule",
	priceFeel: "premium",
	tagline:
		"Your photographs laid out like a real contact sheet — perforated film edges, frame numbers under every shot, a red grease-pencil circle around the ones you chose, and a strip you can drag through with your finger.",
};
