import type { DesignWorld } from "./types";

/**
 * RIBAMBELLE — hand-cut paper collage for the businesses that live around
 * children. One structural idea carries the world: every scene is a SHEET of
 * cut paper laid over the one below it, with a real cut edge, a real contact
 * shadow and a hand's worth of rotation — warmth built from physics, never
 * from clipart. The doc is appended VERBATIM to the builder system prompt.
 */
export const ribambelle: DesignWorld = {
	avoidFor: [
		"law",
		"finance",
		"luxury",
		"industrial",
		"funeral",
		"notary",
		"insurance",
		"crypto",
	],
	doc: `# DESIGN WORLD: RIBAMBELLE — the hand-cut paper collage

## Philosophy
This page is a COLLAGE somebody made with scissors, not a website about children. Sheets of soft pastel paper laid over each other with the cut edges showing; photographs punched out in pebble and scallop shapes; a few strokes drawn with a wax crayon; oversized friendly numerals for ages and steps; a paper-doll chain along the bottom like a garland. Everything is MADE — cut, laid, pinned — and the page has the depth of a real pile of paper, because every sheet overlaps the next and casts a real shadow onto it.

The world exists because the kids corner of the web is a graveyard of clipart: cartoon suns, rainbow gradients, balloon emoji, Comic Sans, primary-color confetti. All of it says "for children" and none of it says "we are careful with your child". Ribambelle takes its warmth from PHYSICS instead — paper, light, a hand that cannot cut straight — so it reads as tender AND competent at once.

Two laws carry it, one thing is refused. THE PAPER LAW: every scene is a sheet with a declared color, a cut (never straight) bottom edge, a rotation from a fixed set of five, and a two-part shadow — sheets OVERLAP, they never abut. THE ONE BRAVE HUE: the pastels are grounds and only grounds; one saturated accent, the crayon, does all the marking. What is refused is DECORATION AS CONTENT: no illustration explains anything, no floating shape fills a hole where an idea should be. If your draft could be rescued by adding a cartoon, the collage was never built. Restraint is what makes this world read as careful rather than cheap: three floaters per scene, never four; five rotation values, never a sixth; one crayon-colored band per page. The softness is in the SHAPES; the discipline is in the COUNTS.

## The vibe
Warm second person, spoken by someone who works there and likes the job. The page talks to the parent, and exactly once to the child. Copy rules carry a third of this design:
- HEADLINES ARE 4-9 WORDS with one plain turn, no cleverness: "Un endroit où on a le droit de se salir." / "Trois heures, dix enfants, deux adultes."
- CONCRETE BEATS CUTE. Name a material, a smell, a time, a rule of the house before a value: toast at ten, shoes off at the door, the nap at 12h30, the blue crate where the doudou waits. "Un espace d'éveil" is nothing; "on peut peindre par terre" is everything.
- LES PETITS MOTS (see Editorial furniture) are the signature voice device: tiny hand-placed observations in the margins with a crayon arrow pointing at what they describe — "on enlève ses chaussures ici", "le doudou a le droit de venir", "ici, ça sent le pain grillé". They describe what the page SHOWS; they never claim, price or promise.
- ONE exclamation mark on the whole page at most, inside a quoted human voice. No ALL-CAPS shouting. Paragraphs of three sentences maximum.
- SYSTEM MESSAGES STAY IN VOICE, in full sentences: "Il nous faut un numéro pour vous rappeler." Never "Champ requis". The success state echoes the parent's own words and says what happens next and when.
- BANNED WORDS: magique, univers, solutions, expérience (as a vague noun), transformer, excellence, premium, leader, épanouissement as a slogan — and their English and Arabic equivalents. Also banned: any sentence a bank could say.

## Visual signatures (what makes it instantly recognizable)
- SHEETS THAT OVERLAP. Every boundary is a cut edge painting the next sheet's color over the outgoing one, and at least twice per page an element crosses the boundary bodily with a real shadow under it. The paper-layer overlap is THE seam of this world.
- CUT EDGES, NEVER LINES: scallops, soft waves, torn edges as SVG paths, 34-72px tall, full bleed. A straight horizontal boundary between two colored scenes is a bug.
- PHOTOGRAPHS PUNCHED OUT in five named cut shapes, each backed by a second sheet of pastel offset 10-14px — the double-sheet. Never a bordered rectangle, never a perfect circle.
- CRAYON STROKES: SVG paths pushed through a turbulence displacement filter so the line wobbles like wax on paper — underlines, a circle around one word, arrows, schedule ticks, the icon set, the success check.
- OVERSIZED FRIENDLY NUMERALS for ages, steps and hours: display 700 at 3.4-7.5rem, on a cut disc, rotated.
- THE RIBAMBELLE: a paper-doll chain of nine linked cut silhouettes, under the nav, across one band, and enormous across the footer. It is the motif that TRAVELS.
- THREE SHAPES DRIFTING per scene at most, on a 4-6s sine breath, behind content, aria-hidden.
- ONE BRAVE BAND: exactly one full-bleed scene in the saturated accent, holding a single line of type.

## The paper law (do this FIRST — it is what makes the world work)
1. EVERY SCENE IS A SHEET: a background from the sheet palette, a cut bottom edge, and a z-index from the token set — --z-sheet:1 · --z-photo:2 · --z-lift:3 · --z-float:4 · --z-chrome:100.
2. SHEETS OVERLAP, NEVER ABUT. Between any two scenes either the outgoing sheet's cut edge paints the incoming color (LA DÉCOUPE) or an element crosses the boundary at margin-top -4rem to -9rem (LE CHEVAUCHEMENT). A boundary of whitespace and a rule does not exist here.
3. FIVE ROTATIONS, NO OTHERS: -2.4deg · -1.4deg · -0.6deg · +0.9deg · +1.8deg. Every paper element takes one; 0deg is reserved for full-bleed sheets and for type. Never two adjacent elements on the same value. Below 640px every value halves. In RTL every sign flips.
4. TWO-PART PAPER SHADOW, and exactly one other shadow exists. A LIFTED element (photo plate, overlapping card, floating pill) carries both stops: 0 2px 3px -1px rgba(ink,.10), 0 22px 46px -26px rgba(ink,.24). A FLAT element carries only the contact half. THE ONE OTHER is the PRINTED OFFSET — 0 3px 0 0 rgba(ink,.16), zero blur, zero spread — which lives on the crayon pill and nowhere else: it is not a shadow, it is a second sheet of paper showing under a first, which is why it collapses to 0 1px 0 on :active instead of softening. Never a glow, never a colored shadow, never a soft-UI double shadow lit from both sides, and never a blurred shadow on a button.
5. NOTHING THAT IS PAPER HAS A STRAIGHT BOTTOM EDGE. Sheets end in a cut, cards in a hand radius, photographs in a mask. The only straight lines here are crayon strokes, and those wobble.

PAPER GRAIN, mandatory, one layer: inline SVG feTurbulence type fractalNoise, baseFrequency 0.78, numOctaves 4, stitchTiles stitch, desaturated via feColorMatrix saturate 0; tiled 260px, position fixed, inset 0, opacity .055, mix-blend-mode multiply, z-index 90, pointer-events none, aria-hidden. Opacity .04 below 640px. This is why the pastels read as paper stock and not as flat UI fills.

THE CRAYON FILTER, mandatory, three seeds: crayon-a / crayon-b / crayon-c, each an feTurbulence type turbulence with baseFrequency "0.028 0.046", numOctaves 3, seeds 7 / 23 / 41, feeding an feDisplacementMap with xChannelSelector R and yChannelSelector G. Scale by job: 3.2 for display strokes, 2.4 for ticks and arrows, 1.6 for the icon set. Never above 4.0 — past that the line turns to mush and reads as a broken render. Filter region x -12% y -12% width 124% height 124% so the displacement is not clipped. Rotate the seed between neighbours so no two strokes wobble identically.

NO CANVAS ANYWHERE. Every texture, edge, shape and stroke is SVG or CSS; a particle system, a confetti burst or a WebGL layer is a ban-list violation here, not an upgrade.

## Color physics (instantiate with the brief's hexes — the physics is law, the hexes are the brief's)
- PAPIER — the ground under everything: the palette's lightest warm neutral pushed warm (the #FBF7F0 register). NEVER pure white — not in text, not in a border, not in an icon stroke.
- LES FEUILLES — three or four PASTEL sheets from the brief's hues, each mixed 12-22% into the papier. They must read as separate sheets: adjacent sheets need at least 4 points of lightness between them or the overlap disappears and the collage collapses into a gradient. Registers only, to show relationships: a blush (#F7E3DC), a sky (#DCE8EE), a mint (#DFEADA), a butter (#F6E9C9). Each sheet gets a SIBLING 6-9 RGB points deeper for cut discs, passe-partout backings, label pills and the ribambelle chain.
- L'ENCRE — a warm dark brown-black where R is greater than G is greater than B (the #2A2018 register). Never #000, never blue-black. All secondary color is an alpha of the ink: body rgba(ink,.78) · captions and petits mots rgba(ink,.58) · placeholders rgba(ink,.42) · soft rules rgba(ink,.12) · strong rules rgba(ink,.24) · contact shadow rgba(ink,.10). A #888 or slate value is a Pass-1 correctness bug.
- LE CRAYON — exactly ONE saturated accent, the palette's brave hue (a real tangerine, coral, cherry or grass, never a pastel). It marks, it does not ground, with the single exception below. Give it a deeper hover sibling (about 12% toward the ink) and a paler sibling for accent type on the accent band.

THE CRAYON HAS AT LEAST TEN JOBS: the underline under one word of the h1 · the circle around one word in the interlude · the friendly numerals · schedule ticks · the arrows of les petits mots · the toise fill line and its major ticks · the primary pill fill · ::selection · :focus-visible · the drawn success check · the strike through a previous price · the dot before each micro-label. An accent living only on a button is a failed palette.

THE ONE EXCEPTION — LE COUP DE CRAYON: exactly ONE full-bleed scene is grounded in the crayon hue, holding one line of type in papier. Two crayon bands is the difference between a warm page and a discount toy catalogue.

CONTRAST LAW: text sits on papier or on a pastel sheet, in the ink. PASTEL-ON-PASTEL TEXT DOES NOT EXIST. Body copy below 1rem never sits on a pastel sheet. On the crayon band, type is papier at full opacity, minimum 1.5rem, weight 600 — never rgba(papier,.7). Verify 4.5:1 on every body pairing before Pass 1; the softness must never cost legibility, because the reader is a tired parent on a phone.

SCRIMS OVER PHOTOGRAPHY: this world honours the global "type never sits on raw image" rule with paper instead of gradient — lay a small cut PASTEL sheet under the type, overlapping the photo edge, rotated, with its contact shadow. Only when type must sit inside the image do you use a gradient: three stops in the ink, rgba(ink,.62) at 0% at the copy's edge, rgba(ink,.22) at 42%, rgba(ink,.04) at 78%, plus a horizontal wash to the copy side.

Declare color-scheme:light on :root and a theme-color meta matching the papier. This world has no dark mode.

## Typography system
TWO families, two sealed jobs. A third family is a bug.
- DISPLAY: a SOFT GROTESK with a tall x-height, generous round counters and slightly softened terminals — the Cabinet Grotesk / General Sans / Bricolage Grotesque / Outfit / Figtree territory. Weights 500-700 ONLY: 800 and 900 read as discount signage, 300 reads clinical.
- TEXT: a humanist sans with open apertures and true tabular figures — the Work Sans / Karla / Public Sans / Source Sans territory. Weights 400 and 500 only.
NEVER A COMIC FACE: Comic Sans, Baloo, Fredoka, Chewy, Patrick Hand, Caveat, Schoolbell and every hand-lettering font are BANNED as display or body. The hand here is DRAWN as SVG, never typed. And per the global rule: never Inter, Roboto or Open Sans.

THE SCALE, ratio about 9:1, with a friendly middle — this world explains things:
- hero h1 clamp(2.9rem, 7.6vw, 6.4rem) / 1.02 / -.02em / weight 600
- section h2 clamp(2rem, 4.4vw, 3.5rem) / 1.06 / -.015em / weight 600 / max-width 14em
- card h3 clamp(1.3rem, 2vw, 1.75rem) / 1.2 / -.005em / weight 600
- lede clamp(1.05rem, 1.4vw, 1.28rem) / 1.62 / 34em / weight 400
- body 1.0625rem / 1.72 / 62ch / weight 400 · petit mot .82rem / 1.5 / rgba(ink,.58)
- micro-label .74rem uppercase weight 600 letter-spacing .12em
- friendly numeral clamp(3.4rem, 9vw, 7.5rem) / .88 / weight 700 / -.03em
- closing wordmark clamp(3rem, 13vw, 9rem) / .9 / weight 700 / -.03em

TWO EXPLICIT OVERRIDES OF THE GLOBAL DEFAULTS. This world overrides the global micro-label tracking band of .16-.30em: here it is .10-.16em, because wide letterspacing reads institutional and undoes the warmth in one gesture. And it overrides the tight-leading habit of the editorial worlds: body runs 1.72 and lede 1.62, because air between lines is what makes a page feel kind. Display still tightens as it grows (.88 on numerals, 1.02 on the h1).

NUMERALS ARE TWO DIFFERENT THINGS, and mixing them is a visible error. FRIENDLY NUMERALS (ages, steps, counts) use PROPORTIONAL figures — a tabular 1 floating in an empty slot looks broken at 7rem — and sit on a cut disc, rotated. WORKING NUMERALS (prices, hours, phones, capacities) use font-variant-numeric: tabular-nums always; hours as 9h00 / 12h30, DZD prices with a THIN SPACE for thousands (3 500 DZD).

NEVER LET A DISPLAY HEADLINE AUTO-WRAP. Break every h1 and h2 into explicit block-level line spans so the rag is AUTHORED, and reuse those spans as the animation stagger targets. Ragged-right, never justified. Centering is allowed in exactly three places: the line inside LE COUP DE CRAYON, the closing wordmark, and the success panel.

THE MARKED WORD — the highest-leverage device here, exactly once per headline: one word wearing a hand-drawn crayon mark. Three marks exist and a page uses at most two: the WOBBLY UNDERLINE (an SVG path 6px below the baseline, stroke-width 7, linecap round, crayon-a at scale 3.2, in the crayon hue), the CIRCLE (an open ellipse whose ends overshoot by about 14 degrees, stroke-width 6, crayon-b), and the HIGHLIGHT (a crayon band at 22% alpha behind the word, drawn as a path with a wobbly top edge at z-index -1). Never two marks in one headline, never a mark on body copy.

## Page chassis
- NO ANNOUNCE BAR. The top of this page is paper.
- THE BANDEAU — the nav is a strip of cut paper, not a bar: position fixed, inset 0 0 auto 0, z-index var(--z-chrome), height 4.4rem, padding-inline var(--gutter), transparent over the hero. Scrolled past 60px: background rgba(papier,.94) plus backdrop-filter blur(10px), and the signature SCALLOPED BOTTOM EDGE — an inline SVG 14px tall, position absolute, inset-inline 0, bottom -13px, preserveAspectRatio none, filled with the same papier tone, so the chrome itself is a cut sheet. Under it, at 34% opacity, a 22px ribambelle chain in a pastel sibling. Transition background-color .5s, transform .42s cubic-bezier(.22,.7,.2,1). Hide on scroll-down past 320px via translateY(-118%), show on scroll-up (ScrollTrigger self.direction), suppressed while the menu is open.
- THE WORDMARK IS A LOCKUP: the business name in display 600 at 1.3rem with ONE letter carrying a cut GALET disc behind it in a pastel sibling at z-index -1, rotated -1.4deg at 1.35x the letter's box. That disc is the page's brand mark — reuse it as the favicon.
- Nav links: text face .88rem weight 500 in rgba(ink,.72) going to full ink, each with a wobbly crayon underline (SVG path, stroke-dashoffset to 0 over .34s power2.out) drawn on hover and on :focus-visible — drawn, never a border-bottom. ONE affordance on the end side: the crayon pill. Never two buttons in the chrome.
- Below 880px: a full-screen PAPER TAKEOVER on a pastel sheet, entering as a sheet dropping from above — translateY(-100%) to 0 over .62s back.out(1.12) — with its own scalloped BOTTOM edge visible as it lands. Links in display 600 at clamp(1.9rem,8vw,3.2rem), each preceded by a small cut disc holding its index, stagger .06s. The burger is A HAND: three crayon-filtered bars of different lengths (24 / 18 / 22px), stroke-width 2.5, linecap round, crossing into an X over .4s. Never three identical rectangles.
- GLOBAL BASE: html and body overflow-x:clip (mandatory — rotated sheets, overlaps, overscan and floaters all overflow), scroll-behavior smooth, scroll-padding-top 5rem, antialiased. ::selection the crayon at 24% with ink text. :focus-visible a 3px crayon outline at outline-offset 3px. A skip link sliding from top -4rem to 1rem over .3s.
- COORDINATED NUMBERS derived once: hero min-height 100svh, sticky offsets top 5.6rem, scroll-margin-top 5rem, and the 4.5rem mobile bar reserved as body padding-bottom below 900px.

## Hero forms (pick the one the business calls for — never the marketplace split)
1. LE GRAND COLLAGE (default). Ground papier, grid 1.06fr/.94fr, gap clamp(2rem,5vw,4.5rem), content starting at 26vh so the sheet has air above it. COPY SIDE: an authored three-line h1 with ONE marked word, a lede at 30em, two affordances (the crayon pill and a ruled text link with the drawn underline), and one petit mot with its arrow. MEDIA SIDE: a photograph clipped to GALET at 42vw / max 560px, rotated +0.9deg, lifted shadow, and behind it the PASSE-PARTOUT — the same shape 12px larger in a pastel sibling, offset x -14px y +16px, rotated -0.6deg. That double sheet is the most recognisable object in this world; it is not optional. THREE floaters maximum: a small scallop at the top-inline-end, a cut arc behind the copy at 6% ink, a crayon squiggle near the pill. The hero ends in a VAGUE cut into the next sheet. SCROLL CUE: a 48px vertical crayon stroke that DRAWS downward on a 2.2s loop (dashoffset full to 0, hold, reset) with a 5px cut dot at its end. Never a chevron, never a bouncing anything.
2. LE MUR (the wall — nurseries, schools, activity clubs, pediatric practices). Ground a full-bleed PASTEL sheet; the composition is the room's wall. The h1 inline-start at clamp(2.9rem,7.2vw,5.6rem) over three authored lines; one photograph in a NUAGE mask pinned by FOUR CORNER MOUNTS (cut triangles in a pastel sibling, 26px, rotated to match); the TOISE drawn down the inline-start margin with three age marks visible, a promise of the showpiece; a ribambelle chain along the bottom at 44px before the cut. Affordances live in a small paper strip under the h1, never floating over the photo.
3. LA PAGE DE GARDE (the endpaper — toy brands, single products, family shops). Ground a pastel sheet. ONE object photograph clipped to COQUILLE at 44vw, centered, on a 5.2s ambient breath, with its passe-partout behind. The h1 WRAPS AROUND the object: two authored lines above, one below, sharing a single optical column. In one corner an oversized friendly numeral on a cut disc carrying the brief's age bracket (3+ / 18 mois). Exactly one affordance: the crayon pill, centered under the last line. No lede — the object is the argument.

## Section seams (Ribambelle's own vocabulary — every boundary uses one, never the same twice in a row; at least five per page)
- LA DÉCOUPE (the cut — the workhorse). The outgoing sheet carries an inline SVG at position absolute, inset-inline 0, bottom -1px (the -1px kills the subpixel hairline), width 100%, height clamp(34px,4.6vw,72px), preserveAspectRatio="none", pointer-events none, aria-hidden, FILLED WITH THE NEXT SHEET'S COLOR. Three authored paths on a 1440x72 viewBox, never the same one twice in a row:
  · VAGUE — one long soft wave: M0 72 L0 26 C240 -4 400 58 640 40 C900 20 1080 -8 1440 22 L1440 72 Z
  · FESTON — seven scallops: M0 72 L0 40, then seven arcs A 103 103 0 0 1 X 40 stepping X by 205.7 across to 1440, then L1440 72 Z. The machine-cut edge of a paper doily.
  · DÉCHIRURE — the torn edge: a 13-point polyline whose y alternates between 18 and 52 with a jitter of plus or minus 9, joined by Q commands at a 6px corner so the tear is soft, never sharp glass.
- LE CHEVAUCHEMENT (the overlap — THE signature seam). The incoming scene's lead element (a photo plate, a card, a quote sheet, the toise's first card) is pulled UP across the boundary at margin-top -4rem to -9rem, at var(--z-lift), rotated, carrying the full two-part shadow so the overlap has real depth. The shadow is what sells it — an overlap with no shadow is just a negative margin. At least twice per page, never adjacent to another chevauchement.
- LE PLI (the fold — the soft color-block cut). A shallow diagonal boundary: clip-path polygon on the incoming sheet at 2.5-4deg (for example polygon(0 3.2%, 100% 0, 100% 100%, 0 100%)), and along the cut, inside that sheet, a 1.5rem gradient from rgba(ink,.06) to transparent — the fold shadow that turns a diagonal stripe into folded paper. Once per page.
- LE COUP DE CRAYON (the loud interlude — exactly ONE per page). A full-bleed scene grounded in the crayon hue, min(64vh, 560px), holding ONE display line in papier at clamp(2.2rem,5.4vw,4.4rem) weight 600, centered, with a drawn CIRCLE around one word in papier at 70% alpha. No heading, no eyebrow, no CTA, no photograph. Top edge a DÉCHIRURE, bottom a FESTON. This is the page's density spike; a generic builder puts three feature cards here.
- LA BANDE (the rail). A full-bleed strip 3.4-4.2rem on a pastel sibling closing a scene: either a 28s marquee of the ribambelle chain with short phrases from the brief, or a flex row of four micro-labels each preceded by a .34em crayon dot, gap 2.4rem, padding-inline var(--gutter); a 2x2 grid below 600px. Once or twice per page, never adjacent to the coup de crayon.
- L'AGRAFE (the pin — a micro-seam, never used alone). A small cut motif laid exactly ON a boundary to pin the sheets: a strip of tape (a rotated rounded rect in a pastel sibling at 42% alpha, 78x26px, one of the five rotations, its two short edges softened with a 2px blur) or a drawn paper clip (a single crayon-b path, stroke 2.5). Twice per page as reinforcement over a découpe or a chevauchement.
- LA MARGE (the asymmetric intro). A scene whose narrow column holds ONLY a friendly numeral on a cut disc plus a 40px crayon tick, and whose wide column starts mid-thought with a lede at weight 400 and no heading at all. Grid .3fr/.7fr. One per page.

## Layout physics
- ONE gutter token: clamp(1.25rem, 4.4vw, 4.5rem) — page padding AND the anchor for every absolutely positioned ornament (floaters, discs, arrows, the toise), so off-grid elements still snap to the margin.
- Container max-width 84rem, margin-inline auto. Sections are always full-bleed; only inner grids are capped. This canvas is deliberately narrower than an editorial world's — closeness is warmth.
- Vertical rhythm is always a clamp whose middle term is vh: clamp(4rem,10vh,7rem) standard · clamp(2.5rem,6vh,4rem) for a scene entered by chevauchement (the overlap ate the space) · clamp(5.5rem,13vh,9rem) closing. Add the cut edge's height to the outgoing sheet's padding-bottom so the cut never eats content.
- NEVER 50/50: 1.06fr/.94fr (hero), .88fr/1.12fr (reversed story), 1.2fr/.8fr (ledger and media), .78fr/1.22fr (questions), .3fr/.7fr (la marge). Alternate reading order with an order-swapping modifier on even indices. Column gaps clamp(2rem,5vw,4.5rem).
- SHAPE COMES FROM CUTTING, and where a radius is used it is a HAND. This world OVERRIDES the global ban on rounded cards, precisely: uniform radius is still banned and rows of identical cards are still banned, but containers here take ASYMMETRIC HAND RADII from a set of three, and no two adjacent containers share a set — 32px 96px 40px 84px · 88px 30px 74px 36px · 44px 46px 100px 38px. Small elements (fields, pills, labels) take a small hand: 14px 22px 16px 20px. Pills are 999px. A container with 16px on all four corners is a violation.
- THE FIVE CUT SHAPES for photographs, declared once as SVG clipPath elements with clipPathUnits="objectBoundingBox" so they scale with any box:
  · GALET (the pebble, the workhorse): M .5 .01 C .74 .01 .96 .17 .98 .43 C 1 .69 .81 .99 .52 .99 C .25 .99 .02 .79 .01 .54 C 0 .3 .26 .01 .5 .01 Z
  · COQUILLE (the scallop): a soft rect whose BOTTOM edge is seven arcs of radius .0715 alternating sweep, top corners eased with .06 cubics.
  · NUAGE (the cloud): the TOP edge is four bumps of unequal radius (.14 / .17 / .13 / .16 — unequal is what makes it hand-cut), the other three edges a soft rect at .05.
  · CERF-VOLANT (the kite): points at (.5,.02) (.98,.44) (.5,.99) (.02,.44) joined by quadratics whose controls bulge 6% outward.
  · PASTILLE (the lozenge): a rounded rect where ONE edge wanders — the inline-end edge is a single quadratic bulging 4% out.
  NEVER REUSE A BLOB PATH IDENTICALLY on one page: nudge three control points by .02-.04 per instance. A perfect circle is not a cut shape and is banned as a photo mask.
- EVERY MASKED PHOTOGRAPH GETS A PASSE-PARTOUT: the same clip on a box 10-14px larger, in a pastel sibling, offset (x -14px, y +16px) or its mirror, rotated one step from the photo's own rotation, at var(--z-sheet) with the photo at var(--z-photo). No borders exist here; the backing sheet IS the frame.
- ASPECT RATIOS carry the silhouette: 4/5 portrait (people, rooms, moments), 1/1 detail (hands, materials, objects), 3/2 wide (the room, the group), 21/9 only inside the toise's pinned frame. Choose object-position consciously per image — a mask cutting a face in half is a Pass-1 bug.
- FLOATER BUDGET, hard: 3 per scene, 9 per page. Each is an inline SVG cut shape or crayon squiggle, 34-90px, in a pastel sibling or the ink at 6-9%, aria-hidden, at var(--z-float) but BEHIND text — never over a word, never over a face. Exactly one floater per page may sit above a photo edge. One per scene below 640px.
- ROTATION BUDGET: at most five rotated elements per scene, four in the hero. A page where everything is rotated reads as an accident, not a hand.
- LEDGERS, NOT FEATURE CARDS, for schedules, age groups, menus and specs: grid-template-columns auto 1fr auto, padding clamp(1.1rem,2.4vw,1.6rem) 0, separated by 2px soft rules in rgba(ink,.12) — this world overrides the global 1px hairline, which reads clinical on paper, so structural rules here are 2px at lower alpha. Each row opens with a crayon tick (crayon-b, stroke 2.5, 18px) and closes with a right-aligned tabular-nums value.
- ONE STICKY ANCHOR per page: a media column at position sticky, top 5.6rem, holding a masked 4/5 plate while three ledger rows pass it.
- THE SHOWPIECE — LA TOISE (the growth chart), specified in Motion. Grid .34fr/.66fr: the ruler in the narrow column, the cards landing in the wide one.
- OVERFLOW IS COMPOSITIONAL: exactly five things break their container — the passe-partout offsets, the chevauchement overlaps, the corner mounts at -12px, the cut discs hanging off a card's edge, and the closing wordmark. Safe only because overflow:clip sits on every scene containing a piercing element. Any parallaxed image is top -12%, height 124% inside its clipped parent, so travel never exposes an edge inside the mask.
- RESPONSIVE: below 1024px two-column grids become one and sticky becomes static; below 900px LA TOISE unpins and the mobile bar appears; below 640px rotations halve, cut edges drop to 34px, floaters drop to one per scene, friendly numerals cap at 4.2rem, and every mask STAYS — the masks are the world, never fall back to rectangles on mobile. Structural collapse only; never delete a scene.

## Motion identity (GSAP 3 + ScrollTrigger via CDN; Lenis optional at lerp .09)
THE SAFETY CONTRACT COMES FIRST. Compute one flag: reduced = matchMedia("(prefers-reduced-motion: reduce)").matches, hasGsap = typeof window.gsap !== "undefined", animate = hasGsap && !reduced. EVERY hidden initial state is set with gsap.set() inside that branch; no stylesheet here contains opacity:0 or a transform on content. If the CDN dies, the page is a complete readable collage — the paper does not depend on JavaScript. With Lenis, expose window.__lenis, drive ScrollTrigger from its scroll event, and kill it under reduced motion.

SHARED IDENTITY: gsap.defaults({ease:"power3.out", duration:.9}). CSS transitions on cubic-bezier(.22,.7,.2,1). power4.out for masked line rises, power3.inOut for clip openings, power2.out for stroke draws, sine.inOut for ambient, none for scrubbed.

THE POP BAND — this world's one motion override. It OVERRIDES the global "entrance reveals .9-1.4s / power3.out" default with a POP-AND-SETTLE band of .7-1.0s on back.out(1.4), on this closed list ONLY: cut discs and friendly numerals · floaters entering · toise cards landing · corner mounts · the success stamp · the mobile bar · pill :active release. Everywhere else the global bands stand. Limits: overshoot never above 1.5 · never on a headline line rise (bouncing text is this genre's amateur tell) · never on a full-bleed sheet · never on more than three elements at once. Interaction feedback .25-.42s, component state .5-.7s, marquee 28s — all inside the global bands. The ambient loop is the world's ONE other timing override: 4-6s instead of the global 3-4s, because a hanging shape breathes slower than a glow pulses, and a 3s drift on a paper cut-out reads as a jitter rather than as air moving in a room.

TRAVEL IS SMALL AND ROTATIONAL: y offsets of 18 / 26 / 34 only, yPercent 112 for masked rises, rotation deltas 1.2-2.6deg, scale deltas .03-.14, parallax yPercent -6 to 6. Nothing slides 100px in a straight line — paper is placed, not thrown.

THE MANDATORY SET:
1. HERO ENTRANCE — one timeline at overlapping absolute positions, complete in about 1.8s. Set: passe-partout x -14 y -16 autoAlpha 0 · photo wrapper scale .9 autoAlpha 0 rotation (rest - 2) · inner img scale 1.16 · h1 lines yPercent 112 · lede and affordances autoAlpha 0 y 22 · floaters autoAlpha 0 scale .6 · the marked word's underline at full dashoffset. Then: passe-partout to rest over .7s power3.out at 0 · photo wrapper to scale 1 / autoAlpha 1 / rest rotation over .95s back.out(1.15) at .12, inner img to 1.04 over 1.6s power2.out · h1 lines to 0 over 1.0s power4.out stagger .10 at .3 · the underline drawing over .62s power2.out at .85 · lede and affordances over .7s stagger .09 at .95 · floaters to autoAlpha 1 scale 1 over .7s back.out(1.5) stagger .12 at 1.1, starting their drift loops onComplete. The paper lands before the words arrive.
2. LE DÉPÔT (the lay-down) — this world's reveal, replacing the fade everywhere. A sheet, card or plate enters at y 26, scale .985, autoAlpha 0, rotation (rest plus or minus 1.2deg) and settles to rest over .85s back.out(1.25) — and its SHADOW CATCHES UP: the two-part shadow lives on a child layer (an absolutely positioned pseudo-element with the same hand radius or clip) whose opacity tweens 0 to 1 over 1.1s power2.out with delay .12. Paper touches down, then the light finds it. start "top 86%", once — worth more than any three other animations here.
3. LA DÉCOUPE DRAW — every cut edge. Duplicate the cut path as a STROKED copy on top (fill none, stroke the ink at 14%, stroke-width 2.5, crayon-a at scale 2.4), set stroke-dasharray from getTotalLength() and animate stroke-dashoffset to 0 over 1.4s power2.inOut, start "top 82%", once. The scissors run along the edge as you arrive.
4. LE TRAIT — every crayon stroke (underlines, the interlude circle, the petits-mots arrows, schedule ticks, the toise fill): dashoffset draw over .62s power2.out on entrance (start "top 88%", once), .34s on hover. The interlude circle draws over .9s power2.inOut and overshoots its start by 14 degrees.
5. L'OUVERTURE — the image reveal. Do NOT animate clip-path path data (fragile across browsers). Scale the CLIPPED wrapper from .86 to 1 over 1.05s power3.out while the inner img counter-scales 1.16 to 1.04 over 1.5s power2.out — de-synced on purpose — with the passe-partout arriving 90ms earlier on its own .9s tween. start "top 86%", once, then clearProps on transform.
6. LA DÉRIVE (the drift). Per floater: gsap.to(el,{yPercent: -4 to -7, rotation:"+=2.4", duration: 4.4 / 5.2 / 6.0, ease:"sine.inOut", yoyo:true, repeat:-1, delay: 0 / .7 / 1.4}). THREE PER SCENE, NINE PER PAGE, never more — the restraint is the design. One masked photograph per page may take the same breath at yPercent -2.5 over 5.2s on its WRAPPER, never on the element ScrollTrigger transforms.
7. MASKED LINE RISES on every display heading: split at REAL browser wrap points (compare offsetTop), preserve em and strong ancestry with a class, run on window.load so font metrics are final, aria-label on the parent and aria-hidden on the lines, then ScrollTrigger.refresh(). yPercent 112 to 0, 1.0s power4.out, stagger .10, start "top 85%", once. Descender-safe masks: padding-bottom .06em, margin-bottom -.06em. NO back.out here, ever.
8. SCRUBBED PARALLAX on full-bleed and large masked photography: gsap.fromTo(img,{yPercent:-6},{yPercent:6, ease:"none"}), start "top bottom", end "bottom top", scrub true — funded by the 124% / -12% overscan.
9. LA TOISE — THE SHOWPIECE (a pinned grow-up timeline). A pin container at min-height 100svh with end "+=320%", pin true, scrub .5, anticipatePin 1, invalidateOnRefresh true. In the narrow column the RULER: a 4px crayon-filtered vertical line in rgba(ink,.16) from 12vh to 12vh-from-bottom, minor ticks every 12% (22px, 2px, rgba(ink,.22)) and a MAJOR tick at each stop (44px, 3px, crayon-filtered, crayon hue). Over it the FILL line in the crayon hue, transform-origin top, scaleY 0 to 1, ease none, scrubbed by the same trigger. THE TRAVELLER: a GALET disc 76px (56px below 900px) in a pastel sibling with a 3px crayon outline, carrying the current label in display 700 at 1.5rem, travelling top to bottom scrubbed with a .5 lag and rotating "+=14" across the journey. THE STOPS: 4-6, from the brief's real content — ages for a nursery (18 mois / 2 ans / 3 ans / 4 ans), hours for a day (8h / 10h / 12h30 / 15h / 17h), steps for a service, milestones for a toy brand. Each stop owns a ScrollTrigger inside the pinned range (start computed as pinStart plus i times range/stops) firing LE DÉPÔT on its card. THE PILE: cards do not replace each other, they STACK like a real pile — at most three visible, each new card landing on top offset (x 10px, y -14px) with its own rotation and hand radius while the ones beneath sink to opacity .38 and scale .96 over .5s; the fourth pushes the oldest out at autoAlpha 0, y -24, over .45s. Each card carries a masked photo, a friendly numeral, two lines of copy and one petit mot. BELOW 900px: unpinned — the ruler becomes a static crayon line down the inline-start gutter, the traveller becomes a per-card badge, each card revealing with the same lay-down at start "top 84%". The pinned version is opt-in inside gsap.matchMedia("(min-width:900px)") with a teardown.
   IF THE BRIEF HAS NO SEQUENCE AT ALL, the showpiece becomes LE MOBILE: five cut shapes hanging from a crayon arc on 1.5px crayon-filtered strings, each group with transform-origin at its string's top, swinging rotation plus or minus 2.6deg on de-synced 3.8 / 4.4 / 5.0 / 4.2 / 5.4s sine.inOut loops, plus one scrubbed rotation of the whole arc from -3deg to +3deg across the scene. Same pinning (end "+=180%"), different instrument.
10. GENERIC REVEALS on roughly fifteen marked elements — ledger rows, label pills, petits mots, trust items, form fields one by one: gsap.set({autoAlpha:0, y:18}) then to({autoAlpha:1, y:0, duration:.8, stagger:.08}), start "top 88%", once. A petit mot reveals 120ms AFTER the element it points at, and its arrow draws after that.
11. COUNT-UPS on real figures from the brief via a tweened proxy over 1.4s power2.out with thin-space thousands, start "top 90%", once, plus a 4000ms setTimeout fallback painting the final value if the trigger never fires on a deep-linked load. True numbers are hard-coded in the HTML.
12. THE RIBAMBELLE MARQUEE: the chain translating -50% over 28s linear infinite, content duplicated for the loop, paused under reduced motion with the chain still fully visible.
13. ALWAYS call ScrollTrigger.refresh() inside document.fonts.ready.then().

MICRO-INTERACTION KIT (CSS, inside the bands): the wobbly underline drawing over .34s · the crayon pill pressing to scale .97 and translateY(2px) over .12s on :active with its offset shadow collapsing from 0 3px 0 to 0 1px 0, releasing over .3s back.out(1.6) · masked photos swelling scale(1.03) over 1.4s on a WRAPPER, never on the element GSAP transforms · a cut disc rotating "+=3deg" over .4s on hover of its card · form label and border turning crayon together over .28s on :focus-within · the accordion icon's vertical bar rotating 90deg over .45s · every :hover rule inside @media (hover:hover) with a keyboard-and-touch parity class.
GLOBAL REDUCED MOTION: animation-duration .01ms !important, animation-iteration-count 1 !important, transition-duration .01ms !important, marquee to animation none with width auto, drift loops stopped, all strokes painted at dashoffset 0, all pile cards visible — alongside the designed static states, never instead of them. once:true on everything non-scrubbed.

## Components
- BUTTONS, two only. PRIMARY is THE CRAYON PILL: border-radius 999px, background the crayon hue, color papier, padding 1.05em 1.9em, display face .92rem weight 600, letter-spacing .01em, inline-flex with gap .55em and a small drawn arrow (crayon-c, stroke 2.2). It carries a PRINTED OFFSET: box-shadow 0 3px 0 0 rgba(ink,.16) — a flat vertical offset reading as a second layer of paper under the button, not a soft UI shadow. On hover the fill goes to the crayon's deep sibling over .3s and the arrow slides 4px. SECONDARY is a ruled text link with the drawn wobbly underline, ink at .82 going to full. No third button, and never a full-width solid rectangle.
- FORMS ARE CUT CARDS, not ruled lines. Field: background the papier lifted 2 RGB points, border 1.5px solid rgba(ink,.14), small hand radius (14px 22px 16px 20px), padding .95em 1.1em, 1.0625rem in the text face. Label ABOVE at .74rem uppercase weight 600 .12em in rgba(ink,.6). On focus three properties move together over .28s: border-color to the crayon, a 3px crayon halo at 18% via box-shadow, and the label to the crayon. Selects match exactly with a DRAWN chevron as an inline SVG background, never the native arrow.
- CHOICE PILLS instead of radios wherever the brief allows (age brackets, days, time slots, formulas): a pill with 1.5px border whose checked state fills with the crayon at 16% and takes a full crayon border over .28s, plus a small drawn check appearing. Real inputs underneath with sr-only labels and full keyboard behaviour.
- VALIDATION IS BLUR-GATED: a touched map so an error appears only after a field's first blur. Errors are full sentences in the world's voice, in a warm brick tone (the only hue outside the palette, used nowhere else), min-height 1.2em reserved so nothing reflows, entering at opacity 0 and translateY(-3px) over .3s, announced with aria-live polite.
- ACCORDION for questions: rows separated by 2px soft rules, the question a full-width flex button in display 600 at clamp(1.1rem,1.6vw,1.32rem), padding 1.4rem 0, opening via grid-template-rows 0fr to 1fr over .5s with an overflow:hidden inner. Icon is a crayon-filtered plus whose vertical bar rotates 90deg to 0. Single-open, aria-expanded maintained, panels with role region.
- THE DRAWN ICON SET: every icon is an inline SVG you author — 22px, fill none, stroke currentColor, stroke-width 1.9, linecap and linejoin round, crayon-a at scale 1.6: a house, a clock, a cup, a hand, a book, a leaf, a shoe, a small sun (a circle with five UNEVEN rays), a phone bubble, a truck. Never emoji, never an icon font, never a filled glyph.
- FAVICON is an inline SVG data URI: the papier as the field, one GALET blob in the crayon hue, one pastel dot. Theme-color matches the papier.
- CRAFT DETAILS: explicit width and height on every image · fetchpriority high on the LCP image, lazy elsewhere · alt text naming what the child or the hand is doing, empty alt plus aria-hidden on decorative duplicates and every floater · sr-only text for icon-only affordances · a skip link · the split headline's aria-label carrying the real sentence · tap targets at least 46px, because half this audience is one-handed with a toddler on the hip.

## Inscription objects (this world converts — the Algerian market shape)
The money here is an enrolment, a visit, a phone call or a WhatsApp thread; for a toy or product brief it is a cash-on-delivery order. These components carry the same design weight as the hero and are built as cut paper like everything else.
- THE INSCRIPTION SHEET sits on its own pastel sheet, entered by a chevauchement, grid 1.2fr/.8fr with the form on the wide side and a masked 4/5 plate plus the trust strip on the narrow side. It collects: full name (autocomplete name) · PHONE, type="tel" inputmode="tel" with a real pattern, the LARGEST field in the form at 1.15rem, because in this market the phone IS the conversion · the child's age as CHOICE PILLS from the brief's real brackets · a styled wilaya select listing the 58 wilayas whenever delivery or travel is involved · address or arrival details · preferred day or time as choice pills · a free note whose placeholder is in voice ("Dites-nous si elle fait encore la sieste").
- PRICE TYPOGRAPHY: display 700, clamp(2rem,3.6vw,2.9rem), tabular-nums, -.02em, THIN SPACE thousands (3 500 DZD), the currency mark in the crayon hue at .52em with vertical-align .34em, and the per-unit qualifier after it in the text face at .82rem in rgba(ink,.58) (par mois / la séance). A previous price is struck with a crayon-colored 2px rule. NEVER a price inside a red badge, never a countdown, never fake scarcity — this audience is choosing care, not chasing a deal.
- WHATSAPP CTA, styled to this world and never a green blob: the crayon pill with a phone-bubble glyph you draw yourself (1.9px stroke, crayon-c), the number in tabular-nums, a .74rem micro-label above. It links to a wa.me URL with a pre-filled message in the page's language and voice, naming the business. Exactly twice per page: the inscription sheet and the mobile bar.
- THE MOBILE BAR: below 900px, fixed to the bottom, revealed once the visitor passes the hero (ScrollTrigger on the hero's bottom, translateY 100% to 0 over .5s back.out(1.2)), height 4.5rem, background rgba(papier,.95) with blur(10px). ITS TOP EDGE IS A CUT: a 12px FESTON SVG above the bar filled with the bar's own color — the motif reaching the bottom of the page. Price or the key fact on the start side, two affordances on the end side (the crayon pill scrolling to the form, and WhatsApp). Its height is reserved as body padding-bottom so it never covers the footer.
- TRUST STRIP: four items, each a small cut pill on a pastel sibling holding a drawn 22px icon, a .74rem micro-label and one factual line from the brief. Laid in a STAGGERED row — vertical offsets 0 / -8px / +6px / -4px and four different rotations — so it reads as four things placed by hand, not a four-column grid. Facts come from the brief ONLY: opening hours, staff ratio, meals included, delivery zone, payment on delivery, first visit free. If the brief does not state it, DROP the item rather than invent it. Never emoji, never star ratings, never a certification nobody granted.
- SUBMIT has a deliberate 700ms pending state whose label becomes a present-tense human sentence, then the form CROSS-FADES IN PLACE into a success panel absolutely positioned in the same box (success in over .7s with delay .25s; form out over .45s to translateY(-10px), visibility switching at .45s so focus never lands on a hidden element). The success mark is a CRAYON CHECK drawing itself (dashoffset over .7s power2.out) inside a cut disc that pops in at back.out(1.4). The panel echoes the parent's own words and says exactly what happens next and when. The moment validation passes — as the crayon check draws — the page passes the note along by dispatching the wandit:lead CustomEvent on document with the parent's fields flat in detail (name, phone as typed, wilaya, commune, plus whatever else the form collects), while one off-canvas decoy input marked data-wandit-hp hides in the margin, never read by the page's own script. No fake server call, no invented reference number unless the brief supplies the scheme.

## Editorial furniture (REQUIRED — this is Ribambelle's voice)
Every page ships all of these, in the page's language and the world's voice. They invent no business fact — they are typesetting and observation, filled from the brief; anything the brief does not supply is DROPPED.
- LES PETITS MOTS — at least FIVE per page, at most one per scene, hand-placed in the margin beside the thing they describe: text face .82rem in rgba(ink,.58), rotated one of the five values, with a 24-34px crayon arrow (crayon-b, stroke 2.2, linecap round, a small open arrowhead) pointing at the element. Observations, never claims: "on enlève ses chaussures ici" · "la sieste commence à 12h30" · "le doudou a le droit de venir" · "cette porte grince, on l'aime bien". Never on a CTA, never two in one scene, never a sales line in disguise.
- LES ÉTIQUETTES — section labels are CUT PAPER TAGS, not eyebrows: a micro-label inside a small pill on a pastel sibling, padding .38em .85em, small hand radius, rotated -1.4deg, preceded by a .34em crayon dot. They replace the letterspaced uppercase eyebrow entirely.
- LES ÂGES — every age bracket in the brief typeset as a friendly numeral on a cut disc with its unit beside it in the text face (18 mois / 3 ans). With no ages, the same object carries group sizes, steps or hours.
- LA JOURNÉE — the day as a ledger: hours in tabular-nums on the start side, a crayon tick, the activity in the text face, one column of right-aligned detail, rows separated by 2px soft rules. A schedule is never a grid of cards here.
- LE CARNET — one human quote from the brief on a rotated cut sheet with two AGRAFE tape strips at its top corners: display 500 at clamp(1.3rem,2.2vw,1.7rem), line-height 1.4, a wobbly crayon underline under two words, attribution beneath at .82rem. Never a script font, never a quote carousel, never a stock portrait.
- LA RIBAMBELLE — the chain itself, the motif that TRAVELS: nine linked cut silhouettes drawn as one inline SVG path (a rounded head-and-shoulders tab whose arms meet its neighbours, each instance nudged 2-3% so the nine are not identical), repeated with use elements, filled in a pastel sibling. It appears three times and only three: 22px under the nav's scallop at 34% opacity, 44px inside one BANDE at full opacity, and clamp(48px,7vw,80px) across the very bottom of the footer.
- LE COLOPHON (the footer, always the last sheet): the business name in display 700 at clamp(3rem,13vw,9rem) rising out of an overflow mask (yPercent 104 to 0, 1.4s power4.out), the practical facts as a ledger (hours, address, phone in tabular-nums, the WhatsApp pill), the ribambelle chain across the bottom edge, and the page's LAST petit mot, placed low and small. The final gesture is the name and the garland, not a link farm.

## Arabic and RTL adaptation
- dir="rtl" on the html element and logical properties everywhere: padding-inline, margin-inline, inset-inline, border-inline-start. A page built on physical left/right will tear itself apart here, because every rotation, offset and cut is directional.
- MIRROR THE HAND. Every rotation value flips sign (+1.8deg becomes -1.8deg) so the collage leans WITH the reading direction. Every passe-partout offset mirrors on x. Every cut-edge SVG takes transform: scaleX(-1) so the wave arrives from the reading side. The ribambelle chain mirrors with it.
- ARABIC TYPE: a soft Arabic display with generous counters and rounded terminals — the Almarai / Rubik / Cairo / IBM Plex Sans Arabic territory, 500-700 for display and 400-500 for text. Sizes run 6-8% larger than the Latin scale and line-heights 0.10-0.14 looser (body 1.84, lede 1.74).
- There is no italic in Arabic and none in this world anyway: the marked word takes the crayon underline plus the crayon color plus a 1.05em size bump.
- NUMERALS: Western Arabic digits (0-9) for the friendly numerals and prices unless the brief explicitly asks for Eastern Arabic digits — the oversized ages must read instantly. Keep tabular-nums on working numerals and the thin space in DZD prices either way.
- Micro-label tracking goes to 0 in Arabic (letterspacing breaks Arabic joins); the labels take weight 600 plus a size bump instead.

## Ribambelle ban list (in addition to the global one)
Clipart of any kind — cartoon suns, smiling animals, balloons, rainbows, alphabet blocks, drawn crayons as illustrations, stars with faces · emoji as icons · any comic or hand-lettering display face (Comic Sans, Baloo, Fredoka, Chewy, Patrick Hand, Caveat, Schoolbell): the hand is DRAWN, never typed · primary-color palettes (fire-truck red plus school-bus yellow plus royal blue) · rainbow or multi-hue gradients · more than ONE crayon-colored full-bleed band · more than 3 floaters per scene or 9 per page · a rotation outside the five values or beyond 2.4deg · uniform border-radius on a content container, or the same hand-radius set on two adjacent containers · perfect circles as photo masks · rectangular photographs with borders · any shadow that is not the two-part paper shadow or the crayon pill's single printed offset · pastel-on-pastel text, or body copy under 1rem on a pastel sheet · pure white anywhere · back.out on a headline line rise (bouncing text) · canvas, confetti bursts, particle systems · speech bubbles with tails used as UI · a straight horizontal boundary between two colored scenes · a boundary made of whitespace plus a rule · 1px hairlines used as structure (2px at lower alpha instead) · stock photography of posed grinning children giving a thumbs-up against white · countdown timers, fake scarcity, red URGENT banners · violet or magenta as the accent (the global rule stands) · testimonial carousels · three-icon feature grids.

PHOTOGRAPHY DIRECTION (for the shot list and for choosing crops): candid and mid-action, natural window light, warm white balance, hands and materials in frame, faces sometimes turned away, the room's real mess allowed. Shallow depth, no flash, no white cyclorama. Every photograph is punched out in a cut shape, so compose knowing the corners will be gone.

## Intensity
This world fails in exactly one way: half-cut. Two seams done properly and the rest left as whitespace; three sheets instead of six; the passe-partout forgotten so the photos read as plain masks; the shadow left off the overlap so the collage flattens into flat design; the petits mots skipped because they felt small. Each omission is invisible alone; together they turn Ribambelle into a pastel template — precisely the thing it exists to replace. It fails the other way faster: a fourth floater, a second crayon band, a cartoon sun, and the page stops being a careful place and becomes a party flyer.

Executed at 100% — sheets overlapping with real shadows, cut edges drawing themselves as you arrive, a photograph punched into a pebble with a second sheet peeking behind it, one word underlined in wax, a paper-doll chain along the footer, and a small line in the margin saying that shoes come off at the door — the page feels like a room somebody prepared for your child. Push INTO the paper. Every number above is load-bearing, and the counts are as load-bearing as the numbers.`,
	energy: "medium",
	id: "ribambelle",
	industries: [
		"baby",
		"kids",
		"nursery",
		"education",
		"school",
		"toys",
		"medical",
		"pediatrics",
		"family",
		"crafts",
		"photography",
		"events",
		"bakery",
		"services",
	],
	kind: "website",
	mood: ["warm", "playful", "handmade", "gentle", "sunny"],
	name: "Ribambelle",
	priceFeel: "accessible",
	tagline:
		"Cut-paper warmth: pastel sheets laid over each other with real shadows and scalloped edges, photographs punched out in pebble shapes, one word underlined in wax crayon — the page of a place that prepared the room for your child.",
};
