import type { DesignWorld } from "./types";

/**
 * SILLAGE — the trail a scent leaves behind.
 * Near-black velvet ground, vapor as the page's material, a bottle floating on
 * a four-second breath above its own cut reflection, the notes pyramid built as
 * typographic architecture with a drawn tie, gold that only shimmers when
 * touched, scenes that evaporate into each other instead of ending, a price
 * whispered in small caps, and a cash-on-delivery form staged as a private
 * commande that closes with a wax seal. Overrides the global radius, shadow,
 * hover-lift, tracking, ease and count-up rules — each override is declared
 * inside the doc. The doc is appended VERBATIM to the builder system prompt.
 */
export const sillage: DesignWorld = {
	avoidFor: [
		"tools",
		"gym",
		"street-food",
		"gaming",
		"fast-food",
		"hard-discount",
		"auto-repair",
		"kids-party",
	],
	doc: `# DESIGN WORLD: SILLAGE — the trail a scent leaves behind

## Philosophy
A sillage is what stays in a room after the person has left. This page is not a product page for a bottle; it is the TRAIL of that bottle rendered as a document. The visitor does not scroll through sections — they walk through air that someone has just walked through, and the page keeps dissolving behind them.

Four laws generate the world. Everything else in this document is a consequence of them, and any decision not covered here should be resolved by asking which law it serves.

LAW ONE — THE GROUND IS AIR, NOT PAPER. The page sits on a near-black warm velvet that is never flat and never lit evenly: three blurred vapor paths drift across the entire document at all times, and one diegetic halo breathes behind the object. When tempted to add a background colour to distinguish a scene, add or subtract LIGHT instead — deepen the velvet by three RGB points, raise the halo, let a plume pass. Flat fills stacked in stripes are how this world dies.

LAW TWO — SCENES EVAPORATE, THEY DO NOT END. The signature seam is the VAPOR-DISSOLVE: the outgoing scene's content blurs, drifts upward and thins out while the next ground rises through it. Exactly two boundaries on the page do this. A boundary announced by whitespace and a hairline is a template boundary and is banned here.

LAW THREE — THE METAL IS ASLEEP UNTIL TOUCHED. Gold is flat, matte and quiet at rest. The ONE place a gradient is permitted as a visible surface is the foil sweep that runs across an accent element on hover or focus and then STOPS. A permanently shimmering element is a casino; a metal that catches the light exactly when a hand approaches it is jewellery.

LAW FOUR — A SILLAGE IS DESCRIBED, NEVER SPECIFIED. This world's copy is evocative by licence, and factual by obligation. Sensation is authorable; duration, concentration, provenance, ingredients, and price are facts and come ONLY from the brief. The page writes what the trail DOES, not what the marketing department wishes it did.

WHAT THIS IS NOT, because a near-black ground invites it: this is not a lit museum room. There is no pool of light travelling from object to object, no plinth-and-cartel grammar, no one-object-per-viewport walk, and no pinned scene of any kind. The subject is not a bottle under a lamp — it is the AIR the bottle has moved through, and air is built from vapor, rationed blur, a masked reflection and typography, never from a spotlight and a label.

Structurally: a vertical sequence of quiet scenes on velvet, one typographic pyramid, two or three dissolves, exactly one scrubbed parallax, ZERO pinned scenes, and a transactional chapter written as a private letter. No carousel, no gallery grid, no product grid, no lightbox, no pinning. The distance between this and a generic dark landing page is not effect budget — it is blur used as a material instead of a filter preset, and restraint held for eleven consecutive scenes.

## The vibe
Late, warm, close, unhurried. A shop that closed twenty minutes ago and still smells of what was open on the counter. The merchant is not selling you anything; they are telling you what a thing does, once, quietly, and then leaving the room. The buyer feels observed by good taste rather than sold to.

Copy rules, non-negotiable — they carry 40 percent of this world:
- EVERY headline is a SHORT DECLARATIVE with no verb of selling: two to six words, ending in a full stop. "Ce qui reste." / "Après vous." / "Le soir, plus proche." / "On le sent avant de vous voir." Never "Découvrez notre parfum d'exception".
- Every scene that carries a claim also carries its reason, in one clause, in the body face: not "tenue longue" but "on le retrouve sur un foulard le lendemain" — and ONLY if the brief supports it.
- ONE HOLD LINE per hold scene: a single line of pure poetry in the display italic, never more than fourteen words, never explained by the paragraph that follows, because no paragraph follows.
- Each note in the pyramid gets exactly ONE sensation word underneath it. "bergamote / vive". "oud / fumé". "musc / peau". Two words is a failure of nerve.
- Validation errors are full sentences in this voice: "Il nous faut votre nom pour l'étiquette." / "Un numéro où l'on peut vous joindre ce soir."
- BANNED WORDS on top of the global list: exception, luxe, prestige, envoûtant, irrésistible, incontournable, sensationnel, unique en son genre, and their Arabic and English equivalents. ZERO exclamation marks on the entire page. No ALL-CAPS shouting outside the micro-cap signage register.
- SILENCE IS CONTENT. At least two scenes carry no CTA, no label, no heading — only an image or a line. A page that sells at every scroll position leaves no trail.

## Visual signatures (what makes it instantly recognizable)
- A warm near-black velvet ground that is never the same twice: three ground steps, six RGB points apart, cutting between chapters.
- Three blurred SVG vapor paths drifting across the whole document forever at 22s, 27s and 31s, opacity oscillating between .04 and .10.
- The object floating in a halo that breathes on a FOUR SECOND cycle, standing on a 1px foil rule, over a reflection that is cut at 46 percent and masked to nothing.
- Gold that is matte until a hand approaches, then sweeps once across the element and settles.
- The NOTES PYRAMID: three ruled tiers of typographic plates with a single gold tie drawn down through them on scroll — the world's best moment and the thing a visitor screenshots.
- Scenes that blur and drift upward into the next scene instead of stopping.
- Micro-caps tracked twice as wide as any other world in this library — perfumery signage is extremely open.
- A price that is deliberately NOT the largest type in its scene.
- A closing wordmark whose letterforms evaporate at their tops through a mask gradient.
- A cash-on-delivery form with no box around it: ruled lines on velvet, like a slip written by hand, sealed at the end with wax.

## Color physics (route the brief's palette through the fixed tokens — the physics is law)
FIXED TOKEN MAP — VELVET→--background · LUMEN→--foreground · GOLD→--primary · VELVET→--primary-foreground · VELVET-WARM→--secondary · GOLD-DEEP→--accent · lumen at 52%→--muted · lumen at 13%→--border · 999px→--radius · DISPLAY→--font-heading · BODY→--font-body. These are the only CSS color/type/radius variables: every pole below is a prose role, literal register hexes belong only in these :root values, and every sibling, foil stop or alpha step is a color-mix(in srgb, var(--foreground) N%, transparent), substituting the mapped fixed token for that pole, or a color-mix between two mapped fixed-token references. Every unmapped role below MUST reuse the nearest mapped token or such a mix; it never gets another custom property or literal. Non-color mechanics may keep their own custom properties. Any rgba(POLE, a) notation below is design shorthand for that color-mix, never emitted CSS.
Build eleven tonal roles from the fixed tokens and never introduce a twelfth hue.
- VELVET (the ground): the palette's darkest WARM pole, a near-black where R is greater than G is greater than B, in the #0B0908 register. NEVER #000, never #111, never a cool charcoal. If the brief's dark pole is cool, warm it by 3-4 points on red before tokenising it.
- VELVET-DEEP: three to four RGB points below VELVET (the #060504 relationship). Used for the well under the object, the hold scenes and the footer.
- VELVET-WARM: five to six points ABOVE velvet and warmer still (the #14100C relationship). Used for the pyramid and the commande chapter. These three grounds are the entire background system — no fourth dark exists.
- LUMEN: a warm off-white cream in the #EFE6D8 register, used for ALL text on velvet. PURE WHITE IS NEVER USED ANYWHERE ON THIS PAGE, including in SVG strokes, rules and icons.
- LUMEN AT ALPHA — this rule is what makes the page read as air rather than as UI. Body copy rgba(lumen,.74) · captions and tertiary rgba(lumen,.52) · micro-signage rgba(lumen,.42) · hairlines rgba(lumen,.13) · strong rules rgba(lumen,.22) · placeholder rgba(lumen,.30) · input ground rgba(lumen,.035), lifting to rgba(lumen,.06) on focus · the wordmark monument rgba(lumen,.09). NO INDEPENDENT GRAY HEX EXISTS on this page. Declaring any #888 / #666 / slate value is a pass-1 correctness bug.
- GOLD: the brief's metallic accent, matte, in the #B9932F / #C9A227 register. Flat by default.
- GOLD-PALE: the highlight sibling, the #E8D9A8 register. It exists ONLY inside the foil gradient and as text on the light-inverted chapter.
- GOLD-DEEP: the shadow sibling, the #7C5F22 register. Inside the foil gradient, and as the accent colour whenever the ground is light.
- THE FOIL GRADIENT (one declaration, reused everywhere): linear-gradient(100deg, gold-deep 0%, gold 20%, gold-pale 36%, gold 52%, gold-deep 74%, gold 100%) at background-size 260% 100%. It is never visible at rest — see the foil law below.
- SMOKE: rgba(lumen,.06) to rgba(lumen,.12) — the fill colour of the vapor paths. The vapor is never gold and never coloured; smoke that glitters is glitter.
- ERROR is not another hue: validation uses a smoked color-mix between var(--primary) and var(--foreground), nowhere else.

THE FOIL LAW (this world's central colour rule, and the one override of the global "gradients are fine as atmosphere" instinct). Gradients as VISIBLE FILLS are banned everywhere on this page with exactly four sanctioned exceptions, each named here and nowhere else: (1) the foil sweep on hover/focus of an accent element; (2) the diegetic halo behind the object, which is a radial light, not a decoration; (3) mask-image and scrim gradients, which paint transparency rather than colour; (4) the foil SEAM rule, a 1px line whose gold fades to nothing at both ends. Anything else — a gradient section background, a gradient button at rest, a gradient text headline that is always coloured — is a failure of this world.

THE FOIL SWEEP, executed: at rest the accent element carries NO background-image and a flat gold ring or flat gold text. On :hover and :focus-visible it gains the foil gradient with background-size 260% 100% and background-position transitions from 0% 50% to 100% 50% over 1.1s cubic-bezier(.32,.06,.24,1); on leave, background-position returns to 0% 50% over .5s and the image is removed after the transition. For gold TEXT (the accent word in a headline, the currency mark, the tier marks) the same gradient is applied with background-clip:text and -webkit-text-fill-color:transparent ONLY in the hover state, wrapped in an @supports (background-clip: text) or (-webkit-background-clip: text) block, with color:gold as the always-present fallback so a non-supporting browser simply sees flat gold. The sweep runs ONCE per interaction. There is no infinite shimmer anywhere on this page.

OPTIONAL, AT MOST ONCE PER PAGE — THE PARCHMENT INVERSION. Exactly one chapter (the commande, or the pyramid, never both) may invert to the palette's light pole. When it does, scope a full token override on that scene: ground becomes the light pole, ink becomes VELVET, every rgba(lumen,X) becomes rgba(velvet,X) at the same alphas, the accent becomes GOLD-DEEP (pale gold is invisible on cream), the vapor layer's mix-blend-mode flips from screen to multiply and its opacity drops to .05, and the grain flips from overlay to multiply at .12. Transition nothing — the ground change is a hard cut in the DOM, and the dissolve seam does the smoothing on either side of it. If the builder is not confident it can hold every one of those substitutions, do not invert; velvet all the way down is a legitimate and beautiful page.

## Typography system
TWO FAMILIES ONLY, plus one italic. This world deliberately overrides the three-family habit of the editorial worlds: a perfume house sets everything in one serif and one signage sans, and the discipline is the point.
- DISPLAY — a high-contrast serif whose thins nearly vanish, in the Cormorant Garamond / Bodoni Moda / Prata / Playfair Display territory. Weights 300 and 400 ONLY. There is no bold display type on this page, at any size; a didone at 600 is a magazine cover, not a sillage. It carries: the h1, every h2, note names, prices, totals, the order reference, the wordmark and the closing monument.
- SIGNAGE — a light geometric or humanist sans in the Jost / Josefin Sans / Questrial / Archivo territory. Weights 300 and 400 ONLY. It carries: every micro-cap label, the tier marks, form labels, button text, hints, the drift rail, and the currency mark.
- THE DISPLAY ITALIC — loaded as its own weight (300 italic) and used for exactly ONE job: the poetry voice. Hold lines, tier roles, figure sensations, the closing sillage line. It is NEVER used upright and never used for anything factual. That self-restriction is part of the world.
Body copy is the SIGNAGE face at 400, not the serif — a high-contrast serif at 16px on a dark ground is unreadable, and this world would rather be legible than picturesque.

Scale (all clamp, all measured):
- Hero h1: clamp(2.9rem, 7.4vw, 6.2rem) / line-height 1.02 / letter-spacing -.015em / display weight 300.
- Scene h2: clamp(2rem, 4.4vw, 3.5rem) / 1.08 / -.01em / display 300 / max-width 14em.
- Sub-head h3: clamp(1.25rem, 2vw, 1.6rem) / 1.2 / -.005em / display 400.
- Hold line (poetry): clamp(1.5rem, 3.2vw, 2.55rem) / 1.42 / +.005em / display 300 ITALIC / max-width 18em.
- Note name: clamp(1.02rem, 1.5vw, 1.28rem) / 1.25 / 0 / display 400 — and the tier taper (see the pyramid) steps it down.
- Price: clamp(1.6rem, 2.6vw, 2.2rem) / 1 / +.005em / display 400 / tabular-nums.
- Body: 1.0625rem / 1.78 / 0 / signage 400.
- Lede: clamp(.98rem, 1.15vw, 1.1rem) / 1.7 / 0 / rgba(lumen,.74) / max-width 26em.
- Micro-caps: .60rem to .78rem uppercase, signage 400.
- Closing monument: clamp(3.4rem, 14vw, 12rem) / .9 / POSITIVE .14em.

TRACKING IS EXTREME AT THE SMALL END AND THIS WORLD OVERRIDES THE GLOBAL .16-.30em MICRO-LABEL BAND. Perfumery signage is twice as open as editorial signage. The values, and use only these: .24em on button labels · .28em on figure numbers · .30em on form labels and trust-strip titles · .34em on eyebrows and price labels · .36em on the drift rail · .38em on the pyramid tier marks · .42em on the wordmark sub-label. At the large end: -.015em above 80px, -.01em at 34-64px, -.005em at 24-32px, 0 at body. Target a display-to-micro size ratio of at least 9:1 — a generic page sits at 3:1.

THE WHISPERED PRICE — the small-caps rule. The price NUMERAL is display 400, tabular-nums, with thousands separated by a NARROW NO-BREAK SPACE, written as the HTML entity &#8239; so it survives every copy-paste: 12&#8239;900. The currency mark follows the numeral in the SIGNAGE face at .40em with font-variant-caps: all-small-caps, letter-spacing .30em, colour rgba(lumen,.52), vertical-align .42em — DZD on a French page, دج on an Arabic one, written exactly as the brief writes it, never a symbol glued to the numeral. If the loaded signage face has no true small caps, fall back to text-transform:uppercase at font-size .78em of that same .40em — declare the fallback, do not leave it to chance. The price label above the row is signage .62rem at .34em in rgba(lumen,.40), and it names what the price buys ("50 ML — FLACON", "COFFRET DE 3"), never "PRIX".

MANDATORY TYPE RULES: no display headline ever auto-wraps — break every h1 and h2 into explicit block-level line spans, author the rag, and reuse those spans as masked-reveal targets · text-wrap: pretty on body copy · tabular-nums on every price, total, quantity and reference · ONE word per page may take the gold accent inside a headline, and only in the h1 · PROMOTE NUMERALS: inside any sentence carrying a quantity, wrap the number in a span set in the DISPLAY face at 1.28em in rgba(lumen,.95) inside a .95rem signage line, so "50 ml, tiré à 120 pièces" carries two type registers in one sentence · nothing on this page is centred except, optionally, the closing monument and one hold line.

## Page chassis
- NO ANNOUNCE BAR. This world does not open by shouting a promotion. If the brief carries a delivery promise, it lives in the trust strip and in the commande, never in a strip above the masthead.
- THE MASTHEAD: position FIXED (not sticky — vapor must be able to pass beneath it), top 0, inset-inline 0, height 4.6rem, z-index 70, background transparent, no border, no shadow. Contents: the wordmark lockup on the leading edge, and on the trailing edge exactly one quiet ruled link ("commander") — no nav list, no burger, no logo-left-links-centre-button-right bar.
- On scroll past 64px it gains a scrolled class: background rgba(velvet,.72), backdrop-filter blur(18px) saturate(118%), and a FOIL SEAM as its block-end edge. Transitions background-color and backdrop-filter over .7s with the shared ease. Remove the class below 64px; the transition back runs at the same duration.
- WORDMARK IS A LOCKUP, NOT A WORD: the business name in the display face at 400, 1.28rem, letter-spacing .30em, uppercase, in lumen; directly beneath it a signage sub-label at .58rem, .42em tracking, uppercase, rgba(lumen,.42) — the house's one-line register from the brief ("parfumeur · alger" / "bougies coulées à la main"). Two type registers inside one mark, line-height 1.35 between them.
- THE VAPOR LAYER (the world's atmosphere, and the thing that makes it): position fixed, inset 0, z-index 2, pointer-events none, mix-blend-mode screen. An inline SVG with preserveAspectRatio="none" holding THREE soft plume paths — closed bezier shapes, no strokes — filled with SMOKE at opacity .07, .05 and .035 respectively and blurred with filter blur(7px), blur(9px), blur(11px). Each drifts on its own CSS keyframe (see motion). This layer is present on EVERY scene; it is not a hero effect.
- THE GRAIN: position fixed, inset -50%, z-index 3, pointer-events none, opacity .09, mix-blend-mode OVERLAY. Note the override: on a dark ground the multiply grain used by the light worlds is invisible; overlay or soft-light is mandatory here. Background-image is an inline SVG data URI of feTurbulence type fractalNoise baseFrequency 0.9 numOctaves 2 stitchTiles stitch, desaturated with feColorMatrix saturate 0, painted onto a 240x240 rect at opacity 0.55.
- Global base: html and body overflow-x: clip · scroll-behavior smooth · -webkit-font-smoothing antialiased · text-rendering optimizeLegibility · color-scheme: dark on :root · meta theme-color set to the velvet ground · ::selection background rgba(gold,.24) with color lumen · :focus-visible outline 1px solid gold at outline-offset 4px PLUS box-shadow 0 0 0 5px rgba(gold,.12) · a skip link sliding from top:-4rem to top:1rem over .4s with the shared ease.
- THE COORDINATED NUMBERS — derive all of them from the measured masthead, never guess them independently: masthead height 4.6rem · hero min-height calc(100svh - 4.6rem), using svh so mobile browser chrome does not clip the composition · sticky column offset top 6.2rem · scroll-margin-top 5.4rem on every anchored scene · sticky mobile order bar height 4.4rem, so below 860px the footer takes padding-block-end 5.6rem plus env(safe-area-inset-bottom).
- SPACING: one inline padding token, clamp(1.4rem, 5vw, 5rem). Container max-width 78rem — narrower than an editorial world on purpose; this page is intimate. A NARROW container at 46rem exists for the hold lines and the commande. Scene block padding clamp(6rem, 14vh, 11rem), with the mobile floor at 4.5rem.

## Hero forms (pick the one the brief's photography calls for — all three are LOADED)
1. LE FLACON (default, and the one to use when the brief supplies a packshot). A full-height stage with a three-point composition AROUND the object rather than a column beside it.
Section: min-height calc(100svh - 4.6rem), display grid, grid-template-rows minmax(0,1fr) auto, padding-block-start 4.6rem, padding-inline the pad token, padding-block-end clamp(2.4rem,5vh,4rem), overflow clip, position relative.
ROW 1 — THE STAGE, position relative, display grid, place-items center, five layers:
- z0 THE WELL: absolute, inset 0, background radial-gradient(ellipse 54% 40% at 50% 64%, velvet-deep 0%, transparent 72%). The floor darkens under the object.
- z1 THE HALO: absolute, left 50%, top 42%, width min(46rem,118%), aspect-ratio 1, transform translate(-50%,-50%), background radial-gradient(circle, rgba(gold-warm,.30) 0%, rgba(gold,.10) 34%, transparent 66%), filter blur(14px), pointer-events none. This is the breathing glow and it is DIEGETIC — it is the object's own light on the air, not a decorative blob.
- z2 THE PLUME: an inline SVG rising from the object's shoulder, width 60% of the stage, height 130% (it overflows the stage top, which is legal because the stage is clipped), three paths at opacity .12 / .08 / .05, blurred 8px, drifting on the vapor keyframes at a phase offset from the global layer.
- z3 THE FLACON: the product image at width min(30vh, 20rem) — HEIGHT-DRIVEN, never width-driven, so a short laptop viewport never crowds it. object-fit contain, filter drop-shadow(0 22px 34px color-mix(in srgb, var(--background) 60%, transparent)), fetchpriority high, explicit width and height attributes, real art-directed alt.
- z4 THE REFLECTION: the SAME image duplicated with alt="" and aria-hidden="true", inside a wrapper whose max-height is 46% of the object's height with overflow hidden. transform scaleY(-1), transform-origin top, margin-block-start -2px, opacity .34, filter blur(1.2px) saturate(.85), and mask-image linear-gradient(to bottom, color-mix(in srgb, var(--foreground) 85%, transparent) 0%, color-mix(in srgb, var(--foreground) 28%, transparent) 32%, transparent 68%) with the -webkit- prefix duplicated. THE CUT AT 46 PERCENT IS LOAD-BEARING: a full mirror is a 2009 effect; a masked 46 percent reads as a polished surface.
- z5 THE PLINTH: a 1px FOIL SEAM at width min(24rem,70%) sitting exactly at the object's base, opacity .5. The object stands ON something. Without this line it floats in a void and the whole composition loses its weight.
ROW 2 — THE FOOT, a three-column grid at grid-template-columns 1.15fr .7fr auto, gap clamp(1.6rem,4vw,3.4rem), align-items end:
- COLUMN A carries the offer: an eyebrow at .70rem/.34em uppercase in rgba(lumen,.46) preceded by a 1.8rem by 1px gold rule; the hand-broken h1 in two or three authored line spans; the lede at clamp(.98rem,1.15vw,1.1rem)/1.7 capped at 26em.
- COLUMN B is THE NOTES TEASER, and it is what stops this hero being a marketplace hero: three rows, tête / cœur / fond, each a .62rem/.38em uppercase tier mark in rgba(gold,.82) followed by that tier's note names in the display face at .95rem in rgba(lumen,.78), separated by a 3px gold square rotated 45deg. It ties forward to the full pyramid, and its notes come only from the brief.
- COLUMN C carries the price whisper (label, numeral, small-cap currency) and beneath it the foil CTA plus the quiet WhatsApp pill.
Below 900px the foot becomes one column in the order A, C, B — the notes teaser goes last, because on a phone the price and the CTA must be reachable before the poetry.
The hero TERMINATES IN THE DRIFT RAIL, never in whitespace.

2. LA PYRAMIDE (use when the brief names the notes and the merchant is selling the composition rather than the flacon). The three tiers ARE the hero. The h1 sits SMALL at clamp(1.9rem,3.4vw,2.8rem) on the leading edge at the top of the scene with its eyebrow, the price whisper sits directly under it, and the three ruled tiers descend the full height of the viewport with the product photographed small (width min(18vh,11rem), contained, with its own halo and a 30 percent reflection) floating on the trailing edge at the vertical centre of the CŒUR tier. The tie is drawn on load rather than on scroll. The drift rail closes it. This hero is the most distinctive in the library and should be chosen whenever the content supports it.

3. LE SILLAGE (use when the brief supplies a lifestyle or atmosphere shot rather than a packshot). The image is full-bleed and cover-cropped with the double scrim (see layout physics), the object or the subject sits at 62 percent down on the trailing edge, and a SINGLE SVG TRAIL PATH — 1px stroke in rgba(gold,.55), no fill — travels from that point up and across the composition to the leading edge where the h1 begins. The path is drawn on load via stroke-dashoffset over 1.8s power2.inOut. The headline sits BELOW the trail's terminus, the price whisper below that. The halo becomes a soft pool at the subject's base instead of a full circle. Same drift rail, same foot structure.

Every hero form, without exception, carries: the halo, a reflection or a base pool, the plinth line, the price whisper, a CTA, and the drift rail. A hero without a price is banned in this world.

IF THE BRIEF SUPPLIES NO PACKSHOT, OR IMAGE GENERATION FAILS: nothing is left empty and no grey placeholder is ever drawn. The stage keeps the well, the halo, the plume and the plinth line, and the object's place is taken by THE NAME — the product or house name in the display face at clamp(2.4rem,7vw,5rem), weight 300, uppercase, letter-spacing .14em, in rgba(lumen,.92) — carrying its own masked reflection: the same duplicated element with aria-hidden, the same scaleY(-1), the same 46 percent cut and the same mask gradient. Write the reflection rules against a CLASS, not against an img selector, precisely so this fallback costs nothing. A scene here is always light standing on a line above its own echo, with or without a photograph.

## Section seams (SILLAGE's own vocabulary — every boundary uses one, never the same twice in a row)
1. THE VAPOR-DISSOLVE — the signature. Use it EXACTLY TWICE per page (two dissolves plus the one parallax is the world's whole scrub budget), never on consecutive boundaries, and NEVER on the boundary leading into or out of the commande chapter (a form must never blur). Execution: wrap the outgoing scene's content in an inner div and scrub it — gsap.to(inner, {filter:"blur(13px)", yPercent:-9, autoAlpha:.05, ease:"none", scrollTrigger:{trigger:scene, start:"bottom 84%", end:"bottom 24%", scrub:.6, onToggle: add/remove a class that sets will-change:filter,transform}}). Simultaneously a VEIL element inside the outgoing scene — position absolute, inset-inline 0, bottom 0, height 34vh, pointer-events none, background linear-gradient(to top, the NEXT scene's ground 0%, transparent 100%) — is already in place, so the incoming ground appears to rise through the evaporating content. The next scene starts at padding-block-start 0, welded. PERFORMANCE AND FALLBACK CONTRACT, mandatory: the blur is capped at 13px; will-change is applied only while the trigger is active; below 860px OR under prefers-reduced-motion the dissolve degrades to yPercent and autoAlpha with NO blur at all; if GSAP is absent, nothing happens and the scenes simply butt-join, which still looks correct.
2. THE VEIL PASS — a full-bleed 26vh band between two scenes containing nothing but a slow SVG vapor sweep at opacity .10 over the incoming ground, drifting 26s. No text, no label, no rule. Use once.
3. THE HOLD — a scene of pure poetry: velvet-deep ground, min-height 46vh, ONE italic display line at the hold-line scale, max-width 18em, positioned at 38 percent from the leading edge (not centred), with a 2.6rem by 1px gold rule above it and, if and only if the brief supplies one, a micro-cap cite beneath at .62rem/.38em in rgba(lumen,.34). No heading, no CTA, no explanation. Use twice.
4. THE FOIL SEAM — a 1px rule whose gold fades to nothing at both ends: height 1px, background linear-gradient(90deg, transparent 0%, rgba(gold,.42) 22%, rgba(gold,.42) 78%, transparent 100%). It appears at exactly FIVE places and nowhere else: the plinth under the object, the block-end edge of the scrolled masthead, the top of the pyramid's first tier, above the total row, and the block-start edge of the sticky mobile bar. It is NOT a scene boundary — this world never separates two scenes with a rule and whitespace alone.
5. TEMPERATURE SHIFT — consecutive chapters cut between VELVET, VELVET-DEEP and VELVET-WARM. Four to five ground changes across a ten-scene page. Hard cuts, no transition; the dissolves smooth what needs smoothing.
6. REFLECTION WELD — one scene's closing object hangs its reflection across the boundary via a negative margin-block-end, and the next scene begins at padding-block-start 0 underneath it. Use once, and give the crossing element a real z-index.
7. THE DRIFT RAIL — a 2.6rem band with border-block 1px rgba(lumen,.09) holding a width:max-content flex track of TWO identical chunks translating -50% over 34s linear infinite (CSS keyframes, never GSAP). Items are signage .66rem at .36em uppercase in rgba(lumen,.40), separated by a 3px gold square rotated 45deg. Its content is note names and material facts from the brief — never slogans, never a promotion. Under prefers-reduced-motion: animation none and width auto.
8. THE PARCHMENT INVERSION — at most once, with the full token override declared in colour physics.

## Layout physics
- RADIUS LAW — exactly THREE radius treatments exist: 0 on every rule, band, plate, frame and image · var(--radius) on the CTA pills, WhatsApp pill and stepper group (:root sets --radius: 999px; true status dots use 50%) · min(var(--radius), 2px) on inputs, the select and the textarea. These var(--radius)-derived declarations are the single sanctioned corner mechanism; another treatment means the page has drifted. The rationale is compositional: the bottle is the only curve in the frame, so everything around it stays orthogonal for that curve to read.
- SHADOW LAW — this world overrides the global permissiveness. Shadows exist in exactly FOUR places, all modelling AIR and never elevation: under the floating object, 0 22px 34px color-mix(in srgb, var(--background) 60%, transparent) · under the sticky mobile bar, 0 -14px 34px -20px color-mix(in srgb, var(--background) 70%, transparent) · the focus bloom, 0 0 0 5px color-mix(in srgb, var(--primary) 12%, transparent) · the foil CTA's hover bloom, 0 0 22px -8px color-mix(in srgb, var(--primary) 35%, transparent). ZERO shadows on plates, inputs, the masthead or any content block. No card carries a shadow because no card exists.
- BLUR IS RATIONED — the world's most abusable material and the fastest way to turn it into fog. backdrop-filter appears at exactly TWO sites: the scrolled masthead (18px) and the sticky mobile bar (16px). The dissolve veil uses a gradient, not a backdrop-filter. filter: blur() appears on the halo (14px), the vapor paths (7/9/11px), the plume (8px), the reflection (1.2px) and the dissolving wrapper (0 to 13px). That is the complete list; a translucent panel with a border and a shadow is glassmorphism and is banned.
- PLATES, NOT CARDS. Every information block is a PLATE: background transparent, border 0, ONE 1px rgba(lumen,.13) rule on the block-start edge, padding clamp(1.5rem,3vw,2.2rem) 0 0. To distinguish a plate from its neighbours give it EITHER a background of rgba(lumen,.028) OR a rule on the inline-start edge — never both, never four edges, never a fill plus a border plus a radius.
- NO GRID IS 50/50. Skew every two-column grid and argue the direction from content weight: hero foot 1.15fr / .7fr / auto · the story chapter .82fr / 1.18fr, with the MEDIA column the wider one because the object needs air · the commande 1.12fr / .88fr, the form wider than its plate · the questions .72fr / 1.28fr, the heading column smaller than the list. Column gaps clamp(2rem,5vw,5rem).
- MEASURES ARE CAPPED IN EM: body 32em · lede 26em · hold line 18em · note caption 20em · form sub-copy 30em · h2 14em. Line length must survive a font-size change.
- OVERFLOW IS COMPOSITION. Exactly three elements deliberately break their container: the halo at width 118%, the plume at height 130%, and the reflection hanging below the stage floor in the reflection weld. Safe only because overflow:clip sits on the stage and every scene containing a piercing element, plus overflow-x:clip on html and body.
- ZERO-ROW-GAP RULED LISTS for every spec, ingredient list or delivery table: display grid, gap 0, each row separated by a 1px rgba(lumen,.10) rule, each row a space-between flex with a signage micro-cap term at .68rem/.30em in rgba(lumen,.46) on the leading side and a display-face value at 1.05rem with tabular-nums on the trailing side. Below 560px it becomes one column with the value falling under its term. NEVER a bordered table, never three columns of cards.
- IMAGE POLICY: every product or detail image is CONTAINED against the velvet with 10-16 percent breathing room and zero radius. EXACTLY ONE image on the page may be full-bleed and cover-cropped — the atmosphere shot — and it carries a double scrim: linear-gradient(to top, velvet 0%, rgba(velvet,.55) 42%, rgba(velvet,.08) 100%) plus a second inline-start scrim linear-gradient(to right, rgba(velvet,.7), transparent 46%) so type never sits on raw image. That image also carries the overscan that funds the page's one parallax: top -11%, height 122%, inside an overflow:hidden parent.
- FIGURE CAPTIONS under every framed image: a space-between row with the description in rgba(lumen,.48) at .74rem/.06em on the leading side and a fig number in gold at .68rem/.28em on the trailing side.
- RESPONSIVE COLLAPSE: below 1024px every multi-column grid becomes 1fr and sticky becomes static · below 900px the hero foot reorders to A, C, B · below 860px the dissolve loses its blur and the sticky order bar appears · below 720px each pyramid tier becomes one column, the tier mark row going space-between above its plates · the flacon narrows to min(64vw, 15rem) with the reflection cut to 34 percent · the drift rail slows to 44s at .60rem · the trust strip becomes a 2x2 grid at gap 1.2rem with rules only on the block edges.

## The notes pyramid (this world's structural centrepiece — build it exactly)
A scene at container max-width 62rem holding THREE TIERS stacked vertically. Each tier: display grid, grid-template-columns clamp(5.5rem,9vw,8rem) 1fr, gap clamp(1.2rem,3vw,2.4rem), padding-block clamp(2rem,4.5vh,3.2rem), border-block-start 1px rgba(lumen,.12) — except the first tier, whose rule is the FOIL SEAM.
- LEFT CELL — THE TIER MARK: the tier name in signage micro-caps at .66rem, tracking .38em, uppercase, in rgba(gold,.82); beneath it the tier's ROLE in display 300 ITALIC at .92rem in rgba(lumen,.44) — "la première minute" / "la première heure" / "ce qui reste". Two registers in one small cell; that pairing is what makes it read as typeset rather than listed.
- RIGHT CELL — THE NOTE PLATES: display flex, flex-wrap wrap, gap clamp(.8rem,1.6vw,1.4rem). Each plate: padding .55rem .95rem .6rem 0, a 1px rgba(lumen,.13) rule on the INLINE-START edge only, no background, no radius. Inside: the note name in the display face at the tier's size in lumen, and beneath it ONE sensation word in signage at .60rem/.30em uppercase in rgba(lumen,.42).
- THE TAPER IS TYPOGRAPHIC, NOT GEOMETRIC. Never draw a triangle, never taper the widths, never centre the tiers. "Pyramide" is perfumery's word and this world honours it in the TYPE: tête plates at 1.28rem with four to six notes · cœur at 1.16rem with three to four · fond at 1.06rem with two to three. And each tier's ground steps one shade deeper (velvet → two points below → velvet-deep) so the composition sinks as it descends.
- THE RULED TIES — the world's best moment. An SVG overlay absolutely positioned across the whole pyramid (inset 0, pointer-events none, preserveAspectRatio="none", viewBox in percentage-friendly coordinates such as 0 0 100 100) draws ONE continuous 1px path in rgba(gold,.28) that leaves the first tier mark, ties across to its first note plate, then descends and curves into the second tier mark, and again into the third — a single trail falling through the composition. Draw it on scroll: read path.getTotalLength(), set strokeDasharray and strokeDashoffset to that length, then animate strokeDashoffset to 0 over 1.8s power2.inOut at start "top 78%", once:true. FALLBACK CONTRACT: if getTotalLength is unavailable or returns 0, set pathLength="1" on the path and animate dasharray 1 / dashoffset 1 to 0 instead; if GSAP is absent, the path renders fully drawn with no animation. It must NEVER render invisible.
- CONTENT LAW: the notes come only from the brief. If the brief names no notes, keep the identical architecture and fill it with whatever three-tier truth the product actually has — for a candle: mèche / cire / parfum; for a body oil: texture / absorption / peau; for a soap: matière / mousse / après. NEVER invent a fragrance note, a concentration, or a hold time.

## Motion identity (GSAP 3 + ScrollTrigger from a CDN; native scroll — smooth-scroll libraries are unavailable)
THE SAFETY CONTRACT COMES FIRST AND IS NON-NEGOTIABLE. Compute one flag: reduced = matchMedia("(prefers-reduced-motion: reduce)").matches; hasGsap = typeof window.gsap !== "undefined"; animate = hasGsap && !reduced. EVERY hidden initial state — every autoAlpha 0, every y offset, every scaleX 0, every dashoffset — is set with gsap.set() INSIDE the animate branch. Never author opacity:0 or visibility:hidden in CSS for an animated element. If the CDN fails or motion is reduced, the page is fully visible, fully readable and fully orderable. Add a CSS prefers-reduced-motion block that, beyond the blanket .01ms override, sets the vapor paths and the drift rail to animation:none, stops the halo breath, renders the tie and the envelope in their final state, and disables the dissolve blur.

gsap.defaults({ ease: "power2.out", duration: 1.2 }) — this world OVERRIDES the global power3.out / 1.1s default. power3's deceleration is too abrupt for air; everything here settles late and softly.

TIMING BANDS — this world overrides the global bands on the fast end, because nothing in a perfume house snaps: .30-.50s interaction feedback (ring, dot, rule, colour) · .60-.90s component state (accordion, sticky bar entry, total recompute, theme swap) · 1.1-1.6s entrance and narrative reveals · 1.8s the trail draw · 2.2s the flacon settle · 4s exactly the halo breath · 20-31s vapor drifts · 34s the drift rail. NOTHING on this page is faster than .30s. ONE shared CSS easing token, cubic-bezier(.32,.06,.24,1) — a long, late deceleration — carrying roughly twenty transitions. GSAP eases: power2.out for entrances, power1.inOut for settles, sine.inOut for ambient, power2.inOut for the trail and the flap, none for every scrub.

TRAVEL DISTANCES ARE TINY. y offsets of 10 / 18 / 26 / 38 only. Scales of .82 (the halo's start) / .96 / 1.03 / 1.06. NOTHING travels 100px. And note the hover override: NOTHING ON THIS PAGE LIFTS ON HOVER. This world overrides the global hover-lift micro-interaction, because nothing here is a physical card sitting above a surface. Hover changes LIGHT — the foil sweeps, a rule brightens, an opacity steps up. The single exception is the CTA's arrow glyph nudging translateX(3px).

THE MANDATORY MOTION SET:
1. THE ARRIVAL — one timeline, about 2.4 seconds, at overlapping absolute positions, never a sequence. gsap.set: halo scale .82, autoAlpha 0 · flacon autoAlpha 0, y 26, scale 1.03 · reflection autoAlpha 0 · plinth scaleX 0 with transform-origin center · headline lines yPercent 112 inside overflow:hidden wrappers carrying padding-block-end .06em and margin-block-end -.06em so descenders survive the mask · lede, notes teaser, price and CTA autoAlpha 0, y 18 · masthead autoAlpha 0, y -10 · drift rail autoAlpha 0. Then: tl.to(halo,{autoAlpha:1,scale:1,duration:1.8,ease:"sine.out"},0) .to(flacon,{autoAlpha:1,y:0,scale:1,duration:1.6},.25) .to(lines,{yPercent:0,duration:1.05,stagger:.12},.55) .to(plinth,{scaleX:1,duration:1.1,ease:"power1.inOut"},.7) .to(reflection,{autoAlpha:.34,duration:1.2},.85) .to(foot,{autoAlpha:1,y:0,duration:.95,stagger:.1},1.05) .to(masthead,{autoAlpha:1,y:0,duration:.8},1.5) .to(rail,{autoAlpha:1,duration:.9},1.7). The reading of that order is the whole world: the LIGHT arrives before the object, the object arrives before its own reflection, and the page's furniture powers on last.
2. THE BREATH — the single ambient loop, and it is diegetic: gsap.to(halo, {scale:1.07, opacity:.78, duration:4, ease:"sine.inOut", yoyo:true, repeat:-1}). Exactly four seconds. Exactly one loop on the page. A second breathing element anywhere is a failure.
3. THE VAPOR DRIFTS — CSS keyframes, not GSAP, so they survive a CDN failure. Path A: translate(3%, -14%) over 22s · Path B: translate(-5%, -19%) over 27s with animation-delay -6s · Path C: translate(2%, -11%) over 31s with animation-delay -13s. All alternate ease-in-out infinite, with opacity oscillating inside the same keyframe between .04 and .10. The negative delays are what stop the three paths from moving in lockstep on load.
4. THE VAPOR-DISSOLVE SEAMS — exactly two scrubbed instances, per the seam spec and its performance contract.
5. THE TRAIL DRAW — the pyramid tie, and the hero trail in LE SILLAGE, per the pyramid spec and its fallback contract.
6. THE REVEALS — roughly fourteen elements marked with a reveal attribute: gsap.set({autoAlpha:0, y:26}) then .to({autoAlpha:1, y:0, duration:1.2, stagger:.1}) with scrollTrigger start "top 88%", once:true. The note plates are the exception: y 10 and stagger .07, so a tier lands as a phrase rather than as a list.
7. ONE SCRUBBED PARALLAX beyond the dissolves — the atmosphere image: gsap.fromTo(img, {yPercent:-6}, {yPercent:6, ease:"none"}) with trigger the scene, start "top bottom", end "bottom top", scrub:true, funded by the 122 percent overscan. This scrub, plus the dissolves, satisfies the global requirement for at least one scrubbed scroll moment on desktop.
8. THE FOIL SWEEP — CSS only, on hover and focus-visible, per the foil law. Never on load, never on scroll, never on a loop.
9. THE PRICE DOES NOT COUNT UP. This world overrides the global "count-up numerals for stats and prices": a price that spins reads as a discount announcement, and this house does not announce discounts. At most ONE count-up exists on the page, and it must be a quantity fact from the brief (millilitres, pieces made, hours of maceration), over 1.6s power2.out, with a 4000ms setTimeout fallback that paints the final value instantly in case the trigger never fires on a deep-linked load.
10. once:true on EVERYTHING non-scrubbed. Nothing re-animates on scroll-up. At most THREE scrubs page-wide. ZERO PINS — this world never pins a scene, because pinning freezes air and the whole page is about air moving. NO CANVAS — the vapor is inline SVG with CSS keyframes; a canvas particle field is banned here as a battery cost that reads as a screensaver. If more atmosphere is wanted, add a fourth SVG path at lower opacity.

MICRO-INTERACTION KIT (all CSS, all inside the timing bands, all on the shared ease):
- THE FOIL CTA: at rest — background transparent, box-shadow inset 0 0 0 1px rgba(gold,.55), colour gold, padding 1.05em 2.1em, radius var(--radius), signage 400 at .74rem/.24em uppercase, inline-flex gap .7em with a 1px-stroked arrow glyph. On hover/focus-visible — the foil sweeps over 1.1s, the ring goes rgba(gold,.9), the label flips to VELVET over .45s with a deliberate .25s DELAY so the text changes just after the light arrives, a bloom 0 0 22px -8px rgba(gold,.35) appears, the glyph nudges 3px. Active: ring .7, bloom halved, .2s. No lift, ever.
- THE QUIET LINK: colour rgba(lumen,.74); its rule is background-image linear-gradient(rgba(lumen,.24), rgba(lumen,.24)) at background-size 100% 1px, position 0 100%, no-repeat. On hover the colour becomes gold and background-size animates 0% 1px to 100% 1px from the inline-start over .6s.
- INPUTS ARE RULED LINES, NOT BOXES: background rgba(lumen,.035), border 0, border-block-end 1px rgba(lumen,.22), radius min(var(--radius), 2px), padding .95em .2em .7em, signage 1rem, caret-color gold. On focus THREE properties move together over .45s: the rule goes gold at 1.5px, the background lifts to rgba(lumen,.06), the 5px rgba(gold,.12) bloom appears. No field on this page has a box.
- THE SELECT: identical, plus a hand-drawn 9px chevron as an inline-SVG data URI at the inline-end, rotating 180deg over .4s under :has(select:focus). appearance:none; the option list inherits colour-scheme:dark.
- RADIO CHOICES ARE RULED ROWS, NOT CARDS: a full-width label at padding .9rem 0, border-block-end 1px rgba(lumen,.10), space-between, with a 1.05rem ring on the trailing side. Under :has(input:checked) the row's rule turns gold, the name goes full lumen over .45s, and the inner gold dot pops scale(0) to scale(1) over .35s.
- THE STEPPER: an inline-flex group at border-radius var(--radius), two 2.6rem true-circle ghost buttons at 50% with 1px rgba(lumen,.22) inset rings, and an <output> at min-width 2.4rem in the display face at 1.35rem, tabular-nums. Rings go gold over .3s on hover; disabled at opacity .3.
- ACCORDIONS: grid-template-rows 0fr to 1fr over .7s with an overflow:hidden inner. The icon is a SINGLE 1px rule rotating 90deg to 0deg over .5s — no plus, no chevron, no icon font.
- VALIDATION ERRORS: opacity 0 and translateY(-3px) to visible over .4s in the error mix of var(--primary) and var(--foreground) at .8rem, with min-height 1.25em reserved so nothing reflows.

## Components
- BUTTONS: exactly TWO forms exist page-wide — the foil pill at border-radius var(--radius) and the quiet ruled link. There is no third button, no ghost variant, no text button, no icon button outside the sticky bar. A full-width solid rectangle appears nowhere except the sticky mobile bar's CTA, which is itself a var(--radius) pill occupying the bar's trailing 58 percent.
- THE WHATSAPP CTA, styled to this world: a pill at border-radius var(--radius) with background transparent, box-shadow inset 0 0 0 1px rgba(lumen,.28), colour rgba(lumen,.86), padding .95em 1.6em, label in signage .70rem at .24em uppercase, preceded by a HAND-DRAWN inline SVG WhatsApp glyph at 15px, stroke 1.4px in currentColor, fill none, on a 24x24 viewBox. On hover the ring and the glyph go gold and the foil sweeps across the label. It NEVER appears as a filled green blob and NEVER as a floating circular bubble in the corner — this world explicitly overrides that reflex. It lives beside the primary CTA in the hero and the commande, and inside the sticky bar as a 2.9rem true-circle icon-only button at 50% with a real aria-label.
- THE TRUST STRIP: three or four items in a ruled row — display flex, gap clamp(1.6rem,4vw,3.4rem), border-block 1px rgba(lumen,.10), padding-block 1.4rem, no boxes, no backgrounds, no radius. Each item pairs a 20px inline SVG icon YOU draw (stroke-width 1.1, stroke rgba(gold,.8), fill none, stroke-linecap round, stroke-linejoin round, 24x24 viewBox) with a .68rem/.30em uppercase title and a .8rem rgba(lumen,.6) line. The icon vocabulary, drawn as line art: a folded envelope with a small wax circle (livraison) · an open palm holding a coin (paiement à la livraison) · a handset with a single sound arc (confirmation par appel) · a small vial with one falling drop (authenticité / échantillon). Never emoji, never a filled icon, never a downloaded icon font. Below 640px it becomes a 2x2 grid at gap 1.2rem with rules only on the block edges.
- THE PRICE PLATE (reused in the hero, the order plate and the sticky bar): the label, the numeral, the small-cap currency, and — only if the brief supplies one — the struck was-price at .82rem in rgba(lumen,.38) with text-decoration-color rgba(gold,.7) at 1px thickness. NO PERCENTAGE BADGE, EVER.
- THE FOOTER: velvet-deep, opening with THE MONUMENT — the wordmark at clamp(3.4rem,14vw,12rem), line-height .9, letter-spacing +.14em, display 300, colour color-mix(in srgb, var(--foreground) 9%, transparent), user-select none, aria-hidden true, and MASKED SO IT EVAPORATES: mask-image linear-gradient(to top, var(--foreground) 18%, transparent 92%) with the -webkit- prefix, so the letterforms dissolve at their tops. This world's monument is not an outlined stroke; it is a word turning into vapor. Beneath it: a ruled row of links at .8rem in color-mix(in srgb, var(--foreground) 60%, transparent), a colophon at .72rem in color-mix(in srgb, var(--foreground) 34%, transparent), and last, THE SILLAGE LINE — one final italic display line at 1.05rem in color-mix(in srgb, var(--foreground) 40%, transparent), the sentence the whole page has been walking toward.
- CRAFT DETAILS THAT SIGNAL INTENT: explicit width and height on every img · fetchpriority="high" on the flacon and loading="lazy" everywhere below the fold · the reflection duplicate carries alt="" and aria-hidden="true" · aria-live="polite" on the error region and the total · a real <output> for the stepper · a skip link · an inline-SVG data-URI favicon · meta theme-color matching velvet · color-scheme dark on :root · one <h1> only, labelled form fields, semantic header/main/section/footer, and a short unique data-wid on every top-level scene with "hero" on the opening and "site-footer" on the close.

## Conversion objects (this world SELLS — and it sells the way a perfumer sells: once, quietly, in a closed room)
- THE COMMANDE CHAPTER, on VELVET-WARM, grid 1.12fr / .88fr, seams: welded on the way in (never dissolved), foil-seamed internally, hard-cut on the way out to the footer.
  - THE TRAILING PLATE, position sticky at top 6.2rem: the flacon again, contained and small with its 30 percent reflection, the price whisper, the trust strip stacked vertically, and ONE line of italic poetry. Below 1024px it takes order:-1, loses its stickiness and collapses to a horizontal row of image plus price whisper.
  - THE LEADING SIDE IS THE FORM, and it has NO CARD: no border, no fill, no radius, no shadow. It is a sequence of ruled lines on velvet, exactly like an order slip written by hand. That absence is the design.
- THE FIELDS, in this fixed order, grouped under TWO micro-cap headers separated by a foil seam — "À QUI" and "OÙ" — so the form reads as two thoughts rather than seven inputs:
  1. NOM COMPLET — autocomplete="name". The label names who receives the parcel, not "your name".
  2. TÉLÉPHONE — type="tel", inputmode="tel" (this world overrides the global inputmode="numeric" suggestion: tel gives an Algerian buyer the keypad they expect), autocomplete="tel", a real pattern, placeholder in the local format 0X XX XX XX XX, and a hint stating that the call is only to confirm the address.
  3. WILAYA — a styled <select> with the identical ruled treatment. Wilaya names are geography and may be listed in full; every delivery FEE, DELAY or zone availability shown beside the select is a business fact and comes ONLY from the brief.
  4. ADRESSE — a <textarea rows="2"> whose helper asks for the landmark a driver would actually use.
  5. QUANTITÉ — the ruled stepper, with a cap, and THE CAP IS GIVEN A REASON in the hint ("deux par foyer, le temps que la série circule").
  6. CONTENANCE or VARIANTE — ruled radio rows, and only if the brief names more than one.
  7. UN MOT (optional) — a single ruled line labelled as a message to the house. This is the "private commande" detail: the form lets a buyer say something to a person, and almost no page in this market does.
- THE TOTAL: a foil-seam-topped row, space-between, padding-block-start 1.4rem — a .68rem/.30em uppercase label on the leading side, and on the trailing side the total in the display face at clamp(1.5rem,2.2vw,1.9rem) with tabular-nums and the same small-cap currency, recomputing on every quantity, variant and delivery change inside an aria-live="polite" region. Beneath it, a .78rem rgba(lumen,.55) line stating exactly what happens next and exactly what is paid to the driver.
- VALIDATION IS BLUR-GATED: keep a touched map so an error appears only after a field's first blur, never while someone is still typing into a fresh field. Errors are full sentences in this world's voice.
- SUBMIT HAS AN 850ms PENDING STATE whose label becomes a present-tense human sentence, and then THE SEAL — the world's closing moment and its best piece of craft:
  1. The fields DISSOLVE, this world's own seam applied to a component: filter blur(0) to blur(10px), autoAlpha to 0, yPercent -6, over .8s on the shared ease.
  2. In the same box, absolutely over it, THE ENVELOPE assembles as one inline SVG at width min(20rem,74%), aspect-ratio 3/2: the body is a 1px rgba(lumen,.30) rect with no fill, drawn by stroke-dashoffset over 1.1s power2.inOut.
  3. THE FLAP CLOSES: a triangle path pointing UP above the body's top edge, with transform-box: fill-box and transform-origin: 50% 0%, animating scaleY(1) to scaleY(-1) over .7s on the shared ease — two declarations, and it reads as a hand folding a letter.
  4. THE WAX: a circle at the flap's point, r 14, fill rgba(gold,.9), a 1px velvet inner ring, and the merchant's initial from the brief in the display face at 12px in velvet — scaling .4 to 1 over .5s with back.out(2.2) at timeline position .9.
  5. Then the order reference in the display face at 1.7rem with tabular-nums, a .62rem/.30em uppercase sub-label, and ONE line echoing the buyer's own name and wilaya: "Nadia, on vous appelle à Oran avant ce soir."
  About 2.1 seconds total. IT NEVER CELEBRATES: no confetti, no checkmark burst, no green tick, no exclamation mark. Under reduced motion or without GSAP the envelope renders already sealed with the reference present. And as the seal begins — the instant validation passes — the letter is truly entrusted: the page dispatches the wandit:lead CustomEvent on document with the buyer's fields flat in detail (name, phone as written, wilaya, commune, plus the canonical order keys product, quantity, price, delivery and total when collected, and contenance under its own key), while one off-canvas decoy input marked data-wandit-hp lies in the commande, never read by the page's own script.
- THE STICKY MOBILE ORDER BAR (below 860px only), appearing once the hero's bottom crosses 60 percent of the viewport via ScrollTrigger with an IntersectionObserver fallback so it survives a GSAP failure: position fixed, inset-inline 0, bottom 0, height 4.4rem, z-index 80, background color-mix(in srgb, var(--background) 82%, transparent), backdrop-filter blur(16px), a FOIL SEAM as its block-start edge, box-shadow 0 -14px 34px -20px color-mix(in srgb, var(--background) 70%, transparent), padding-inline clamp(1rem,4vw,1.4rem), padding-block-end env(safe-area-inset-bottom), flex, align-items center, gap .9rem. It carries the price whisper at .9 scale (label .58rem/.30em), the 2.9rem circular WhatsApp button, and the foil pill on the remaining width with its label at .68rem/.24em. Enters from autoAlpha 0 / yPercent 100 over .7s — and, the detail almost every page in this market misses, IT HIDES AGAIN while the commande is in view, so the bar never covers the form it points at.
- CROSS-SCENE STATE: if the brief gives more than one contenance, a chooser anywhere on the page rewrites the price whisper in the hero, the order plate and the sticky bar at the same instant, each over .6s, and pre-selects the matching ruled radio row. Persist the choice and the completed order in localStorage; on return, restore the choice and paint the sealed envelope INSTANTLY with no animation, so a returning buyer is never asked to order twice.
- Every conversion element works with JavaScript degraded: the form validates and shows an honest success state without GSAP, the WhatsApp link is a real href, and the price is in the HTML, never written by script.

## Editorial furniture — the poetry licence (REQUIRED; this is SILLAGE's voice)
- THE HOLD LINE: one italic display line per hold scene, under fourteen words, never followed by an explanation. This is the world's signature piece of writing and there are exactly two of them on the page.
- THE SENSATION WORD: one word beneath every note name. It describes what the note DOES to a person, never what the ingredient is.
- MICRO-CAP LABELS name what the page SHOWS, never what the business claims: "PLANCHE 02" · "LA PYRAMIDE" · "LE FLACON, 50 ML" · "COMMANDE PRIVÉE" · "SILLAGE" · "FIG. 03". They are typesetting, and they invent no business fact.
- THE FIGURE CAPTION under every framed image, with its fig number in gold.
- THE CITE: under a hold line, a micro-cap credit naming the composition, the house or the year — from the brief ONLY. If the brief supplies none, the cite is omitted entirely rather than invented.
- THE DRIFT RAIL's content: note names and material facts, set as signage micro-caps. Never a slogan, never a promotion, never a countdown.
- THE COLOPHON in the footer: one line naming what the page is and when it was set, in the world's register.
- THE SILLAGE LINE: the last line on the page, in italic, the sentence everything has been walking toward.
- THE HARD LIMIT ON LICENCE: sensation is authorable — duration, concentration, notes, provenance, ingredients, prices, delivery times, phone numbers and reviews are FACTS and come only from the brief. A page that invents "tenue 12 heures" has broken this world's fourth law, no matter how beautifully it is set.

## Arabic and RTL adaptation
- dir="rtl" on the html element, logical properties throughout (padding-inline, margin-inline, border-inline-start, inset-inline). Every asymmetric grid mirrors for free; the halo, the reflection, the plinth and the wax seal are vertically symmetric and need nothing.
- ARABIC IS NEVER LETTER-SPACED — tracking breaks the shaping of joined script. EVERY micro-cap tracking value in this document (.24em, .28em, .30em, .34em, .36em, .38em, .42em) drops to 0 under html[lang="ar"], and text-transform:uppercase is REMOVED. The signage register is rebuilt from three substitutions: size +2px, weight +100, and rgba(lumen,.42) becoming rgba(gold,.8). Scope all of it under html[lang="ar"].
- NO ITALIC EXISTS IN ARABIC. Because this world's only italic is the poetry voice, the substitution is clean: hold lines, tier roles and the sillage line lose the slant and are carried instead by (a) GOLD-PALE at 82 percent alpha and (b) a size step of 1.15x. Use both, always together. The Arabic page is therefore structurally identical to the French one.
- Line-height goes UP: body 1.95, lede 1.80, hold line 1.60. Arabic on a dark ground with generous tracking removed needs the vertical room.
- FACES: an Arabic display face in the Amiri / Aref Ruqaa / Noto Naskh Arabic territory for the name, the hold lines, the note names and the price; an Arabic UI face in the IBM Plex Sans Arabic / Almarai / Cairo territory for labels, hints and the form. Never stretch one Latin face across both scripts — a didone has no Arabic and faking one is visible instantly.
- NUMERALS: keep Western Arabic digits (0-9) for the price, the total, the reference and the phone field — that is what Algerian commerce uses — with the same &#8239; thin space. Tier marks may take Eastern Arabic numerals. The currency takes its Arabic form with small-caps and tracking removed.
- The drift rail's direction reverses automatically with dir; the rotated-square separator is symmetric and survives. The wax seal takes the Arabic initial. The chevron on the select mirrors for free with a logical background-position.

## Global rules this world overrides (declare each in an HTML comment beside the relevant code, then obey it)
1. Overrides the tolerance for mid-radius containers: exactly THREE treatments exist page-wide — 0 on every rule, band, plate, frame and image · var(--radius) on pills and the stepper group, with 50% reserved for true status dots · min(var(--radius), 2px) on the input, select and textarea and nowhere else.
2. Overrides soft box-shadows as a depth device: four shadows exist page-wide and all four model AIR, never elevation. No card carries one, because no card exists.
3. Overrides the hover-lift micro-interaction: NOTHING on this page moves on hover. Hover changes LIGHT — the foil sweeps once, a rule brightens, an alpha steps up. The single exception is the CTA glyph nudging translateX(3px).
4. Overrides the micro-label tracking band of .16-.30em: perfumery signage runs .24em to .42em, and only the seven values listed in Typography are legal.
5. Overrides the global GSAP default and the fast end of the timing bands: gsap.defaults power2.out at 1.2s instead of power3.out at 1.1s, and NOTHING on the page runs under .30s — interaction feedback lives at .30-.50s where the global band says .25-.45s.
6. Overrides the hero-entrance ceiling of about 1.6s: THE ARRIVAL runs about 2.4s, because the light must arrive before the object and the object before its own reflection, and that order IS the world.
7. Overrides "count-up numerals for stats and prices": the price never counts. At most ONE count-up exists on the page and it must be a real quantity fact from the brief.
8. Overrides the global phone inputmode of numeric: type tel with inputmode tel, the keypad this market expects.
9. Overrides "the COD order form is numbered steps or a card with presence": here it is a sequence of ruled lines on velvet with NO card, NO border, NO fill and NO step numerals, grouped under two micro-cap headers. Its presence comes from the ruling, the total's foil seam and the seal; the absence of a box IS the design.
10. Overrides the pinned half of "at least one pinned or scrubbed scroll moment on desktop": ZERO pins, ever — pinning freezes air. The requirement is met by three scrubs: two vapor-dissolves and one parallax.
11. Overrides the "layered radial gradients instead of flat backgrounds" licence: gradients as VISIBLE FILLS are banned outside the four sanctioned exceptions of the foil law. Ground changes are TEMPERATURE CUTS between three velvets, not stacked radials.
12. It does NOT override the honesty rules, and they bind harder here than anywhere: invented notes, hold times, concentrations, provenance, delivery promises or reviews break Law Four no matter how beautifully they are set.

## SILLAGE ban list (in addition to the global one)
Pure #000 ground or pure #fff text, rules, strokes or icons · a gradient used as a visible FILL anywhere outside the four sanctioned exceptions · a shimmer that runs on a loop instead of on interaction · glassmorphism — translucent panels with borders and shadows · backdrop-filter beyond its two sanctioned sites · cards of any kind, and any container carrying a fill plus a border plus a radius · box-shadows used as elevation · a uniform 12-16px radius as the page's only shape · hover lifts of any kind (nothing moves on hover; light changes) · neon, acid, saturated or cool-violet accents — the accent is a metal · a full uncut mirror reflection · a floating green WhatsApp bubble · countdown timers, percentage-off starbursts, "STOCK LIMITÉ" banners, any manufactured urgency · exclamation marks anywhere on the page · emoji, icon fonts, filled icons, downloaded icon sets · three-column feature-card grids · a product grid — this world sells ONE thing · a carousel or a lightbox · centred running prose · per-character text splitting · more than ONE ambient loop · more than THREE scrubs · ANY pinned scene · canvas particle fields · the price as the largest type in its scene · a hero without a price · a spec list without promoted numerals · a success state that celebrates · any hidden state authored in CSS · invented notes, invented hold times, invented concentrations, invented reviews.

## Intensity
This world fails in two opposite directions and both are easy.

It fails DOWN into a dark landing page with a gold button: velvet ground, a photo, a headline, rounded cards, a green WhatsApp blob, and a hairline between every section. Every one of those is a comfortable default and every one of them is banned above. At 60 percent intensity — dark plus gold plus a serif — this is precisely the generic page it exists to replace.

It fails UP into fog: blur on every panel, four ambient loops, a shimmer that never stops, three pinned scenes, vapor at 30 percent opacity, and a page you cannot read. Restraint is not a lack of ambition here; it IS the ambition. The vapor lives between .04 and .10. The blur lives at exactly seven declared sites. The shimmer runs once and stops. The breath is four seconds and there is only one.

Executed at 100 percent — three warm near-blacks cutting between chapters, three plumes drifting forever at 22, 27 and 31 seconds, a bottle breathing in its own light above a reflection cut at 46 percent, a gold tie drawn down through three ruled tiers of notes, two scenes that evaporate upward into the next, a price whispered in small caps and never the loudest thing on its screen, and an order slip of ruled lines that folds itself into a sealed envelope — a buyer scrolling on a phone in Algiers feels the room the merchant just walked out of. Push INTO the quiet. Every number above is load-bearing.`,
	energy: "quiet",
	family: "dark-luxury",
	id: "sillage",
	industries: [
		"perfume",
		"fragrance",
		"oud",
		"beauty",
		"cosmetics",
		"skincare",
		"spa",
		"candles",
		"home-decor",
		"jewelry",
		"fashion",
		"wellness",
		"gifts",
		"hammam",
	],
	kind: "product",
	mood: ["dark", "hushed", "sensual", "drifting", "opulent"],
	name: "Sillage",
	preview: {
		ground: "#0B0908",
		ink: "#EFE6D8",
		accent: "#B9932F",
		fontFamily: "Cormorant Garamond",
		sampleWord: "Le sillage",
	},
	priceFeel: "premium",
	tagline:
		"Near-black velvet with gold that only catches the light when a finger comes near it, your bottle breathing above its own reflection while scent drifts up the page — and every scene evaporates into the next instead of simply ending.",
};
