import type { DesignWorld } from "./types";

/**
 * VERGER — the terroir harvest page for one dated food product.
 * Unbleached paper under golden-hour light, two hues with strict roles (honey
 * owns commerce, leaf owns provenance), a provenance dateline used as furniture,
 * the product's own silhouette drawn as a single stroke that travels the page —
 * watermark, price frame, showpiece, order stamp — a year typeset as a
 * seasonality band with the harvest window marked, a purity table carrying facts
 * and nothing else, and a cash-on-delivery docket with weight variants as
 * designed pills. Overrides the one-accent habit, the uniform-radius rule, the
 * single-scrub economy and the count-up-the-price habit; each override is
 * declared inside the doc. Appended VERBATIM to the builder system prompt.
 */
export const verger: DesignWorld = {
	avoidFor: ["tech", "gaming", "streetwear", "nightclub", "crypto", "gadgets"],
	doc: `# DESIGN WORLD: VERGER — the dated harvest

## Philosophy
This page sells ONE thing that came out of a specific place, in a specific month, in a specific year — honey, olive oil, dates, argan, saffron, dried herbs, a spice blend. It never behaves like a shop; it behaves like a HARVEST RECORD that happens to take orders: light, a place, a date, a method, a table of facts, and a docket at the end that a person fills in and pays for at their door.

LAW ONE — EVERYTHING IS DATED AND PLACED. The provenance dateline (season and year, place, coordinates) is FURNITURE, not an eyebrow used once: it opens the page above the nav, labels the hero, heads the purity table, and returns at the end as the shape the buyer's own order is printed in.

LAW TWO — THE SILHOUETTE TRAVELS. The container the product is sold in — jar, bottle, tin, pouch — is drawn ONCE as an inline SVG outline, fill none, and that one stroke does six jobs: a mark in the nav, a watermark behind a chapter, the frame that holds the price, the thing that draws itself in the showpiece, the icon in the sticky bar, the stamp on the finished order. One shape, six scales, filled exactly once.

LAW THREE — LIGHT ARRIVES FROM THE TOP AND LEAVES AS YOU DESCEND. Every paper chapter is lit by a golden wash entering its top edge, every photograph is golden hour or macro, and the ground steps down a four-rung tone ladder as you scroll. Nothing is lit flat: when tempted to add a background colour, step the LADDER instead.

Structurally: paper chapters welded to full-bleed field photographs, one pinned showpiece, one dark chapter, a docket at the end. No carousel, no product grid, no lightbox. The distance from a generic natural-products template is not effect budget — it is dating everything, drawing one shape well, and refusing to invent a single fact.

## The vibe
Picked by someone whose father picked it, in a valley you can find on a map, in a month that has already ended. Warm, sunlit, patient, faintly technical.

THE PRICE FEEL SITS BETWEEN accessible and premium, and that is deliberate: this world must carry a 900 DZD jar without looking precious and a 6 500 DZD gift crate without looking cheap. It buys that range with provenance rather than with luxury signals — no gold foil, no black-and-gold, no "luxe" vocabulary. The dateline, the coordinates and the purity table do the work that a luxury page does with materials. Never dress a staple product as a collector's item here; state where it came from and let the price be whatever it is.

Copy rules, non-negotiable — they carry 40 percent of the design:
- EVERY headline is a short declarative with EXACTLY ONE italic word, and that word is a place, a season, a method or a sensory verb, never praise: "Récolté en mai, dans le M'zab." / "Pressée à froid, le jour même." Never two italic words, never a whole italic clause.
- EVERY constraint carries its reason: not "6 pots maximum" but "Six pots par commande — au-delà c'est une palette, écrivez-nous."
- EVERY number carries its unit, typeset with a narrow no-break space: 250 g, 1 kg, 24 °C, 36°28′ N. Never 250g.
- Validation errors are full sentences in the merchant's voice: "Il nous faut votre numéro — c'est par là qu'on confirme."
- Exactly ONE unexplained line of voice on the page, over a photograph, with no heading and no CTA.
- Banned words: premium, exceptionnel, révolutionnaire, solutions, expérience, élever, transformer, and authentique or naturel used as a bare self-applied adjective. If the brief certifies something, state the certification; otherwise say nothing.
- Write in the brief's language. Arabic keeps every rule; having no italic, it carries the emphasised word with LEAF colour, a leaf underline and one weight step.

## Visual signatures (what makes it instantly recognizable)
- Unbleached warm paper with a faint yellow-green cast. Never white, never a neutral gray, anywhere.
- TWO hues whose roles never swap: HONEY does commerce (price, CTA, totals, focus ring, the pour), LEAF does provenance (dateline, coordinates, ticks, harvest window, the silhouette stroke).
- The product silhouette as a single 1.2-1.6px stroke, six appearances, six scales, filled once.
- Photographs that do not end — they DISSOLVE into the next chapter's paper through a horizon weld.
- The dateline in mono caps, leaf, with honey middots: RÉCOLTE 2026 · VALLÉE DU M'ZAB · 36°28′ N.
- A twelve-month typographic strip with the harvest window as a leaf bar and its peak fortnight in honey.
- A ruled purity table with a 2px head rule and promoted mono numerals — facts, nothing else.
- Jar-shouldered shapes: big top radii, near-square bottoms, so every frame stands like a jar on a shelf.
- The price sitting inside the silhouette's label rectangle, on paper, as if printed on the jar.
- A closing monument: the merchant's name at 17vw, transparent, 1px honey stroke, silhouette behind it.

## Color physics (route the brief's palette through the fixed tokens — the physics is law)
FIXED TOKEN MAP — GROUND-0→--background · INK→--foreground · HONEY→--primary · GROUND-0→--primary-foreground · GROUND-2→--secondary · LEAF→--accent · ink at 54%→--muted · ink at 18%→--border · 999px→--radius · DISPLAY→--font-heading · BODY→--font-body. These are the only CSS color/type/radius variables: every pole below is a prose role, literal register hexes belong only in these :root values, and every ground rung, sibling or alpha step is a color-mix(in srgb, var(--foreground) N%, transparent), substituting the mapped fixed token for that pole, or a color-mix between two mapped fixed-token references. Every unmapped role below MUST reuse the nearest mapped token or such a mix; it never gets another custom property or literal. Non-color mechanics may keep their own custom properties. Any rgba(POLE, a) notation below is design shorthand for that color-mix, never emitted CSS.
TEN tonal roles from the fixed tokens, never an eleventh hue. EVERY HEX BELOW IS A REGISTER, NOT A VALUE: it names the temperature, lightness and chroma relationship to hit while instantiating the brief's own poles. Copying these hexes onto a brief that handed you a different amber is the failure this section exists to prevent.
THE TONE LADDER — four warm grounds, each about 4 percent darker than the last; chapters step DOWN it instead of separating with whitespace. GROUND-0 is the brief's lightest warm pole, unbleached paper in the #F7F1E3 register (never #fff, never a cool off-white) · GROUND-1 one rung down (the #F0E7D3 relationship) · GROUND-2 (the #E7DCC2 relationship) for the trust strip, the band and the pill trough · GROUND-3, the deepest paper (the #DCCDAC relationship), used once or twice under the showpiece or the docket.
- INK: a near-black shifted toward GREEN, G at least R and both above B — the #1E241A relationship. Deliberately vegetal, not a warm brown-black. Never #111.
- INK AT ALPHA, the rule that makes this read as paper rather than UI: body and secondary rgba(ink,.74) · captions and footnotes rgba(ink,.54) · ALL hairlines rgba(ink,.18) · table body rules rgba(ink,.16) and the table head rule rgba(ink,.5) at 2px · placeholder rgba(ink,.34) · the watermark rgba(ink,.10) · the price frame stroke rgba(ink,.22). No independent gray hex exists.
- HONEY: the brief's amber or gold pole at full chroma (the #C88A21 register), HONEY-DEEP for hover and text at roughly 18 percent darker (the #A66E14 relationship), HONEY-LIGHT for dark grounds at roughly 22 percent lighter (the #E8BE6A relationship). LEAF: the brief's green or olive pole (the #4F6B3A register), LEAF-LIGHT on dark (the #8FA96E relationship). If the brief hands only ONE warm pole, LEAF is derived from the ink by pulling it toward its green side until it clears 4.5:1 on GROUND-0 — never imported from outside the palette. SOUS-BOIS and CREAM-ON-DARK are scoped mixes of var(--foreground), var(--accent) and var(--background), with their hairline at 16%; they get no custom color properties. ERROR is a contrast-safe mix of var(--primary) and var(--foreground), used only in validation.
THE ROLE SPLIT, never violated. HONEY: the currency mark, the CTA fill, the focus ring, ::selection, the total's rule, the dateline middots, the pour fill, the bar silhouette, the monument stroke, the current-month marker. LEAF: the dateline text, coordinates, the harvest bar and ticks, the nav mark, the trust icons, figure numbers, the select chevron, the accordion glyph, the one italic word. Never blend them except in the purity meter; never add a third hue for a secondary action.
CONTRAST LAW — what silently kills amber pages. Full-chroma HONEY on paper does not reach 4.5:1, so honey is legal as a FILL, a RULE, a dot, or as text ONLY above 24px; below that it becomes HONEY-DEEP, on dark HONEY-LIGHT. Body text is always rgba(ink,.74) on paper or CREAM on dark.

## Typography system
THREE families, three non-overlapping jobs; load only the weights used.
- DISPLAY SERIF (400, 500, plus ONE italic 400): headlines, price, total, wordmark, pull-quote, monument. Territory — an old-style or transitional serif with a genuine italic: Newsreader / Lora / Source Serif 4 / Petrona / Libre Caslon / Cormorant. Never a face without a real italic, because this world's only emphasis device depends on it; never a script face.
- BODY SANS (400, 500, 600): paragraphs, ledes, buttons, inputs, sub-lines. Territory — a quiet humanist sans that does not fight the serif: Karla / Work Sans / Public Sans / Archivo / Manrope.
- MONO (400, 500): every label, micro-cap, dateline, coordinate, table numeral, stepper output, weight pill, footnote. Territory — IBM Plex Mono / DM Mono / Space Mono / Courier Prime. Not a code gesture: it is a producer's record book, and it is why the facts read as measured rather than marketed.
Scale, all clamp: hero h1 clamp(2.9rem,7.2vw,6.2rem) / 1.02 / -.018em / 400 · h2 clamp(2.05rem,4.4vw,3.6rem) / 1.08 / -.012em / max 15em · h3 clamp(1.3rem,2.1vw,1.75rem) / 1.2 / -.005em / 500 · price clamp(2.6rem,5vw,3.8rem) / .95 / -.015em / 500 tabular-nums · total 2rem · lede clamp(1.05rem,1.35vw,1.2rem) / 1.62 / max 29em · body 1.0625rem / 1.68 / max 33em · mono micro-caps .64-.80rem uppercase at .14-.24em · the dateline .72rem / .18em / LEAF · footnotes .68-.74rem rgba(ink,.44) · monument clamp(4rem,17vw,15rem) / .84 / POSITIVE .02em.
TRACKING IS A FUNCTION OF SIZE: -.018em above 90px, -.012em at 40-70px, -.005em at 28-34px, 0 at body, +.14em to +.24em at 10-13px mono caps. Line-height: .84-1.02 display, 1.08-1.2 subheads, 1.62-1.68 body. Target a display-to-micro ratio of at least 9:1; a generic page sits at 3:1.
THE ONE ITALIC WORD — the highest-leverage device here and the easiest to over-use. One class, applied ONCE per headline: font-style italic, weight 400, colour LEAF, letter-spacing 0 (cancelling the display face's negative tracking, because an italic needs its own fit), font-size 1.02em inside h2 and h3 so it optically matches the roman x-height.
NEVER LET A DISPLAY HEADLINE AUTO-WRAP: break every h1 and h2 into block-level line spans so the rag is AUTHORED, then reuse those spans as the stagger targets.
PROMOTE NUMERALS. In every fact row and table cell the number is MONO at 1.15em of its row, tabular-nums, full ink, with the unit after a narrow no-break space at .62em rgba(ink,.5). "Humidité — 17,2 %" then reads as a measurement inside a sentence — that one rule is the whole record-book effect.

## The silhouette (build this FIRST, before any markup)
Draw the container ONCE, as subpaths with fill="none" stroke="currentColor" stroke-width="1.4" stroke-linejoin="round" vector-effect="non-scaling-stroke" and — essential — pathLength="100" on every path, so every draw animation is unit-based. Two recipes to adapt:
- JAR, viewBox 0 0 100 140. Lid M30,16 h40 a5,5 0 0 1 5,5 v7 h-50 v-7 a5,5 0 0 1 5,-5 z · body M26,28 h48 c7,0 11,5 11,13 v76 c0,8 -4,13 -11,13 h-48 c-7,0 -11,-5 -11,-13 v-76 c0,-8 4,-13 11,-13 z · label M20,74 h60 v28 h-60 z.
- BOTTLE, viewBox 0 0 72 180. Cap M25,6 h22 v8 h-22 z · body M27,10 h18 v24 c0,7 12,11 12,25 v99 c0,8 -5,13 -13,13 h-16 c-8,0 -13,-5 -13,-13 v-99 c0,-14 12,-18 12,-25 z · label M15,96 h42 v34 h-42 z.
SIX APPEARANCES — at least FIVE present, the price frame and the showpiece mandatory. 1 THE MARK, 18px in the nav lockup, stroke 1.2, LEAF. 2 THE WATERMARK, clamp(16rem,34vw,30rem) wide, stroke 1, rgba(ink,.10) on paper or rgba(cream,.08) on dark, absolute, z-index 0, rotate(-4deg) in odd chapters and rotate(3deg) in even ones, bleeding up to 12 percent past the section's inline edge, aria-hidden — one per chapter, in at least three chapters. 3 THE PRICE FRAME, 7.5rem wide in the hero and 5.4rem in the sticky column, stroke 1.2 at rgba(ink,.22), its LABEL RECTANGLE filled GROUND-0 so the price numeral sits on paper INSIDE the jar, centred on that rectangle and nudged translateY(.35rem); it replaces every badge, starburst and coloured price pill. 4 THE SHOWPIECE, the self-drawing scrub below. 5 THE BAR ICON, 2.4rem in the sticky bar, stroke 1.3, HONEY-DEEP. 6 THE STAMP, 9rem in the success panel, stroke 1.6 HONEY, drawn then filled.
Never fill it with a flat colour, never shadow it, never rasterise it, never let it become a logo.

## Page chassis
- THE DATELINE BAR (mandatory): full-bleed above the nav, height 2.2rem, GROUND-2, border-bottom 1px rgba(ink,.18), centred, mono .70rem / .20em uppercase LEAF, HONEY middots at opacity .85; below 560px it drops the coordinates. It dates the page before anything else is read, and gives the nav a plate to detach from.
- NAV: sticky, top 0, z-index 100, height 4.4rem, DOUBLE-STATED. Default transparent over the hero photograph with CREAM text and text-shadow 0 1px 2px color-mix(in srgb, var(--foreground) 35%, transparent); past 40px of scroll background color-mix(in srgb, var(--background) 93%, transparent), backdrop-filter blur(12px), border-bottom 1px var(--border), INK text, transitioned over .55s with the shared ease.
- WORDMARK IS A LOCKUP: the 18px silhouette mark, the name in display serif 500 at 1.35rem tracked .01em, and a mono sub-label on the baseline below at .58rem / .28em uppercase at opacity .55 carrying category and year. Nav row flex, gap 2rem, max-width 84rem; links .9rem/500 at opacity .82 to 1 over .25s with a 1px LEAF underline growing 0 to 100 percent over .3s, plus a honey pill CTA on the end side. Below 860px the links disappear and only the CTA remains — no burger overlay needed.
- THE LIGHT WASH: every paper chapter carries a ::before at inset-inline 0, top 0, height 62%, pointer-events none, z-index 0, background radial-gradient(140% 70% at 50% 0%, rgba(honey,.11), transparent 62%), content at z-index 1. On dark chapters it inverts to rgba(honey,.07) entering from the BOTTOM — dusk from below the horizon.
- THE POLLEN LAYER: fixed, inset -30%, z-index 92, pointer-events none, opacity .10, mix-blend-mode multiply, an inline SVG data URI of feTurbulence type fractalNoise baseFrequency 0.9 numOctaves 2 stitchTiles stitch, desaturated with feColorMatrix saturate 0, on a 220x220 rect at opacity 0.5.
- GLOBAL BASE: html and body overflow-x clip, scroll-behavior smooth, antialiased · ::selection rgba(honey,.28) with ink text · :focus-visible a 2px HONEY-DEEP outline at offset 3px, radius min(var(--radius), 3px) · a skip link sliding from top -4rem to 1rem on focus over .3s.
- THE COORDINATED NUMBERS, all derived from the measured 6.6rem dateline-plus-nav stack and never guessed separately: hero min-height calc(100svh - 6.6rem) with a calc(100vh - 6.6rem) fallback declared first · sticky offsets top 5.6rem · scroll-margin-top 7.2rem on anchored sections · body padding-bottom 4.6rem below 900px so the sticky bar never covers the footer.

## The harvest arc (this world's blueprint unless the brief names another order)
Dateline bar, nav, HERO ending in the harvest rail · LE LIEU, a welded golden-hour field photograph carrying the dateline · LA MÉTHODE, a paper chapter one tone step down with a sticky media column beside three ruled fact rows · LA BANDE SAISONNIÈRE as a full-bleed seam · LE TABLEAU DE PURETÉ with the watermark behind it · LA COULÉE, the pinned showpiece · LE VERSANT, the dark chapter carrying the producer's word and the founding-year count-up, entered by a dusk weld and left by a dawn weld · LA CITATION, a macro band with one unexplained line of voice · LE BON DE RÉCOLTE, the docket with weight pills, sticky product column and trust strip · questions as a ruled accordion · the footer monument.
Ten to twelve sections. If the brief is thin, CUT sections rather than padding them — an eight-section verger beats a twelve-section one with two invented chapters.

## Hero forms (pick what the brief's photography supports — all three are LOADED)
1. LE PLEIN CHAMP (default when a landscape exists). A full-bleed golden-hour orchard, grove or plot filling the hero, welded to the nav with zero gap, min-height calc(100svh - 6.6rem), object-fit cover, at height 124% and top -12% inside an overflow:hidden parent so parallax never exposes an edge. A two-ended scrim: linear-gradient(to bottom, rgba(ink,.44) 0%, rgba(ink,.08) 36%, rgba(ink,.58) 100%) — dark at the top for the nav, clear where the light is, dark at the bottom for the type. Content bottom-aligned in a 1.08fr/.92fr container grid, gap clamp(2rem,5vw,4.5rem), padding-block clamp(3rem,9vh,6rem).
LEFT COLUMN carries the whole offer — nine differentiated pieces, not a headline and a button: the dateline in mono .72rem / .20em HONEY-LIGHT with a 2.2rem by 1px LEAF-LIGHT ::before rule · the hand-broken h1 in CREAM with its single italic LEAF-LIGHT word · a lede at 29em in rgba(cream,.84) · the PRICE FRAME with currency label, struck was-price if real, and per-unit line · the WEIGHT PILLS · a CTA row (honey pill plus ghost WhatsApp) · the reassurance line at .8rem in rgba(cream,.7).
RIGHT COLUMN IS A PLINTH OF LIGHT, NOT A PHOTO SLOT: the product shot on seamless, object-fit CONTAIN at width min(100%,22rem), justify-self centre, contact shadow 0 40px 70px -34px color-mix(in srgb, var(--foreground) 62%, transparent), and a pool behind it at radial-gradient(circle, color-mix(in srgb, var(--primary) 50%, transparent) 0%, transparent 60%) with filter blur(8px). It overlaps the hero's bottom edge by 3rem into the next section.
THE HERO TERMINATES IN THE HARVEST RAIL, never in whitespace: full-bleed on GROUND-1, border-block 1px rgba(ink,.18), padding-block 1.1rem, a flex list of FOUR mono micro-facts at .72rem / .12em uppercase each with a .3em LEAF dot ::before — origin, harvest month, net weight, method, never adjectives. Below 600px a 1fr 1fr grid at .66rem.
2. L'ÉTABLI (split — product photography but no landscape). Grid 1.08fr/.92fr on GROUND-0, same min-height and same left column in INK; the right column is a jar-shouldered frame at radius 3rem 3rem .6rem .6rem, aspect-ratio 4/5, overflow hidden, holding the macro drizzle shot at shadow 0 26px 56px -30px rgba(ink,.34), with the WAX SEAL hanging at top -1.8rem inline-end -1.2rem OUTSIDE the frame, the watermark behind at 26rem rotated -4deg, and the fig. caption row beneath.
3. L'ÉTIQUETTE (poster, phone-first, best for an Arabic build). One centred column at max-width 46rem — dateline, h1, lede, the PRICE FRAME oversized with the silhouette at 11rem, the weight pills, the CTA row, the reassurance line — then, welded with padding-top 0, a full-bleed 21/9 golden-hour band with the seasonality strip across its lower third on a rgba(ground-0,.9) plate. Centring is legal here and in exactly two other places (the pull-quote, the monument) — nowhere else.

## Section seams (Verger's own vocabulary — never the same twice in a row; at least five per page)
1. LA SOUDURE D'HORIZON (the horizon weld) — the signature, and why this world is not a stack. A full-bleed field photograph is followed by a paper chapter whose ground matches the sky just above the photograph's horizon: the photo section and the next chapter repeat the EXACT SAME fixed ground token or color-mix expression (var(--background), var(--secondary), or their authored mix) as the final gradient stop and the chapter background. Never create a ground-N color property. The next section takes padding-top 0. No rule, no gap, no radius — the photograph does not end, it becomes paper. At least TWO per page, plus ONE inverse (a top gradient welding a photo's upper edge into the ground above) so photographs can arrive as well as depart.
2. LE PALIER (the tone step) — adjacent paper chapters change ground by exactly one rung, with no rule and no extra whitespace at the join. At least four steps per page, climbing back UP once so the descent is not monotone. Never the same ground twice running unless a weld or the band intervenes.
3. LE CHEVAUCHEMENT (the overlap) — an element from the closing chapter crosses the boundary by 2.5-4rem with the next ground behind it: the hero plinth, the price frame, the wax seal, a captioned plate. z-index 2 on the crosser, overflow visible on that edge only. Exactly TWO per page; more reads as collage.
4. LA BANDE SAISONNIÈRE — the twelve-month strip as a full-bleed seam, once per page.
5. LE FILET DE RÉCOLTE — the weakest seam, capped at ONE: a full-bleed 1px rgba(leaf,.4) line with a mono .68rem / .24em LEAF micro-label sitting ON it (background the chapter's ground, padding-inline .9rem, translateY(-50%)) carrying a dateline fragment. A boundary made of whitespace plus a hairline and nothing else stays BANNED.
6. LE VERSANT — the single dark chapter, entered by a weld from a dusk photograph and left by a weld into a dawn one, so darkness reads as NIGHT IN THE ORCHARD, not an inverted marketing band. Text CREAM, rules HAIRLINE-DARK, provenance LEAF-LIGHT, commerce HONEY-LIGHT.
7. LA COULÉE INTERLUDE (the breath) — a full-bleed macro band at height min(64vh,38rem) showing the pour, the drizzle or the hands, with ONE line of serif voice over it and nothing else: no heading, no eyebrow, no CTA. A generic builder puts a headline and three cards here. Do not.

## Layout physics
- ONE inline-padding token clamp(1.15rem,4.2vw,4rem); container max-width 84rem, narrower than a catalogue because this world sells one thing; section block-padding clamp(4.5rem,10vh,7.5rem), the middle term in vh so rhythm follows viewport height, with welded sections overriding the top value to 0.
- MEASURE IS CAPPED IN EM: body 33em, lede 29em, pull-quote 19em, table footnote 36em, form sub-copy 30em, hero copy 34rem.
- NO GRID IS 50/50, and each skew is argued from content weight: hero 1.08fr/.92fr · method .95fr/1.05fr (the media column narrower because it is sticky and the fact rows are long) · purity 1.15fr/.85fr (table wider than its introduction) · docket .9fr/1.1fr · questions .78fr/1.22fr. At least one grid must invert expectation. Gaps clamp(2.2rem,5.5vw,5rem).
- SHAPE IS THE JAR SHOULDER: hero frame 3rem 3rem .6rem .6rem · media plates 2.2rem 2.2rem .5rem .5rem · docket plate 1.6rem 1.6rem .4rem .4rem · small plates 1.2rem 1.2rem .35rem .35rem · inputs and selects min(var(--radius), .55rem) · buttons, pills and stepper var(--radius) (:root sets --radius: 999px). THIS WORLD OVERRIDES the global "consistent corner radii from one scale": the scale here is a RATIO — top radius 3 to 6 times the bottom radius on every container above 12rem wide. A uniform 16px radius on a large container is a ban-list violation.
- OVERFLOW IS COMPOSITIONAL, and exactly four elements break their container: the watermark bleeding 12 percent past a section's inline edge · the hero plinth or wax seal crossing a boundary by 3rem · a dateline strip straddling a photograph's bottom edge at bottom -1.1rem · the seasonality ticks overshooting the band by .5rem. Safe only because overflow:clip sits on every section containing a bleeding element, plus overflow-x:clip on html and body.
- RULED ROWS, NEVER CARDS, for facts, methods, specs and delivery: padding-block clamp(1rem,2.2vw,1.35rem), border-top 1px rgba(ink,.16) with border-bottom on the last, grid-template-columns auto 1fr auto, gap 1.2rem, opening with a mono index or a .3em leaf dot and closing with a right-aligned promoted numeral. Zero background, zero radius, zero shadow.
- Exactly two sticky columns (the method photograph, the docket product column), both top 5.6rem, both static below 1000px; in the docket the product column takes order:-1 on mobile so the buyer sees the jar before the form. Every parallaxed photograph is top -12% and height 124% inside an overflow:hidden parent, and a dateline or quote laid over a photograph uses the same container class and the same 84rem measure.
- RESPONSIVE COLLAPSE: below 1000px two-column grids become 1fr and sticky becomes static; below 900px the showpiece loses its pin; below 720px the purity table drops to two columns and the band becomes a scrolling rail; below 600px the harvest rail becomes 2x2 and the weight pills a 3-column grid.

## The seasonality band (LA BANDE SAISONNIÈRE — build it before the order form)
The year, typeset — the second most recognisable object in the world, and about forty lines of code.
- Full-bleed on GROUND-2, border-block 1px rgba(ink,.18), padding-block clamp(2.4rem,5vh,3.6rem). Twelve equal columns at gap 0, each cell border-inline-start 1px rgba(ink,.14) (none on the first), height 4.6rem, position relative. Month labels in mono .64rem / .16em uppercase rgba(ink,.5) at each cell's top, padding .5rem .55rem, three letters in the brief's language.
- THE HARVEST WINDOW: an absolutely positioned bar spanning the harvest months — height .5rem, background LEAF, radius var(--radius), bottom 1.15rem, with inset-inline-start and width computed as percentages from the month indices. Inside it the PEAK segment, the ideal fortnight, as a second bar at the same height in HONEY at 20-25 percent of the window's width. Two tones, one bar: the season and its best moment.
- THE TICKS: 1px LEAF verticals at both ends OVERSHOOTING the band by .5rem top and bottom, each labelled in mono .62rem with the real opening and closing dates. THE CURRENT-MONTH MARKER: a 1.5px HONEY vertical the full height of its cell with a .34rem honey dot on top, positioned from new Date().getMonth() so the page ages honestly; without JavaScript it simply does not render — never hard-code a month, never fake today.
- Under the band, ONE sentence at .82rem rgba(ink,.6), max 34em, saying what the window means for the buyer — only if it is true. The band NEVER carries a CTA, a price or a claim. It is a calendar.
- MOTION on enter: the leaf bar scaleX 0 to 1 from the inline-start edge over 1.1s power3.out · the honey peak autoAlpha 0 to 1 over .6s at +.35s · the ticks scaleY 0 to 1 over .4s stagger .08 at +.5s · the marker last over .5s. once:true.
- BELOW 720px it becomes an overflow-x:auto rail at min-width 44rem with scroll-snap-type x proximity, and JavaScript sets scrollLeft on load so the HARVEST WINDOW is what the visitor sees first, not January. In RTL invert that scrollLeft sign and set the bar's transform-origin to the inline-end edge via a CSS custom property.

## The purity table (LE TABLEAU DE PURETÉ — facts only)
Real table markup: border-collapse collapse, a caption, thead with scope="col", tbody with scope="row" on each first cell. Never a div grid pretending to be a table, never cards.
- Caption: the 1.6rem LEAF silhouette bullet, then mono .70rem / .22em uppercase rgba(ink,.54), aligned to the start, padding-bottom 1rem. Head cells: mono .68rem / .2em uppercase rgba(ink,.5), padding-block .8rem, border-bottom 2px solid rgba(ink,.5) — the ONLY 2px rule in the world, and it belongs to this table.
- Body cells: padding-block .82rem, border-bottom 1px rgba(ink,.16), the last row also 2px. The fact name in the body face at .95rem; the value column text-align end with the numeral promoted (mono, 1.15em, tabular-nums, full ink) and its unit at .62em rgba(ink,.5); an optional third column for method or source in mono .72rem. Row hover above 1024px only: background rgba(honey,.07) over .2s. ZEBRA STRIPING IS BANNED — the rules do the work. A footnote at .74rem rgba(ink,.5), max 36em, names the method or date of analysis, and only what the brief supplies.
- THE HARD RULE, and the most important sentence in this document: EVERY NUMBER IN THIS TABLE COMES FROM THE BRIEF. Three facts means three rows and it looks deliberate. Inventing a humidity percentage, an acidity level, a vitamin content, a lab name or a certification is not a style choice — in the food trade it is a correctness bug and a legal one. A short table is fine; a fabricated table is a failed build.
- THE PURITY METER, optional and only for a real measurable on a real scale: a 4px track at rgba(ink,.14) radius min(var(--radius), 2px) with a linear-gradient(to right, leaf, honey) fill whose width is written by JavaScript at the moment the count-up fires and transitioned over 1.3s. Never a made-up quality score, never five stars.

## Motion identity (GSAP 3 + ScrollTrigger from a CDN; Lenis optional and welcome here)
THE SAFETY CONTRACT COMES FIRST AND IS NON-NEGOTIABLE. Compute one flag: reduced = matchMedia("(prefers-reduced-motion: reduce)").matches, hasGsap = typeof window.gsap !== "undefined", animate = hasGsap && !reduced. EVERY hidden initial state — autoAlpha 0, y offsets, strokeDashoffset, start scales — is set with gsap.set() INSIDE the animate branch; never author opacity:0, visibility:hidden or a dash offset in CSS for an animated element. If the CDN fails or motion is reduced, the page is fully visible, fully drawn and fully functional, with the wax seal at animation:none and nothing pinned. Ship a CSS prefers-reduced-motion block that, beyond the blanket .01ms override, sets the wax seal and the mobile band rail to animation:none and width:auto, parks the light wash at its resting opacity, leaves the silhouette fully drawn AND filled, and shows the seasonality bar, ticks and marker at their final values. CANVAS IS NOT USED IN THIS WORLD — every drawn thing is inline SVG.
TIMING BANDS — every duration belongs to one: .28-.45s interaction feedback · .55-.75s component state · .9-1.4s narrative reveals · 1.6-2.0s the hero photograph settle · 5.5s the one ambient loop · 46s the decorative seal. ONE shared CSS easing token cubic-bezier(.24,.62,.18,1) across roughly twenty transitions. gsap.defaults({ease:"power2.out", duration:1.1}) — this world is unhurried; a .4s reveal here feels like being hurried out of an orchard. Eases: power3.out entrances, power2.out settles and counters, power2.inOut stroke draws, power3.inOut the pour wipe, sine.inOut the ambient loop, "none" every scrub.
TRAVEL IS SMALL: y offsets of 12 / 24 / 40 only, all three inside the hero to encode three depth planes · scales .965 / 1.06 / 1.12 · hover lift -2px · glyph nudge 4px · parallax yPercent -6 to 6 and never more. Nothing travels 100px.
1. HERO ENTRANCE — about 2.3s of overlapping tweens at absolute positions, never a sequence. Set: photograph autoAlpha 0 with inner img scale 1.12 and yPercent -3 · copy line spans autoAlpha 0 y 24 · the price frame autoAlpha 0 y 40 scale .965 with its silhouette path strokeDashoffset 100 · pills, rail and reassurance autoAlpha 0 y 12. Then tl.to(photo,{autoAlpha:1,duration:.9},0) .to(img,{scale:1,yPercent:0,duration:1.9,ease:"power2.out"},0) .to(lines,{autoAlpha:1,y:0,duration:1,stagger:.10},.28) .to(priceFrame,{autoAlpha:1,y:0,scale:1,duration:1.1},.72) .to(silPath,{strokeDashoffset:0,duration:1.3,ease:"power2.inOut"},.72) .to(furniture,{autoAlpha:1,y:0,duration:.8,stagger:.09},1.25). The jar's outline drawing itself under the price while the field settles behind it is the page's first impression; spend the code there.
2. THE ONE AMBIENT LOOP, diegetic, hero only: gsap.to(lightWash,{opacity:.62, scale:1.06, duration:5.5, ease:"sine.inOut", yoyo:true, repeat:-1}) — a cloud crossing the sun. A floating blob, a bobbing leaf or a particle field is not diegetic and is BANNED.
3. GENERIC REVEALS — roughly sixteen elements: gsap.set({autoAlpha:0,y:24}) then {autoAlpha:1,y:0,duration:1,ease:"power3.out",stagger:.08}, start "top 88%", once:true.
4. THE POUR WIPE on framed images — clipPath inset(0% 0% 100% 0%) to inset(0%) over 1.2s power3.inOut so the image fills from the TOP DOWN like honey entering a jar, never a bottom-up curtain, while the inner image counter-scales 1.12 to 1 over 1.5s power2.out at position 0; clearProps both. start "top 86%", once:true.
5. GENTLE ORCHARD PARALLAX on up to THREE full-bleed photographs: gsap.fromTo(img,{yPercent:-6},{yPercent:6,ease:"none",scrollTrigger:{trigger:section,start:"top bottom",end:"bottom top",scrub:.6}}). The .6 lag is deliberate — scrub:true reads mechanical, a lagged scrub reads unhurried. This OVERRIDES the global one-scrub economy.
6. COUNT-UP on the founding year and at most two other REAL numbers: a proxy tweened over 1.4s power2.out with onUpdate writing Math.round into textContent. FOR A YEAR, count from target minus 60, never from zero — a year counting from 0 is a slot machine. start "top 90%", once:true, plus a 4000ms setTimeout painting the final value if the trigger never fires on a deep-linked load.
7. The showpiece scrub, the band draw, the seal's 46s rotation and the sticky bar's enter and retreat, all specified in their own sections. once:true on EVERYTHING non-scrubbed; nothing re-animates on scroll-up. At most ONE pin, and NEVER a pin below 900px.
MICRO-INTERACTIONS, all CSS: buttons translateY(-2px) over .32s AND a separately transitioned arrow glyph at translateX(4px) — two transitions, not one — returning to 0 over .12s on :active · inputs changing THREE properties together on focus over .28s (border-color HONEY-DEEP, box-shadow 0 0 0 3px rgba(honey,.18), background .55 to .8 alpha) · validation entering opacity 0 and translateY(-3px) over .3s with min-height 1.15em reserved so nothing reflows · accordion panels grid-template-rows 0fr to 1fr over .55s with an overflow:hidden inner · the price and total BLINKING .32s from 1 to .4 to 1 on every recalculation.

## The showpiece: LA COULÉE (the pour)
The page's one pinned moment and the fourth appearance of the silhouette. The section: min-height 100svh, background GROUND-3 (or SOUS-BOIS if the dark chapter sits here), entered by a horizon weld, content centred.
- The SVG: the silhouette at width min(78vw,28rem), stroke HONEY at 1.6 (LEAF-LIGHT on dark), fill none, pathLength="100" and stroke-dasharray="100" on every path, stroke-linecap round, strokeDashoffset set to 100 by gsap.set inside the animate branch ONLY. Inside it define a clipPath whose child is the BODY path and a linearGradient from HONEY to HONEY-DEEP at x1=0 y1=0 x2=0 y2=1; place a rect with clip-path referencing that clipPath, covering the viewBox, filled with the gradient, its y attribute at the viewBox height so it rests below the jar.
- One ScrollTrigger at {trigger:section, start:"top top", end:"+=120%", pin:true, pinSpacing:true, scrub:.5, anticipatePin:1}. 0 to .55 draws strokeDashoffset 100 to 0 across the three subpaths in physical order (lid, body, label) at stagger .06 — the jar draws itself as you scroll. .50 to .82 tweens the rect's y attribute from the viewBox height to 34 with ease "none" via attr:{y:34} — the jar fills with honey. .78 to 1 fades in three FACT LINES beside it at stagger .1, each a mono micro-cap with a promoted numeral: origin, harvest month, net weight.
- BELOW 900px THERE IS NO PIN: run the identical timeline unpinned at {start:"top 80%", end:"bottom 60%", scrub:.5}. Pinning on a phone in this market is a scroll-jail and it is banned.
- FALLBACK CONTRACT: if GSAP fails or motion is reduced, the SVG renders FULLY DRAWN (strokeDashoffset is never authored in CSS, so its default is 0), the fill rect sits at its final y from the markup with the animate branch moving it to the start, and the three fact lines are plainly visible — a finished, filled, labelled jar, and no section is ever empty.
- The showpiece carries NO CTA. It is the object, told properly; the CTA is thirty lines below, in the docket.

## Components
- BUTTONS: pills only at border-radius var(--radius) — with the wax seal, the only round shapes here. PRIMARY: HONEY-DEEP fill, GROUND-0 text, padding 1.05em 1.8em, .95rem/600, tracking .02em, inline-flex gap .6em with a drawn 1.4px arrow; hover to INK with the lift; disabled opacity .45, no lift; SMALL variant .82em 1.35em at .84rem. GHOST: transparent with box-shadow inset 0 0 0 1px rgba(ink,.28) as its outline, going to inset 0 0 0 1px HONEY-DEEP with HONEY-DEEP text on hover; on dark grounds the ring is rgba(cream,.3) and the text CREAM. UI NEVER uses a real border property for its outline — inset box-shadow is the border replacement, so nothing shifts a pixel on state change.
- SHADOWS: only on PHOTOGRAPHS and the contained product, always large-blur, large-negative-spread, low-opacity, hue-tinted: 0 40px 70px -34px color-mix(in srgb, var(--foreground) 42%, transparent) under the hero product · 0 26px 56px -30px color-mix(in srgb, var(--foreground) 34%, transparent) on framed images · 0 40px 70px -34px color-mix(in srgb, var(--foreground) 60%, transparent) on frames over the dark chapter. ZERO shadows on plates, rows, inputs, nav, buttons or the sticky bar; depth here comes from light and tone, not elevation.
- INPUTS: background color-mix(in srgb, var(--background) 55%, transparent), border 1px color-mix(in srgb, var(--foreground) 22%, transparent), radius min(var(--radius), .55rem), padding 1em 1.05rem, 1rem body face, min-height 3.1rem (a real 48px+ tap target); labels above in mono .70rem / .18em uppercase var(--muted), hints at .76rem color-mix(in srgb, var(--foreground) 50%, transparent) below, textareas 2 rows. SELECTS: appearance none, the input's box, and a DRAWN chevron — an inline SVG data URI 12x8, stroke 1.4 var(--accent), fill none — at background-position calc(100% - 1rem) centre, with a mirrored rule under [dir="rtl"].
- RULED ACCORDION: border-top 1px hairline per item, the question a full-width flex button in the display serif at clamp(1.05rem,1.5vw,1.25rem) weight 500, padding-block 1.35rem, turning HONEY-DEEP when open, with a two-bar LEAF glyph (1.4px, the vertical bar scaleY 1 to 0 over .4s). Single-open, aria-expanded maintained, role="region" on the panels.
- THE WAX SEAL: a 6.4rem circle SVG — a 1px HONEY circle at .55 alpha, a mono textPath at 8.4px / .24em uppercase naming origin and year, one .3rem LEAF dot; rotating 46s linear infinite, 5rem below 600px.
- FOOTER: the dark pole. A contact row at 1fr 1fr collapsing to 1fr (phone, hours, the real address if the brief has one, never an invented one), then THE MONUMENT: the merchant's name at clamp(4rem,17vw,15rem), display serif 400, line-height .84, tracking +.02em, colour transparent, -webkit-text-stroke 1px rgba(honey,.5), user-select none, aria-hidden, centred, with the watermark at 22rem in rgba(cream,.08) behind it; then a hairline-topped link row at .84rem rgba(cream,.7) and a credit at .78rem rgba(cream,.45).
- CRAFT DETAILS: explicit width and height on every image · fetchpriority="high" on the LCP image, loading="lazy" elsewhere · art-directed alt on content images, alt="" plus aria-hidden on watermarks, seal and decorative duplicates · aria-live="polite" on the total and on errors · an output element for the stepper · a skip link · an inline-SVG data-URI favicon of the silhouette · theme-color matching GROUND-0.

## Conversion objects (this world SELLS, cash on delivery — its money components)
- THE PRICE FRAME. The numeral in display serif 500 at clamp(2.6rem,5vw,3.8rem), tabular-nums, INK (CREAM over the hero photograph), inside the silhouette's label rectangle as specified above.
  - THOUSANDS TAKE A NARROW NO-BREAK SPACE, written as the entity &#8239; so it survives copy-paste and never wraps: 4&#8239;900 renders as 4 900. Never a comma, never a period, never a plain space. A hard law governing the price, the per-unit line, the total, the sticky bar and every promoted numeral.
  - The currency: mono 500 at .26em of the numeral, uppercase, tracking .22em, rgba(ink,.55), aligned to the numeral's baseline with align-self flex-end and padding-bottom .5em — a micro-label, never a superscript; in Arabic it becomes دج at tracking 0. A struck was-price only if the brief has a real previous price: a real del element at 1.1rem rgba(ink,.5) with text-decoration-color HONEY at 1.5px. NEVER a percentage-off badge, NEVER a starburst.
  - THE PER-UNIT LINE beneath, mono .72rem rgba(ink,.55): "soit 1 960 DZD le kilo" — on a weight-variant page the most persuasive line available, and almost nobody writes it; it recomputes with the selection. Then the REASSURANCE LINE at .8rem: exactly what happens on submit and what it costs today, in the brief's real terms.
- THE WEIGHT PILLS (les formats) — the signature commerce object. The group: inline-flex, gap .5rem, padding .34rem, background GROUND-2, radius var(--radius), box-shadow inset 0 0 0 1px rgba(ink,.14), role="radiogroup" with an aria-label; below 400px a 3-column grid at gap .5rem, each pill keeping var(--radius). Each pill: a label wrapping a visually-hidden radio, padding .62em 1.15em, radius var(--radius), mono .78rem tracked .1em, colour rgba(ink,.62), min-height 44px, transition .32s shared ease, weights typeset properly (250 g · 500 g · 1 kg).
  - Checked via :has(input:checked): background GROUND-0, colour INK, box-shadow 0 1px 0 rgba(ink,.10), and the pill's own per-unit micro-line at .62rem HONEY-DEEP fading in over .3s. ONLY the selected pill shows its per-unit price — that restraint is the designed detail. Focus-visible draws the 2px HONEY-DEEP ring at offset 3px.
  - PICK ONE and hold it page-wide: the background swap above, or a sliding thumb — an ::after on the group at inset .34rem, width calc(33.333% - .23rem), background GROUND-0, radius var(--radius), transform translateX transitioned over .5s with the shared ease from a data-index on the group (sign inverted under RTL). Mixing the two is a correctness bug.
  - Changing the weight updates FOUR things through ONE render() reading ONE state object: the price numeral (with the .32s blink), the per-unit line, the sticky bar's price and weight line, and the form's weight field. Never let two places compute the price independently.
- THE STICKY ORDER BAR (la barre de récolte): fixed, inset-inline 0, bottom 0, z-index 96, height 4.6rem with env(safe-area-inset-bottom) added as padding-bottom, background rgba(ground-0,.93), backdrop-filter blur(16px), border-top 1px rgba(ink,.18), radius min(var(--radius), 0px), NO shadow; grid auto 1fr auto, gap .8rem, align-items centre, padding-inline clamp(.9rem,4vw,1.4rem).
  - START: the silhouette at 2.4rem, stroke 1.3, HONEY-DEEP, aria-hidden. CENTRE: the price in display serif 500 at 1.2rem, tabular-nums, thin-space thousands, mono DZD label at .58em, and beneath it the ACTIVE WEIGHT in mono .64rem / .14em uppercase rgba(ink,.55). END: the primary pill, small variant, min-width 8.4rem, label "Commander" or its Arabic equivalent; it scrolls to the docket honouring scroll-margin-top and focuses the phone field after a 700ms settle, and it NEVER opens a modal.
  - ABOVE 560px the bar also carries the weight pills at .68rem between price and button, so the buyer can change format without scrolling back; below 560px only the active-weight line remains. Above 900px the bar becomes a floating plate: max-width 36rem, margin-inline auto, bottom 1.2rem, 1px hairline on all four sides, radius min(var(--radius), 999px).
  - It ENTERS translateY(100%) to 0 over .55s with the shared ease when a ScrollTrigger passes the hero's bottom, and RETREATS over .45s when the docket enters the viewport — a bar must never cover the thing it points at, and that retreat is the detail most builds forget.
- THE ORDER FORM — LE BON DE RÉCOLTE (the harvest docket), the climax. Chapter on GROUND-1 or GROUND-3, entered by a horizon weld, grid .9fr/1.1fr. The STICKY PRODUCT COLUMN at top 5.6rem holds the contained jar, the dateline, the price frame in miniature (silhouette 5.4rem) and the trust facts as a vertical ruled list; on mobile it takes order:-1 and goes static. The PLATE: GROUND-0, border 1px rgba(ink,.16), radius 1.6rem 1.6rem .4rem .4rem, padding clamp(1.6rem,4vw,2.6rem), max-width 34rem, no shadow. Its DOCKET HEAD is a mono .68rem / .24em uppercase rgba(ink,.5) row with a hairline beneath — start side "BON DE COMMANDE · PAIEMENT À LA LIVRAISON", end side the real current date written by JavaScript. No order number exists before submission; inventing one is a lie the success state would contradict.
  - FIELD ORDER, not negotiable in this market: PHONE, then full name, then wilaya, then commune and address, then quantity, then an optional note. No email field. No account. No password. Ever.
  - PHONE: type="tel" inputmode="tel" autocomplete="tel" pattern="[0-9 ]{9,14}" with a hint naming the local format — this world OVERRIDES the global inputmode="numeric" default for phone specifically, because inputmode tel raises the keypad this market expects. NAME autocomplete="name". WILAYA: a real select of all 58, styled exactly like the inputs with the drawn LEAF chevron, never free text; if the brief supplies per-wilaya fees, changing it updates the delivery row and the total, otherwise the delivery row states the policy in one honest sentence. ADDRESS: a 2-row textarea plus an optional landmark line.
  - QUANTITY: a STEPPER, never a number input — an inline-flex group at border-radius var(--radius) with two 2.9rem true-circle buttons at 50% carrying drawn 1.4px minus and plus glyphs and an output element at min-width 2.8rem in mono 1.15rem tabular-nums between them; buttons invert to INK fill over .26s on hover, opacity .32 when disabled. The cap is stated and REASONED in the hint.
  - THE DELIVERY ROW sits directly ABOVE the submit and is never hidden: border-top 1px hairline, padding-block 1rem, space-between, the wilaya's fee and delivery window in mono on the start side and "à la livraison" on the end — the buyer's first worry answered at the second they decide.
  - THE FOOT: border-top 1.5px rgba(ink,.4), the docket's total rule, padding-top 1.3rem, space-between — the label "TOTAL À PAYER À LA LIVRAISON" in mono .68rem / .22em uppercase rgba(ink,.5) and the total in display serif 500 at 2rem, tabular-nums, thin-space thousands. It recomputes on every weight, quantity and wilaya change with the .32s blink, never a count-up.
  - VALIDATION IS BLUR-GATED: a touched map so an error appears only after a field's first blur, never while someone is typing into a fresh field, and never blocking typing. Errors are full sentences in the merchant's voice in the error mix of var(--primary) and var(--foreground) at .76rem with min-height 1.15em reserved so nothing reflows; aria-invalid, aria-describedby and aria-live="polite" wired properly.
  - SUBMIT: the primary pill at full width inside the plate — the one place a full-width button is legal here — labelled "Commander — paiement à la livraison", with a deliberate 750ms pending state replacing the label with a present-tense human sentence and a disabled flag for double-submit protection.
- THE SUCCESS STATE — LE BON TAMPONNÉ. The form transitions opacity to 0 over .48s with visibility 0s .48s so focus never lands on a hidden control, while a panel absolutely positioned over it INSIDE THE SAME BOX fades in over .75s with a .28s delay; the plate's height is never animated. The instant validation passes — as the panel begins — the harvest is entered in the register: the page dispatches the wandit:lead CustomEvent on document with the buyer's fields flat in detail (name, phone as typed, wilaya, commune, plus weight and quantity), while one off-canvas decoy input marked data-wandit-hp rests in the docket, never read by the page's own script.
  - It opens on THE STAMP: the silhouette at 9rem, stroke 1.6 HONEY, strokeDashoffset 100 to 0 over 1.2s power2.inOut at a .35s delay, then the honey fill rect rising inside it over 1.1s power2.out at +.5s — the jar fills as the confirmation. Above it "COMMANDE ENREGISTRÉE" in mono .68rem / .28em uppercase LEAF.
  - Below it, THE BUYER'S ORDER RENDERED AS A DATELINE, in the exact dateline format: their name · wilaya · weight · quantity · total, middot-separated in mono .74rem with HONEY middots. The customer's order becomes provenance — the whole world in twenty lines of markup. Then the WhatsApp ghost pill so they can confirm in one tap, and one sentence saying who calls and when, only if the brief supplies it.
  - PERSIST IT: store the order and chosen weight in localStorage; on return restore the weight and paint the success state INSTANTLY with no animation, so a returning buyer is never asked to order twice.
- THE WHATSAPP CTA, styled to the world and NEVER in the brand green: the GHOST pill with a hand-drawn inline SVG at 15x15 — stroke 1.4 HONEY-DEEP, fill none, linecap and linejoin round: a circle outline with a small tail triangle at its lower start corner and a handset path inside. Gap .65em, glyph on the inline-start side, label "Commander sur WhatsApp" or its Arabic equivalent. The href is the brief's wa.me link with a prefilled text naming the product, the selected weight and the dateline, so the merchant knows instantly which jar and which harvest.
- THE TRUST STRIP (le bandeau): full-bleed on GROUND-2, border-block 1px rgba(ink,.16), padding-block 1.5rem, a 4-column grid at gap clamp(1.2rem,3vw,2.6rem), 2x2 below 720px. Each cell: a 22x22 inline SVG icon YOU draw — stroke 1.2, linecap and linejoin round, fill none, stroke LEAF, opacity .9 — then a mono .68rem / .22em uppercase line and a .78rem rgba(ink,.54) sub-line. Draw exactly these, no emoji, no icon font, nothing filled: 1 PAIEMENT À LA LIVRAISON, a 14x9 banknote rectangle with a 3-radius circle centred inside · 2 LIVRAISON 58 WILAYAS, a truck built from a 12x7 body box, a 6x5 cab welded to its end and two 2.2-radius wheels · 3 RÉCOLTE DATÉE, a calendar built from a 13x12 rounded rectangle, two 3-unit hangers, a rule under the head band and one small HONEY dot on a day cell · 4 the brief's REAL purity claim as a 9-unit teardrop outline with a 1px arc highlight inside. If the brief certifies nothing, cell 4 becomes ÉCHANGE SOUS 7 JOURS (a circular arrow sweeping 20 to 80 percent of a 9-radius circle, closed by a 3-unit chevron), and if that is not true either the cell does not exist and the grid becomes 3 columns. Sub-lines are FACTS from the brief, never adjectives: a trust strip with an invented claim is worse than no trust strip.
- CROSS-SECTION STATE: the weight chosen anywhere — hero pills, sticky bar, showpiece fact lines — writes to the SAME state object and pre-selects the docket's weight; an early CTA sets the weight AND scrolls to the docket, so a button in section two rewrites section nine before travelling to it.

## Editorial furniture (REQUIRED — this is Verger's voice)
- LA DATELINE, the signature. Mono .72rem / .18em uppercase LEAF (LEAF-LIGHT on dark), fields in a FIXED order separated by HONEY middots at opacity .85: season and year · place · coordinates. Four appearances minimum — the top bar, the hero eyebrow, above the purity table, the success panel. The prime marks are the real characters ′ and ″, never apostrophes. No coordinates in the brief means the third field is dropped; never invent a valley or a latitude.
- LA MENTION DE MÉTHODE — one technical footnote per chapter at .68rem / .2em rgba(ink,.44), the page describing its own making: "Extraction à froid · 24 °C maximum" / "Mise en pot le 12 mai, à la main". A narrow no-break space always precedes the unit.
- LE MOT DU PRODUCTEUR: the merchant's voice, exactly once, on the dark chapter — two or three flat sentences with no adjectives, signed with a name in mono .68rem / .24em uppercase HONEY-LIGHT and, if the brief supplies it, the founding year as the page's one count-up.
- LE RELEVÉ: ruled fact rows with promoted mono numerals. FIG. CAPTIONS under every framed image: a space-between row with descriptive text on the start side at .76rem rgba(ink,.5) and the figure number in LEAF on the end. LA CITATION: exactly one unexplained line of serif voice over a photograph at clamp(1.4rem,3vw,2.2rem) / 1.35 in CREAM with one italic word, centred, max 19em.
- THE HARVEST RAIL's four micro-facts: origin, month, net weight, method — facts, never adjectives. Units typeset properly everywhere (250 g, 1 kg, 24 °C, 17,2 %) with the brief's decimal convention.
- None of these invent a business fact. They are TYPESETTING. Where the brief is silent, delete the device rather than inventing its content.

## Photography direction
Five images asked for as ONE coherent shoot: THE FIELD (the orchard, grove, hives or plot at golden hour, sun low and to the side, a clear horizon around the upper third, nobody facing camera, no text — hero and weld source) · THE MACRO DRIZZLE (the product pouring or being cut, extremely close, backlit so the material glows) · THE CONTAINED PRODUCT (the jar on neutral seamless in soft daylight, one contact shadow, 15 percent breathing room on every side, for object-fit contain) · THE HANDS (a real pair at work, no stock-photo smiles) · THE DUSK (the same place at last light, for the dark chapter's entry weld).
All frames share ONE light family; a cold studio shot between two golden-hour frames breaks the world instantly. IF IMAGE GENERATION FAILS, the affected section falls back to a TONE FIELD — the chapter's ground plus the light wash plus the watermark at 34vw plus the dateline. Never a gray box, never a deleted section: the weld still works, because the weld is a gradient into a ground and the ground is always there.

## Arabic and RTL adaptation
- dir="rtl" on html, logical properties throughout (padding-inline, margin-inline, border-inline-start, inset-inline); every asymmetric grid mirrors for free.
- ARABIC IS NEVER LETTER-SPACED — it breaks the shaping of joined script. Every tracking value in this document (.12em through .28em) drops to 0 and text-transform:uppercase is REMOVED entirely; the signage register is carried instead by size +2px, weight +100, and rgba(ink,.5) becoming LEAF. Scope it under html[lang="ar"]. Line-height goes UP: body 1.9, lede 1.75, table values 1.8.
- NO ITALIC EXISTS IN ARABIC: the emphasised word takes LEAF, weight +100, and a 1.5px LEAF underline at text-underline-offset .18em. Same rule, same rhythm, different device.
- FACES: an Arabic display in the Amiri / Aref Ruqaa / Noto Naskh territory (a naskh with real stroke contrast is the honest partner to a Latin old-style serif) and a UI face in the Tajawal / Almarai / IBM Plex Sans Arabic / Cairo territory. THE MONO ROLE HAS NO ARABIC EQUIVALENT — never force a monospace Arabic; the mono role is played by the UI face at +.5px weight 500, and where the record-book register matters most (dateline, table heads) by LEAF plus a 1px rule beneath.
- NUMERALS: keep Western digits 0-9 for prices, weights and phone — that is what Algerian commerce uses — with the same thin-space thousands; the currency label becomes دج at tracking 0.
- COORDINATES MUST BE ISOLATED: wrap the coordinate field in a span with dir="ltr" and unicode-bidi:isolate, or the degree and prime marks reorder and the latitude scrambles. The most common RTL bug in this world.
- THE BAND keeps calendar order and mirrors so January sits on the right, its bar's transform-origin flipping to the inline-end edge and the mobile rail's scrollLeft sign inverting. THE SEAL: Arabic on a circular textPath breaks shaping, so the seal keeps its circle and dot, its text becomes two straight stacked lines, and the rotation is switched off. The middot survives in Arabic typography; keep it. Build the Arabic page as the same world in another script, never as a translation of the French one.

## Global rules this world overrides (state them, then do them)
1. Overrides the ONE-ACCENT habit: TWO hues with absolute role separation — HONEY owns commerce, LEAF owns provenance; they never swap, never blend (except the purity meter), and no third hue exists.
2. Overrides "consistent corner radii from one scale": the jar shoulder is asymmetric BY LAW — top radius 3 to 6 times the bottom radius on every container above 12rem wide.
3. Overrides the single-scrub economy: up to THREE gentle parallax scrubs plus the showpiece scrub, because the orchard interludes are the world's spine. The pin cap stays at ONE and pinning below 900px stays banned.
4. Overrides "count up the price": prices and totals BLINK (.32s, 1 to .4 to 1), never count — a recalculating price that counts is a slot machine. Only the founding year and real harvest counts count up, from target minus 60.
5. Overrides the global phone inputmode: tel, not numeric.
6. Overrides the global MASKED LINE RISE on display headlines: headlines here are still hand-broken into block-level line spans, but they arrive on autoAlpha and y 24 with NO overflow-hidden mask, because a mask is a hard travelling edge and this world has none — its light has soft edges everywhere, including on type. The only clipped reveal on the page is the POUR WIPE, which is a liquid filling a frame, not a line leaving a slot.
7. Overrides the global hero entrance ceiling of about 1.6s: this arrival runs about 2.3s, because the jar's outline drawing itself under the price is the page's first impression and it cannot be hurried. Nothing else on the page exceeds 2.0s except the photograph settle.
8. Overrides the tolerance for whitespace-plus-hairline seams: a boundary must be a weld, a tone step, an overlap, the band, or the single permitted harvest rule.
9. It does NOT override the shadow discipline, the invented-claims ban or the data-slop ban. In a food world those are the strictest rules on the page: the purity table, the trust strip and the dateline are exactly where fabricating one number would be a real harm.

## Verger ban list (in addition to the global one)
Neutral grays of any kind · pure white grounds or pure white text · a uniform 12-16px radius as the page's only shape · burlap, hessian, wood-plank or kraft-paper background textures · raster wax stamps, ribbon banners and rosette badges · handwriting or script display faces · bee, olive-branch, leaf-sprig and wheat clipart icon sets (the silhouette plus four drawn trust icons are the entire icon budget) · emoji anywhere · the WhatsApp brand green · "100 % NATUREL" starbursts, percentage-off badges, countdown timers · INVENTED nutrition values, certifications, lab results, coordinates or founding years — the worst failure available here · zebra-striped tables · feature cards with icons and two lines of gray text · product card grids (this is a single-product world; the variants are WEIGHTS, not products) · carousels and lightboxes · gradients as decorative fills (the light wash, the honey pour and the 4px purity meter are the only gradients) · more than ONE italic word per headline · italics or letter-spacing on Arabic text · centred running prose (only the poster hero, the pull-quote and the monument may centre) · per-character text splitting · more than ONE ambient loop · more than ONE pin, and NEVER a pin below 900px · a hero without a price · a page without a dateline · any hidden state authored in CSS · box-shadows on plates, rows, inputs, nav or the sticky bar.

## Intensity
This world fails by being merely BEIGE. A cream page with a serif headline, a honey button and a jar photo ships every week somewhere; it is not Verger. The difference is entirely physics: a date and a place stated before anything else is read, one outline drawn once and walked down the page at six scales, photographs that dissolve into paper instead of ending, a ground stepping down four rungs as the light leaves, a year typeset as a calendar with its best fortnight marked in honey, a table carrying only what the merchant can prove, a jar that draws and fills itself as you scroll, weights as designed pills that rewrite four places at once, and a docket that hands the buyer's own order back in the same format as the harvest itself.

Executed at 60 percent — cream background, gold button, rounded cards, a stock honey photo, a made-up nutrition table — this is exactly the generic produit-naturel page it exists to replace, and the invented table makes it worse than generic. Executed at 100 percent, a buyer scrolling on a phone in Oran feels the low sun on a valley they could find on a map, understands in nine seconds what was picked, when, by whom, in what quantity and what it costs at their door, and orders because the page never once asked them to take anything on faith. Push INTO the specificity. Every number above is load-bearing.
`,
	energy: "medium",
	family: "verger",
	id: "verger",
	industries: [
		"food",
		"honey",
		"olive-oil",
		"dates",
		"spices",
		"herbal",
		"tea",
		"coffee",
		"grocery",
		"agriculture",
		"crafts",
		"cosmetics",
		"beauty",
		"bakery",
	],
	kind: "product",
	mood: ["sunlit", "rooted", "unhurried", "wholesome", "documentary"],
	name: "Verger",
	preview: {
		ground: "#F7F1E3",
		ink: "#1E241A",
		accent: "#C88A21",
		fontFamily: "Newsreader",
		sampleWord: "Le Verger",
	},
	priceFeel: "premium",
	tagline:
		"Unbleached paper under low golden light, a harvest date and a valley printed above everything like provenance on a bottle of oil, and your jar's outline drawn in one honey line that follows the buyer all the way down — until it draws itself, fills up, and stamps their order at the bottom.",
};
