import type { FeedbackItem } from "@/features/feedback/types";

export const MOCK_FEEDBACK: FeedbackItem[] = [
	{
		id: "FDB-2841",
		title: "Published site shows a blank hero after editing",
		message:
			"I changed the hero copy, clicked publish, and the whole hero became empty on the live site. The editor still shows it correctly. Republishing did not fix it, but restoring yesterday's version brought it back.",
		type: "bug",
		status: "new",
		priority: "urgent",
		createdAt: "2026-07-30T08:42:00.000Z",
		reporter: {
			name: "Maya Benali",
			email: "maya@atelier-kite.com",
			avatarUrl: "/images/avatars/03.png",
			plan: "Business",
			memberSince: "2025-09-18T00:00:00.000Z",
		},
		context: {
			page: "Website editor",
			path: "/projects/solace-studio/editor",
			project: "Solace Studio",
			browser: "Chrome 138",
			device: "MacBook Pro · macOS 15.6",
			viewport: "1512 × 982",
		},
		tags: ["publishing", "hero", "regression"],
		attachment: {
			name: "blank-hero-recording.mov",
			type: "video",
			size: "18.4 MB",
		},
		adminNote: "",
		activity: [
			{
				id: "activity-2841-1",
				label: "Feedback received",
				description: "Submitted from the editor feedback button.",
				createdAt: "2026-07-30T08:42:00.000Z",
				tone: "accent",
			},
		],
	},
	{
		id: "FDB-2838",
		title: "Let me copy a section from one page to another",
		message:
			"I often build a section on the home page and need the same structure on another page. Duplicating the whole page and deleting everything else is the only workaround I found.",
		type: "idea",
		status: "reviewing",
		priority: "high",
		createdAt: "2026-07-30T07:06:00.000Z",
		reporter: {
			name: "Théo Marchand",
			email: "theo@maison-braise.fr",
			avatarUrl: "/images/avatars/07.png",
			plan: "Pro",
			memberSince: "2026-01-11T00:00:00.000Z",
		},
		context: {
			page: "Website editor",
			path: "/projects/maison-braise/editor",
			project: "Maison Braise",
			browser: "Firefox 141",
			device: "Dell XPS · Windows 11",
			viewport: "1440 × 900",
		},
		tags: ["editor", "sections", "workflow"],
		adminNote:
			"Compare with the existing duplicate-page behavior before product review.",
		activity: [
			{
				id: "activity-2838-2",
				label: "Moved to review",
				description: "Nadia is checking related editor requests.",
				createdAt: "2026-07-30T07:48:00.000Z",
				tone: "default",
			},
			{
				id: "activity-2838-1",
				label: "Feedback received",
				description: "Submitted from the editor feedback button.",
				createdAt: "2026-07-30T07:06:00.000Z",
				tone: "accent",
			},
		],
	},
	{
		id: "FDB-2834",
		title: "Domain setup language is hard to follow",
		message:
			"The DNS instructions use terms I don't understand, especially CNAME and propagation. A simple checklist that says exactly where to click in common domain providers would make this much easier.",
		type: "experience",
		status: "new",
		priority: "medium",
		createdAt: "2026-07-29T20:18:00.000Z",
		reporter: {
			name: "Nour El Amrani",
			email: "nour@ceramique-nomade.ma",
			avatarUrl: "/images/avatars/11.png",
			plan: "Starter",
			memberSince: "2026-07-04T00:00:00.000Z",
		},
		context: {
			page: "Domain settings",
			path: "/projects/ceramique-nomade/settings/domains",
			project: "Céramique Nomade",
			browser: "Safari 18.6",
			device: "iPad Air · iPadOS 18.6",
			viewport: "1180 × 820",
		},
		tags: ["domains", "onboarding", "copy"],
		attachment: {
			name: "dns-step.png",
			type: "image",
			size: "1.8 MB",
		},
		adminNote: "",
		activity: [
			{
				id: "activity-2834-1",
				label: "Feedback received",
				description: "Submitted from domain settings.",
				createdAt: "2026-07-29T20:18:00.000Z",
				tone: "accent",
			},
		],
	},
	{
		id: "FDB-2829",
		title: "Uploads freeze at 94% in Safari",
		message:
			"Three product photos stopped at 94% and never completed. Refreshing made me lose the rest of the upload queue. The same files worked in Chrome a few minutes later.",
		type: "bug",
		status: "reviewing",
		priority: "high",
		createdAt: "2026-07-29T14:33:00.000Z",
		reporter: {
			name: "Sofía Paredes",
			email: "sofia@lumbre-casa.es",
			avatarUrl: "/images/avatars/05.png",
			plan: "Pro",
			memberSince: "2025-11-27T00:00:00.000Z",
		},
		context: {
			page: "Asset library",
			path: "/projects/lumbre-casa/assets",
			project: "Lumbre Casa",
			browser: "Safari 18.6",
			device: "iMac · macOS 15.6",
			viewport: "1920 × 1080",
		},
		tags: ["uploads", "safari", "assets"],
		attachment: {
			name: "upload-stall.png",
			type: "image",
			size: "742 KB",
		},
		adminNote: "Requested browser logs from support.",
		activity: [
			{
				id: "activity-2829-2",
				label: "Moved to review",
				description: "Assigned to the media pipeline investigation.",
				createdAt: "2026-07-29T15:08:00.000Z",
				tone: "default",
			},
			{
				id: "activity-2829-1",
				label: "Feedback received",
				description: "Submitted from the asset library.",
				createdAt: "2026-07-29T14:33:00.000Z",
				tone: "accent",
			},
		],
	},
	{
		id: "FDB-2826",
		title: "A small brand kit would keep my pages consistent",
		message:
			"I would love one place to save my logo, two brand colors, and preferred fonts so each new page starts with the same basics. Right now I repeat those changes every time.",
		type: "idea",
		status: "planned",
		priority: "medium",
		createdAt: "2026-07-29T10:02:00.000Z",
		reporter: {
			name: "Rafael Costa",
			email: "rafael@onda-works.pt",
			avatarUrl: "/images/avatars/09.png",
			plan: "Business",
			memberSince: "2025-06-03T00:00:00.000Z",
		},
		context: {
			page: "Project settings",
			path: "/projects/onda-works/settings/general",
			project: "Onda Works",
			browser: "Chrome 138",
			device: "Mac mini · macOS 15.6",
			viewport: "2560 × 1440",
		},
		tags: ["brand kit", "fonts", "colors"],
		adminNote: "Included in the Q3 project foundations exploration.",
		activity: [
			{
				id: "activity-2826-2",
				label: "Added to roadmap",
				description: "Linked to the project foundations initiative.",
				createdAt: "2026-07-29T12:24:00.000Z",
				tone: "success",
			},
			{
				id: "activity-2826-1",
				label: "Feedback received",
				description: "Submitted from project settings.",
				createdAt: "2026-07-29T10:02:00.000Z",
				tone: "accent",
			},
		],
	},
	{
		id: "FDB-2819",
		title: "The new mobile preview saved me a lot of time",
		message:
			"Being able to check the phone layout without opening another device is excellent. I caught a heading wrap before publishing and fixed it immediately. Please keep this preview simple.",
		type: "praise",
		status: "resolved",
		priority: "low",
		createdAt: "2026-07-28T16:41:00.000Z",
		reporter: {
			name: "Aïcha Kouyaté",
			email: "aicha@terre-claire.sn",
			avatarUrl: "/images/avatars/01.png",
			plan: "Starter",
			memberSince: "2026-02-20T00:00:00.000Z",
		},
		context: {
			page: "Website editor",
			path: "/projects/terre-claire/editor",
			project: "Terre Claire",
			browser: "Chrome 138",
			device: "Lenovo Yoga · Windows 11",
			viewport: "1366 × 768",
		},
		tags: ["mobile preview", "editor"],
		adminNote: "Shared with the editor team.",
		activity: [
			{
				id: "activity-2819-2",
				label: "Closed with thanks",
				description: "Positive signal shared with the editor team.",
				createdAt: "2026-07-28T17:05:00.000Z",
				tone: "success",
			},
			{
				id: "activity-2819-1",
				label: "Feedback received",
				description: "Submitted from mobile preview.",
				createdAt: "2026-07-28T16:41:00.000Z",
				tone: "accent",
			},
		],
	},
	{
		id: "FDB-2815",
		title: "Checkout forgot the +213 phone prefix",
		message:
			"The checkout preview looked correct, but after saving, the phone field went back to +1. This only happened once and I could fix it by removing and adding the form again.",
		type: "bug",
		status: "resolved",
		priority: "medium",
		createdAt: "2026-07-28T11:27:00.000Z",
		reporter: {
			name: "Imène Boudjellal",
			email: "imene@beldi-market.dz",
			avatarUrl: "/images/avatars/12.png",
			plan: "Pro",
			memberSince: "2025-12-14T00:00:00.000Z",
		},
		context: {
			page: "Form settings",
			path: "/projects/beldi-market/editor/forms/checkout",
			project: "Beldi Market",
			browser: "Edge 138",
			device: "HP Spectre · Windows 11",
			viewport: "1536 × 864",
		},
		tags: ["forms", "localization", "checkout"],
		adminNote: "Confirmed fixed in the form defaults patch.",
		activity: [
			{
				id: "activity-2815-3",
				label: "Marked resolved",
				description: "Verified against the form defaults patch.",
				createdAt: "2026-07-29T08:14:00.000Z",
				tone: "success",
			},
			{
				id: "activity-2815-2",
				label: "Fix verified",
				description: "Could not reproduce on the current preview build.",
				createdAt: "2026-07-28T15:32:00.000Z",
				tone: "default",
			},
			{
				id: "activity-2815-1",
				label: "Feedback received",
				description: "Submitted from form settings.",
				createdAt: "2026-07-28T11:27:00.000Z",
				tone: "accent",
			},
		],
	},
	{
		id: "FDB-2807",
		title: "Templates should say when they include a store",
		message:
			"I clicked through several templates trying to find one for a small catalog. A filter or label for commerce pages would save time before opening each preview.",
		type: "experience",
		status: "new",
		priority: "low",
		createdAt: "2026-07-27T18:56:00.000Z",
		reporter: {
			name: "Emil Varga",
			email: "emil@folk-form.hu",
			avatarUrl: "/images/avatars/06.png",
			plan: "Free",
			memberSince: "2026-07-26T00:00:00.000Z",
		},
		context: {
			page: "Template gallery",
			path: "/templates",
			project: "No project yet",
			browser: "Chrome 138",
			device: "Acer Swift · Windows 11",
			viewport: "1440 × 900",
		},
		tags: ["templates", "commerce", "discovery"],
		adminNote: "",
		activity: [
			{
				id: "activity-2807-1",
				label: "Feedback received",
				description: "Submitted from the template gallery.",
				createdAt: "2026-07-27T18:56:00.000Z",
				tone: "accent",
			},
		],
	},
	{
		id: "FDB-2798",
		title: "Show estimated image credits before generating",
		message:
			"Before I start a batch, I want to know roughly how many credits it will use. The final cost makes sense, but seeing it only afterward makes it hard to plan a larger campaign.",
		type: "idea",
		status: "planned",
		priority: "medium",
		createdAt: "2026-07-26T09:12:00.000Z",
		reporter: {
			name: "Haruto Watanabe",
			email: "haruto@field-note.jp",
			avatarUrl: "/images/avatars/10.png",
			plan: "Business",
			memberSince: "2025-08-07T00:00:00.000Z",
		},
		context: {
			page: "Image generator",
			path: "/projects/field-note/assets/generate",
			project: "Field Note",
			browser: "Chrome 138",
			device: "MacBook Air · macOS 15.6",
			viewport: "1470 × 956",
		},
		tags: ["credits", "image generation", "pricing"],
		adminNote: "Pair with the generation-cost preview work.",
		activity: [
			{
				id: "activity-2798-2",
				label: "Added to roadmap",
				description: "Linked to generation-cost previews.",
				createdAt: "2026-07-28T09:36:00.000Z",
				tone: "success",
			},
			{
				id: "activity-2798-1",
				label: "Feedback received",
				description: "Submitted from the image generator.",
				createdAt: "2026-07-26T09:12:00.000Z",
				tone: "accent",
			},
		],
	},
];
