// Router factory for TanStack Start.
// The generated client and server entries call getRouter().
// routeTree.gen.ts is generated by the Start plugin during dev and build.
import { createRouter } from "@tanstack/react-router";
import { routeTree } from "./routeTree.gen";

/** Builds the app router. Scroll restoration keeps anchor jumps working. */
export function getRouter() {
	return createRouter({
		routeTree,
		scrollRestoration: true,
		defaultPreload: "intent",
	});
}

declare module "@tanstack/react-router" {
	interface Register {
		router: ReturnType<typeof getRouter>;
	}
}
