// Router factory for TanStack Start, with the React Query cache in the router context.
// The generated client and server entries call getRouter(), once per SSR request.
// routeTree.gen.ts is generated by the Start plugin during dev and build.
import { QueryClient } from "@tanstack/react-query";
import { createRouter } from "@tanstack/react-router";
import { setupRouterSsrQueryIntegration } from "@tanstack/react-router-ssr-query";
import { routeTree } from "./routeTree.gen";

/** Builds the app router and its own QueryClient. Scroll restoration keeps anchor jumps working. */
export function getRouter() {
	// One cache per call: an SSR request never sees the data of another request.
	const queryClient = new QueryClient({
		// 30 s: the loader fetch stays fresh, so the page does not fetch it again on mount.
		defaultOptions: { queries: { staleTime: 30_000 } },
	});
	const router = createRouter({
		routeTree,
		context: { queryClient },
		scrollRestoration: true,
		defaultPreload: "intent",
		// React Query owns the cache, so the router keeps no second copy of loader data.
		defaultPreloadStaleTime: 0,
	});
	// Sends server-fetched queries to the browser and adds the QueryClientProvider.
	setupRouterSsrQueryIntegration({ router, queryClient });
	return router;
}

declare module "@tanstack/react-router" {
	interface Register {
		router: ReturnType<typeof getRouter>;
	}
}
