/**
 * Provider adapter for deterministic product commercials.
 *
 * Authorization and source preparation happen before the durable attempt is
 * created. This boundary accepts only the prepared public JPEG/PNG reference,
 * invokes the fixed Seedance renderer, captures provider evidence before
 * publishing, and writes the deterministic recovery object.
 */
import { writeFile } from "node:fs/promises";

import { gateway } from "@ai-sdk/gateway";
import { env } from "@wandit/env/server";
import { experimental_generateVideo as generateVideo } from "ai";

import {
	IMMUTABLE_ASSET_CACHE_CONTROL,
	isR2Configured,
	publicAssetUrl,
	putSiteFile,
	siteVideoKey,
} from "../../../../infrastructure/storage/r2";
import { VIDEO_PRODUCT_ENGINE_MODEL } from "../../../media-generations/domain/video-quality-models";
import {
	type GatewayGenerationFailure,
	type GatewayGenerationMetadata,
	type GatewayMeteringContext,
	gatewayGenerationCaptureFromError,
	withGatewayAttribution,
} from "../../../metering/domain/gateway-metering";
import { videoProviderTimeoutMs } from "./generate-video";

const EXTENSION_BY_MEDIA_TYPE: Record<string, string> = {
	"video/mp4": "mp4",
	"video/webm": "webm",
};

export type ProductVideoSourceMediaType = "image/jpeg" | "image/png";

export type ProductVideoResult =
	| GatewayGenerationFailure
	| { message: string; status: "unavailable" }
	| ({
			mediaType: string;
			status: "generated";
			url: string;
			warnings?: string[];
	  } & GatewayGenerationMetadata);

export async function productVideo(params: {
	abortSignal?: AbortSignal;
	attemptId: string;
	imageUrl: string;
	mediaType: ProductVideoSourceMediaType;
	metering: GatewayMeteringContext<"video">;
	onProviderGeneration?: (
		generation: GatewayGenerationMetadata,
	) => Promise<void>;
	onPublishing?: () => void;
	outputPath: string;
	projectId: string;
	prompt: string;
}): Promise<ProductVideoResult> {
	if (
		!env.AI_GATEWAY_API_KEY ||
		!env.R2_PUBLIC_BASE_URL ||
		!isR2Configured() ||
		!env.TRIGGER_SECRET_KEY
	) {
		return {
			message: "product video generation is not configured on this server",
			status: "unavailable",
		};
	}

	if (!isPublicHttpsUrl(params.imageUrl)) {
		return {
			message:
				"the prepared product image is not publicly reachable over HTTPS",
			status: "failed",
		};
	}

	let providerEvidence: GatewayGenerationMetadata | null = null;

	try {
		const timeoutSignal = AbortSignal.timeout(videoProviderTimeoutMs(5));
		const abortSignal = params.abortSignal
			? AbortSignal.any([params.abortSignal, timeoutSignal])
			: timeoutSignal;
		const providerOptions: NonNullable<
			Parameters<typeof generateVideo>[0]["providerOptions"]
		> = withGatewayAttribution({}, params.metering);
		// Seedance's verified reference recipe uses the provider-only "adaptive"
		// value. AI SDK 7.0.19 exposes only `${number}:${number}` publicly, so
		// keep the single unavoidable cast at this adapter boundary.
		const adaptiveAspect = "adaptive" as `${number}:${number}`;
		const result = await generateVideo({
			abortSignal,
			aspectRatio: adaptiveAspect,
			duration: 5,
			inputReferences: [{ data: params.imageUrl, mediaType: params.mediaType }],
			maxRetries: 0,
			model: gateway.video(VIDEO_PRODUCT_ENGINE_MODEL),
			n: 1,
			prompt: params.prompt,
			providerOptions,
		});

		providerEvidence = {
			model: VIDEO_PRODUCT_ENGINE_MODEL,
			providerMetadata: result.providerMetadata,
		};
		// Provider evidence is the billing authority. It must be durable before
		// generated bytes can appear at the deterministic recovery key.
		await params.onProviderGeneration?.(providerEvidence);
		params.onPublishing?.();

		const mediaType = result.video.mediaType;
		const extension = EXTENSION_BY_MEDIA_TYPE[mediaType] ?? "mp4";
		const key = siteVideoKey(params.projectId, params.attemptId, 1, extension);
		await writeFile(params.outputPath, result.video.uint8Array);
		await putSiteFile(
			key,
			result.video.uint8Array,
			mediaType,
			IMMUTABLE_ASSET_CACHE_CONTROL,
		);

		return {
			mediaType,
			model: VIDEO_PRODUCT_ENGINE_MODEL,
			providerMetadata: result.providerMetadata,
			status: "generated",
			url: publicAssetUrl(key),
			...(result.warnings.length > 0
				? {
						warnings: result.warnings.map((warning) => JSON.stringify(warning)),
					}
				: {}),
		};
	} catch (error) {
		const errorCapture = gatewayGenerationCaptureFromError(error);
		const evidence =
			providerEvidence ??
			(errorCapture
				? {
						model: VIDEO_PRODUCT_ENGINE_MODEL,
						providerMetadata: errorCapture.providerMetadata,
					}
				: null);

		return {
			...(evidence ?? {}),
			message: error instanceof Error ? error.message : String(error),
			...(evidence ? { providerUnits: providerEvidence ? 1 : 0 } : {}),
			status: "failed",
		};
	}
}

function isPublicHttpsUrl(value: string): boolean {
	try {
		const url = new URL(value);
		return (
			url.protocol === "https:" && url.username === "" && url.password === ""
		);
	} catch {
		return false;
	}
}
