import type { JSONValue } from "ai";
import type { CapturedGeneration } from "./metering";
import type { AiUsageOperation } from "./operation-registry";

export type GatewayAttribution = {
	tags: [string, string];
	user: string;
};

export type GatewayMeteringContext<
	TOperation extends AiUsageOperation = AiUsageOperation,
> = {
	operation: TOperation;
	/** Acting member — always a user id, even inside an org workspace. */
	userId: string;
	/** Set when the org pool pays; drives quotaEntityId (the payer). */
	organizationId?: string | null;
};

export type GatewayGenerationMetadata = {
	model: string;
	provider?: string;
	providerMetadata: unknown;
	usage?: unknown;
};

/**
 * A provider helper can fail after the gateway has completed work (for
 * example, while storing generated bytes). Carry the provider evidence on
 * that failed result so callers can persist the generation reference before
 * deciding whether the reservation is refundable.
 */
export type GatewayGenerationFailure = {
	message: string;
	/** Provider outputs completed before a later delivery/storage failure. */
	providerUnits?: number;
	status: "failed";
} & Partial<GatewayGenerationMetadata>;

export function hasGatewayGenerationMetadata(
	value: unknown,
): value is GatewayGenerationMetadata {
	return (
		typeof value === "object" &&
		value !== null &&
		"model" in value &&
		typeof value.model === "string" &&
		"providerMetadata" in value
	);
}

/**
 * Fixed-price reconciliation must use completed customer units, not the
 * reservation size. Nest the provider's native usage so the durable unit
 * marker cannot collide with SDK fields.
 */
export function fixedGenerationStepUsage(
	providerUsage: unknown,
	fixedUnits: number,
): { metering: { fixedUnits: number }; providerUsage: unknown } {
	if (!Number.isSafeInteger(fixedUnits) || fixedUnits < 0) {
		throw new Error("Fixed generation units must be a non-negative integer");
	}

	return {
		metering: { fixedUnits },
		providerUsage: providerUsage ?? null,
	};
}

/**
 * AI Gateway errors expose their generation id at the top level instead of in
 * successful-result `providerMetadata`. AI SDK retry/call wrappers can retain
 * that error under `lastError`, `errors`, or `cause`, so walk only those known
 * error links and guard against cyclic causes.
 */
export function gatewayGenerationIdFromError(error: unknown): string | null {
	return findGenerationIdByKey(error, "generationId", new Set<unknown>());
}

/**
 * The OpenRouter stream wrapper tags failed calls with the distinct
 * `openrouterGenerationId` key (never `generationId`, so a Vercel id can
 * never be confused with an OpenRouter one — they reconcile against
 * different cost APIs). Same error-link walk as the gateway variant.
 */
export function openrouterGenerationIdFromError(error: unknown): string | null {
	return findGenerationIdByKey(
		error,
		"openrouterGenerationId",
		new Set<unknown>(),
	);
}

/** Build the successful-result metadata shape expected by MeteringService. */
export function gatewayGenerationCaptureFromError(
	error: unknown,
): CapturedGeneration | null {
	const generationId = gatewayGenerationIdFromError(error);

	return generationId
		? { providerMetadata: { gateway: { generationId } } }
		: null;
}

/**
 * Error capture for TEXT call sites, which can run on either provider. Tries
 * the Vercel shape first, then the OpenRouter tag, and returns metadata in
 * the matching provider's shape so capture records the right source. Media
 * call sites keep using gatewayGenerationCaptureFromError — they never run
 * on OpenRouter.
 */
export function llmGenerationCaptureFromError(
	error: unknown,
): CapturedGeneration | null {
	const gatewayCapture = gatewayGenerationCaptureFromError(error);

	if (gatewayCapture) {
		return gatewayCapture;
	}

	const generationId = openrouterGenerationIdFromError(error);

	return generationId
		? { providerMetadata: { openrouter: { generationId } } }
		: null;
}

/**
 * Adds the mandatory AI Gateway attribution while retaining provider-specific
 * settings and gateway routing controls such as `order`.
 */
export function withGatewayAttribution<T extends Record<string, unknown>>(
	providerOptions: T,
	input: GatewayMeteringContext,
): T & { gateway: Record<string, JSONValue> & GatewayAttribution } {
	return {
		...providerOptions,
		gateway: {
			...asRecord(providerOptions.gateway),
			// No quotaEntityId here: the gateway hard-rejects any request naming
			// an entity that has no quota registered on the gateway account, so
			// sending it unconditionally broke every generation. Credits are
			// enforced by our own metering; the paying pool remains identifiable
			// through the ws:org/ws:personal tag plus `user`.
			tags: [
				`op:${input.operation}`,
				input.organizationId ? "ws:org" : "ws:personal",
			],
			user: input.userId,
		},
	};
}

function asRecord(value: unknown): Record<string, JSONValue> {
	return typeof value === "object" && value !== null && !Array.isArray(value)
		? (value as Record<string, JSONValue>)
		: {};
}

function findGenerationIdByKey(
	value: unknown,
	key: "generationId" | "openrouterGenerationId",
	visited: Set<unknown>,
): string | null {
	if (!isUnknownRecord(value) || visited.has(value)) {
		return null;
	}

	visited.add(value);
	const generationId = validGenerationId(value[key]);

	if (generationId) {
		return generationId;
	}

	const lastErrorGenerationId = findGenerationIdByKey(
		value.lastError,
		key,
		visited,
	);

	if (lastErrorGenerationId) {
		return lastErrorGenerationId;
	}

	if (Array.isArray(value.errors)) {
		for (let index = value.errors.length - 1; index >= 0; index -= 1) {
			const nestedGenerationId = findGenerationIdByKey(
				value.errors[index],
				key,
				visited,
			);

			if (nestedGenerationId) {
				return nestedGenerationId;
			}
		}
	}

	return findGenerationIdByKey(value.cause, key, visited);
}

function validGenerationId(value: unknown): string | null {
	if (typeof value !== "string") {
		return null;
	}

	const normalized = value.trim();
	return normalized.length > 0 ? normalized : null;
}

function isUnknownRecord(
	value: unknown,
): value is Record<PropertyKey, unknown> {
	return typeof value === "object" && value !== null;
}
