import type { JSONValue } from "ai";
import type { CapturedGeneration } from "./metering";
import type { AiUsageOperation } from "./operation-registry";

export type GatewayAttribution = {
	quotaEntityId: string;
	tags: [string, string];
	user: string;
};

export type GatewayMeteringContext<
	TOperation extends AiUsageOperation = AiUsageOperation,
> = {
	operation: TOperation;
	/** Acting member — always a user id, even inside an org workspace. */
	userId: string;
	/** Set when the org pool pays; drives quotaEntityId (the payer). */
	organizationId?: string | null;
};

export type GatewayGenerationMetadata = {
	model: string;
	provider?: string;
	providerMetadata: unknown;
	usage?: unknown;
};

/**
 * A provider helper can fail after the gateway has completed work (for
 * example, while storing generated bytes). Carry the provider evidence on
 * that failed result so callers can persist the generation reference before
 * deciding whether the reservation is refundable.
 */
export type GatewayGenerationFailure = {
	message: string;
	/** Provider outputs completed before a later delivery/storage failure. */
	providerUnits?: number;
	status: "failed";
} & Partial<GatewayGenerationMetadata>;

export function hasGatewayGenerationMetadata(
	value: unknown,
): value is GatewayGenerationMetadata {
	return (
		typeof value === "object" &&
		value !== null &&
		"model" in value &&
		typeof value.model === "string" &&
		"providerMetadata" in value
	);
}

/**
 * Fixed-price reconciliation must use completed customer units, not the
 * reservation size. Nest the provider's native usage so the durable unit
 * marker cannot collide with SDK fields.
 */
export function fixedGenerationStepUsage(
	providerUsage: unknown,
	fixedUnits: number,
): { metering: { fixedUnits: number }; providerUsage: unknown } {
	if (!Number.isSafeInteger(fixedUnits) || fixedUnits < 0) {
		throw new Error("Fixed generation units must be a non-negative integer");
	}

	return {
		metering: { fixedUnits },
		providerUsage: providerUsage ?? null,
	};
}

/**
 * AI Gateway errors expose their generation id at the top level instead of in
 * successful-result `providerMetadata`. AI SDK retry/call wrappers can retain
 * that error under `lastError`, `errors`, or `cause`, so walk only those known
 * error links and guard against cyclic causes.
 */
export function gatewayGenerationIdFromError(error: unknown): string | null {
	return findGatewayGenerationId(error, new Set<unknown>());
}

/** Build the successful-result metadata shape expected by MeteringService. */
export function gatewayGenerationCaptureFromError(
	error: unknown,
): CapturedGeneration | null {
	const generationId = gatewayGenerationIdFromError(error);

	return generationId
		? { providerMetadata: { gateway: { generationId } } }
		: null;
}

/**
 * Adds the mandatory AI Gateway attribution while retaining provider-specific
 * settings and gateway routing controls such as `order`.
 */
export function withGatewayAttribution<T extends Record<string, unknown>>(
	providerOptions: T,
	input: GatewayMeteringContext,
): T & { gateway: Record<string, JSONValue> & GatewayAttribution } {
	return {
		...providerOptions,
		gateway: {
			...asRecord(providerOptions.gateway),
			// quotaEntityId identifies the PAYING pool; `user` stays the acting
			// member for per-person observability.
			quotaEntityId: input.organizationId
				? `org:${input.organizationId}`
				: input.userId,
			tags: [
				`op:${input.operation}`,
				input.organizationId ? "ws:org" : "ws:personal",
			],
			user: input.userId,
		},
	};
}

function asRecord(value: unknown): Record<string, JSONValue> {
	return typeof value === "object" && value !== null && !Array.isArray(value)
		? (value as Record<string, JSONValue>)
		: {};
}

function findGatewayGenerationId(
	value: unknown,
	visited: Set<unknown>,
): string | null {
	if (!isUnknownRecord(value) || visited.has(value)) {
		return null;
	}

	visited.add(value);
	const generationId = validGenerationId(value.generationId);

	if (generationId) {
		return generationId;
	}

	const lastErrorGenerationId = findGatewayGenerationId(
		value.lastError,
		visited,
	);

	if (lastErrorGenerationId) {
		return lastErrorGenerationId;
	}

	if (Array.isArray(value.errors)) {
		for (let index = value.errors.length - 1; index >= 0; index -= 1) {
			const nestedGenerationId = findGatewayGenerationId(
				value.errors[index],
				visited,
			);

			if (nestedGenerationId) {
				return nestedGenerationId;
			}
		}
	}

	return findGatewayGenerationId(value.cause, visited);
}

function validGenerationId(value: unknown): string | null {
	if (typeof value !== "string") {
		return null;
	}

	const normalized = value.trim();
	return normalized.length > 0 ? normalized : null;
}

function isUnknownRecord(
	value: unknown,
): value is Record<PropertyKey, unknown> {
	return typeof value === "object" && value !== null;
}
