/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 7a16797bc8bbaebb86c7716eb642598c)
interface __BaseEnv_Env {
	PREVIEW_KV: KVNamespace;
	PREVIEW_ANALYTICS: AnalyticsEngineDataset;
	PREVIEW_RATE: RateLimit;
	PREVIEW_DOMAIN: "wanditpreview.app";
	FRAME_ANCESTORS: "https://wandit.dev https://staging.wandit.dev https://*.vercel.app http://localhost:*" | "https://wandit.dev https://staging.wandit.dev http://localhost:*";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface StagingEnv {
		PREVIEW_KV: KVNamespace;
		PREVIEW_ANALYTICS: AnalyticsEngineDataset;
		PREVIEW_RATE: RateLimit;
		PREVIEW_DOMAIN: "wanditpreview.app";
		FRAME_ANCESTORS: "https://wandit.dev https://staging.wandit.dev https://*.vercel.app http://localhost:*";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
