/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 398aeb93fbcd64925fada3416483b0be)
interface __BaseEnv_Env {
	PREVIEW_KV: KVNamespace;
	PREVIEW_ANALYTICS: AnalyticsEngineDataset;
	PREVIEW_RATE: RateLimit;
	PREVIEW_DOMAIN: "wanditpreview.app";
	FRAME_ANCESTORS: "https://wandit.dev https://preview.wandit.dev http://localhost:*";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface StagingEnv {
		PREVIEW_KV: KVNamespace;
		PREVIEW_ANALYTICS: AnalyticsEngineDataset;
		PREVIEW_RATE: RateLimit;
		PREVIEW_DOMAIN: "wanditpreview.app";
		FRAME_ANCESTORS: "https://wandit.dev https://preview.wandit.dev http://localhost:*";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
